### ISSUE TITLE
[FEATURE] Import PojavLauncher as a git submodule and build automatically.

### ISSUE THREAD

**Issue by gusbunce** [QuestCraftPlusPlus/QuestCraft#1]
**Is your feature request related to a problem? Please describe.**
Currently the only way to build QuestCraft is by entering into the [PojavLauncher](https://github.com/QuestCraftPlusPlus/PojavLauncher) and downling the artifact from GH Actions which becomes less user friendly. 

**Describe the solution you'd like**
PojavLauncher, Fabric, MCXR, etc. Need to all be imported into the [QuestCraft Repo](https://github.com/QuestCraftPlusPlus/QuestCraft) as git submodules and then a custome GH Actions build script to pull each artifact and compile into one executable apk.

**Comment by SpringTrap-SFM2006** [comment]
They could all go into the installation automatically or it could all be one apk

**Comment by CADIndie** [comment]
We are going with a direct intergration method and will breif you shorty.
