### ISSUE TITLE
[BUG] Infinite loading

### ISSUE THREAD

**Issue by Illpie** [QuestCraftPlusPlus/QuestCraft#10]
Whenever i try to launch the game (on fabric 1.18.1) I get an infinite quest loading screen, did i do something wrong during the setup? or is this just a bug?

**Comment by thetoastpancake** [comment]
I am having the same issue too when I launch the game it starts up as normal three loading dots and all of that and in about 5 minutes it becomes a black screen and nothing happens after.

**Comment by markoboyo** [comment]
monger... suspicious

**Comment by markoboyo** [comment]
Don't be sus.... Do your tasks

**Comment by markoboyo** [comment]
having the same issue, it just stays on a 3 dot loading screen no matter what i do. tried all of the fixes but none work

**Comment by thetoastpancake** [comment]
I will send my latest.log file here if it helps
[latestlog.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8112848/latestlog.txt)

**Comment by JD-The-65th** [comment]
Same issue, weird how for some people it works, while for others, it doesn't. I'm on a quest 2 v37, I've had my quest trying to run QC for the last 20 minutes just loading and it's stuck on the 3 dots.

**Comment by thetoastpancake** [comment]
> 

For me I get past the 3 dots to nothing but black. Could it be a mod issue?

**Comment by Ethanscharlie** [comment]
same

**Comment by JD-The-65th** [comment]
Does your install temporarily open up to red, and then goes back to the 3 dots for infinity?

**Comment by missingcupid** [comment]
Same issue here, I have everything loaded and installed properly (I think) and when I start up the latest 1.18.1 fabric (or the other 1.18.1 fabric) all that shows is the black screen with the 3 loading dots in the middle with no red screen.

**Comment by Ethanscharlie** [comment]
> Does your install temporarily open up to red, and then goes back to the 3 dots for infinity?

Mine just goes to 3dotblack in the middle of the loading bar

**Comment by Illpie** [comment]
mine just goes to three dots when i click play and doesnt stop

**Comment by lrutjens** [comment]
same

**Comment by JD-The-65th** [comment]
Did y'all set up QC using the easy method or the complicated method?

**Comment by EnterTheVoid-x86** [comment]
Easy

**Comment by lrutjens** [comment]
both

> Did y'all set up QC using the easy method or the complicated method?

**Comment by lrutjens** [comment]
same result each time

**Comment by Ethanscharlie** [comment]
If you have PojavLauncher installed, Uninstall it
1. Side load this apk https://cdn.discordapp.com/attachments/927024272076070933/945032505692672040/app-debug.apk
2. (don't open the app) Download this file https://www.mediafire.com/file/lsrsm9y2it1wlyd/net.kdt.pojavlaunch.debug.zip/file and unzip it so its a folder called net.kdt.pojavlaunch.debug
3. put your new folder (net.kdt.pojavlaunch.debug) into /sdcard/Android/data (on ur quest) (easiest way is with sidequest)
4. Open pojavlauncher
5. goto settings, Video And renderer, Renderer, and set it to GL4ES 1.1.5 (OpenGL ES 3)
6. Make sure you have the 1.18.1 fabric launcher profile selected and hit play
7. a prompt will pop up DO NOT PRESS OK, press play anyway. (if you press ok you have to repeat this guide)
8. it will load for a little bit, wait a second. when its done it will turn red (this is good it means it worked) it will lag a little bit and the menu will pop up
9. ENJOY!!! (if you want to add servers, you have to goto .minecraft and edit the servers.dat file (if it doesn't exist, grab it from your .minecraft folder on your computer (if you don't have a .minecraft folder on ur pc ask me I'll give u a servers.dat)))



I did this way

**Comment by missingcupid** [comment]
> Did y'all set up QC using the easy method or the complicated method? Thumbs up for easy method, thumbs down for complicated

Complicated

**Comment by Illpie** [comment]
same

**Comment by thetoastpancake** [comment]
I Used the complicated method, I am reading the offtopc chat.
https://discord.com/channels/820767484042018829/820774522244038686/945488715801829488
https://discord.com/channels/820767484042018829/820774522244038686/945487657205628960

**Comment by lrutjens** [comment]
hit keep me logged in when logging in

**Comment by Ethanscharlie** [comment]
> hit keep me logged in when logging in

why?

**Comment by lrutjens** [comment]
> I Used the complicated method, I am reading the offtopc chat. https://discord.com/channels/820767484042018829/820774522244038686/945488715801829488 https://discord.com/channels/820767484042018829/820774522244038686/945487657205628960

these messages

**Comment by wuhtwp** [comment]
what ive done to fix this problem is just reinstalling the whole thing, it might have just messed up when you were downloading

**Comment by ManiacGamer156** [comment]
Please make your own issue and I will help you there, follow the new instructions on the Github releases

**Comment by ZGPixel** [comment]
Yeah, I have been having this problem for like an hour and I can't get it to work. I used both methods, advanced and simplified, but it just ended with the same result stuck on an infinite loading screen unable to do anything.

**Comment by Xe-k** [comment]
i have the same infinite loading issue but then it crashes back to pojav launcher

**Comment by Flamgop** [comment]
This issue is caused by user error in 9/10 cases

**Comment by EnterTheVoid-x86** [comment]
Try enabling keep logged in when starting PJ

**Comment by EnterTheVoid-x86** [comment]
Worked for me

**Comment by firmeeeee** [comment]
> If you have PojavLauncher installed, Uninstall it
> 
>     1. Side load this apk https://cdn.discordapp.com/attachments/927024272076070933/945032505692672040/app-debug.apk
> 
>     2. (don't open the app) Download this file https://www.mediafire.com/file/lsrsm9y2it1wlyd/net.kdt.pojavlaunch.debug.zip/file and unzip it so its a folder called net.kdt.pojavlaunch.debug
> 
>     3. put your new folder (net.kdt.pojavlaunch.debug) into /sdcard/Android/data (on ur quest) (easiest way is with sidequest)
> 
>     4. Open pojavlauncher
> 
>     5. goto settings, Video And renderer, Renderer, and set it to GL4ES 1.1.5 (OpenGL ES 3)
> 
>     6. Make sure you have the 1.18.1 fabric launcher profile selected and hit play
> 
>     7. a prompt will pop up DO NOT PRESS OK, press play anyway. (if you press ok you have to repeat this guide)
> 
>     8. it will load for a little bit, wait a second. when its done it will turn red (this is good it means it worked) it will lag a little bit and the menu will pop up
> 
>     9. ENJOY!!! (if you want to add servers, you have to goto .minecraft and edit the servers.dat file (if it doesn't exist, grab it from your .minecraft folder on your computer (if you don't have a .minecraft folder on ur pc ask me I'll give u a servers.dat)))
> 
> 
> I did this way

It says i cant put the file into data.HELP

**Comment by Dracotyoshi** [comment]
im having the same issue but its in vanilla

**Comment by Jackhooverguy** [comment]
I have the same problem as all of you. I have lithium on(used to work all the time) but now when I load questcraft it goes to the three dots and then black screen. I’ve tried holding controllers in front of the camera, leaving the boundary, u name it. Any idea?

**Comment by Dracotyoshi** [comment]
Yep that’s what I’m dealing with
