### ISSUE TITLE
Rearanging resource packs cases a soft lock[BUG]

### ISSUE THREAD

**Issue by jakershaker1** [QuestCraftPlusPlus/QuestCraft#103]
**Describe the bug**
i was playing around earlier and I tried re-arranging the resource pack list which cases a soft lock in the appearance of the mojang loading screen looping
**To Reproduce**
1. Go to settings
2. Click on resource packs
3. Move one of the other included resource packs in the hierarchy

**Expected behavior**
it loads and then dosent soft lock

**Headset Details (please complete the following information):**
 - Quest Build: v.37.0
 - Device: Quest 2
 - QuestCraft Version: im pretty sure its 1.1 but im not sure

**Comment by Flamgop** [comment]
Assets-v0.zip should not be re-arranged. It causes the shaders to disable and crash the game.

**Comment by jakershaker1** [comment]
I left dhaders where they were. I moved the vanilla textures up in an attempt to get the crosshair back in menus.
