### ISSUE TITLE
[FEATURE] make maps show up in the hand like in flatscreen Minecraft. 

### ISSUE THREAD

**Issue by TheBigGuy1** [QuestCraftPlusPlus/QuestCraft#104]
**Describe the bug**
When opening a map in vr, the game only shows the item and does not show the actual map.

**To Reproduce**
1. Go in the game
2. Grab a map
3. Use map

**Expected behavior**
The map to show up like how it does in flatscreen.

**Screenshots**
None

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest_2
 - QuestCraft Version v1.2.3

**Comment by IzzyDotExe** [comment]
Maps will be fixed at some time in the future it's not a priority however.
