### ISSUE TITLE
Is there a list of controls somewhere

### ISSUE THREAD

**Issue by Zest-God** [QuestCraftPlusPlus/QuestCraft#105]
Even if there is please tell me them

**Comment by SebasPro9864** [comment]
QUESTCRAFT CONTROL LIST:

LEFT THUMBSTICK: ANALOGUE MOVEMENT
LEFT TRIGGER: PLACE/USE
LEFT GRIP (HOLD): CROUCH
LEFT BOTTOM BUTTON: PAUSE MENU
LEFT TOP BUTTON: INVENTORY/CREATIVE MENU

RIGHT THUMBSTICK (L/R): SNAP TURNING
RIGHT THUMBSTICK (U/D): CHANGE HOTBAR SLOT
RIGHT TRIGGER: MINE/ATTACK/CLICK
RIGHT GRIP (HOLD): SPRINT
RIGHT BOTTOM BUTTON: JUMP
RIGHT TOP BUTTON: RIGHT CLICK IN INVENTORY (I.E SINGLE ITEM FROM STACK)

**Comment by Flamgop** [comment]
They are pinned in the discord and will be added to the readme.
