### ISSUE TITLE
[FEATURE] A "Public Server" mode

### ISSUE THREAD

**Issue by Mage-Enderman** [QuestCraftPlusPlus/QuestCraft#106]
**Is your feature request related to a problem? Please describe.**
So as this is a VR port of a non-VR game
to PC/Non-VR users we might look a bit off/odd in game
Which is fine, but for a Servers anti-cheat that off/odd can sometimes look like cheating
I think that's a problem

**Describe the solution you'd like**
I think it'd be good to have a "Server Mode"
Where some stuff might be different between Client and Server
or even some stuff changed for both, to prevent false bans/kicks
Stuff like 
"If in Server Mode, Local Client can still lean/move a tad bit but if they move more than given amount view fades to black to prevent cheating, and while again Local Client can move a tad that movement is not transferred to server only rotational movement
and movement from joystick/controller"

**Describe alternatives you've considered**
A Plugin/Mod for Servers to add that communicates in some way with MCXR/QuestCraft
so that they can relax when it comes to those users in some respects like movement mentioned above
Though this wouldn't fix this universally and might be a bit too niche
plus it could in theory add a security risk if other mods/clients are able to add that flag or whatever that MCXR/QuestCraft has
to then be less likely to be caught

**Additional context**
I feel if there could be a white/blacklist of servers the user could add so it'd automatically use
this "Server Mode" on some servers but not others
or to varying degrees, like on [Server Here] it'd do everything it can to be like a regular non-VR player to the server
Whereas on [ServerB Here] it'd just do a minimal amount etc

**Comment by Mage-Enderman** [comment]
> Having a mod to support VR-like movement and share them to other chient is interesting, but I think that it the client to not send illegal moves and not every server to accept them.

What are you trying to say?

**Comment by Mage-Enderman** [comment]
I feel I found a better way to say "Local Client can move a tad that movement is not transferred to server only rotational movement"
Like when you're on a horse you can still turn and look up and down but if you walk around IRL it doesn't move the horse

**Comment by wellsilver** [comment]
I think you should re-post this in MCXR's github page wich is what Questcraft uses

**Comment by wellsilver** [comment]
> > Having a mod to support VR-like movement and share them to other client is interesting, but I think that it the client to not send illegal moves and not every server to accept them.
> 
> What are you trying to say?

So, the clients need a middle man who can help them talk between eachother to recieve the positions of the VR players arms and head and stuff. But a problem is that the middle man most likely wont be accepting these messages to send to other players.

**Comment by Mage-Enderman** [comment]
> I think you should re-post this in MCXR's github page wich is what Questcraft uses

https://github.com/Sorenon/MCXR/issues/37

**Comment by Mage-Enderman** [comment]
> > > Having a mod to support VR-like movement and share them to other client is interesting, but I think that it the client to not send illegal moves and not every server to accept them.
> > 
> > 
> > What are you trying to say?
> 
> So, the clients need a middle man who can help them talk between eachother to recieve the positions of the VR players arms and head and stuff. But a problem is that the middle man most likely wont be accepting these messages to send to other players.

So they were talking about something that AFAIK/IMO is very unrelated to what I was talking about?
Cool
