### ISSUE TITLE
[BUG]loading forever

### ISSUE THREAD

**Issue by Jakeislostt** [QuestCraftPlusPlus/QuestCraft#107]
i have the correct fabric version, whenever i click play (ive done everything right by the way) it doesnt load ive tried all of the fixes and nothing works

**Comment by sona53773** [comment]
check login automatically when you login to pojavlauncher.

i had that issue too

**Comment by wellsilver** [comment]
to fix it:
-restart
-open questcraft
-click "select account" nothing else

**Comment by IzzyDotExe** [comment]
I'm closing this as it's inactive and op did not provide enough information. If you still have this issue make a new ticket in our discord or make a new issue.
