### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Lacymonster** [QuestCraftPlusPlus/QuestCraft#108]
A bedrock verison if possible so i can play with my console friends

**Comment by jakershaker1** [comment]
Guyser mc is a good server proxy for your friends but as java and bedrock are 2 different beasts, your request is impossible.

**Comment by hellidox** [comment]
bedrock vr already exists

**Comment by jakershaker1** [comment]
But we dont have any source code and modifying the android version is illegal to modify and distribute.

**Comment by IsraelAristide** [comment]
QuestCraft is a wrapper for Minecraft: Java Edition. Even if we wanted to make a bedrock version, it has very limited modding support. Bedrock already has a VR version so you can play that if you really wanna play with console friends :)

**Comment by Dawidak** [comment]
> A bedrock verison if possible so i can play with my console friends

Minecraft Gear VR version works and it's a bedrock port. The only issue is that it's not updated anymore and not originally meant for the quest platform.

**Comment by oliverwesley1** [comment]
I don't think this is possible, as bedrock is hard to mod and would have not port possible due to them being completely different games

**Comment by jakershaker1** [comment]
Could we close this ticket? This is a tired question and has been answered multiple times in the last year.

**Comment by oliverwesley1** [comment]
Yeh, I think it would be a good idea to add some kind of Moderator to purge some of the repeats/ stupid questions

**Comment by hellidox** [comment]
you can start minecraft bedrock with a special uri to enable pcvr mode
(windows 10/11)

**Comment by Mage-Enderman** [comment]
What might make more sense as a request since Bedrock and Java are very different and separate games
Maybe a mod to allow you to connect to your Bedrock friends
Like how there's ViaFabric/Multiconnect that let you connect to servers on different versions
Or similar to how there's Geyser allowing Bedrock users to connect to Java servers

There should be a mod allowing kinda the reverse 
(I wanna be able to play the fun maps that exist in the Bedrock marketplace with my friends in VR can't do that with Geyser)

**Comment by oliverwesley1** [comment]
I mean if you host a server that can be joined on java and bedrock, then you can play together that way. As joining servers is similar to vanilla Minecraft

**Comment by jakershaker1** [comment]
This is closed. Bedrock will not happen within the confines of this project at this time due to legal amd technical challenges as well as the fact the devs just don't want to do it.
