### ISSUE TITLE
Fabric 1.18.1 isn't present in the version list despite following installation to a T.

### ISSUE THREAD

**Issue by CallMeLexi** [QuestCraftPlusPlus/QuestCraft#11]
The title is pretty self-explanatory, but when I go to find 1.18.1 Fabric... It just flat-out isn't there. I looked at the bottom too, but the list simply stops at 1.0.

**Comment by CallMeLexi** [comment]
> i had the same problem

Did you get any sort of solution other than "you installed it wrong"? I followed the easy tutorial step by step.

**Comment by Exist43** [comment]
when the imposter is sus!

**Comment by Exist43** [comment]
don't be sus!

**Comment by Exist43** [comment]
sussy bakas

**Comment by Exist43** [comment]
sussssssssssssssssssssssssssssssssy

**Comment by Exist43** [comment]
Do your tasks

**Comment by Exist43** [comment]
im cleaning the vents

**Comment by Exist43** [comment]
uh oh, orange just saw me vent

**Comment by Exist43** [comment]
u guys are sussy bakers

**Comment by Exist43** [comment]
omg so sussy

**Comment by CrimsonClient06** [comment]
ur not funny

**Comment by ProtatoPlus** [comment]
@Exist43 github issues are for actual issues to be patched not to screw around if you want to screw around go to discord not github.

**Comment by IM-THE-GRASS** [comment]
What fixed it for me was not using Winrar or 7zip and instead using the one built into windows.

**Comment by ManiacGamer156** [comment]
Please use the new instructions on the release
