### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KlaysYT** [QuestCraftPlusPlus/QuestCraft#110]
Hit play but no warning screen then black screen and then red, and then crash

I don't know if it's something with my quest or not.

I thought it would work fine

 - Quest Build: v37.0
 - Device: Quest_1
 - QuestCraft Version 1.1.1

**Additional context**
I got it to work once, but then when i was fixing the render distance it froze, and hasn't been working since.

**Comment by wellsilver** [comment]
to fix it:
-restart
-open questcraft
-click "select account" nothing else

**Comment by ATXLtheAxolotl** [comment]
@KlaysYT did you manage to fix this?

**Comment by ATXLtheAxolotl** [comment]
> to fix it:
> -restart
> -open questcraft
> -click "select account" nothing else

I also don’t believe this would be the solution as he mentioned it broke upon changing render distance. I believe he just needs to edit the config files to fix it if he still has these problems.
