### ISSUE TITLE
Infinity 3 dot loading

### ISSUE THREAD

**Issue by CloudyEveryWhere** [QuestCraftPlusPlus/QuestCraft#115]
**Describe the bug**
When I start the game it loads forever

**To Reproduce**
1. Go to 'pojavlauncher'
2. Click on 'play
3. loads forever

**Expected behavior**
I downloaded some mods(they were on the mods list) they are all compatible and when I clicked play it never loaded. so I decided to increase ram, still didn't work.

**Headset Details (please complete the following information):**
 - Quest Build: [most recent]
 - Device: [Quest_2]
 - QuestCraft Version [most recent]

**Comment by Ma100Dev** [comment]
Same problem here, can confirm that the bug is reproducible.

**Comment by Ma100Dev** [comment]
Same problem here, can confirm that the bug is reproducible.

**Comment by srepmub** [comment]
same for me on quest 1.

**Comment by andiweli** [comment]
Same here on Quest 1

**Comment by mcdermott87** [comment]
Same here on Quest 1

**Comment by wellsilver** [comment]
-restart
-open questcraft
-click "select account" nothing else

**Comment by srepmub** [comment]
fixed for me by installing the APK from github, _and_ copying the extractroot.zip contents to the device. I guess I assumed it would just work after installing via the sidequest 'install' button.. but you really need the extractroot stuff I guess, otherwise the fabric loader won't even show up in the list.

**Comment by mcdermott87** [comment]
@srepmub As I see it it's identical to the SideQuest version. I have removed all files created on headset and reinstalled multiple times and it did not help. Tried to click "select account" but still, after 10 mins of "three dots" nothing happened.

**Comment by ATXLtheAxolotl** [comment]
> to fix it: -restart -open questcraft -click "select account" nothing else

> fixed for me by installing the APK from github, _and_ copying the extractroot.zip contents to the device. I guess I assumed it would just work after installing via the sidequest 'install' button.. but you really need the extractroot stuff I guess, otherwise the fabric loader won't even show up in the list.
> 
> so just download the APK and extractroot.zip from the questcraft releases page. then use sidequest to _manually_ install the APK and also to copy the exctractroot contents (on linux you need to drag-and-drop from e.g. nautilus).

Two solutions have been provided.

**Comment by IzzyDotExe** [comment]
Make sure you are using version 1.18.1 fabric. 

If anyone is still experiencing this issue, open a new ticket.
