### ISSUE TITLE
[BUG] Infinite black screen on launch

### ISSUE THREAD

**Issue by Ma100Dev** [QuestCraftPlusPlus/QuestCraft#116]
**Describe the bug**
Infinite black screen on launch after trying to install the latest version of lithium mod, even after deleting it

**To Reproduce**
1. Install QuestCraft as instructed
2. Play the game, works normally
3. Close the game, try installing Lithium mod
4. Try playing the game but see black screen instaed
5. Delete Lithium mod
6. Problem persists

**Expected behavior**
Game launches normally, at least after removing new mod

**Headset Details (please complete the following information):**
 - Quest Build: [latest]
 - Device: [Quest_2]
 - QuestCraft Version [latest]

**Additional context**
Latest version of Lithium [Lithium mc1.18.1-0.7.8](https://www.curseforge.com/minecraft/mc-mods/lithium/files/3659182) was used

**Comment by Leeo97one** [comment]
Here are the logs with crash: [2022-02-24-1.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8145361/2022-02-24-1.log)
Note that it also crashes on PC so I guess it is just a matter of updating Fabric.

**Comment by D2Lx0wse** [comment]
Wrong lithium, 0lease close the issue

**Comment by Ma100Dev** [comment]
Ok, seems like it's my bad. What lithium version should be used?

**Comment by Leeo97one** [comment]
[0.7.7](https://www.curseforge.com/minecraft/mc-mods/lithium/files/3590908)
