### ISSUE TITLE
[FEATURE] a way to see coordinates 

### ISSUE THREAD

**Issue by William-06** [QuestCraftPlusPlus/QuestCraft#117]
Could you make it so you can see coordinates.

Since the quest 2 cant support a high render distance it would be useful if you could pull up coordinates to find your base after exploring.

**Comment by IsraelAristide** [comment]
Some way to see fps and coordinates will be added at some point. No timeline yet.

**Comment by Mage-Enderman** [comment]
https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap

Both of these mods have the option to see coordinates

**Comment by Flopgop** [comment]
Stale.
