### ISSUE TITLE
[BUG] Boats moving to the wrong direction

### ISSUE THREAD

**Issue by Antorboy** [QuestCraftPlusPlus/QuestCraft#118]
**Describe the bug**
When riding a boat, pushing forward on the stick doesn't always make the boat go forward and maybe either turn left or right instead.

**To Reproduce**
1. Place a boat in the water,
2. Click on it to ride the Boat,
3. Put the stick forward navigate on the boat,
4. See the boat not going forward.

**Expected behavior**
The boat is following the direction given by the left stick.

**No ScreenshotsProvided**

**Headset Details:**
 - Quest Build: [v37.0.0]
 - Device: [Quest_2]
 - QuestCraft Version [1.1.1]

**Additional context**
It seems that the boat control is linked to the original direction the player is facing (before starting the game or holding the home button to reset the view) and looking in another direction "turn" the boat controls relative to the original direction.

**Comment by ArtifexFulguris** [comment]
I don't really think this is a bug. The boat just moves forward in whatever direction the front of the boat is facing... which is not necessarily where the player is looking. It is pretty disconcerting at first but there isn't anything really wrong with it.

**Comment by Irrelevent** [comment]
I think this is a good thing so that you can look at the landscape while sailing around.

**Comment by Antorboy** [comment]
The issue is when I look forward and press the thumbstick forward, it either spin on the left or right or try to go backward, wich is not intended.

**Comment by nikitavychuz** [comment]
If you sit down to where the in-game model would be and look straight ahead, the controls become normal again: it must be that the in-game controls and the position of the headset are conflicting with each other
