### ISSUE TITLE
[FEATURE] Smooth turn!

### ISSUE THREAD

**Issue by CD912** [QuestCraftPlusPlus/QuestCraft#119]
I want an option for smooth turn! Snap turn takes a lot of immersion out of the game for me, and i'm sure a lot of other people find it annoying that you have to use snap turn.

**Comment by nexioss** [comment]
i agreed

**Comment by Mage-Enderman** [comment]
Yeah same

**Comment by mwglen** [comment]
Same

**Comment by parkerlreed** [comment]
Snap being the "comfortable" option that games default to has always been weird to me. Jarring around feels WORSE than smooth. Agreed that smooth needs to be an option.

**Comment by IsraelAristide** [comment]
This will be added sometime in the future, no timeline just yet :)
