### ISSUE TITLE
[BUG] Crashes on title screen

### ISSUE THREAD

**Issue by kaiw1011** [QuestCraftPlusPlus/QuestCraft#12]
**Describe the bug**
Whenever I load QuestCraft, after 5-6 seconds, the game crashes

**To Reproduce**
1. Open QuestCraft
2. Crash

**Expected behavior**
Able to play Questcraft

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Comment by Exist43** [comment]
when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus! when the imposter is sus!

**Comment by Exist43** [comment]
Amogus

**Comment by Exist43** [comment]
Sus

**Comment by Exist43** [comment]
Im the imposter

**Comment by kaiw1011** [comment]
please stop

**Comment by JD-The-65th** [comment]
> Im the imposter

Don't. These issue reports are serious, if you wanna be unfunny, go to #off-topic in the qc discord

**Comment by Exist43** [comment]
you guys are sussy af

**Comment by Exist43** [comment]
im the imposter though so I vented

**Comment by kaiw1011** [comment]
please go to #off-topic

**Comment by Exist43** [comment]
I dare you to say Invented without the first N

**Comment by kaiw1011** [comment]
stop

**Comment by Exist43** [comment]
sus

**Comment by kaiw1011** [comment]
these are serious reports

**Comment by Exist43** [comment]
maybe you are the imposter

**Comment by Exist43** [comment]
were you doing your tasks?

**Comment by kaiw1011** [comment]
everyone can see this you know?

**Comment by JD-The-65th** [comment]
Please actually fill out the issue template and note which Quest Version you're using, and which device. Also, do you mind sending us a crash report? The crash reports are saved in
Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/logs/latest.log

**Comment by Exist43** [comment]
you guys are sussy bakas

**Comment by CrimsonClient06** [comment]
pov: **not funny** @Exist43

**Comment by Exist43** [comment]
you guys are the amogus imposters

**Comment by Exist43** [comment]
amogus sus
