### ISSUE TITLE
[BUG] stuck on infinite black screen 

### ISSUE THREAD

**Issue by jim-commits-sometimes** [QuestCraftPlusPlus/QuestCraft#120]
**Description**
when i hit play and let it load it just gets stuck on a black screen with the loading dots

**To Reproduce**
1. start pojavlauncher
2. click on the proper settings and fabric
3. press play

**Expected behavior**
the game would boot up as normal

**Screenshots**
screenshot would just be black loading screen

**Headset Details :**
 - Quest Build: [v37.0]
 - Device: [ Quest_2]
 - QuestCraft Version [v1.1.1]

**Comment by gusbunce** [comment]
Have you been able to play the game previously without error?

**Comment by jim-commits-sometimes** [comment]
nope this was an issue since when i downloaded the apk to my headset

**Comment by andiweli** [comment]
Can confirm, same issue.
Quest (1), latest firmware, 50gb free mem.

**Comment by Dieber** [comment]
Can confirm, same issue.
Quest (2),latest firmware, 20gb free mem

**Comment by PoDiax** [comment]
> 

Can confirm, same issue, 
I completely removed app,  then reinstalled, no result.
Latest stable firmware 85 GB free.

**Comment by IsraelAristide** [comment]
This is a known issue, please check in our discord in the #common-issues channel, if nothing still works send your net.kdt.pojavlaunch.debug folder as a zip here.

**Comment by joemama4556** [comment]
same here and how do u send the bug zip here

**Comment by andiweli** [comment]
Here's my log...

`
--------- beggining with launcher debug
Info: Launcher version: null
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-opengles-natives-linux-arm64.jar, lwjgl-opengles.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10
--------- beginning of system

--------- beginning of main

[WARNING:spdy_session.cc(3232)] Received HEADERS for invalid stream 11
--------- beggining with launcher debug
Info: Launcher version: null
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-opengles-natives-linux-arm64.jar, lwjgl-opengles.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10
--------- beginning of main

--------- beginning of system

[WARNING:spdy_session.cc(3232)] Received HEADERS for invalid stream 11
--------- beggining with launcher debug
Info: Launcher version: null
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-opengles-natives-linux-arm64.jar, lwjgl-opengles.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10
--------- beginning of main

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!

read: unexpected EOF!
`

**Comment by korben546** [comment]
Are you using the fabric profile because that log looks like you are trying to load vanilla minecraft and that won’t work

**Comment by andiweli** [comment]
tried also with 1.16.4 and .16.5 - same issue
tried several renderers - same issue

**Comment by oliverwesley1** [comment]
the only version supported is the 1.18 fabric version. afaik there isnt any support for older versions like 1.16.4 or 1,17,1 as shown in that log. try following the instructions and using the correct version and launcher. 

also in future when your submitting bug reports read the others to see if there is a similar issue

**Comment by wellsilver** [comment]
please read #common-issues in the discord, the way to solve it is by clicking "select account" when logging in. 
This won't fix @andiweli 's problem (it is more serious)

**Comment by wellsilver** [comment]
> * tried also with 1.16.4 and .16.5 - same issue
> * tried several renderers - same issue
> * also tried sidequest version now - first apk fails (/data/local/tmp/_stream.apk could not be installed (install_failed_version_downgrad) - second apk installs OK - game also refuses to start, 3 dots of death :)

3 dots "of death" isnt "of death" its just a loading screen. 
The only supported version is 1.18 do not use any other versions.
The only supported renderer is the one provided. Dont use any other renderers
There is only one apk you install.

I recommend you RE-INSTALL questcraft the CORRECT way, link to the tutorial is [here](https://youtu.be/O2amKbJ09HI) click on "[here](https://youtu.be/O2amKbJ09HI)" and follow the videos instructions

**Comment by ATXLtheAxolotl** [comment]
> please read #common-issues in the discord, the way to solve it is:
> 
> restart launch pojav click "select account" instead of logging in, select the account you would like to use

Common problem and has already been addressed in this comment thread.

**Comment by IzzyDotExe** [comment]
It has been mentioned in this issue but I will say it again

!!DO NOT use any version of Minecraft that is not 1.18.1-fabric!! 

1.18.1-fabric is the only version that is supported currently. 

1.18.2 will be added in update 1.2.0

**Comment by IzzyDotExe** [comment]
If anyone is still experiencing this issue open a new issue or open a ticket in our discord.
