### ISSUE TITLE
[FEATURE] The ability for pc players to see hand movement of QuestCraft user(s)

### ISSUE THREAD

**Issue by davidkra230** [QuestCraftPlusPlus/QuestCraft#121]
**Is your feature request related to a problem? Please describe.**
this feature request is related to the issue/ bug of mcxr core (both questcraft and mcxr) not allowing the ability to see quest players hand movement.

**Describe the solution you'd like**
external mod for pc users

**Describe alternatives you've considered**
none.

**Additional context**
pc users cannot see the hand movement of quest players but instead, pc users see the default animations.

**Comment by sethpeace** [comment]
Without a mod this is impossible. Do you mean with a modded pc client?

**Comment by gusbunce** [comment]
So this isn't actually possible without a mod on pc. Which would in itself be pretty demaning. Maybe look at asking Sorenon in the MCXR Discord.
