### ISSUE TITLE
[FEATURE]: Better Binding Menu

### ISSUE THREAD

**Issue by TheMilkman001** [QuestCraftPlusPlus/QuestCraft#122]
**Is your feature request related to a problem? Please describe.**
This isn't really a problem, I would just like a better binding system where half of the buttons aren't [Unknown} or left mouse
**Describe the solution you'd like**
Make it so you can bind actions to buttons and see what they're binded to
**Describe alternatives you've considered**
there really arent any other than "just deal with it"

**Comment by gusbunce** [comment]
We will look at this. I personally think it could be beneficial. Maybe in release v1.2.0. We don't know yet.

**Comment by Flopgop** [comment]
Stale.
