### ISSUE TITLE
[BUG]Worlds freeze then crash above 3 Chunk Render Distance

### ISSUE THREAD

**Issue by Rykst3r** [QuestCraftPlusPlus/QuestCraft#123]
**Describe the bug**
Having your game's render distance set above 3 chunks may result in the game crashing upon creating/loading a world.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Video Settings'
3. Slide 'Render Distance' to anything above 3 (Game may crash while sliding the slider, so that is another bug that has already been reported)
4. If your game does not crash from just sliding the slider, load up an existing world or create a new one.
5. Game will freeze (as expected) but then crash shortly after, booting you to Oculus Home

**Expected behavior**
The 'sweet spot' for render distance on Oculus Quest 2 is around 6 chunks (supposedly).

**Screenshots**
I do not have any screenshots to provide.

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Oculus Quest 2 (64GB)
 - QuestCraft Version: Latest (As of writing)

**Additional context**

**Comment by gusbunce** [comment]
Do you have all the mods for optimization? Worst case scenario please reinstall qc.

**Comment by Rykst3r** [comment]
> 

I do have all the optimization mods installed, but it ain't a big deal for me. However, others may get peeved if it's plaguing them too. I only made this report so that it's known and eventually gets fixed for others. I'm not one that cares much about good graphics. As long as it runs, I'm happy.

**Comment by JD-The-65th** [comment]
Did you set your graphics to fancy? Afaik this bug was fixed.

**Comment by RealityXP** [comment]
*fabulous settings

**Comment by IzzyDotExe** [comment]
Does this still happen to you? @Rykst3r if so can you reproduce it and send the crash log?

**Comment by Rykst3r** [comment]
It is no longer happening to me. I can now have it set above 3 chunks. Currently have it set to 5 chunks but 6 chunks also works. The issue was I had clouds on.
