### ISSUE TITLE
Enable Microphone permissions?

### ISSUE THREAD

**Issue by wooperTM** [QuestCraftPlusPlus/QuestCraft#124]
Questcraft isnt able to use mods like voice chat because the mod isnt able to reconize that there is a microphone,

Can that be fixed? or at least have the ability to turn it on without it requesting it.

**Comment by gusbunce** [comment]
I can take a look at having an option to request microphone access.

**Comment by gusbunce** [comment]
With discussion with the other devs they have discovered that mic support does not work with qc. Sorry.

**Comment by wooperTM** [comment]
Ouch that sucks
