### ISSUE TITLE
[BUG] Infinite Red Screen Loading

### ISSUE THREAD

**Issue by monkemungus** [QuestCraftPlusPlus/QuestCraft#125]
Whenever I press play on the pojavlauncher, it goes to a red screen but it never loads, I've waited for it to load for 20 minutes sometimes.

1. Go to PojavLauncher
2. Click on Play

**Expected behavior**
I expected to load into the game.

**Screenshots**
I can't add screenshots

**Headset Details (please complete the following information):**
 - Quest Build: 37.0
 - Device: Quest 1
 - QuestCraft Version: 1.1.0

**Comment by IsraelAristide** [comment]
Please join our discord and check the #common-issues channel to solve your issue

**Comment by ATXLtheAxolotl** [comment]
Are you using the Fabric version?

**Comment by ATXLtheAxolotl** [comment]
profile*

**Comment by gusbunce** [comment]
If you are still having issues send me your latestlog.txt. gus#0069.
