### ISSUE TITLE
[FEATURE] Easy 1.18.1 Modloader

### ISSUE THREAD

**Issue by Cartrigger** [QuestCraftPlusPlus/QuestCraft#126]
When some people installed, they were unable to get 1.18.1 and or other jars. It would make it easier if you had a cached jar or some kind of download for easy installing. 

When people press a "Install Jar" they can pick between the jars that are in that are in cache or in a file, it will make it easier for everyone if they want to have support, or they want a older fabric versions.

Have a file browser integrated and have the user pick from installed fabric install jars. (Like install jars folder on SQ or File Explorer ETC... Doesn't Pojav have some GUI already for installing jars?)

Replace that jar install button, or put it in settings.

**Comment by IsraelAristide** [comment]
Seems interesting, we will look into it.

**Comment by gusbunce** [comment]
I am happy to look into this. Maybe a http server with a database with the links to the jar's, that then download to the quest.

**Comment by IzzyDotExe** [comment]
This feature is in active development, discuss it here.
