### ISSUE TITLE
[BUG] QC can not reload shaders for some reason when nor iris or optifine is installed. Quest 2.

### ISSUE THREAD

**Issue by Mysticpasta1** [QuestCraftPlusPlus/QuestCraft#127]
**Describe the bug**
When trying over and over again to install and reinstall, QC will load with 3 dots then red screen then crash with a crash report in the files while it looks like it is hanging up in the quest.

**Current behavior** 
logging in: normal
starting up: normal
loading: three dots then red screen, then crash report in file (looks like a normal crash to hanging in quest)

**to Reproduce**
[net.kdt.pojavlaunch.debug.zip](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8138300/net.kdt.pojavlaunch.debug.zip)
using the following files, (should be the same files as in QC install download)
using the following steps provided in sidequest/github/discord for installation of QC provided by the devs

**Expected behavior**
Loading to be normal and to be able to load into the game.

**Screenshots**
I don't know how to take a screenshot when loading into a crash like this

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest_2
 - QuestCraft Version 1.1.1

**Additional context**
Here is the crash report that was in the files: 
[crash-2022-02-25_03.19.07-client.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8138324/crash-2022-02-25_03.19.07-client.txt)
I don't know why this is happing exactly but it seems shader based looking at the class that are crashing.

**Comment by Flamgop** [comment]
Shaders are referring to core shaders.

**Comment by Flamgop** [comment]
The zip you included is missing a lot of files. I recommend re-downloading the zip and re-installing it.

**Comment by Mysticpasta1** [comment]
ok I got the base game working but now when I try to put the mod https://www.curseforge.com/minecraft/mc-mods/atlantis in I'm getting the same error.

**Comment by Mysticpasta1** [comment]
I'm the lead dev of the mod Atlantis and I don't have any shader code in my mod afaik

**Comment by IzzyDotExe** [comment]
> I'm the lead dev of the mod Atlantis and I don't have any shader code in my mod afaik

Unfortunately were unable to provide support for other developers when it comes to their mods being incompatible with questcraft. Do let us know if ever you figure this out though so we can add Atlantis to the compatibility megalist.
