### ISSUE TITLE
[FEATURE] Mod gui

### ISSUE THREAD

**Issue by ultimatexilliam** [QuestCraftPlusPlus/QuestCraft#129]
I think that always checking the compatible mod list when installing mods is too hard and its also frustrating.

I would like a GUI where you could select your mods. There would be mods that fully support QC and if a mod doesn't fully yet, there would be a warning before install. To make searching easier, there would be a search bar. The categoryising wold happen like in curseforge. Clear and simple categoryes of mods.

I have tried none alternatives

A (very) quick sketch i made about the gui

![Sketch.jpg](https://user-images.githubusercontent.com/78660109/155675109-c2caa319-b197-4cf3-a24c-51b54c621e50.jpg)

**Comment by IsraelAristide** [comment]
#126 Duplicate, we're currently talking about how to implement this.
