### ISSUE TITLE
Hand-Tracking[FEATURE]

### ISSUE THREAD

**Issue by slodkipiesio** [QuestCraftPlusPlus/QuestCraft#132]
For me. It would be verry fun if u will be able to use hand-tracking i know i know its hard BUT imagine play minecraft on VR and u will be able to set down block with gestures or crafting an item with gestures!

**Comment by jakershaker1** [comment]
No. Just. No.

**Comment by IsraelAristide** [comment]
> No. Just. No.

Yes, just yes. This is a planned feature. No timeline yet tho.

**Comment by oliverwesley1** [comment]
How would you move tho??? There's isn't enough gestures to have all of the binds

**Comment by IsraelAristide** [comment]
> How would you move tho??? There's isn't enough gestures to have all of the binds

Only certain actions would be done with gestures such as fighting, eating, breaking blocks etc...

**Comment by oliverwesley1** [comment]
Ohhh I thought they meant hand tracking, like without controllers, this is what I was referring to be impossible  and I think jakershaker was thinking the same as me

**Comment by jakershaker1** [comment]
I meant immpossible for no controllers. If you were crazy you could add to the project support for the lucid vr gloves but that would be an afterthought.

**Comment by oliverwesley1** [comment]
Hand-Tracking[FEATURE]
when i read hand tracking i think of no controllers

**Comment by ManiacGamer156** [comment]
Can't do this unfortunately.
