### ISSUE TITLE
[BUG]There is not fabric version to pick!!Thank u😁

### ISSUE THREAD

**Issue by JonGaming** [QuestCraftPlusPlus/QuestCraft#133]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by IsraelAristide** [comment]
You did  not fill out the template. Please fill out another issue with all the information so we are able to help you.
