### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KeparYTbcc** [QuestCraftPlusPlus/QuestCraft#137]
Hi i have an oculus quest 2,
I downloaded everything correctly,

I start the game, it load, (Black screen with the 3 dots),
i start hearing the music, but infinite loading screen...

**Comment by FlyingBlooper** [comment]
You gotta load the fabric launcher on the bottom of the versions

**Comment by ATXLtheAxolotl** [comment]
Did you choose the fabric launcher as asked above.
Did you try:
"for everyone getting infinite loading, reboot your quest, open pojav launcher and hit select account after previously signing in."
