### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mmdgamer** [QuestCraftPlusPlus/QuestCraft#139]
When I log in as offline account and then select fabric 1.12-1.18 and press play it tells me
Error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
And a bunch of other errors if I press show more. Any ideas how to fix this?

>

**Comment by dugo3number2** [comment]
Reinstall

**Comment by mmdgamer** [comment]
I was skeptical because I thought I did everything right but after reinstalling it worked, thanks.
