### ISSUE TITLE
Application presents error when logging in with Microsoft

### ISSUE THREAD

**Issue by SneakyAssasin01** [QuestCraftPlusPlus/QuestCraft#14]
![image](https://user-images.githubusercontent.com/76673155/155044285-77f6110b-8caf-412a-a376-432080aef5ca.png)
I keep getting this error when I try to login with Microsoft. 

How to recreate:

1. Open pojavlauncher
2. Press Microsoft Login
3. Enter login details
4. Receive Error

**Comment by dugo3number2** [comment]
Not getting this error, I logged in just fine.

**Comment by SneakyAssasin01** [comment]
Okay, Restarted the headset, didnt help, Reset the appdata and relogged in with a different microsoft account and it works.
