### ISSUE TITLE
[FEATURE] Fire a bow like an actual bow

### ISSUE THREAD

**Issue by kaiw1011** [QuestCraftPlusPlus/QuestCraft#143]
**Is your feature request related to a problem? Please describe.**
No, I just have a feature I think will be cool

**Describe the solution you'd like**
I would like to be able to pull back the string on my bow with my other hand

**Describe alternatives you've considered**
Faking it

**Additional context**
None

**Comment by IzzyDotExe** [comment]
No eta but this is on the idea board and its most likely gonna be added in the future.
