### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Moscatel70** [QuestCraftPlusPlus/QuestCraft#147]
**Describe the bug**
i installed the game a few minutes ago and I start the game it boots to just red then it goes into a loading loop 
**To Reproduce**
1. Go to 'Launcher'
2. Click on 'play'

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [v37.0]
 - Device: [Quest_2]
 - QuestCraft Version [  v1.1.0]

**Additional context**

**Comment by ATXLtheAxolotl** [comment]
Is there a crash log?
