### ISSUE TITLE
[FEATURE] Geyser but the reverse (Not another basic request for Bedrock VR)

### ISSUE THREAD

**Issue by Mage-Enderman** [QuestCraftPlusPlus/QuestCraft#148]
I feel this is slightly outside the box for QuestCraft as it'd just kinda be useful in general not just for this but
Maybe a mod to allow you to connect to your Bedrock friends
Like how there's ViaFabric/Multiconnect that let you connect to servers on different versions
(or ViaVersion that let users connect from different versions for servers)
Or similar to how there's Geyser allowing Bedrock users to connect to Java servers

There should be a mod allowing kinda the reverse
(I wanna be able to play the fun maps that exist in the Bedrock marketplace with my friends in VR can't do that with Geyser)

**Comment by jakershaker1** [comment]
This is too out of box for this project. There are too many technical challenges for this to even be considered. If someone wants to make their own mod for this concept the devs would consider supporting it.

**Comment by bootrec-exe** [comment]
I agree with @jakershaker1 because this isn't really something that deals with QuestCraft, it would be more in line with a normal Java mod. You might have some luck asking someone from the ViaVersion or the Geyser team if they would be interested in making something like you said. It still sounds like a good idea though!

**Comment by IzzyDotExe** [comment]
This isn't a valid questcraft feature request, and not something we're going to work on. This would be a completly separate project and Is most likely impossible.

**Comment by Mage-Enderman** [comment]
> I wanna be able to play the fun maps that exist in the Bedrock marketplace with my friends in VR can't do that with Geyser

You seemingly didn't read the last bit
I wanna be able to play the fun maps that exist in the Bedrock marketplace with my friends in VR can't do that with Geyser

**Comment by ATXLtheAxolotl** [comment]
Well as stated above this certainly is not a QuestCraft project. QuestCraft is for the Java Edition, if you desire this so badly you can use an Oculus Go Minecraft APK as I’ve said before or use Oculus Link with a Windows 10 PC and launch MC bedrock on the oculus app.

**Comment by ATXLtheAxolotl** [comment]
> This isn't a valid questcraft feature request, and not something we're going to work on. This would be a completly separate project and Is most likely impossible.

Also btw it’s not most likely impossible but just extremely difficult.

**Comment by Mage-Enderman** [comment]
> Well as stated above this certainly is not a QuestCraft project. QuestCraft is for the Java Edition, if you desire this so badly you can use an Oculus Go Minecraft APK as I’ve said before or use Oculus Link with a Windows 10 PC and launch MC bedrock on the oculus app.

I get that.. wasn't replying to you? (intentionally anyhow)

Plus I did start this off with "I feel this is slightly outside the box for QuestCraft"

**Comment by jakershaker1** [comment]
Can we lock this ticket? This is going nowhere.
