### ISSUE TITLE
Start button registering and also joystick clicks

### ISSUE THREAD

**Issue by EyaeM** [QuestCraftPlusPlus/QuestCraft#150]
Baccicly add a way to use joystick clicks and the start button also add a way to open chat so we can click on stuff In servers

**Comment by IzzyDotExe** [comment]
Chat and new bindings are coming in version 1.2.0

**Comment by Mage-Enderman** [comment]
> 

Already working on it and requested please look around before submitting "new" things
https://github.com/QuestCraftPlusPlus/QuestCraft/issues/98
