### ISSUE TITLE
[FEATURE] basically everything

### ISSUE THREAD

**Issue by sona53773** [QuestCraftPlusPlus/QuestCraft#151]
I understand that lag is an issue that will take a long time to add but it would be great if you focused on some quality of life features like a keyboard so we can use chat and add servers. also, a cursor in the menus would be a big game-changer.

what I would like to see most is being able to hit mobs by actually swinging your controller at them because it would make the experience so much more immersive. without this feature it kind of just feels like your playing the gear VR version except you have hands. 

I'm not saying that quest craft is bad because I have been playing it every day since it was released but I am saying it would be so much better if you add these features.

thankyou for reading and i hope you listen to me.

**Comment by jakershaker1** [comment]
These are all planned features but the mod QCXR is based on (mcxr) has a few growing pains of its own. Just wait and they will eventually be added.

**Comment by IzzyDotExe** [comment]
Please only request one feature at a time.

All of these requests are also duplicates of already existing feature requests. They are coming in future updates.
