### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BigMat06** [QuestCraftPlusPlus/QuestCraft#154]
Black infinite loading screen. Whenever I try to load in, it either kicks me out of the app or there is just a black loading screen with 3 dots.
Oculus quest 2
I haven’t downloaded any mods for it, I tried resetting my headset, and nothing works.

**Comment by ATXLtheAxolotl** [comment]
Have you tried “For everyone with the 3 dots loading for more than 1-3 minutes, press the Oculus button and close PojavLauncher, tick keep me logged in once you have rebooted PojavLauncher and log in, and then launch the game again.”
