### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sajaprity** [QuestCraftPlusPlus/QuestCraft#155]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] no

**Describe the solution you'd like**
A clear and concise description of what you want to happen. pc and other vr players being able to see your movements and being able to swing and punch to attack

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. idk

**Additional context**
Add any other context or screenshots about the feature request here. nop

**Comment by Declipsonator** [comment]
real great feature right here

**Comment by jakershaker1** [comment]
This is a planned feature. A mod will be required for pc users to see vr movements. And motion controls are coming but the devs are more worried about the game reliable launching and closing at the moment.
