### ISSUE TITLE
[BUG] the game doesnt launch if you change the video resolution using sidequest

### ISSUE THREAD

**Issue by IDEKWHATCHaTHINK** [QuestCraftPlusPlus/QuestCraft#157]

**Comment by jakershaker1** [comment]
please give a description of the issue you are experiencing.

**Comment by QuestCraftEnjoyer** [comment]
> please give a description of the issue you are experiencing.

if you change the video resolution using sidequest the game doesn't launch

**Comment by ManiacGamer156** [comment]
Use the template, as for the issue, go change the resolution back to default, probably something we can not fix
