### ISSUE TITLE
[FEATURE] Aiming Projectiles with Hand

### ISSUE THREAD

**Issue by Scothulu** [QuestCraftPlusPlus/QuestCraft#158]
So I was testing out QuestCraft for the first time, and probably one of the more mildly annoying things is having to aim with your head for things like Bows or Crossbows. It ends up really bugging me out and I’m hoping it gets added in one of the upcoming versions.

**Comment by Scothulu** [comment]
> Duplicate of #143
Not really what I was meaning, I meant that when you fire from a bow, it fires from your face, not your hand. Which is weird, since you can normally attack with you hand with swords

**Comment by ATXLtheAxolotl** [comment]
Oh never mind my bad I had misread this one

**Comment by ReubenDollmanYT** [comment]
Only reason it currently is this way is so servers dont break as you normally look where you face whats stopping you from shooting were you are not looking then getting slapped with a ban
