### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mmdgamer** [QuestCraftPlusPlus/QuestCraft#160]
**Describe the bug**

After I installed the recommended mods and I try to launch fabric I get a black screen then the guardian flashes for a second and three dots appear which take forever.
Note: if I move my hands I can hear and feel the controller selecting stuff

**To Reproduce**
1. Installed using the official youtube tutorial 
2. Launched the game and played normally for a bit 
3. Pressed the oculus button and clicked quit game while still in the world (to try and install the mods)
4. Downloaded all the recommended mods and copied them to the mods folder
5. Started the launcher again without restarting
**Expected behavior**
I expected the game to work normally since it did without mods

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v37
 - Device: Quest_2
 - QuestCraft Version 1.1.1

**Additional context**
I was using the third renderer and 3000 ram and also logged in as offline account.
Restarting didn’t help.
someone else on discord had the same problem as me

**Comment by William-06** [comment]
If removing the “Pling“ mod doesnt work try removing all the mods you downloaded, but dont remove the mods that where already in the mod folder. then add each mod individually and test them all on thier own to see wich work and wich dont. after that you can put all the ones that work into the mod folder. Hope this helps.

**Comment by ATXLtheAxolotl** [comment]
Could you provide us a list of mods you've used.

**Comment by mmdgamer** [comment]
Sorry forgot to mention this but lithium 0.7.8 was causing it. I tried 0.7.7 and it worked perfectly. Not just me everyone who had the same issue was because of lithium 0.7.8 so I recommend putting a warning to install 0.7.7 because I’m pretty sure 0.7.8 is broken

**Comment by ATXLtheAxolotl** [comment]
Could you close the ticket then since you've found the solution.

**Comment by mmdgamer** [comment]
Sure

**Comment by CheatEvent** [comment]
Offline mode isn't supported (if i remember correctly)
