### ISSUE TITLE
[BUG] Crashes on world load

### ISSUE THREAD

**Issue by BoxOfUnity** [QuestCraftPlusPlus/QuestCraft#163]
**Describe the bug**
I created a survival world- now every time I try to load it, it crashes. (crashed as soon as I created it too)
the only thing I've seen so far is that it's missing- "Sodium"? Or something like that... and I haven't a clue what that is, or where I might download or enable it.

**To Reproduce**
1. Launch
2. Click single player mode- top option
3. Select the single player survival world previously created
4. Press play
5. Immediately experience a freeze. (The kind where it shows one way in front of you- and completely upside down when you turn around.) 

**Expected behavior**
It is expected that the world loads for the entertainment of its creator.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: I remain uncertain where one finds this information-
 - Device: Meta: Oculus Quest 2
 - QuestCraft Version: v1.11 I believe?

**Additional context**
The log file contained the following
"--------- beggining with launcher debug
Info: Launcher version: null
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-opengles-natives-linux-arm64.jar, lwjgl-opengles.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1"

Selected version was not 1.18.1 but in fact the "fabric" (I think) version found at the bottom of the version list
Also, I find it difficult to understand how the launcher version was null-

Well if any of you know how to help, it would be well appreciated.
     Thank you,
        -B.O.U.

**Comment by Tommi2a** [comment]
I have the bug, too

**Comment by BoxOfUnity** [comment]
Was this fixed? Is that why this Issue was closed?
