### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by CitruFruit** [QuestCraftPlusPlus/QuestCraft#164]
**Is your feature request related to a problem? Please describe.**
The Nausea effect when entering a nether portal is well, Nauseating.

**Describe the solution you'd like**
I would love a way to turn off the effect.

**Describe alternatives you've considered**
An alternative would be the ability to disable any effects that take up the screen (For example, the red overlay when you die)

**Additional context**
No additional context needed.

**Comment by ATXLtheAxolotl** [comment]
Didn’t read all the details but I believe this is a duplicate of #134

**Comment by IzzyDotExe** [comment]
#134
