### ISSUE TITLE
[BUG] No fishing bubbles

### ISSUE THREAD

**Issue by Kealam** [QuestCraftPlusPlus/QuestCraft#165]
**Describe the bug**
A clear and concise description of what the bug is. Bubbles do not show when a fish is approaching your fishing rod hook.

**To Reproduce**
1. Throw your fishing hook out onto water.
2. Wait for fish.
3. See the hook dip down into water without bubbles approaching beforehand.
4. Reel in the hook and catch fish.

**Expected behavior**
A clear and concise description of what you expected to happen. I expected to see bubbles approaching my hook indicating a fish was approaching.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest 1
 - QuestCraft Version v1.1.1

**Additional context**

**Comment by oliverwesley1** [comment]
this is probably due to your particle settings, change them from minimal to decreased. this should probably fix that
