### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Stealthr** [QuestCraftPlusPlus/QuestCraft#167]
**Describe the bug**
The game doesn't load, nomatter what. I copied my friends exact working settings, then it didn't work for me or him. Doesn't even load.

**To Reproduce**
Try play the game

**Expected behavior**
The game to work

**Screenshots**
3 dots

**Headset Details (please complete the following information):**
 - Quest Build: 37.0
 - Device: Quest 2
 - QuestCraft Version Latest

**Additional context**
WHY RELEASE A GAME WITHOUT ANY QA

**Comment by WafflesDev** [comment]
There's a FAQ in the [official discord](https://discord.gg/questcraft).

**Comment by ATXLtheAxolotl** [comment]
Have you tried:
"for everyone getting infinite loading, reboot your quest, open pojav launcher and hit select account after previously signing in."

**Comment by Stealthr** [comment]
Yeah, entire FAQ Tried, nothing works
