### ISSUE TITLE
[BUG]Nothing renders when tracking is disabled

### ISSUE THREAD

**Issue by Dawidak** [QuestCraftPlusPlus/QuestCraft#169]
**Describe the bug**
When your room is too dark and tracking is disabled Minecraft launches, you can hear the music but everything is black. I know it's probably not meant to be played that way but a lot of games that are blocked without 6DOF tracking are working pretty well in 3DOF, eg. Beat Saber, VRChat or Open Brush.

**To Reproduce**
1. Turn off tracking (dark room or in settings)
2. Launch Minecraft
3. Wait until a red screen
4. After a red screen is gone you are stuck on a black screen but can hear sounds

**Expected behavior**
The game should render normal like with 6DOF tracking

**Screenshots**
*Imagine a screenshot of darkness*

**Headset Details (please complete the following information):**
 - Quest Build: v37.147.0
 - Device: Quest_2
 - QuestCraft Version: 1.0.0 and 1.1.0

**Additional context**
I opened the log file and where it normally writes: "Loaded 0 advancements" additionally it writes every ms: "Invalid headset position, try restarting your device"

**Comment by ManiacGamer156** [comment]
Can't fix this because of how the "tracking" system is implemented in Oculus.
