### ISSUE TITLE
Cant Change Items in Hotbar

### ISSUE THREAD

**Issue by totallyJM** [QuestCraftPlusPlus/QuestCraft#170]
**Describe the bug**

**To Reproduce**
1. Press the buttons to change hotbar items
2. See its not working

**Expected behavior**
I expected my selected item to change

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0] v37.0
 - Device: [e.g. Quest_1, Quest_2] - Quest 2
 - QuestCraft Version [e.g. v1.2.3] - 1.1.1 or whatever the latest version is

**Additional context**

**Comment by ATXLtheAxolotl** [comment]
Do you have a recording? I personally haven't run into this problem and I'm quite curious about this one.

**Comment by ManiacGamer156** [comment]
Up and down on right stick
