### ISSUE TITLE
[BUG] Java 8 problem

### ISSUE THREAD

**Issue by Ashrindy** [QuestCraftPlusPlus/QuestCraft#172]
So I've been trying to setup QuestCraft for like 2 days, but always it would say: Java 8 needs to be installed.
Can someone please tell me if I am dumb and missed something, or if it's a bug.

I've expected just to launch the fabric 1.18.1 and play, but nope.

 - Quest Build: 37.0.0.147
 - Device: Quest 2
 - QuestCraft Version 1.1.1

**Comment by sdpixl** [comment]
> So I've been trying to setup QuestCraft for like 2 days, but always it would say: Java 8 needs to be installed. Can someone please tell me if I am dumb and missed something, or if it's a bug.
> 
> I've expected just to launch the fabric 1.18.1 and play, but nope.
> 
> * Quest Build: 37.0.0.147
> * Device: Quest 2
> * QuestCraft Version 1.1.1

You have had some sort of user error when installing. Please refer to our [tutorial](https://www.youtube.com/watch?v=O2amKbJ09HI) or if that does not work, check our recent fix in #common-issues in our discord.
