### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ramack1** [QuestCraftPlusPlus/QuestCraft#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to see XYZ coordinates added,like they do on bedrock version.

**Describe alternatives you've considered**

**Additional context**

**Comment by jakershaker1** [comment]
planned feature. just be patient.

**Comment by Mage-Enderman** [comment]
https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud

**Comment by ramack1** [comment]
Is that a trusted Mod for QuestCraft?

**Comment by jakershaker1** [comment]
Probably not a guaranteed functional mod but i dont see why it wouldnt work

**Comment by Mage-Enderman** [comment]
> Probably not a guaranteed functional mod but i dont see why it wouldnt work

I guarantee it *can* function
Functions perfectly fine for me on my Quest 2

**Comment by ramack1** [comment]
Thanks for everyone's help.👍

**Comment by IzzyDotExe** [comment]
Please fully fill out the template or delete parts that you feel aren't necessary next time! Thanks.

**Comment by ramack1** [comment]
No Problem thanks.👍
