### ISSUE TITLE
my game keeps crashing on entering[BUG]

### ISSUE THREAD

**Issue by darksaizow** [QuestCraftPlusPlus/QuestCraft#177]
once i open questcraft it puts me in a loading screen, the after a while it gets all red then crashes its really annoying

i was supposed to be sent to the main menu of minecraft 

Quest craft is 1.1.1 and my vr is oculus quest 2

**Comment by gusbunce** [comment]
@darksaizow if you could please upload your latestlog.txt that would be great!
