### ISSUE TITLE
[BUG] empty map not reacting when using the interact button

### ISSUE THREAD

**Issue by tylerhacker999** [QuestCraftPlusPlus/QuestCraft#178]
**Describe the bug**
The empty map, once created, does not work when using the interact button(left trigger). 

**To Reproduce**
1. enter world
2. make a Compass and 8 Paper 
3. go to crafting table and make map
4. put map in off hand and use left trigger to fill empty map, then use left trigger to try and read it

**Expected behavior**
For the map to display your location and surrounding terrain properly

**Screenshots**
Could not aquire, but if do will post in the comments

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [ Quest_2]
 - QuestCraft Version [Fabric version 0.12.12-1.18]

**Additional context**
Would be better for the map to always appear open when in off hand, once its initially created.

**Comment by tylerhacker999** [comment]
Also was curious what programming language you were using as well.

**Comment by ATXLtheAxolotl** [comment]
Java for the MCXR and Pojav but I believe Pojav uses some C.

**Comment by ManiacGamer156** [comment]
I will look into this

**Comment by gusbunce** [comment]
Will now close issue and label with "looking into it".
