### ISSUE TITLE
[BUG] Stuck on loading game can only see 3 dots

### ISSUE THREAD

**Issue by zmanbro** [QuestCraftPlusPlus/QuestCraft#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Ethanscharlie** [comment]
yup

**Comment by JD-The-65th** [comment]
Please actually fill out the issue template, or else the devs will not be able to help you

**Comment by Ethanscharlie** [comment]
fixed with "tick keep me logged in"

**Comment by 1percentbattery** [comment]
@Ethanscharlie keep me logged in doesnt work if youve migrated your account and you have to login with microsoft

**Comment by Xe-k** [comment]
it does work actually, i migrated mine and it still works.

**Comment by 1percentbattery** [comment]
huh. it doesnt work for me

**Comment by gusbunce** [comment]
Please make sure you click _**keep me logged in**_ also refer to this [message](https://discord.com/channels/820767484042018829/820788932123688960/945501497968443453) in the discord for help.
