### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ScowlingZebra** [QuestCraftPlusPlus/QuestCraft#180]
**Is your feature request related to a problem? Please describe.**

It is slightly a problem for people that can't use PC

**Describe the solution you'd like**

Make a similar UI as bmbf while trying to add mods. You can manage, add, remove, disable, enable mods or even make folders for different mods packs. You could also manage your servers and resource packs with it as well.

**Describe alternatives you've considered**

I don't know what alternatives I would consider

**Additional context**

Idk, search up the mods section of the bmbf app, maybe also add a section where you can search up mods and download them.

**Comment by MrNavaStar** [comment]
I am currently working on a pr for this

**Comment by Mage-Enderman** [comment]
Can you please add a title so it's not just [FEATURE]?

**Comment by gusbunce** [comment]
> I am currently working on a pr for this

Perfect if so please reach out to me on discord gus#0069
