### ISSUE TITLE
[FEATURE] allow non vr users to see vr movements

### ISSUE THREAD

**Issue by JoshTGHgithub** [QuestCraftPlusPlus/QuestCraft#181]
I don't know if downloading and using the mcxr mod in non vr allows you to see vr movements, but if it does then you can just get rid of this

**Comment by CorbinD331** [comment]
Hey :)
I was wondering the same thing, I'll be testing this soon so I'll let you know about my results once I'm done.

**Comment by fishiidev** [comment]
Any update in this????

**Comment by CorbinD331** [comment]
soon(tm)

**Comment by CorbinD331** [comment]
Update: Internet issues resolved, *now* I am testing this method

**Comment by CorbinD331** [comment]
Attempting to test right now. Hopefully I will have results soon.

**Comment by CorbinD331** [comment]
I have finished testing and have not been able to see my movements through the PC. If someone else wants to to more in-depth testing feel free to :)

**Comment by wellsilver** [comment]
This will be added soon and I would guess is a fairly meh high priority

**Comment by Mage-Enderman** [comment]
> 



> both questcraft and MCXR are very new (should've waited before releasing -_-) and will be adding this soon

"should've waited before releasing -_-" I am personally quite happy they released even in the current state
If you don't want it as it is don't use it, You can wait for updates if you want but that is your choice
Doodly doo not trying to start a fight just saying I don't see the point in expressing that they should've waited

**Comment by gusbunce** [comment]
@Mage-Enderman good way to end this issue. we have this planned for the future but are currently working on more pressing matters. Not to mention the auto-installer.

**Comment by TecEash1** [comment]
> I don't know if downloading and using the mcxr mod in non vr allows you to see vr movements, but if it does then you can just get rid of this

BTW - this has been added on the latest version of QC as it now uses vivecraft (Ik this issue is from a long time ago)
