### ISSUE TITLE
[FEATURE] Menu to trigger buttons not available on quest controllers 

### ISSUE THREAD

**Issue by Blankky** [QuestCraftPlusPlus/QuestCraft#182]
**Is your feature request related to a problem? Please describe.**
The Inability to bind buttons in general (I'm aware with the upcoming virtual keyboard this would be solved)

**Describe the solution you'd like**
A Menu Much like the Gesture Manager in VRCHAT that can be used to activate binds

**Describe alternatives you've considered**
Something like the action menu but I figured the gesture menu would be the best

**Additional context/images**
Triggered By the Menu Button On the Left Controller The Image Provided is roughly what id imagine it would look like.
![image](https://user-images.githubusercontent.com/100796796/156427823-fc548215-0521-415a-90aa-3d42c8aeb6fe.png)

**Comment by wooperTM** [comment]
I have an addon to this, 
Buttons in the inventory that could allow you to access chat or that will act as a keys that could be used to access mods that menus can only be opened with keybinds

**Comment by Mage-Enderman** [comment]
> I have an addon to this, Buttons in the inventory that could allow you to access chat or that will act as a keys that could be used to access mods that menus can only be opened with keybinds

Personally that sounds awful I don't want that stuff in the inventory
Maybe I could get used to it if it was actually implemented though as I've probably been wrong with other stuff like that in the past

**Comment by gusbunce** [comment]
We can look into this later down the line for the mean time i will be marking this as closed but with the looking into it, and future tags.
