### ISSUE TITLE
[BUG] Cant convert older worlds to new version

### ISSUE THREAD

**Issue by TSBROSMH** [QuestCraftPlusPlus/QuestCraft#184]
It won't let me convert old worlds to a newer version, there isn't a button for it

**Comment by wellsilver** [comment]
There is no button for it because it does it for you.

**Comment by IzzyDotExe** [comment]
If you click the play button your world will convert to whichever version of Minecraft you're playing.

**Comment by TSBROSMH** [comment]
It won't let me click the world to do that

**Comment by wellsilver** [comment]
> It won't let me click the world to do that

When you JOIN A WORLD it does that for you.

**Comment by MicahBun** [comment]
If you're transferring your older PC world into Quest you can Optimize it for 1.8.1 before transferring it over to avoid having Quest doing it real-time. Just click Edit world while on Minecraft's main menu on your PC.
