### ISSUE TITLE
[BUG] World Load Freeze Issue

### ISSUE THREAD

**Issue by BoxOfUnity** [QuestCraftPlusPlus/QuestCraft#185]
**Describe the bug**
I created a survival world- now every time I try to load it, it crashes. (crashed as soon as I created it too)
Having done some research I found the Sodium mod - which is what I thought was causing it the first time I posted this issue - and downloaded it into my quest's .minecraft/mods folder. The only thing this did was create a perpetual loading screen. (I also tried not clicking "start anyway" and instead "ok" after pressing "Play" (Haven't yet tried this without the sodium mod)

**To Reproduce**
1. Launch
2. Click single player mode- top option
3. Select the single player survival world previously created
4. Press play
5. Immediately experience a freeze. (The kind of freeze where it shows one way in front of you- and completely upside down when you turn around.) 

**Expected behavior**
It is expected that the world loads for the entertainment of its creator.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: I remain uncertain where one finds this information-
 - Device: Meta: Oculus Quest 2
 - QuestCraft Version: v1.1.1 I believe??

**closing**
If any of you know how to help, it would be well appreciated.
     Thank you,
        -B.O.U.

**Comment by Mage-Enderman** [comment]
You may have to reinstall since you pressed "Ok" instead of "Play Anyway"
Make sure clouds are disabled too

**Comment by BoxOfUnity** [comment]
Ok,  should I uninstall Sodium?
Also, "Clouds" as in Oculus Cloud backup thing?

**Comment by Mage-Enderman** [comment]
> Ok, should I uninstall Sodium? Also, "Clouds" as in Oculus Cloud backup thing?

No clouds as in the stuff in the sky in Minecraft 
And yeah uninstall Sodium

**Comment by BoxOfUnity** [comment]
Ok thanks XD sorry

**Comment by BoxOfUnity** [comment]
Ok so I uninstalled the whole thing and tried again.
Without sodium
with the third option on the first drop down in Video and Rendering or som'n like that
with ignore notch
with 60% graphics (found in settings in the launcher)
scrolled to the bottom and selected the fabric version.
pressed "play anyway",  let it download-
without clouds- also changed the graphics settings from fabulous to fast- the chunks to the lowest setting- and mob distance to like- 75% 
created a new survival world
looked behind me to see what I saw in front of me but upside down... again... no loading.  
It's definitely not freezing my quest because the oculus home menu loads fine- in fact it loads better than in a lot of oculus store games.

**Comment by Mage-Enderman** [comment]
> Ok so I uninstalled the whole thing and tried again. Without sodium with the third option on the first drop down in Video and Rendering or som'n like that with ignore notch with 60% graphics (found in settings in the launcher) scrolled to the bottom and selected the fabric version. pressed "play anyway", let it download- without clouds- also changed the graphics settings from fabulous to fast- the chunks to the lowest setting- and mob distance to like- 75% created a new survival world looked behind me to see what I saw in front of me but upside down... again... no loading. It's definitely not freezing my quest because the oculus home menu loads fine- in fact it loads better than in a lot of oculus store games.

Maybe you need to adjust allocated ram? I have mine set to 3070mb
For now though go to the support channels on the Discord instead of here

**Comment by Mage-Enderman** [comment]
> no idea how to do that.. XD there is a discord?- I was looking to see if there was- well ok thanks!

https://discord.com/invite/QuestCraft

**Comment by wellsilver** [comment]
I know this seems obvious but did you wait the required 3 hours? It takes a LONG time to load

**Comment by BoxOfUnity** [comment]
it was just a time thing- I waited like 3 minutes the first few times and it didn't load- guess I'm just not patient
