### ISSUE TITLE
[FEATURE] Add a seated/standing toggle in the menu

### ISSUE THREAD

**Issue by Pajamaland** [QuestCraftPlusPlus/QuestCraft#187]
**Is your feature request related to a problem? Please describe.**
When I tried to play sitting down last night, I was at floor height for some reason.

**Describe the solution you'd like**
A simple toggle in the menu that adjusts your view accordingly for seated play and standing play, like a standard VR title.

**Comment by wellsilver** [comment]
seated is currently in progress

**Comment by Mage-Enderman** [comment]
You can open the oculus menu then go to accessibility then I think it was "Raise up" or something
