### ISSUE TITLE
[BUG] fix questcraft website

### ISSUE THREAD

**Issue by javapcl** [QuestCraftPlusPlus/QuestCraft#188]
**Describe the bug**
QuestCraft Website is not working properly.

**To Reproduce**
1. Go to 'https://quest-craft.com' or 'https://quest-craft.github.io/QuestCraft-Website'
2. See Error

**Issue Description**
The QuestCraft Website isn't working, the css are not loaded, the domain apparently is not receiving the GitHub Pages content and the downloads were not posted in the Website. You can check it on: https://quest-craft.github.io/QuestCraft-Website. Tomorrow i'll do a pull request in the website repo to solve the css and downloads errors, but i will leave this issue for a while.(pd: i know i need to do a pull request in the website repo but im writing this on the phone and i can't type code right now and i think the css were deleted)

**Comment by wellsilver** [comment]
I dont think the website is finished yet

**Comment by IzzyDotExe** [comment]
The website is still in the works.
