### ISSUE TITLE
[FEATURE] Hand position controlled shield blocking

### ISSUE THREAD

**Issue by Kolin63** [QuestCraftPlusPlus/QuestCraft#191]
Not a problem, just something I think would be super cool. My idea is to make it so that if you have a shield in either of your hands, if you hold it up to an attacker, it would block the shield as if you blocked with the button. Kind of like swing breaking, but with combat.

Edit: Also swinging at a mob without pressing a button to damage it would be cool

**Comment by IzzyDotExe** [comment]
Add your ideas to #64 where we discuss gestures in the game.
