### ISSUE TITLE
Not really a feature, but any way to appeal a ban from the discord server?

### ISSUE THREAD

**Issue by MissHotHeartness** [QuestCraftPlusPlus/QuestCraft#195]
When QuestCraft came out, I was among those that was muted and pretty much instantly banned, and I get I was asking for it, but looking back, I feel really stupid for doing that and not to mention I have not been able to get the app to work at all.

If I could join back into the Discord under the promise of being able to behave, then that would actually help me because I cannot get QuestCraft to work at all, and I've tried for at least five days now.

Of course, there is the option of deleting this and ignoring it entirely, but I really would appreciate being given one more chance, because I actually do appreciate the hard work you guys do, and I am very deeply sorry for acting like an immature child that day.

**Comment by WaffleDevs** [comment]
1. Please do not add the feature label to non-feature issues.
2. You need to add more information. I.e. discord account + tag, actual reason why you were banned

**Comment by MissHotHeartness** [comment]
I'll just close it, I'm sorry.
