### ISSUE TITLE
[BUG]I cant get minecraft to play

### ISSUE THREAD

**Issue by ThatOneGuy1331** [QuestCraftPlusPlus/QuestCraft#196]
When i sart up the game it just gives me a black loading screen with music. I changed the render and tried different versions but the black loading screen still happens.(note: this is after I have started everything when you actually try to play minecraft)

1. Go to the game startup
2. Click on render and version then play
3. Look at nothingness with minecraft music

**Expected behavior**
I expected a main menu or game.

**Headset Details):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Comment by L0um15** [comment]
I had similar issue. Click "select account" button then choose your account. "Play" button sometimes does not work.

**Comment by IzzyDotExe** [comment]
Always click select account when logging into pojav and make sure you click play anyways after launching. OP please update us on what you've tried so far and if the issue is fixed.

**Comment by ThatOneGuy1331** [comment]
Sorry about the wait, I didn't know you guys responded. Here's a video of me doing the things you said to do.
https://photos.app.goo.gl/3vMtmXBWxFdKgU7Z8

I tried to just put in the video but it hates me for some reason

**Comment by L0um15** [comment]
You just downloaded the launcher. PCVR version contains preinstalled fabric environment.

![obraz](https://user-images.githubusercontent.com/44427021/157894519-7057934e-7ae3-4664-8fc9-91eff798aa1b.png)

You have to download pcvr edition and extract all contents to the root of the oculus storage.

**Comment by ThatOneGuy1331** [comment]
Nvm, let me try something

**Comment by ThatOneGuy1331** [comment]
I'll just have to use someone else's computer. Thx fir helping
