### ISSUE TITLE
[FEATURE] Left-Handed Mode/Controller Bindings

### ISSUE THREAD

**Issue by BlazeFolf** [QuestCraftPlusPlus/QuestCraft#198]
**Is your feature request related to a problem? Please describe.**
I noticed that it seems that the game is more oriented toward right-handed individuals. And it seems to be difficult to change the controller bindings.

**Describe the solution you'd like**
Would it be possible to add an option to switch the controls for both hands? like instead of the right hand being for placing and breaking blocks you use the left hand? Also, Could you make it a little easier to change the control bindings?

If solutions to my request already exist then could someone please point me in the direction of how to change this?

Thank you for reading!

**Comment by gusbunce** [comment]
Hi @BlazeFolf thanks for reaching out to implement this, i do also agree with you one of my friends has mentioned the same thing. It is going to be something in the long term to be implemented, it is not high on our priority list. Currently our highest priorities are:

1. Optimisations
2. Auto Installer

I will be closing this issue now.
