### ISSUE TITLE
[BUG] Loading World Crashes game

### ISSUE THREAD

**Issue by kaiw1011** [QuestCraftPlusPlus/QuestCraft#20]
Quest 2, Version 37

When I play the game and load a world, the screen goes red, then crashes to PojavLauncher

ADded both logs

[latest.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8113040/latest.log)
[latestlog.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8113041/latestlog.txt)

**Comment by JD-The-65th** [comment]
This bug also happens to me.

**Comment by JD-The-65th** [comment]
Set your chunk render distance to 3. That fixed it for me

**Comment by ATXLtheAxolotl** [comment]
@kaiw1011 did you manage to fix your problem?
