### ISSUE TITLE
[FEATURE] make it so you can play the snapshot

### ISSUE THREAD

**Issue by William-06** [QuestCraftPlusPlus/QuestCraft#206]
Could you add the newest snapshot. I wanna Pet frogs in vr

**Comment by jakershaker1** [comment]
Cant until the update is fully released.

**Comment by ReverseAli** [comment]
Yes

**Comment by IzzyDotExe** [comment]
Questcraft will be updated when the 1.19 update is fully released.

**Comment by AirplaneBoi** [comment]
wut
