### ISSUE TITLE
[FEATURE] Colon on Keyboard

### ISSUE THREAD

**Issue by kingarthurjr** [QuestCraftPlusPlus/QuestCraft#208]
The keyboard was supposed to make joining servers easier. But you added a semicolon instead of a colon. Trying to join my server format of 000.00.00.000:00000 was impossible.

 I recommend switching those out because I have no idea who even uses semicolons.

**Comment by camwamfam** [comment]
I can back this. My server includes a port inside of the IP, but I can't join the server due to there being no semicolon on the keyboard...

**Comment by WaffleDevs** [comment]
Planned. The devs have been notified about this already.

**Comment by IzzyDotExe** [comment]
This will be added in the 1.2.1 update

**Comment by loqk** [comment]
It's probably irrelevant to say, but It costs me $11 per month to get a fixed ipv4 address to run a server from, and, i believe, $0 per month to run a server from my ipv6 address, and so far, it seems that ipv6 addresses also need colons.
