### ISSUE TITLE
[BUG OR FEATURE?]

### ISSUE THREAD

**Issue by eypacha** [QuestCraftPlusPlus/QuestCraft#209]
**Describe the bug**
When you crouch, your height become only one block high (instead of 1.5 blocks).

**To Reproduce**
Crouching in real world.

**Expected behavior**
I didn't expect anything. My nephew pointed out to me that I "broke minecraft". I think that is a nice "feature". But maybe it gives us more advantages over no-see user in multiplayer.

EDIT: Its no only a visual thing. You can get into space one block high

**Comment by jakershaker1** [comment]
crouching IRL does not actually crouch in game last i checked. it just manipulates the camera. this will eventually be fixed.

**Comment by eypacha** [comment]
Ohh, so the real bug is the camera that does not collide with blocks.

**Comment by jakershaker1** [comment]
yeah pretty much.not really much of a fix except for blanking out the screen but im also not a dev and i have no clue how how hard that would be to integrate

**Comment by DED0026** [comment]
> crouching IRL does not actually crouch in game last i checked. it just manipulates the camera. this will eventually be fixed.
its not a bug its a feature there is nothing to fix
it doesnt let you crouch in multiplayer by going down

**Comment by eypacha** [comment]
@DED0026 its not only camera... you can enter in one block high spaces and mine blocks which you could not have reached

**Comment by Flamgop** [comment]
> @DED0026 its not only camera... you can enter in one block high spaces and mine blocks which you could not have reached

That only works on singleplayer and servers that have the MCXR Core mod

> Ohh, so the real bug is the camera that does not collide with blocks.

Camera can't have collision, because we can't force your head to move in real life, the only solution would be to move the entire player.

**Comment by DED0026** [comment]
@eypacha  it is in singleplayer only and i didnt say it was only camera
i said its a feature that you could enter one block/half a block gaps in singleplayer
you can not reach more places because the server wouldnt let you
anti reach
sort of the same thing happens in singleplayer your quest is also the server so it makes actions and checks if they are valid

**Comment by Flopgop** [comment]
Stale.
