### ISSUE TITLE
[BUG] New Main menu world cause issue for people suffering of fear of height

### ISSUE THREAD

**Issue by Antorboy** [QuestCraftPlusPlus/QuestCraft#212]
**Describe the bug**
The void cause discomfort for people having fear of height in the main menu

**Suggested Solution**
Change the main menu world so it does not create this discomfort, like having the camera closer to the ground, or having a bigger lobby platform to reduce the void presence.

**Screenshots**
No screenshot

**Headset Details:**
This is not dependent on the headset but on the user.

**Comment by jakershaker1** [comment]
not really much of a fix for this. this is more of a user issue and if it really bothers the user they can manually change the title world in the QC files.

**Comment by IzzyDotExe** [comment]
You can go into the titleworlds folder in the .minecraft directory and change the title world.
