### ISSUE TITLE
[FEATURE] Keyboard support

### ISSUE THREAD

**Issue by jakershaker1** [QuestCraftPlusPlus/QuestCraft#214]
Even after the addition of the new keyboard it will still always be slow due to the inherent nature of an onscreen keyboard. I offer the solution of adding keyboard support so we can use real keyboards via bluetooth to chat or any text interface. Hell, if enough people ask for it using keyboards for input could also be done.

**Comment by parkerlreed** [comment]
External keyboard support would still be good for those that want all characters/be able to type faster.

**Comment by wellsilver** [comment]
im sure external keyboard support would be cool but thats far off as its not even out of experimental

**Comment by ReubenDollmanYT** [comment]
> im sure external keyboard support would be cool but thats far off as its not even out of experimental

It is out of experamental on the latest quest 2 update

**Comment by Flopgop** [comment]
Stale.
