### ISSUE TITLE
[BUG OR FEATURE?] The new login menu lacks a normal login button

### ISSUE THREAD

**Issue by squirrelite** [QuestCraftPlusPlus/QuestCraft#216]
**Describe the bug**

When I load QuestCraft the login screen only presents the option to select accounts or login via a Microsoft account, with no discernible way to login using a legacy account. The username and password fields are there, but I can't move forward after filling them in..

**To Reproduce**

Launch QuestcCraft

**Expected behavior**

I expected to be able to log onto my legacy account.

**Headset Details (please complete the following information):**
 - Quest Build: ??where do I find this?
 - Device: Quest_2
 - QuestCraft Version: 1.2.0

**Comment by IzzyDotExe** [comment]
You cannot play QuestCraft with a legacy account. A Microsoft account is required

**Comment by IzzyDotExe** [comment]
You need to migrate your mojang account to a microsoft account

**Comment by D2Lx0wse** [comment]
Feature. Now close this
