### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Iquagmire69** [QuestCraftPlusPlus/QuestCraft#217]
Random flashes of what looks to be pixels. Everything else runs fine but I will get flashes on my screen that look like pixels and it disoriented me every time

 - Device: quest 1 
 - QuestCraft version 1.2

**Comment by IzzyDotExe** [comment]
@ManiacGamer156 have you experienced this before? it might be a quest 1 issue.

**Comment by kwmc-lucas** [comment]
Looks the same as https://github.com/QuestCraftPlusPlus/QuestCraft/issues/303

I have the same issue on a Quest 1.

**Comment by Flopgop** [comment]
Stale.
