### ISSUE TITLE
[BUG] Unable to edit singleplayer world/server titles Unable to select ip address field

### ISSUE THREAD

**Issue by L0um15** [QuestCraftPlusPlus/QuestCraft#218]
**Describe the bug**
Onscreen keyboard wont apply changes to the text field after confirming it with enter.

Also i'am unable to select ip address field. i'am allowed to only edit title field

**To Reproduce**
1. Add server or create single player world
2. Click edit button
3. Change text
4. Confirm changes

**Video clip**
https://youtu.be/3bMBcESwfQU

**Headset Details (please complete the following information):**
 - Quest Build: 38
 - Device: Quest 2
 - QuestCraft Version: 1.2.0

**Comment by IzzyDotExe** [comment]
This is a known issue in the changelog.

**Comment by L0um15** [comment]
Sorry. I didn't noticed
