### ISSUE TITLE
[FEATURE] In addition to the colon request, add the "shift" key and all the other remaining special characters in a irl keyboard to the questcraft keyboard

### ISSUE THREAD

**Issue by AirplaneBoi** [QuestCraftPlusPlus/QuestCraft#219]
Not a problem, just a minor inconvenience, mainly because I cannot capitalize letters or add certain characters that I would in java Minecraft with a traditional physical keyboard. 

Applies to both quest 1 and 2 

No workaround found

**Comment by IzzyDotExe** [comment]
Duplicate of #208

**Comment by IzzyDotExe** [comment]
If you want to add ideas to a feature request, please add a comment to that feature rather than making a new one
