### ISSUE TITLE
[BUG] Black screen

### ISSUE THREAD

**Issue by toaster4201** [QuestCraftPlusPlus/QuestCraft#220]
**Describe the bug**
whenever i try to playit shows a black screen but doesnt go to ht actual game. it plays the music annd everything. but it wont start the game to the. Opening screen

**To Reproduce**

**Expected behavior**
i whant it to go to the start up screen so i can play.

**Screenshots**

- [](u
![net kdt pojavlaunch debug-20220318-190724](https://user-images.githubusercontent.com/100814762/159098558-1d6a9cdf-8c7b-40bf-b8f2-dc2a6339232a.jpg)
rl)

**Headset Details (please complete the following information):**
 - Quest Build: [ v38.0]
 - Device: [ Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by IzzyDotExe** [comment]
Please make sure you've selected the third option in the renderer settings despite it already appearing as being selected.

**Comment by Flopgop** [comment]
Stale.
