### ISSUE TITLE
[BUG] quit game bug

### ISSUE THREAD

**Issue by maxplayz2746** [QuestCraftPlusPlus/QuestCraft#221]
very common issue i have where my game wont close

open the oculus menu and click quit

i was hopeing it wold close the game but it wont it will run in the background

**Headset Details (please complete the following information):**
 - Quest Build: [v38.0.0.63]
 - Device: [Quest_2]
 - QuestCraft Version [v1.2.0]

**Comment by maxplayz2746** [comment]
this was written on my quest 2

**Comment by JadianRadiator** [comment]
you have to use the in-game quit button

**Comment by IzzyDotExe** [comment]
Known issue, Use the in-game menu to quit QuestCraft for now until it's fixed.

**Comment by maxplayz2746** [comment]
ok

**Comment by maxplayz2746** [comment]
thx

**Comment by Flopgop** [comment]
Stale.
