### ISSUE TITLE
[BUG] server prompt causes the game to become stuck

### ISSUE THREAD

**Issue by mrflappi** [QuestCraftPlusPlus/QuestCraft#223]
**Describe the bug**
When I join some servers, I'm met with a red screen and music which just goes on forever. I'm 99% sure that the issue is caused when the server gives some kind of prompt before joining (like the messages you get after the server closes or crashes) though I don't know for sure, this is just based on which servers worked and which didn't.

**To Reproduce**
1. Go to 'Multiplayer'
2. Join a server that gives a prompt on joining (the server I tried was 'play.stoneworks.gg' which occasionally checks your connection speed then asks you to re-join)
3. See error

**Expected behavior**
The server will load and then give when the server sends the prompt the game would display it as UI and then let you try to re-join.

**Headset Details (please complete the following information):**
 - Quest Build: v38.0
 - Device: Quest_2
 - QuestCraft Version: v 1.2.0

**Additional context**
Again, I'm assuming this is the problem but I have no idea, I might be wrong.

**Comment by IzzyDotExe** [comment]
Known issue, its being worked on 👍

**Comment by mrflappi** [comment]
Oh ok, good to know its being fixed! (hopefully)

**Comment by Flopgop** [comment]
Stale.
