### ISSUE TITLE
[FEATURE] Add a second crosshair when blocks are held in the off-hand

### ISSUE THREAD

**Issue by ghost** [QuestCraftPlusPlus/QuestCraft#224]
**Is your feature request related to a problem? Please describe.**
I usually hold torches in my off-hand when I'm mining, and it's a little confusing when I point that hand outward and it ends up placing the torch where my main hand is

**Describe the solution you'd like**
A second crosshair that follows the off-hand only when blocks are held in it, and blocks will place where the crosshair is pointed
EDIT: Blocks that are selected in the main hand should override this, and the second crosshair should disappear.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Flopgop** [comment]
No.
