### ISSUE TITLE
[BUG] There isn't a login button to log in with a mojang account

### ISSUE THREAD

**Issue by AntogamerYT** [QuestCraftPlusPlus/QuestCraft#225]
**Describe the bug**
Simply, you can't login with a mojang account

**To Reproduce**
1. Open QuestCraft
2. input your mojang account details
3. you can't login because there isn't a login button
4. 
**Headset Details (please complete the following information):**
 - Quest Build: v38
 - Device: Quest_2
 - QuestCraft Version 1.2.0

**Additional context**
Please don't tell me to migrate my account to a microsoft account, this is an account I bought from a site and since I don't have access to the email I can't receive the microsoft email, thank you.

**Comment by AydenLdear** [comment]
You need to migrate your mojang account to a [microsoft account](https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account)

**Comment by AntogamerYT** [comment]
> You need to migrate your mojang account to a [microsoft account](https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account)

...

**Comment by Flamgop** [comment]
We removed the login button because mojang has removed support for mojang accounts as of recently. Your only option is to buy an actual account.

**Comment by Raven13111** [comment]
Fuck you

**Comment by AydenLdear** [comment]
> Fuck you
 
Didn’t ask

**Comment by jakershaker1** [comment]
Gentlemen, this is the bug tracker for qc, not the fighting ring. Take this to the dms.
