### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by FemFatal** [QuestCraftPlusPlus/QuestCraft#226]
Please add smooth turn

**Comment by IzzyDotExe** [comment]
duplicate of #119

**Comment by wellsilver** [comment]
They are adding smooth turning, I think it was projected for v1.2 but if it wasnt added it may be added in the future,

in the meantime, ACTUALLY TURN YOUR BODY! Though there will be support added for sitting there is no support for it at the moment
