### ISSUE TITLE
[BUG] QuestCraft Keyboard does not contain : 

### ISSUE THREAD

**Issue by Myrdincx** [QuestCraftPlusPlus/QuestCraft#227]
**Describe the bug**
QuestCraft Keyboard does not contain `:`

**To Reproduce**
1. Open QuestCraft and go to Multiplayer, click on add server or direct connect
2. Click on the box to open the keyboard function

The keyboard contains a ; but not a :

**Expected behavior**
A `:` is in the keyboard, thus you are able to add servers with an IP port.

**Headset Details:**

- Quest Build: v38
 - Device: Quest 2
 - QuestCraft Version 1.2.0

**Additional context**
I am not able to add any servers that contain a server port.

**Comment by 1XxEPICDJxX1** [comment]
Workaround: Create the server on a Windows or Mac device then go to your .minecraft folder, take out the servers.dat and paste it into the .minecraft folder on the Quest.

**Comment by IzzyDotExe** [comment]
known issue, a fix is coming.
