### ISSUE TITLE
[BUG] ok i have this very small bug to where when im typing commands it will sometimes click behind the letter and take out the command say for instance: when im playing in a multiplayer server and im trying to type a command i click the letter but the other players name is behind it i click the letter but it acts like i clicked the name so it wipes what i wrote in the command bar so far and puts something like “/tell technobryan…” so yeah i just wanted to report it if possible could you make it to where the keyboard is lower or make to where you could move it around or like to not change much (i think) make it to where the keyboard is seprate and you would have to click the back button to go back to the chat thing pls one of them but is not its VERY understandable and i love this project and i hope the best for yall and the project.

### ISSUE THREAD

**Issue by Braylenw98** [QuestCraftPlusPlus/QuestCraft#228]
[BUG] ok i have this very small bug to where when im typing commands it will sometimes click behind the letter and take out the command say for instance: when im playing in a multiplayer server and im trying to type a command i click the letter but the other players name is behind it i click the letter but it acts like i clicked the name so it wipes what i wrote in the command bar so far and puts something like “/tell technobryan…” so yeah i just wanted to report it if possible could you make it to where the keyboard is lower or make to where you could move it around or like to not change much (i think) make it to where the keyboard is seprate and you would have to click the back button to go back to the chat thing pls one of them but is not its VERY understandable and i love this project and i hope the best for yall and the project.

**Comment by Goldenfreddy0703** [comment]
Holy Crap, this is the longest title i have ever seen on github, you made github history for me. lol 😂

**Comment by wellsilver** [comment]
^

**Comment by IzzyDotExe** [comment]
please don't use such long titles. This keyboard atm was only stopgap until a better keyboard is made. A new one will be coming soon.

**Comment by Goldenfreddy0703** [comment]
> please don't use such long titles. This keyboard atm was only stopgap until a better keyboard is made. A new one will be coming soon.

If a new one will be coming soon, will it be just like the vivecraft keyboard?

**Comment by wellsilver** [comment]
> 
> If a new one will be coming soon, will it be just like the vivecraft keyboard?

No, it will either be a custom keyboard (wich may or may not be similar to vivecraft keyboard) or the built in oculus keyboard

**Comment by Tyson6474** [comment]
Uhh... plz simplify title

**Comment by techiesces** [comment]
Actually I have found that when you are using the trigger it will click behind the keyboard.

instead of using the trigger, use the A button instead to select what you are typing and you will not click behind the keyboard anymore.

you are welcome!

**Comment by Flopgop** [comment]
Stale.
