### ISSUE TITLE
[BUG] Log in without an account

### ISSUE THREAD

**Issue by lrutjens** [QuestCraftPlusPlus/QuestCraft#23]
**Describe the bug**
Your able to log without an account

**To Reproduce**
1. click offline mode when logging in
2. enter any name

**Expected behavior**
Requiring an account to log in

**Headset Details (please complete the following information):**
 - Quest Build: 37.147.0
 - Quest_2
 - 1.0.0

**Comment by gusbunce** [comment]
We are aware of this, this is something built into pojav. It is mainly used for testing. Do what you want but if you get in to trouble for not using an account that is on you and not on us. :)

**Comment by lrutjens** [comment]
i just saw someone metion it was all
