### ISSUE TITLE
[BUG] placing liquids ignores crosshair

### ISSUE THREAD

**Issue by dmcpacks** [QuestCraftPlusPlus/QuestCraft#230]
**Describe the bug**
When placing any liquid (water/lava) instead of placing it where the crosshair is pointing it will place it to where you are looking.

**To Reproduce**
1. Grab a water bucket
2. Place bucket but don't look at where you're pointing
3. You should see that the water placed where you were looking, not on the crosshair

**Expected behavior**
The bucket would place where you're pointing at.

**Headset Details (please complete the following information):**
 - Quest Build: v37
 - Device: Quest 2
 - QuestCraft Version: 1.2

**Comment by Flopgop** [comment]
Stale.
