### ISSUE TITLE
[BUG] Server data pack reinstall issue

### ISSUE THREAD

**Issue by MostRandomGamer** [QuestCraftPlusPlus/QuestCraft#231]
The bug will not allow players to open the game and have the game crash when the red screen is shown.

Go to Servers
Load into a server that uses a custom resource or data pack (I'm not sure which one crashes the game but a good example for a server that does is origin realms)
Join
You will see a black and white Mojang studios loading screen that will always reset right as it's about to finish loading and be forced to restart the game
Now when you boot the game you will be unable to get past the red screen without it crashing
The game will get to the red screen and crash shortly after. The only way to fix this issue is to reinstall the game.

Quest Build: v37.0
Device: Quest 2
QuestCraft Version 1.2.0

**Comment by ReubenDollmanYT** [comment]
This is known you need (from what i know) a 32x pack any higher or lower soft locks the game this is known by the qc team

**Comment by Flopgop** [comment]
Stale.
