### ISSUE TITLE
Red Flashes Randomly

### ISSUE THREAD

**Issue by BloxBoss6** [QuestCraftPlusPlus/QuestCraft#234]
After I launch the game and after it finishes loading, random flashes of red appear for a second and then disappear again. They also happen randomly around the screen, both in the main menu and in game. Will add photos later to show if I am able to. The mods I had were the original ones that came with the new update.

I am running on a Quest 1 with the latest update. I do not have it in front of me so I cannot confirm what specific version. The version of Questcraft is the latest that was on Sidequest as of last night, but I will update with the specific version later.

**Comment by BloxBoss6** [comment]
Quest 1 Version **38.0.0.83.7728.356672341**
Sidequest Installed Version: **9935128** according to App Settings inside of Sidequest

[Video Link](https://drive.google.com/file/d/163kStNZT3-lOR5KBsjaKSaj_IulrJ7QX/view?usp=sharing) (Currently being processed by Google. Will hopefully work by the time you're looking at it)

The video only has one flash of red that at least I can see and it happens at about 16-18 seconds. But on my side, it was basically happening every ten seconds or so. I wonder if it only records the right eye cause I tended to notice the red flashes with my left eye.

**Comment by IzzyDotExe** [comment]
@ManiacGamer156 Can you check this out? thanks.

**Comment by kwmc-lucas** [comment]
Looks the same as https://github.com/QuestCraftPlusPlus/QuestCraft/issues/303

I have this too on a Quest 1.

**Comment by kwmc-lucas** [comment]
This was marked as fixed on [1.3.0](https://github.com/QuestCraftPlusPlus/QuestCraft/releases/tag/1.3.0), it is not fixed.

**Comment by Flopgop** [comment]
Stale.
