### ISSUE TITLE
[BUG] 1.2.0's setup isn't setting the render correctly.

### ISSUE THREAD

**Issue by JadianRadiator** [QuestCraftPlusPlus/QuestCraft#235]
**Describe the bug**
On a completely fresh install of 1.2.0 the renderor setting shows it's on gl4es 1.1.5.
But it immediately crashes off of the black screen.
The crash report shows it's actually set to gl4es 1.1.4,
despite the setting showing the correct/third setting of 1.1.5.

**To Reproduce**
1. Do a complete and thorough wipe/erase of QuestCraft
2. Login and go through the setup.
3. See that it says it's set to the correct renderer
4. Click play
5. See it crash
6. Open/read the crash report for proof that it isn't on the correct renderer.

**Expected behavior**
For it to use the correct renderer that the settings say it's set to.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: 38.0.0.63.727.351486028
 - Device: [e.g. Quest_1, Quest_2]: Quest_2
 - QuestCraft Version: 1.2.0

**Additional context**
[crash-2022-03-20_00.46.32-client.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8311486/crash-2022-03-20_00.46.32-client.txt)
[crash-2022-03-20_13.59.39-client.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8311487/crash-2022-03-20_13.59.39-client.txt)
[crash-2022-03-20_14.00.09-client.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8311488/crash-2022-03-20_14.00.09-client.txt)

**Comment by maxplayz2746** [comment]
try the second renderer cuz its suposed to be "gl4es (openGL es 2):exports OpenGL 2.1"

**Comment by JadianRadiator** [comment]
the issue isn't the renderer's capabilities.
the issue is that it's not set to the 3'rd renderer like it says it is.
manually changing the renderer selection to something else and back corrects it though.

**Comment by JadianRadiator** [comment]
it's set to the third by default (or is supposed to).
however that would be openGL es 3.
so why the switch to openGL es 2?

**Comment by IzzyDotExe** [comment]
It appears to be set to the 3rd by default but you still need to click the third renderer despite it already being selected. Sorry for the confusion.

**Comment by Flopgop** [comment]
Stale.
