### ISSUE TITLE
[BUG] Crosshair disappears when it rains, and never comes back.

### ISSUE THREAD

**Issue by imcommonsense** [QuestCraftPlusPlus/QuestCraft#236]
**Describe the bug**
Whenever it rains, the crosshair disappears. and then never comes back until you restart questcraft.

**To Reproduce**
1. Go into world/server
2. Wait for rain.
3. Crosshair gone, doesn't come back.

**Expected behavior**
Crosshair stays there.

**Screenshots**
haven't taken one yet, might take one later.

**Headset Details (please complete the following information):**
 - Quest Build: v37
 - Device: Quest_2
 - QuestCraft Version 1.2.0

**Additional context**
Has been happening since atleast 1.1.0

**Comment by ReubenDollmanYT** [comment]
This is already a knowen bug please check #common  issues before makeing a issue here

**Comment by Flopgop** [comment]
Stale.
