### ISSUE TITLE
[BUG] wont let me login

### ISSUE THREAD

**Issue by Floffy02** [QuestCraftPlusPlus/QuestCraft#237]
it keeps sayying error 404 and makees me relogin

**Comment by knightryry** [comment]
Mojang or Microsoft?

**Comment by Floffy02** [comment]
Microsoft

**Comment by wellsilver** [comment]
You need to migrate your microsoft account

**Comment by Floffy02** [comment]
What does migrate an account

**Comment by ReubenDollmanYT** [comment]
The question is have you already migrated your Mojang account to a Microsoft account

**Comment by walksanatora** [comment]
I am having the same issue. I created my account as a microsoft account. any help would be nice

**Comment by OBSAM4** [comment]
same issue and its a Microsoft account already

**Comment by OBSAM4** [comment]
i just migrated it again and it worked

**Comment by Floffy02** [comment]
I never had too I bought it with my mircosoft account

**Comment by walksanatora** [comment]
> same issue and its a Microsoft account already

wait how do i migrate a allready-migrated account. there is no username/password as it is sign in via microsoft

**Comment by ReubenDollmanYT** [comment]
> I never had too I bought it with my mircosoft account

You need to migrate from a mojang account on the Minecraft website

**Comment by JaffaJace** [comment]
> 

guessing others havent helped, im guessing youre using a gamepass account, right?
if so, the you need to run the game atleast once on pc before using QC

**Comment by Floffy02** [comment]
No I bought Minecraft java with my money using my mircosoft account and I need to migrate it and idk what that means

**Comment by JaffaJace** [comment]
If you use a microsoft account to sign in then its already migrated

**Comment by wellsilver** [comment]
> 

Did you buy it with gamepass?

**Comment by Floffy02** [comment]
No I did not buy it with a game pass. Than how do I play on there.

**Comment by wellsilver** [comment]
You might be logging in with the wrong account

**Comment by Floffy02** [comment]
I log trough my account to double check it work but not on my vr

**Comment by Floffy02** [comment]
So is it because I didn't do it trough side quest?

**Comment by charlesbedrosian** [comment]
I had this issue and it was resolved by installing Minecraft Java edition on my computer (Mac in this case), launching it, logging into my Microsoft account and setting up a Minecraft Java username. This seems to have activated my profile. After that I was able to login to my Microsoft account using QuestCraft on my Quest 2 without any problem.

**Comment by LoriSpecks** [comment]
This has been an infuriating experience.  I keep getting this error too.  I am trying to help my son play minecraft on VR and it has taken me 2 days and I am still unsuccessful.  Please help!!  He was playing on ipad for years.  Not sure if it was free or if we bought something years ago.  I don't think he was ever signed in for mojang or microsoft.  At the beginning of this jpurney I signed him in with my microsoft account.  When we first got the error I bought the minecraft for windows starter collection for 30 bucks.  I used my microsoft account to purchase.  I read above about migrating, but I don't have a mojang account so I don't think that is the issue.  I launched on PC and then tried but still same error.  I restarted everything and tried again.  I don't think this package came with the "java edition" and I certainly don't want to spend more money!!  Any suggestions????

**Comment by walksanatora** [comment]
You don't have a Java edition account you have bedrock on the iPad
Luckily Java is going to be coming free with minecraft windows 10 during the summer. And if you own Xbox game pass you also get minecraft for free

**Comment by wellsilver** [comment]
> So is it because I didn't do it trough side quest?

no, we would normally blame sidequest first lmao its never because you didn't use sidequest

**Comment by LoriSpecks** [comment]
This wasn’t my question.  I copied my question here:

Are you saying QuestCraft cannot be played without Java edition?  Must you have minecraft for windows 10 also?  I will return minecraft for windows 10 and just buy java if that will solve this problem

**Comment by wellsilver** [comment]
> This wasn’t my question. I copied my question here: Are you saying QuestCraft cannot be played without Java edition? Must you have minecraft for windows 10 also? I will return minecraft for windows 10 and just buy java if that will solve this problem
> […](#)
> Sent from my iPhone
> On Jun 3, 2022, at 8:32 PM, wellsilver ***@***.***> wrote: ﻿ So is it because I didn't do it trough side quest? no, we would normally blame sidequest first lmao its never because you didn't use sidequest — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

you need the "java" edition, and by the way you described it you bought the "bedrock" edition, try making a new issue instead of commenting on this one (that's already closed, or resolved) for better support

you can click right here to make the new issue
![image](https://user-images.githubusercontent.com/67511181/172072055-b00d4345-aaf2-49e8-8ac5-d20c8c5d5238.png)

**Comment by wellsilver** [comment]
> This wasn’t my question. I copied my question here: Are you saying QuestCraft cannot be played without Java edition? Must you have minecraft for windows 10 also? I will return minecraft for windows 10 and just buy java if that will solve this problem
> […](#)
> Sent from my iPhone
> On Jun 3, 2022, at 8:32 PM, wellsilver ***@***.***> wrote: ﻿ So is it because I didn't do it trough side quest? no, we would normally blame sidequest first lmao its never because you didn't use sidequest — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

sorry for replying multiple times but 

# This issue has already been resolved please make a new issue

to make a issue you click on "issues" (your already here) and click "new issue"
![image](https://user-images.githubusercontent.com/67511181/172072055-b00d4345-aaf2-49e8-8ac5-d20c8c5d5238.png)

**Comment by LoriSpecks** [comment]
Are you saying QuestCraft cannot be played without Java edition?  Must you
have minecraft for windows 10 also?  I will return minecraft for windows 10
and just buy java if that will solve this problem
