### ISSUE TITLE
[FEATURE] Shift Clicking items in GUIs

### ISSUE THREAD

**Issue by JaffaJace** [QuestCraftPlusPlus/QuestCraft#238]
**Is your feature request related to a problem? Please describe.**
You have to transfer items between inventories manually one at a time.
Its pretty painful to move items to a chest, especially if your inventory is full after mining or something.

**Describe the solution you'd like**
When inside a GUI (e.g. chest, furnace), make it so if you hold either grip button and click on an item it does the same as shift clicking the item.

**Describe alternatives you've considered**
You could just
Not do it
If you dont want to

**Additional context**

**Comment by Unknown-64** [comment]
I think the x button on your left controller is like shift clicking, but it could be a different button than x if I am remembering incorrectly.
