### ISSUE TITLE
[FEATURE]have the ability to see other players arms

### ISSUE THREAD

**Issue by peter-w07** [QuestCraftPlusPlus/QuestCraft#239]
**Is your feature request related to a problem? Please describe.**
similar to vivcraft they have a spigot plugin that allows you to see players arms move along with a fabric mod
this would allow people on PC and vr to see their friends arms moving
**Describe the solution you'd like**
I don't know what to put here besides the ability to see people's arms in and out of vr
sort if like this
![image](https://user-images.githubusercontent.com/80288113/159404874-edcdedb2-1731-4165-bc6a-f16b6471f44b.png)

**Comment by JaffaJace** [comment]
Theyve already confirmed that this is a priority.

**Comment by peter-w07** [comment]
oh for real that's actually really cool I looked on the sorry I didn't know

**Comment by Flopgop** [comment]
Dupe.
