### ISSUE TITLE
[BUG] Infinite dots, even with "Keep me signed in"

### ISSUE THREAD

**Issue by CatCentralGitHub** [QuestCraftPlusPlus/QuestCraft#24]
**Describe the bug**
No matter how many times I try, I keep getting the three dots, and after a few minutes it goes back to PL and says "Game closed"

**To Reproduce**
1. Install everything perfectly
2. Open PL and sign in using Microsoft with "Keep me signed in" checked.
3. Set renderer and game version to correct settings.
4. See the three dots, and after a few minutes it goes back to PL and says "Game closed"

**Expected behavior**
See the three dots, and after a minute a red screen, and then minecraft launches.

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest 2
 - QuestCraft Version: v1

**Additional context**
Logs:
[latestlog.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8113183/latestlog.txt)

**Comment by ManiacGamer156** [comment]
Odd, it seems that a OpenXR thing went wrong, though it works fine on mine.

**Comment by CatCentralGitHub** [comment]
It works after charging quest.
