### ISSUE TITLE
[FEATURE] Option to disable crosshair

### ISSUE THREAD

**Issue by Soup333** [QuestCraftPlusPlus/QuestCraft#240]
**Is your feature request related to a problem? Please describe.**

Could there be an option to disable the crosshair? I feel more immersed when i didn't have it because of the rain bug lol

**Describe the solution you'd like**

A toggle to turn off crosshair in the settings

**Describe alternatives you've considered**

**Additional context**

**Comment by aidenchanter1** [comment]
You can use a resource pack to change or remove the crosshair. VanillaTweaks has an option to remove the crosshair.

**Comment by Flopgop** [comment]
Stale.
