### ISSUE TITLE
[FEATURE] Cross Platform VR Body support with VIVECRAFT Extensions

### ISSUE THREAD

**Issue by PantsAreForLegsNOTARMS** [QuestCraftPlusPlus/QuestCraft#241]
problem:
 - We want moveable bodies in VR, so our friends on PC to see us hugging them :)

solutions:
(a) Work with VIVECRAFT team to ensure VR Body support is cross compatible with VIVECRAFT Extensions
(b) Maybe just adapt VIVECRAFT Extensions rather than writing something from scratch
(c) Look at the VIVECRAFT Extensions spigot plugin to make a fabric mod for QuestCraft

alternatives:
 - Fragment the already small VR player base lol

context:

Links for VIVECRAFT contact and resources
https://discord.gg/2x3QCk8qa9
https://github.com/jrbudda/
http://www.vivecraft.org/downloads/

Thanks guys!
(also where do I give you money?)

**Comment by AbyssAlley** [comment]
Use mcxr core

**Comment by gusbunce** [comment]
We recommend the use of MCXR Core, we currently have no way of being able to see vivecraft players in QuestCraft we could look into a plugin for servers and users later down the line but currently this is not on the priority list.

**Comment by wellsilver** [comment]
sorry for commenting on a closed issue but;

There is no current server build or client build to allow for even PC-MCXR though im sure it is high on sorenons priority list 
The people who work on Vivecraft have actually contributed to questcraft
I highly doubt there will be any cross vivecraft-MCXR support at all as they are built on forge and fabric respectively and I dont know of any mods that have achieved cross compatibility other than ports
MCXR is still extremely new and difficult features to implement like this are to be better mentioned further down the line

**Comment by D2Lx0wse** [comment]
> sorry for commenting on a closed issue but;
> 
> There is no current server build or client build to allow for even PC-MCXR though im sure it is high on sorenons priority list The people who work on Vivecraft have actually contributed to questcraft I highly doubt there will be any cross vivecraft-MCXR support at all as they are built on forge and fabric respectively and I dont know of any mods that have achieved cross compatibility other than ports MCXR is still extremely new and difficult features to implement like this are to be better mentioned further down the line

Yes there is it's mcxr core and it's server side, however it's used to calculate the player's height, crawling and crouching

**Comment by wellsilver** [comment]
> > sorry for commenting on a closed issue but;
> > There is no current server build or client build to allow for even PC-MCXR though im sure it is high on sorenons priority list The people who work on Vivecraft have actually contributed to questcraft I highly doubt there will be any cross vivecraft-MCXR support at all as they are built on forge and fabric respectively and I dont know of any mods that have achieved cross compatibility other than ports MCXR is still extremely new and difficult features to implement like this are to be better mentioned further down the line
> 
> Yes there is it's mcxr core and it's server side, however it's used to calculate the player's height, crawling and crouching

I messed around with that and all I got was errors
