### ISSUE TITLE
[FEATURE] right clicking items in menus

### ISSUE THREAD

**Issue by SC0FI** [QuestCraftPlusPlus/QuestCraft#243]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

items in your inventory or in menus say to right click them to open a menu. At least from what I can see is that there is no way to right click an item in your inventory or in a menu without equipping it.

**Describe the solution you'd like**

Some form of way to right click items in menus. maybe just making it so you can press left trigger on an item in a menu to "right click" it.

**Describe alternatives you've considered**

I have no idea.

**Additional context**

**Comment by Unknown-64** [comment]
I think b right clicks in your inventory but I am not sure.

**Comment by SC0FI** [comment]
> I think b right clicks in your inventory but I am not sure.

Hm let me check
