### ISSUE TITLE
[BUG] Spyglass UI Broken

### ISSUE THREAD

**Issue by eusfisdf** [QuestCraftPlusPlus/QuestCraft#244]
**Describe the bug**
when you use the spyglass it shows a little menu on the left hand as if you were playing flat screen

**To Reproduce**
1. get spyglass 
2. use left trigger on spyglass
3. see issue

**Expected behavior**
3 solutions, 1. have the same ui on the right hand exept, it actually zooms in. 2. have the end of the spyglass actually work. 3. put the spyglass ui over all of the screen

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Quest_2
 - QuestCraft Version latest

**Additional context**
please fix this it would add to the emersion immensely

**Comment by ReubenDollmanYT** [comment]
This is allready knowin by the qc team please check common issues in the discord server before posting a issue here
