### ISSUE TITLE
[FEATURE] rumble support

### ISSUE THREAD

**Issue by KeepTheChange0** [QuestCraftPlusPlus/QuestCraft#245]
**Is your feature request related to a problem? Please describe.**
I think it would feel a lot more immersive if the controllers vibrated in response to what the player is doing in game.

**Describe the solution you'd like**
Maybe placing/breaking blocks would make the left and right controllers vibrate respectively, and taking damage makes both controllers vibrate

**Describe alternatives you've considered**
Would probably need an option to disable, for players that don't want rumble (or better yet, a vibration intensity slider)

**Additional context**
There may be other scenarios where the player might want rumble feedback, like fishing, firing a bow, absorbing exp, eating ect. Would be ideal to have granular control though as some players might not want rumble when eating or absorbing exp

**Comment by JaffaJace** [comment]
this is already planned for 1.2.1 im pretty sure

**Comment by DED0026** [comment]
its called haptics and they are allready adding it

**Comment by Blitszy** [comment]
Haptics have been added in 1.2.1 (I think), this issue is now resolved.

**Comment by wellsilver** [comment]
> Haptics have been added in 1.2.1 (I think), this issue is now resolved.

1.2.1 isnt out?
