### ISSUE TITLE
[BUG] targeted block does not show wireframe/outline

### ISSUE THREAD

**Issue by KeepTheChange0** [QuestCraftPlusPlus/QuestCraft#246]
**Describe the bug**
The black wireframe showing which block the cursor is aimed at usually found in Minecraft is not present.

**To Reproduce**
1. Go to any world
2. Get in range of any block and point at it
3. See error

**Expected behavior**
A thin black wireframe outlining the block the player is currently targeting is usually present to aid with counting blocks and knowing whether or not the block you are pointing at is in range

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v38
 - Device: Quest_2
 - QuestCraft Version: v1.2.0

**Additional context**

**Comment by Flopgop** [comment]
Stale.
