### ISSUE TITLE
[FEATURE] add abillity to move hud around

### ISSUE THREAD

**Issue by AbyssAlley** [QuestCraftPlusPlus/QuestCraft#250]
I kinda want to be able to move the hotbar and stuff around to make it seem more accessible to the player. I dont mean freely, like maybe add 3 options in the mcxr settings for like normal, on arm, or no hud. I would be very thankful if this could be added just as a small feature and I hope it can be added!

**Comment by Blitszy** [comment]
Yeah, I'd love this too. Maybe something like a PC feature where it's stuck in the middle just like on Desktop. Hopefully.

**Comment by Flopgop** [comment]
Stale.
