### ISSUE TITLE
[BUG] Items similar to dandelions z fight with skin layers

### ISSUE THREAD

**Issue by D2Lx0wse** [QuestCraftPlusPlus/QuestCraft#252]
**Describe the bug**
Dandelions have a cube in their model that z fight with my skin's hand layer

**To Reproduce**
1. Get skin with layers
2. Open QuestCraft
3. Get a Dandelion in your hand

**Expected behavior**
I should either see my skin or the dandelion model

**Screenshots**
![net kdt pojavlaunch debug-20220326-011159](https://user-images.githubusercontent.com/92229936/160217779-a39c6b67-ccd1-4410-86ad-86bf5543be52.jpg)

**Headset Details (please complete the following information):**
 - Quest Build: v38.0
 - Device: Quest_2
 - QuestCraft Version: v1.2.0

**Additional context**
None, it could be fixed by moving models by a small fraction of a block

**Comment by Flopgop** [comment]
Stale.
