### ISSUE TITLE
[FEATURE] Remove the Mojang email/password fields from the sign in page, since signing in with them is no longer supported.

### ISSUE THREAD

**Issue by ashelleyPurdue** [QuestCraftPlusPlus/QuestCraft#253]
**Is your feature request related to a problem? Please describe.**
When new users first launch the app, their first instinct will be to enter their email and password into the giant "email" and "password" fields...only to notice that there is no way to "submit" them.  What users are _actually_ supposed to do is click the "Log in with Microsoft" button, and enter their credentials on a _separate_ form.

It's pretty silly to have these text boxes if users aren't even supposed to use them.  It just causes confusion and generates unnecessary support requests on Discord.

**Describe the solution you'd like**
Remove the email and password fields from the sign in page, leaving only the "Log in with Microsoft" button.

**Describe alternatives you've considered**
Another option would be to add a giant red label at the top of the screen saying, "Ignore these textboxes.  Click the 'Log in with Microsoft' button instead."  But if you're going to be editing the page anyway, you may as well remove the textboxes while you're at it.

Alternatively, you could re-purpose the textboxes so that they take your Microsoft account instead of your Mojang account.  That might not be possible, though.

If you _really_ don't want to make any changes to the app, then adding a note to the FAQ would be better than nothing.

**Additional context**
No additional context.  It's just really weird that there are two vestigial textboxes.

**Comment by MrNavaStar** [comment]
They are removed in the gh actions build, will be gone in the next official release
