### ISSUE TITLE
[FEATURE] Voice Chat or Microphone support

### ISSUE THREAD

**Issue by kirbster7** [QuestCraftPlusPlus/QuestCraft#255]
**Describe the solution you'd like**
Microphone/Simple Voice Chat Mod support

**Describe alternatives you've considered**
Party chat or Discord would work... but I need in-game voice chat.

**Additional context**
![a05c91ad0a618ef6ae4f5d9b632ea896](https://user-images.githubusercontent.com/90074338/160264596-efb09f38-b00e-44c9-9d9a-99505f1a6002.png)

**Comment by FedFer98123** [comment]
As far as I know this should be in progress

**Comment by Blitszy** [comment]
Yep, this mod is in progress. There's no current ETA on it but there was footage posted on it on March 18th, which means they may of started around March 10th. I assume it should be finished by early April. But who knows, that's just my guess.

**Comment by wellsilver** [comment]
theres no "mod in progress" a pre-existing voice chat mod has either allready or will update with support

**Comment by ReubenDollmanYT** [comment]
They are working on support for this mod as this is a qc side problem as its not passing through the quest microphone to minecraft

**Comment by JadianRadiator** [comment]
It actually can pass the mic through to minecraft

1. give Quest Craft mic permission with a sideloaded app that can access it
2. set mic and output in Simple Voice Chat
3. Cycle the 3D sound to off, and then back on

Enable mic testing or use voice activation for proof that it's now poass the mic to Minecraft

**Comment by Flopgop** [comment]
Stale.
