### ISSUE TITLE
[FEATURE] Optimize keyboard

### ISSUE THREAD

**Issue by JacobWasTaken** [QuestCraftPlusPlus/QuestCraft#256]
Add more keys to the keyboard and make it easier to use. There are a few keys that would be useful (":", "{}") that just aren't there. Trying to type on the current keyboard is a little tedious so maybe add arrows or lines from the players hand when typing. This also would help with selecting text boxes as right now you cannot see where you are aiming.

**Comment by Blitszy** [comment]
Good idea! For some people who don't know how to port forward and set domains, the : key is essential! Also great idea with the selecting too, would've never thought of that. If it's not a thing, they should also make it so you can click on the text with controllers.

**Comment by wellsilver** [comment]
> the : key is essential

It should automaticly select 25565 I dont see why you would need the ":" key

**Comment by JacobWasTaken** [comment]
> I dont see why you need to change the port your connecting to

What about connecting to servers with custom ports? A lot of hosting companies use custom ports and you need the ":" to access those servers. And nbt in commands sometimes requires ":".

**Comment by ManiacGamer156** [comment]
@JacobWasTaken that will be fixed next update, that was a mess up on our end. Update should be out real soon.

**Comment by ManiacGamer156** [comment]
I can add {} to the keyboard right now.

**Comment by ManiacGamer156** [comment]
Accidental close with comment moment

**Comment by JacobWasTaken** [comment]
> @JacobWasTaken that will be fixed next update, that was a mess up on our end. Update should be out real soon.
Ok, thanks!

**Comment by wellsilver** [comment]
> > I dont see why you need to change the port your connecting to
> 
> What about connecting to servers with custom ports? A lot of hosting companies use custom ports and you need the ":" to access those servers. And nbt in commands sometimes requires ":".

Servers with custom ports? They don't exist.

"Alot of hosting companies use special ports" not one popular one does, nor could I find one that uses a special port

**Comment by DDR-Khat** [comment]
> Servers with custom ports? They don't exist.
> 
> "Alot of hosting companies use special ports" not one popular one does, nor could I find one that uses a special port

You are incredibly ignorant of the issue. A **lot** of minecraft servers default away from the typical 25565 due to sweeping bot DDoS attacks or just generally malicious agents. Why should the keyboard be prevented from typing ":" to specify a custom port just because "the big places" like HyPixel etc do not use them?

**Comment by DDR-Khat** [comment]
> > I dont see why you need to change the port your connecting to
> 
> What about connecting to servers with custom ports? A lot of hosting companies use custom ports and you need the ":" to access those servers. And nbt in commands sometimes requires ":".

Whilst you are awaiting for a resolution. You can work around this issue by copying the "servers.dat" from your PC minecraft installation and putting it onto your Quest headset in the appropriate folder location. It's the same file with the exact same data structure.

**Comment by Flopgop** [comment]
Stale.
