### ISSUE TITLE
[BUG] Microsoft login DNS error

### ISSUE THREAD

**Issue by rjk95** [QuestCraftPlusPlus/QuestCraft#257]
**Describe the bug**
I downloaded and installed Questcraft through sidequest. On starting the app the microsoft login page will not load, instead showing what I believe is a DNS error. Reinstalling several times has not resolved the problem, nor has restarting the quest. I've attached a video below

**To Reproduce**
1. Click on unknown sources
2. Select Questcraft
3. On the login page click "Microsoft login"

**Expected behavior**
I expected the microsoft login page to load.

**Screenshots**
The video is from a different user with the same problem, but I get the exact same page load
https://user-images.githubusercontent.com/36208990/160306872-cb684768-8a5a-4964-871b-384a0a3ddceb.mov

**Headset Details (please complete the following information):**
 - Quest Build: [v38.0]
 - Device: [Quest_2]
 - QuestCraft Version [v1.2.0]

**Additional context**

**Comment by Arri0** [comment]
Hi, I solved it by changing primary and secondary DNS in my router settings to 8.8.8.8 and 8.8.4.4.

**Comment by wellsilver** [comment]
> Hi, I solved it by changing primary and secondary DNS in my router settings to 8.8.8.8 and 8.8.4.4.

I would recommend a different DNS
1.1.1.1 1.0.0.1 
its cloudflare's DNS and normally takes off about 2-5 ms off your ping

**Comment by Flopgop** [comment]
Can't reproduce.
