### ISSUE TITLE
[BUG] Error code when signing into microsoft 

### ISSUE THREAD

**Issue by s2tb2007** [QuestCraftPlusPlus/QuestCraft#259]
When I attempt to sign into microsoft via questcraft, it will give me a long string of error code.
 I tried to reinstall, and reset the Oculus and nothing works.

1. Go to microsoft login
2. put in your email and password
3. press next
4. then theres the error code.

**Expected behavior**
The wait popup will appear, loading into the play menu.

**Headset Details (please complete the following information):**
 - Quest Build: v38
 - Device: Quest 2
 - QuestCraft Version 1.2.0

![com oculus vrshell-20220329-161751](https://user-images.githubusercontent.com/102624202/160699708-70915750-4810-4628-85ee-9ceb5a77542b.jpg)

**Comment by SpaceGentleman** [comment]
I am having the same problem (I think), what’s the error code?

**Comment by ReubenDollmanYT** [comment]
This is as your Microsoft account is under 18 add it to a family to fix this

**Comment by SpaceGentleman** [comment]
I don’t know about the family thing, but it turns out I didn’t have my ADV drivers installed. How I (seemingly) fixed the problem was by uninstalling QuestCraft, installing the drivers, then reinstalling QuestCraft.

**Comment by s2tb2007** [comment]
aparently i needed to disable some of the parental controls via parents permission.

**Comment by Flopgop** [comment]
Can't reproduce.
