### ISSUE TITLE
My Suggestions

### ISSUE THREAD

**Issue by Blitszy** [QuestCraftPlusPlus/QuestCraft#260]
My Suggestions
 
1. Create an option to make smooth camera movements, like when you gently move your cursor on PC (yes I'm aware you can look around in VR)

2. Add an option to replace your hands with Quest, Valve knuckles and the HTC Vives controllers. Also make it so you can change the color of them and hold them in your Minecraft hand if the hand is empty (sorry for such specifications, I just like the other controllers)

3. Make it so you instantly open the QuickChat menu instead of it giving the button to open it, you pressed the button after all

4. Add a feature to adjust how high and low the main menu screen is, the one with Multiplayer and Singleplayer

5. Create the feature to click on an inventory slot using your other hand/controller

6. Make it optional to keep the inventory, health, XP and the rest 

7.  (For the Future) If it's possible, add hand tracking. It may be hard, but it could add alot

8.  (For the Future) Try to add full body tracking, and make it an optional mod to make the Minecraft body more flexible

9.  (For the Future) Also make it a feature or mod to make the arms connect or disconnect. Let me explain, sometimes in VR the hands are seperated from the body and are just floating but it's the opposite for others. Whatever it is on QuestCraft (I don't have a Quest so I don't know,) make it a mod for the opposite

Also, these are just suggestions I made and these are completely optional to you, you don't need to add these. Also, you can do these when your done finishing working on mods and other things. Also excited to see the new launcher and I may get a Quest soon, keep the hard work up because it'll pay off, and hats off to you guys for making this a thing! Also sorry for how picky number 2 is, I'm just kind of weird but I overheard other people wanting it too, so I thought I would add it, anyways thanks for reading and have a good day!

**Comment by wellsilver** [comment]
> Create an option to make smooth camera movements, like when you gently move your cursor on PC (yes I'm aware you can look around in VR)
WIP

> Add an option to replace your hands with Quest, Valve knuckles and the HTC Vives controllers. Also make it so you can change the color of them and hold them in your Minecraft hand if the hand is empty (sorry for such specifications, I just like the other controllers)
impossible or extremely difficult, and not to mention useless to implement, if you had HTC or valve controllers you could play vivecraft and get better FPS

> Create the feature to click on an inventory slot using your other hand/controller
this would rather be asked for MCXR

> (For the Future) If it's possible, add hand tracking. It may be hard, but it could add alot
Hand tracking isnt very good for games

> Try to add full body tracking, and make it an optional mod to make the Minecraft body more flexible
quest doesnt have full body tracking, and if it will it will most likely be very limited

> Also make it a feature or mod to make the arms connect or disconnect. Let me explain, sometimes in VR the hands are seperated from the body and are just floating but it's the opposite for others. Whatever it is on QuestCraft (I don't have a Quest so I don't know,) make it a mod for the opposite
this is not true

**Comment by ReubenDollmanYT** [comment]
> Add a feature to adjust how high and low the main menu screen is, the one with Multiplayer and Singleplayer

This allready exsists use the menu button on the controller to do this
