### ISSUE TITLE
[FEATURE] Realistic motion breaking and placing

### ISSUE THREAD

**Issue by Tyson6474** [QuestCraftPlusPlus/QuestCraft#261]
I always wanted to know how it'd feel like to actually love your arm and place a block, break a block, etc.

Using motion controls in order to place and break stuff.

I just swing my arm and press the left trigger to feel like I am placing a block.

**Comment by Mathias-Boulay** [comment]
*mapping motions to inputs could be fun indeed*

**Comment by D2Lx0wse** [comment]
Issue/feature duplicate, please check my statement, if true close this

**Comment by Tyson6474** [comment]
Please provide link.

**Comment by Tyson6474** [comment]
Ah. Now this issue will be closed.
