### ISSUE TITLE
[BUG] Keyboard

### ISSUE THREAD

**Issue by Tyson6474** [QuestCraftPlusPlus/QuestCraft#262]
**Describe the bug**
Link replaces letters.

**To Reproduce**
1. Go to a popular server.
2. Click on chat.
3. Click a letter with a link behind it.
4. Accidently click link.

**Expected behavior**
Click on a letter with a link behind it and it won't open the link.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v38
 - Device: Quest 2
 - QuestCraft Version v1.2.0

**Additional context**
You can move the keyboard below the chat is a alternative and fixes the problem.

**Comment by ReubenDollmanYT** [comment]
I can add on to this as command popups also have this problem

**Comment by Flopgop** [comment]
Dupe.
