### ISSUE TITLE
The exactroot.zip isn't showing up

### ISSUE THREAD

**Issue by M1CR0WAVEEE** [QuestCraftPlusPlus/QuestCraft#263]
I don't know if this is happening to anybody else, but its just not showing up

**Comment by parkerlreed** [comment]
It's no longer needed. Everything is included in the apk on the latest release.

**Comment by JoshyJoshyVR** [comment]
Try uninstalling, but going into sidequest, the box with a line in it, custom command and then copy "adb uninstall net.kdt.pojavlaunch", now reinstall the apk. That will FULLY remove everything, but should fix your problem

**Comment by Flopgop** [comment]
Stale.
