### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by mineblox6197** [QuestCraftPlusPlus/QuestCraft#267]
When i am trying to login it says cannot reach login.live.com idk what to do is it normal do i have to uninstall reinstall like what?

**Comment by SeishinShinso** [comment]
Minecraft from gamepass or yours? What exactly error shows? Did you reinstall questcraft?

**Comment by AbyssAlley** [comment]
Mineblox, please try to describe the issue in more detail or send a screenshot.

**Comment by Flopgop** [comment]
Can't Reproduce.
