### ISSUE TITLE
[BUG] Hands Disappear after closing game

### ISSUE THREAD

**Issue by AriSparks** [QuestCraftPlusPlus/QuestCraft#27]
**Describe the bug**
Closing the game through the oculus menu causes a player's hands to disappear at next launch and the player no longer able to interact with the menu.

1. Join and then leave multiplayer game.
2. Open oculus menu from the oculus button on the right controller.
3. Click quit game through the oculus menu without closing Minecraft through it's own menu.
4. Relaunch the game as usual.

**Expected behavior**
The game should launch normally and the player's hands should be visible and usable.

**Headset Details (please complete the following information):**
 - Quest Build: [v37.0]
 - Device: [Quest_2]
 - QuestCraft Version [e.g. v1.0.0]

**Additional context**
I have no clue if this has anything to do with multiplayer or not, but that's the first thing that I did when I was able to play.

**Comment by MangoSwirl** [comment]
Are there any known workarounds to revert this?

**Comment by jakershaker1** [comment]
i have witnessed this bug after multiple crashes. might be from dropping my quest resolution via adb, might have been from increasing the ram available to the JVM. all i know is this seems to happen after crashes in general.

**Comment by jakershaker1** [comment]
> i have witnessed this bug after multiple crashes. might be from dropping my quest resolution via adb, might have been from increasing the ram available to the JVM. all i know is this seems to happen after crashes in general.

update:i think the hand model is still loaded but is just out of sight. im led to this conclusion because i saw the hand load in at launch and when the game freezes, i can see the hand just barely

**Comment by MangoSwirl** [comment]
I had the same problem. My hands dissapeared, but it turns out I was still able to interact with the menu.
