### ISSUE TITLE
[FEATURE] General features 

### ISSUE THREAD

**Issue by Envercety** [QuestCraftPlusPlus/QuestCraft#270]
- Add crossair when shooting projectile/bow
- Add dedicated drop item button
- Add smooth turning
- Add pointer/crossair to Menus
- Add guiding tips for new players on log in screen ex: "You must own a legit copy of Minecraft Java edition and it must be linked with your Microsoft Account"
- Add properly working in app crash log

**Comment by D2Lx0wse** [comment]
Since the average user doesn't use crash logs they are in the game folder

**Comment by wellsilver** [comment]
Yeah nobody except modders use the crash log, and even though this is a mod its just better that you dont need a crash log

**Comment by Undercoverer** [comment]
> Yeah nobody except modders use the crash log, and even though this is a mod its just better that you dont need a crash log

Sorry but what are you talking about... Plenty of people and projects use crash logs.

**Comment by Flopgop** [comment]
Stale.
