### ISSUE TITLE
[BUG] Game freezes upon instant kick in multiplayer servers

### ISSUE THREAD

**Issue by ofjowhswhe** [QuestCraftPlusPlus/QuestCraft#272]
**Describe the bug**
The game freezes on the red screen upon joining a server that automatically kicks you (e.g. 2b2t)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Multiplayer'
2. Join a server that kicks you before you join.
3. Game freezes.

**Expected Behaviour**
You will receive a kick message

**Headset Details (please complete the following information):**
 - Quest Build: 38.32
 - Device: Quest_2
 - QuestCraft Version: 1.2.0

**Comment by Flopgop** [comment]
Stale.
