### ISSUE TITLE
[BUG] controls bugged

### ISSUE THREAD

**Issue by Micocono123** [QuestCraftPlusPlus/QuestCraft#275]
**Describe the bug**
when i press the inventory button (Y on the left controller) it just opens the minecraft menu with the save and leave and all of that and the button that is supposed to open the minecraft menu does open the menu too

**To Reproduce**

**Expected behavior**
i really want a control binding so i can choose what button does what function
**Screenshots**

**Headset Details (please complete the following information):**
 - Quest build: i dont know probobly not the newest
 - Device:  Quest_2
 - QuestCraft Version: the one from sidequest i think its the newest

**Additional context**

**Comment by Flopgop** [comment]
Not enough information and stale.
