### ISSUE TITLE
[BUG] questcraft 1.2.0 showing black screen

### ISSUE THREAD

**Issue by Manguyyesno332** [QuestCraftPlusPlus/QuestCraft#277]
questcraft 1.2.0 showing black screen when opening but also plays music and sounds in the backround

**Comment by Flamgop** [comment]
Before clicking play goto the versions list (it's left to the PLAY button)  and scroll all the way to the bottom and click the one that says fabric

**Comment by ATXLtheAxolotl** [comment]
We’re you able to resolve this @Manguyyesno332

**Comment by Manguyyesno332** [comment]
yeah

**Comment by AirplaneBoi** [comment]
are you by anychance playing with a roomscale boundary?

**Comment by Manguyyesno332** [comment]
its solved now, but yes i am.
