### ISSUE TITLE
[BUG] Cant login with majong account

### ISSUE THREAD

**Issue by Xnitro67** [QuestCraftPlusPlus/QuestCraft#278]
there is no button to log in with majong account on latest version

**Comment by parkerlreed** [comment]
Yes... You HAVE to use a Microsoft account now. All legit Mojang accounts got months of advanced warning to migrate. 

https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account

**Comment by Flopgop** [comment]
Won't fix, not a bug.
