### ISSUE TITLE
[BUG]when signed into quest-craft the fabric loader doesn't show up so it will not let me play

### ISSUE THREAD

**Issue by idasuperman** [QuestCraftPlusPlus/QuestCraft#279]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by gusbunce** [comment]
Can you please provide more details about your issue

**Comment by Flopgop** [comment]
Stale.
