### ISSUE TITLE
read this to explain why i got falsely banned from the mysticle server even though i have undeniable proof and they don't and how the mods are corrupt 

### ISSUE THREAD

**Issue by Pickymarker** [QuestCraftPlusPlus/QuestCraft#28]
the discord server which was the mysticle discord server i got banned on that got me banned from the quest craft server was being stupid and false banned me even and wouldn't unban me even though i had so much undeniable proof that if should be unbanned and when i try to get unbanned they would just block me and when my friend try to help me he got banned and they said because he was me but they have heard him before and they also the mods try to get me banned from any vr server i'm in they got me banned from gethips server and now questcraft and also any one that tries to help me get unbanned from that server gets banned so can i get unbanned from the questcraft discord server because i did nothing wrong and that person that caused me to get banned from the mysticle server is fine with my unban and he said the thing i gave him was safe and he was over exaggerating because the mods on that server were saying stuff to him so can i get unbanned from the quest craft discord server and if you can get me in contact with mysticle so i can show him the proof i have to get me unbanned from there also because the mods are saying stuff to mysticle to keep me banned which is not true

**Comment by Pickymarker** [comment]
and also if you want the proof i can send it

**Comment by jakershaker1** [comment]
the questcraft github is not where you take this. if you have a problem talk to the mods or people connected to mods.

**Comment by ProtatoPlus** [comment]
dont take this here this is for reporting bugs in questcraft

**Comment by Pickymarker** [comment]
then can i get unbanned from questcraft server and also where would i take this

**Comment by Pickymarker** [comment]
and i don't know any of the mods on the questcraft server and the mystical server mods are corrupt even when i have undeniable proof and when i asked if i could talk to mysticle they were like you not getting unbanned even though if mysticle saw my proof and saw they had no proof i would of been unbanned

**Comment by gusbunce** [comment]
Im closing this issue. @Pickymarker this is not the place for this you did the crime you do the time and thats that.
