### ISSUE TITLE
[BUG] When clicking start, infinite 3 dots loading

### ISSUE THREAD

**Issue by glambombkl** [QuestCraftPlusPlus/QuestCraft#283]
when i click play, it shows me loading screen (3 dots) for infinity. btw i also hear music, nothing else. it worked the first time i used this.

**To Reproduce**
1. Go to pojavlauncher
2. Click on play
3. Infinite loading

**Expected behavior**
Play the game.

**Headset Details
 - Quest Build: newest
 - Device:  Quest_2
 - QuestCraft Version fabric loader (tried other versions too)

**Comment by Flamgop** [comment]
you selected the wrong version
Scroll all the way to the bottom and click fabric,
If you have 2 fabrics, uninstall and only install the apk (don't install anything else)

**Comment by itayalush** [comment]
Nothing can fix This, I only have the Old Version, Because I don't Have a Paid Account. I think QuestCraft app needs Offline Accounts also.
Say this to QuestCraft Developers**!**

**Comment by WMasterJedi** [comment]
I’m having the same issue but I am not able to scroll down to see the other game versions it’s just 2 fabric versions, 1.18 and 1.19

**Comment by Flopgop** [comment]
Stale.
