### ISSUE TITLE
[BUG] What type of game do you need to run it

### ISSUE THREAD

**Issue by BananBus** [QuestCraftPlusPlus/QuestCraft#284]
When i try to login it says i don't own the game. Is there a certain version from a certain place that you need for it to start?

**Comment by kirbster7** [comment]
you need java edition

**Comment by wellsilver** [comment]
You need to buy java edition with your Microsoft account that you are logging into linked

**Comment by anameleth** [comment]
I'm having the same issue and I definitely own java and play it regularly

**Comment by Flopgop** [comment]
Can't reproduce.
