### ISSUE TITLE
Add issue tab for the Sodium fork

### ISSUE THREAD

**Issue by ImUrX** [QuestCraftPlusPlus/QuestCraft#285]
You can activate the issues tab in the settings and make some issues so its easier to contribute to the project

**Comment by wellsilver** [comment]
1, the sodium fork isnt getting user input
2, they know
3, how does complaining about it not working contributing?

**Comment by ImUrX** [comment]
1. >At the moment, Sodium, Iris, and Canvas do not work. We are working on porting sodium, if you would like to contribute, please make a PR for your work on our [Sodium](https://github.com/QuestCraftPlusPlus/sodium-fabric) repo.
2. [why dont you use markdown features](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#lists) and knowing doesnt mean much in this case if they dont do it.
3. issues are the most used way currently in open source projects for documenting problems, enhancements and things that need to be done. If there is an alternative to it in the repo for helping, I'm all ears.
