### ISSUE TITLE
[BUG] 2 bugs

### ISSUE THREAD

**Issue by Xnitro67** [QuestCraftPlusPlus/QuestCraft#286]
first bug is that the menu is facing the opposite direction im facing regardless of pressing recenter and second is that creating or starting worlds games crashes(i wait but still nothing)

**Comment by adran06** [comment]
You can work around this with the Menu button on the left controller. It moves the menu to wherever you're facing/pointing (I can't remember which). Still annoying and needs to be fixed.

**Comment by gusbunce** [comment]
@Xnitro67 you need to press the menu button on the left hand controller. we will evenutally incorporate a fix to this.
