### ISSUE TITLE
QuestCraft Stalls out when using Roomscale Boundary [BUG]

### ISSUE THREAD

**Issue by AirplaneBoi** [QuestCraftPlusPlus/QuestCraft#287]
When I launch questcraft with a roomscale boundary (the guardian setting prompt when you start the quest), the game loads into the infinite dots and stalls out, where it knows that it has crashed, but it is not closing and this results in me needing to force reboot the headset entirely. However going into "stationary" guardian mode, the game runs fine. I assume something to do with the game having to handle a custom set boundary causes an issue with the loading. 

To Recreate: 
Simply select roomscale guardian boundary and make a custom guardian and then run the game. 

Meta Quest 2
v39

**Comment by AirplaneBoi** [comment]
This actually might be the reason why majority of other people are crashing; they are in roomscale boundary.

**Comment by jameswilddev** [comment]
I'm still experiencing the crash you describe in stationary guardian mode.  Thanks for the suggestion though I would never have thought to try it!

Perhaps a good quick fix might be to put a note on the "PLAY" button instructing the player to switch to stationary mode before starting?

**Comment by Flopgop** [comment]
Can't reproduce.
