### ISSUE TITLE
[BUG] game crashing randomly when trying to open

### ISSUE THREAD

**Issue by Corrupt17** [QuestCraftPlusPlus/QuestCraft#29]
**Describe the bug**

Game will crash anywhere before a world has been opened. It has now crashed as I'm opening the menu (during the red screen) while in the game menu (choosing a world), and loading a world.

**Comment by JD-The-65th** [comment]
Set your chunk render distance to 3.

**Comment by Corrupt17** [comment]
Wow, such a simple fix, thanks :D working amazing now.
