### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by paris1234567890** [QuestCraftPlusPlus/QuestCraft#290]
**Describe the bug**

**To Reproduce**
1. Go to 'play on fabric”
2. Click on 'ok’

**Expected behavior**
To open Minecraft 
It downloaded 316mb what did I do
**Screenshots**
E
**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by paris1234567890** [comment]
Please help I am worryed

**Comment by JD-The-65th** [comment]
You're gonna have to provide us more info if you want help. We aren't gonna be of much help if you don't fully fill out the template
