### ISSUE TITLE
[BUG] Getting a "Cant find Java 8" error when clicking "Install .jar"

### ISSUE THREAD

**Issue by ocarroll157** [QuestCraftPlusPlus/QuestCraft#291]
**Describe the bug**
Unable to install required files through the launcher

**To Reproduce**
1. Download the newest version of the launcher
2. Sign in through Microsoft account and select Fabric version and correct shader 
3. Click "Install .Jar"

**Expected behavior**
Files should be installed and game can be launched

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v38
 - Device: Quest_2
 - QuestCraft Version v1.2.0

**Additional context**
New Quest purchased last week with no previous Questcraft instances installed

**Comment by BurAndBY** [comment]
You don't need to. Just click fabric-loader in versions if you don't have it already
