### ISSUE TITLE
[BUG] cannot login

### ISSUE THREAD

**Issue by LeGuideMinecraft** [QuestCraftPlusPlus/QuestCraft#294]
**Describe the bug**
when i click on "microsoft login" they tell me it is impossible to load the web page "https://login.live.com/.... for the reason :
net::ERR_NAME_NOT_RESOLVED "

**To Reproduce**
1. Go to 'Unknown sources'
2. Click on 'QuestCraft'
3. Click on 'Microsoft Login'

**Expected behavior**
Bring me to the microsoft login web page

**Headset Details (please complete the following information):**
 - Quest Build: v39.0
 - Device: Quest_2
 - QuestCraft Version v1.2.0

**Comment by LeGuideMinecraft** [comment]
please ? ;-;

**Comment by LeGuideMinecraft** [comment]
please ? ;-;

**Comment by LeGuideMinecraft** [comment]
please ? ;-;

**Comment by LeGuideMinecraft** [comment]
please ? ;-;

**Comment by LeGuideMinecraft** [comment]
please ? ;-;

**Comment by wellsilver** [comment]
Change DNS

**Comment by yummysquash** [comment]
hiw tf do you change dns

**Comment by Flopgop** [comment]
Can't reproduce.
