### ISSUE TITLE
[BUG] i can't login by my phone's pojavlauncher not premium minecraft account, i put my username, my password and nothing happends.

### ISSUE THREAD

**Issue by GeometricAlexOfficial** [QuestCraftPlusPlus/QuestCraft#296]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by MrNavaStar** [comment]
You must own the java edition of the game on microsoft.
