### ISSUE TITLE
[BUG] i can't login by my phone's pojavlauncher not premium minecraft account, i put my username, my password and nothing happends., i expected to login and be in the pojavlauncher page, i have the latest version, the latest hardware version, and i use quest 2

### ISSUE THREAD

**Issue by GeometricAlexOfficial** [QuestCraftPlusPlus/QuestCraft#297]
**Describe the bug**
i can't login by my phone's pojavlauncher not premium minecraft account

**To Reproduce**
I try to login: i open questcraft on the qust 2, i put my username, my password, and nothing happends.
also if i click on the screen no mather where unless i'm not clicking on the app, it shows me the choose language menu

**Headset Details (please complete the following information):**
 -oculus quest 2 with the latest version of the hardware
-the latest version of questcraft

**Comment by L0um15** [comment]
> i can't login by my phone's pojavlauncher not premium minecraft account

After you open Questcraft click "Login using microsoft account", put your credentials and log in into microsoft account. If you own a copy of minecraft you should be able to download assets and start playing the game. Ofcourse i assume you migrated your mojang account.

**Comment by wellsilver** [comment]
> not premium minecraft account

You **NEED** a migrated premium mojang account to use this. **You need to buy the game!**

> I cant login by my phones pojav launcher

If you cant login to pojav launcher on your phone please clarify that and this is the questcraft github, not the pojav launcher github.

**Comment by GeometricAlexOfficial** [comment]
ah ok, i will buy it when i have the money, thanks for info
