### ISSUE TITLE
[BUG] Questcraft deleting `libjvm.so` when quest is powered off

### ISSUE THREAD

**Issue by walksanatora** [QuestCraftPlusPlus/QuestCraft#300]
**Describe the bug**
whenever quest craft is running and the quest is powered off (restart,low battery, powered off by holding the button) `libjvm.so`  gets removed which wont allow questcraft to start

**To Reproduce**
1. open questcraft
2. forcefully power off your quest by holding the power button
3. try to open questcraft again
4. infinite black loading screen and error in log stating `cannot find libjvm.so`

**Expected behavior**
`libjvm.so` is not deleted

**Screenshots**
not a screenshot but a log
[latest.log.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8551348/latest.log.txt)
(look at line 79 for start of the error)

**Headset Details (please complete the following information):**
 - Quest Build: v39.0.0.100.36350567
 - Device: Quest 2
 - QuestCraft Version: 1.2.0

**Comment by walksanatora** [comment]
NOTE: `libjvm.so` is re-installed if you just `adb install -r <questcraft apk>` but it is annoying to have to do it everytime i poweroff/reboot without exiting
my suggestion (if possible) is a `re-extract libraries` button somewhere in `miscellaneous settings`

**Comment by ManiacGamer156** [comment]
This is very odd, I have never experienced this bug but that is very bad. I will look into this.

**Comment by ManiacGamer156** [comment]
Accidental Close

**Comment by Flopgop** [comment]
Seems to be fixed(?)
