### ISSUE TITLE
[FEATURE] Add an option in settings for auto-adjusting height when sitting in minecarts, boats and horses and etc without having to physically sit down and stand up

### ISSUE THREAD

**Issue by AirplaneBoi** [QuestCraftPlusPlus/QuestCraft#301]
not a problem at all, just an idea that there should be an option to make it so the height of the player auto adjusts in vr for sitting in a minecart or a boat depending on whether the player wishes to physically have to sit down irl to simulate sitting in the minecart or not. 

If not sitting down physically, the player appears to stand whilst riding the minecart or boat currently which is kinda weird, thus forcing the player to physically adjust.  I assume this will get a lot of conflicting view points, so a togglable setting in the mcxr menu would be preferable for this depending on the players preferences, like i said above. 

thanks :D

**Comment by thejudge156** [comment]
Will be included in the new VR mod
