### ISSUE TITLE
[FEATURE] Cursors on all menus

### ISSUE THREAD

**Issue by walksanatora** [QuestCraftPlusPlus/QuestCraft#302]
**Is your feature request related to a problem? Please describe.**
I dislike how when in cartain GUIs like when on the keyboard, the crafting gui, ETC there is no cursor. this is annoying because some buttons dont have hover over effects (like the recipies in the recipe book) and it becomes really hard to tell where your cursor is pointing

**Describe the solution you'd like**
You can do one of two things. just create a 2d cursor that hovers over the gui to show where you are pointing. or draw a line pointing out from the players hand where it is pointing

**Comment by thejudge156** [comment]
Will be included in the new VR mod
