### ISSUE TITLE
Cant log in [BUG]

### ISSUE THREAD

**Issue by wenzoto** [QuestCraftPlusPlus/QuestCraft#304]
**Describe the bug**
When i am trying to login it says error

**Headset Details (please complete the following information):**
 - Quest Build: v39.0.0.88.336...
 - Device: Quest_2
 - QuestCraft Version: v1.2.0

**Comment by wenzoto** [comment]
when i try  log in

**Comment by wenzoto** [comment]
![4](https://user-images.githubusercontent.com/10740685/165598080-80cdcf8f-cb3f-4ae3-9313-5948ecfee825.jpg)
![5](https://user-images.githubusercontent.com/10740685/165598087-70f983c9-5859-4900-96c4-b7906af871ee.jpg)
![6](https://user-images.githubusercontent.com/10740685/165598088-f611c763-42d2-47bc-91ee-d68abd9a8237.jpg)
![3](https://user-images.githubusercontent.com/10740685/165598092-b702af3c-c198-4477-8a07-6b155fa81bfa.jpg)
![1](https://user-images.githubusercontent.com/10740685/165598095-a27e0b40-f1bf-4c9d-8950-763e9ef48aa6.jpg)
![0](https://user-images.githubusercontent.com/10740685/165598096-0287c98e-1f24-45ff-9acd-965704be8495.jpg)

**Comment by s2tb2007** [comment]
look at my bug thread i think it will help you out

**Comment by MrNavaStar** [comment]
Do you own java edition on microsoft? It wont work with bedrock accounts

**Comment by s2tb2007** [comment]
yes and i think OP has the same prob as i had

**Comment by wellsilver** [comment]
Lots of other people are having this issue, there is no publicly declared solution but you can try changing your DNS settings and join the discord to recieve help from people who have solved it

**Comment by Jack123672** [comment]
has anyone found a fix for this issue? :/

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))
