### ISSUE TITLE
[FEATURE] Separate keyboard instead of changing screen

### ISSUE THREAD

**Issue by YPetremann** [QuestCraftPlusPlus/QuestCraft#305]
**Is your feature request related to a problem? Please describe.**
This is related to multiple bugs :
- #228 #288 #262 
- Some interface like sign or from mods don't handle correctly the new keyboard (MTR when writing station/routes/depots names)

**Describe the solution you'd like**
The idea would be that when clicking an input, instead of changing the ui screen, it would make a separate keyboard 
- either with ube buttons like in the vivecraft mod, 
- or make a new surface under interface ui to render the keyboard ui.  

**Describe alternatives you've considered**
- forcing using physical keyboard via bluetooth

**Additional context**
![](https://i2.wp.com/www.vivecraft.org/wp-content/uploads/2020/08/584fc397ed656c177d3610bef68757fc-1.png?resize=300%2C169)

**Comment by Tman564ws1** [comment]
What about if also you could use the Oculus keyboard?

**Comment by YPetremann** [comment]
@Tman564ws1 that would be awesome, but as I've seen for now, a lot of app on the quest use their own keyboard instead of the oculus one (I don't know why)

**Comment by Flopgop** [comment]
This is planned.

> What about if also you could use the Oculus keyboard?

> @Tman564ws1 that would be awesome, but as I've seen for now, a lot of app on the quest use their own keyboard instead of the oculus one (I don't know why)

Mainly because it's not feasibly possible.

**Comment by thejudge156** [comment]
Will be included in the new VR mod
