### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#309]
**Describe the bug**
When holding any type of map that has been used, the item of the map will show instead of the actual map
**To Reproduce**
1. Make or Find a map
2. Use the map
3. Hold the map

**Expected behavior**
I expected the map to load and show the surrounding area like usual.
**Screenshots**
I don't have my Quest 2 with me at the moment
**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Oculus Quest 2
 - QuestCraft Version: 1.2.0

**Additional context**

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))
