### ISSUE TITLE
X-ray when looking into water

### ISSUE THREAD

**Issue by Ezrelek** [QuestCraftPlusPlus/QuestCraft#31]
**Describe the bug**
A clear and concise description of what the bug is. Whenever I look into the water I can see caves and liquids below

**To Reproduce**
1. Go to 'a world’
2. Click on 'nothing’
3. Stroll down to ‘the water’
4. See error ‘in the water’

**Expected behavior**
A clear and concise description of what you expected to happen. I would see more fish less cave 

**Screenshots**
![7E2A2602-19B9-40BE-AE70-2100F9F895BE](https://user-images.githubusercontent.com/100187472/155075800-428ace52-d1b6-4185-a4f9-eb42d35b6625.jpeg)

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0] v37
 - Device: [e.g. Quest_1, Quest_2] quest 2
 - QuestCraft Version [e.g. v1.2.3] newest 

**Additional context**

**Comment by lrutjens** [comment]
This will happen with any semi-transparent block
