### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#310]
**Is your feature request related to a problem? Please describe.**
When I open a Book And Quill, there is no keyboard available to type.

**Describe the solution you'd like**
I'd ask if you guys can add the keyboard add in the last update to the Book and Quill menu as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by Flopgop** [comment]
Stale.
