### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#311]
**Describe the bug**
When it is raining in game, the cursor is invisible

**To Reproduce**
1. Wait for it to rain
2. And see for yourself

**Expected behavior**
I expected the cursor to appear the same as it were not raining
**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Oculus Quest 2
 - QuestCraft Version: 1.2.0

**Additional context**

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))
