### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#312]
**Is your feature request related to a problem? Please describe.**
When I try to sprint or sneak ingame, I have to hold down the joysticks the do so.
**Describe the solution you'd like**
I'd like for you guys to make a feature were you just click the joystick once and it will stay like that.

**Describe alternatives you've considered**

**Additional context**
Same the happens when flying in creative, and swimming.

**Comment by KevinKharma** [comment]
Sorry I forgot to name the issue.

**Comment by wellsilver** [comment]
You haved to do the same thing for consoles, this is just a controller scheme you dont like instead of a feature request. Its also not following the template

**Comment by Flopgop** [comment]
Intended function.
