### ISSUE TITLE
[BUG] The player can look through all by simply moving into them IRL

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#313]
**Describe the bug**
The player can look through all by simply moving into them IRL
**To Reproduce**
1. Go near a 2 block high wall
2. Walk towards it IRL

**Expected behavior**
I'd expected to be pushed make by some barrier to prevent looking through walls but there wasn't any.
**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Oculus Quest 2
 - QuestCraft Version: 1.2.0

**Additional context**

**Comment by wellsilver** [comment]
no

**Comment by wellsilver** [comment]
> > no
> 
> Wat

In Pavlov it's extremely annoying when you get pushed back, especially when half the time your not near a wall. Sorenon might be addressing the issue in the future though I don't know how that works and there's no word on it

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))
