### ISSUE TITLE
[BUG] Black screen with 3 dots loading.

### ISSUE THREAD

**Issue by Semper-Viventem** [QuestCraftPlusPlus/QuestCraft#315]
**Describe the bug**
After pressing a `Play` button I see just a black screen with a loading state. Nothing happening then.

**To Reproduce**
1. Select the 3rd option in the `Video and renderers` menu (gl4es 1.1.5)
2. Select `fabric-loader 0.13`
3. Tap the `Play` button

**Expected behavior**
App launched

**Actual behavior**
Black loading screen

**Headset Details (please complete the following information):**
 - Quest Build: 39.00.88.336
 - Device: Quest_2
 - QuestCraft Version 1.2.0 (from sidequest)

**Additional context**

**Comment by KevinKharma** [comment]
I uninstalled quest craft and reinstalled it and it worked, also make sure to put the app file you download on the GitHub page into your quest 2 internal storage which can easily be done using Sidequest. 

Good luck and I hope you get it fixed 👍

**Comment by Semper-Viventem** [comment]
Hey @KevinKharma ,

Thank you, but unfortunately, I did this three times before reporting the issue 😞

**Comment by Semper-Viventem** [comment]
Apparently, it really was a loading screen. On Quest 2, the loading screen was over two minutes long, so I interpreted it as a freeze. Closing Issues.
