### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sloushi** [QuestCraftPlusPlus/QuestCraft#316]
Multiple bugs I found while playing

Rain Removes crosshair when outside 
(not sure what causes this)

you can see caves through water and portals
(not sure what causes this)

Walking joystick flickers backwards when holding forward *sometimes* (not sure if this is a game issue or a controller issue but it only seems to happen on questcraft)

Other than that the game is really playable 
Just a few framerate problems that can probably be fixed through some other optimization mods or settings

**Comment by gusbunce** [comment]
Thank you!
