### ISSUE TITLE
[BUG]cant play a game a piad 24$ for

### ISSUE THREAD

**Issue by Questcraftsucks** [QuestCraftPlusPlus/QuestCraft#317]
Let me play my fucking game this 3 dots bug isnt fixable for me and a second bug to.
These three dots keep apearing and now i cant go to microsoft login page
**
**Expected behavior**
the game I paid 24$ dollars for

**actual behavior**
three dots and cant get to microsoft page

**Comment by WaffleDevs** [comment]
You didn't pay money for questcraft? You spent that money on a java account. Please create a ticket in the discord and ping @WaffleDevs#3065 for further assistance.
