### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Questcraftsucks** [QuestCraftPlusPlus/QuestCraft#318]
How about instead of this shitty gameplay of three dot watching how about u put in actual minecraft ya like in java minecraft?youve scammed me out of 24$ for microsoft

**Comment by ethpsa09** [comment]
maybe try factory resetting your device or try reinstall it bc that issue doesnt happen for me

**Comment by ethpsa09** [comment]
also issue #300  says that it could be caused by powering off the headset while its trying to open / open

**Comment by ManiacGamer156** [comment]
Maybe try reading the discords frequently asked questions.
