### ISSUE TITLE
[Spyglass issue]

### ISSUE THREAD

**Issue by Ezrelek** [QuestCraftPlusPlus/QuestCraft#32]
**Describe the bug**
A clear and concise description of what the bug is. When using the spyglass a seperate window will open on your left hand that will show the typical spyglass view but rather than zooming in it just has a see through window

**To Reproduce**
1. Go to 'your inventory'
2. Click on 'spyglass'
3. Select 'the spyglass'
4. Interact with 'the spyglass'

**Expected behavior**
A clear and concise description of what you expected to happen. The window having a zoomed in view of whatever is in front of it.

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/100187472/155078262-9718bb62-b0bf-4fce-8492-a2ecb5ec1b34.jpeg)![image](https://user-images.githubusercontent.com/100187472/155078307-25bd4ce3-a16f-4f09-bca4-cfbecacb447b.jpeg)

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0] 'v37'
 - Device: [e.g.Quest_1,Quest_2] 'quest 2'
 - QuestCraft Version [e.g. v1.2.3] 'latest version'

**Additional context**

**Comment by dugo3number2** [comment]
Interesting

**Comment by CorruptedPlazma** [comment]
Can confirm, actually, anything that would modify the FOV (zooming in via the spyglass or other means included) does not work.
