### ISSUE TITLE
[BUG]not really sure how to describe it, but shadows seem to dance and shimmer.

### ISSUE THREAD

**Issue by jakershaker1** [QuestCraftPlusPlus/QuestCraft#322]
**Describe the bug**
Shadows in the distance seem to shimmer and move with the player rotations and such. video attached.

**To Reproduce**
1.create/join world.
2.look at shadows in the distance(i saw it most with icebergs but does appear less dramatic in all spots)

**Screenshots**

https://user-images.githubusercontent.com/61605734/170734534-285edc0b-9e1d-498a-8792-ad25b70a8a14.mp4

**Headset Details (please complete the following information):**
 - Quest Build:v40
 - Device:quest2
 - QuestCraft Version 1.3

**Comment by wellsilver** [comment]
I think this happens when you click the incorrect option when it says opengl is bad

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))
