### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xnitro67** [QuestCraftPlusPlus/QuestCraft#325]
still having menu backwards/too low and still freezes after world creation. i can try reisntalling but im sure ill have same problem
![net kdt pojavlaunch-20220531-233800](https://user-images.githubusercontent.com/11791620/172887065-86b0ce53-ca1b-48e8-976b-94c2a2adde9f.jpg)

**Comment by LameMan0** [comment]
1. Press the menu button (on the left controller) to recenter the menu
2. It's supposed to freeze after world creation, give it 30-60 seconds to create the world

**Comment by Xnitro67** [comment]
If I recenter it it's still behind me

**Comment by AlecMcCutcheon** [comment]
I've been having the same problem with the menu being down and behide me

**Comment by AlecMcCutcheon** [comment]
it seems to be fixed after I load a world and go back to the menu, but it is no longer transparent

**Comment by AlecMcCutcheon** [comment]
also the back buttons in the launcher settings always logs me out. which makes navigating the setting really frustrating, also after I update my hotbar controls worked for a short time and now don't work at all, I tried a install and got the same as before.

**Comment by gusbunce** [comment]
Hey guys! It's been put on our known issues list and we will be pushing a fix in the next update.
