### ISSUE TITLE
[FEATURE] Add a non vr mod so pc players could see your VR movements

### ISSUE THREAD

**Issue by ReyTheDog** [QuestCraftPlusPlus/QuestCraft#326]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wellsilver** [comment]
QuestCraft uses MCXR Wich does have this, please refer to MCXR

**Comment by Cartrigger** [comment]
Soon.

**Comment by StormDragon-64** [comment]
Already coming, there is already an image in #dev-chat in the discord

**Comment by Flopgop** [comment]
Dupe of #385
