### ISSUE TITLE
[BUG] Attempting to install a .jar comes up with no Java 8 installed

### ISSUE THREAD

**Issue by DiamondSw0rd** [QuestCraftPlusPlus/QuestCraft#328]
I have seen this bug with others but haven`t seen/understood a solution yet. I don`t know if this is known or not but I haven`t seen it listed in the issues or anyone where else

When selecting "Install .jar", it comes up with "Can`t find java 8. In order to use this option, you need to install java 8"

If I`m just being stupid then please tell me and help with this because I have been trying to put other mods onto it.

**Comment by Cartrigger** [comment]
Go to the mods folder and install mods there only.
