### ISSUE TITLE
[FEATURE] Arrows fire depending on head direction instead of crosshair

### ISSUE THREAD

**Issue by KevinKharma1** [QuestCraftPlusPlus/QuestCraft#329]
**Is your feature request related to a problem? Please describe.**
When firing a bow or crossbow, the arrow gets fired from the head and not the direction of the hand holding the bow. This makes aiming the bow very hard and
**Describe the solution you'd like**
I'd like to have some way to aim the bow by holding in front of the player and firing.
**Describe alternatives you've considered**

**Additional context**
Another thing I've noticed was that when holding the crossbow, it's pointing towards the right.

**Comment by wellsilver** [comment]
Not QuestCraft issue make a new one at OPENXR

**Comment by thejudge156** [comment]
Will be included in the new VR mod
