### ISSUE TITLE
hand tracking crashes game

### ISSUE THREAD

**Issue by oliverwesley1** [QuestCraftPlusPlus/QuestCraft#33]
**Describe the bug**

**To Reproduce**
launch game
put controllers down and wait for hand tracking to turn on

**Expected behavior**
the contollers to follow the hands, or the hands to just dissapear

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [v37.0]
 - Device: [Quest_2]
 - QuestCraft Version [v1.0.0]

**Additional context**

**Comment by Flamgop** [comment]
Questcraft does not have support for hand tracking, and we have no plans to add hand tracking support in the future.
