### ISSUE TITLE
[CLOSED] [BUG] YOU DO NOT OWN THE GAME

### ISSUE THREAD

**Issue by JKDos** [QuestCraftPlusPlus/QuestCraft#330]
It's working now.

--The hell I do too--

--I can log onto my PC and play it right now....--

![image](https://user-images.githubusercontent.com/17679930/174403422-f97e6e34-b3c8-4083-afd3-4063aa3b6ef7.png)

![image](https://user-images.githubusercontent.com/17679930/174403476-dbdc6bcb-b944-4fb7-b030-7ef6ca22539c.png)

**Comment by StormDragon-64** [comment]
if there are no problems then close the issue
