### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by singe** [QuestCraftPlusPlus/QuestCraft#342]
**Describe the bug**
Infinite three dots loading after clicking play. Can't exit. Need to restart headset.

I'm using the third renderer and the fabric loader. I only have one fabric loader.

**To Reproduce**
1. Click play

**Expected behavior**
The game loads

**Headset Details (please complete the following information):**
 - Quest Build: v41.0
 - Device: Quest2
 - QuestCraft Version v1.3.1

**Additional context**
- fabric loader 0.14.8
- renderer gl4es 1.1.5 (OpenGL ES 3): exports OpenGL 2.1 + partial 3.2 (no 1.17 supported yet)

Installed via sidequest on device.
Uninstalling and reinstalling doesn't fix the problem.

**Comment by singe** [comment]
I saw https://github.com/QuestCraftPlusPlus/QuestCraft/issues/283 and can confirm I chose the right render.

**Comment by ReubenDollmanYT** [comment]
You no longer need to change the render in the past 2 updates they use Ultimate and it fixes alot of bugs

Thats why its not working
