### ISSUE TITLE
[BUG] Cannot Sprint or Sneak in 1.3.1

### ISSUE THREAD

**Issue by WI87** [QuestCraftPlusPlus/QuestCraft#343]
When i start up a world i cannot Sprint or Sneak

Pressing down on the joysticks will no longer cause the player to spring or sneak

I expected to be able to Sprint and/or Sneak by pressing down on the joysticks

Headset Details
 - Quest Build: v41.0
 - Device: Quest 2
 - QuestCraft Version Hotfix 1.3.1

Uninstalling and reinstalling did not fix

**Comment by gusbunce** [comment]
I will check the ActionSets in MCXR. When I am up and out of bed! :))

**Comment by WI87** [comment]
Thx :)

**Comment by JaffaJace** [comment]
sprinting and sneaking has been moved back to the grip buttons
the left grip is sneaking
the right grip is sprinting

**Comment by WI87** [comment]
Thanks for telling me
