### ISSUE TITLE
[FEATURE]When moving around your inventory slots. You should have a choice to use grip Or a thumbstick. 

### ISSUE THREAD

**Issue by Tman564ws1** [QuestCraftPlusPlus/QuestCraft#344]
**Describe the solution you'd like**
I would like when you are in the MCXR Menu that you could choose to Move around your inventory slots using grip or using the thumbstick.

**Comment by CyorgGit** [comment]
I agree. Grip should be the default, and for some people that prefer the thumbstick, it could be toggled somewhere in the controls menu.

**Comment by ReubenDollmanYT** [comment]
The reason it was changed from grips was that they were broken 
in the next update they should be back to grips

**Comment by Tman564ws1** [comment]
ya

**Comment by Flopgop** [comment]
Kinda dupe of #383
