### ISSUE TITLE
[Feature] Close button combination

### ISSUE THREAD

**Issue by Tman564ws1** [QuestCraftPlusPlus/QuestCraft#345]
**Is your feature request related to a problem? Please describe.**
Every time when I quit Questcraft From the Oculus menu, it sort of glitches. So I was wondering if you're stuck on a red screen. What about if a certain button combination Could get you to force quit?

**Describe the solution you'd like**
When you hold down a Certain button combination. It gets the game to force quit Example: A B X Y Grip left 

**Describe alternatives you've considered**
You also could fix the glitching when you exit using the Oculus menu.

Example of when this could be used. 
Let's say you go on a random server with an unsupported port. It would get stuck on a red screen. So then you just press that button combination or you could press the button and then it wouldn't glitch.  To recreate this. 
Go to: piesteal.feathermc.gg You will get stuck on a red screen.

**Comment by thejudge156** [comment]
This is a difficult issue to solve, a solution could be when the OpenXR session stops to force-quit the game.
