### ISSUE TITLE
Microsoft account 404 error

### ISSUE THREAD

**Issue by TFJ1802** [QuestCraftPlusPlus/QuestCraft#348]
Hi when signing into my Microsoft account on the quest I get an error: 
excited to get it working!
![IMG_3737](https://user-images.githubusercontent.com/49064004/178165582-e5bc13df-9e3c-4c5b-82f0-eabb1daa5690.jpeg)
![IMG_3736](https://user-images.githubusercontent.com/49064004/178165583-8bc72870-098d-41a0-b5c1-5936f2ca2450.jpeg)
![IMG_3735](https://user-images.githubusercontent.com/49064004/178165584-12677646-b419-4688-be9f-ed80a24b1213.jpeg)
![IMG_3734](https://user-images.githubusercontent.com/49064004/178165585-3c552ed1-7636-4d48-8821-2dd9e98bf28c.jpeg)
![IMG_3733](https://user-images.githubusercontent.com/49064004/178165586-78911f45-74ca-42d8-8dab-89cb818532d8.jpeg)

**Comment by Flopgop** [comment]
You don't own Minecraft: Java Edition on that microsoft account, you cannot play questcraft without it.
