### ISSUE TITLE
FSR support

### ISSUE THREAD

**Issue by LetoDK** [QuestCraftPlusPlus/QuestCraft#35]
Implementing AMD's FSR upscaling technology (FidelityFX Super Resolution) could potentially bring a considerable performance increase.
I have been using FHolger's OpenVR FSR, and his newer VR Performance Toolkit in order to use FSR with PCVR games, and most of the time it gives a significant performance boost.

As far as I can tell, Vulkan supports FSR, and the Quest supports Vulkan, so it sounds to me like it's theoretically possible to implement it.

Here is an article talking about how one could optimize FSR for use on mobile devices.
https://atyuwen.github.io/posts/optimizing-fsr/

**Comment by Foxlum** [comment]
This technically requires a ton of things happen first before it's even possible for fsr to work, Minecraft is pretty strictly Opengl with lots of GLSL, and very quickly going up in core specification. I'm not sure it's very viable to translate it to vulkan, but it would immediately throw wrenches the developer's wouldn't want.

**Comment by LetoDK** [comment]
I see. 
Here's a guy who got FSR running on OpenGL, so maybe this could be an approach?

https://jntesteves.github.io/shadesofnoice/graphics/shaders/upscaling/2021/09/11/amd-fsr-demystified.html

https://www.reddit.com/r/linux_gaming/comments/pnh1tp/amd_fidelityfx_super_resolution_10_fsr_demystified/

**Comment by gusbunce** [comment]
@LetoDK It doesn't seem particully dificult due to the fact that we are using gl4es but not only that we would have to do a lot of work inside of MCXR. This doesn't seem possible right now. But i will be closing this issue and tagging it with something to be looked at in the future.
