### ISSUE TITLE
[BUG]When installed, simple voice chat makes the game crashes upon reaching the red screen.

### ISSUE THREAD

**Issue by in801fo** [QuestCraftPlusPlus/QuestCraft#350]
**Describe the bug**
When installed, simple voice chat makes the game crashes upon reaching the red screen.

**To Reproduce**
1. Install simple voice chat 1.18.2.
2. Open the quest craft laucher.
3. Click play.
4. Wait for game to reach teh red screen.
5. See error

**Expected behavior**
The game should start with the mod functioning correctly.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: 41
 - Device: Quest 2
 - QuestCraft Version: 1.3.1.

[crash-2022-07-12_19.17.16-server1.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/9096739/crash-2022-07-12_19.17.16-server1.txt)

**Comment by Flopgop** [comment]
Fixed in 2.0.0 I believe.
