### ISSUE TITLE
Missing Java 8[BUG]

### ISSUE THREAD

**Issue by Julcraftlp** [QuestCraftPlusPlus/QuestCraft#352]
Bug:
Java 8 is missing and because of that I can not install the remaining depends

1. Install Questcraft
Log in
Click on install .jar in the bottom right

Headset Details:
 - Quest Build: 41.0.0.124.307.379035663
 - Device: Quest_2
 - QuestCraft Version v1.3.1

**Comment by Flopgop** [comment]
This button is supposed to be broken and is being removed soon.
