### ISSUE TITLE
[BUG] Where is your zip. file? I am only getting the APK and the source codes. It's crashing everytime I get to the red loading screen and I need to install the zip. file everyone is telling me and on my screen I only have the apk and the 2 source codes. No extractroot.zip file

### ISSUE THREAD

**Issue by NoahXSims** [QuestCraftPlusPlus/QuestCraft#353]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by questoutvr** [comment]
when you get to red screen dont touch anything untill its done and why do you need zip file apk file is for quest

**Comment by questoutvr** [comment]
do you have another headset?

**Comment by questoutvr** [comment]
if yes use it for questcraft like i did

**Comment by NoahXSims** [comment]
I'm using a quest 2 and I am using it for questcraft but for some reason it isn't showing

**Comment by JoshyJoshyVR** [comment]
Try uninstalling, but going into sidequest, the box with a line in it, custom command and then copy "adb uninstall net.kdt.pojavlaunch", now reinstall the apk. That will FULLY remove everything, but should fix your proble,

**Comment by Flopgop** [comment]
"extracttoroot.zip" does not exist anymore, any website or video that told you that is outdated. The only website Questcraft owns is https://questcraft.org. Please follow an up to date tutorial such as [BIG QUESTCRAFT UPDATE (NEWEST TUTORIAL)](https://www.youtube.com/watch?v=_jU8oDQblW8).
