### ISSUE TITLE
[BUG] Multiplayer and mods not working

### ISSUE THREAD

**Issue by kirbo-Dead** [QuestCraftPlusPlus/QuestCraft#356]
multiplayer and mods not working
when trying to set up multiplayer adding the severs.dat files multiplayer didn't work, so I uninstalled and reinstalled and then after adding my mods it crashed, so uninstalled and reinstalled and only added Cullleaves and lithium and then crashed I did this nine more times all getting the same result on both side quest release and GitHub release and even on older versions

**Headset Details 
 - Device Quest_2
 - QuestCraft v1.3.1, 1.3.0 1.2.0

**Additional context**
weirdest thing about this bug is if I delete ALL the files from sidequest, (witch will usually delete QuestCraft) QuestCraft will work normally (if you don't have any mods on) it seems like the flies in side quest through net.kdt.pojavlaunch.debug are completely separate to questcraft game

**Comment by Flopgop** [comment]
How odd.

**Comment by thejudge156** [comment]
Old issue, closing
