### ISSUE TITLE
I[BUG] menu dosen't load 

### ISSUE THREAD

**Issue by Fatface123290** [QuestCraftPlusPlus/QuestCraft#36]
**Describe the bug**
A clear and concise description of what the bug is.so i was put into the loading menu where singleplayer would be but all that was there was the menu world below 

**To Reproduce**
1. Go to 'pojav launcher ...'
2. Click on '.play...'
3. Scroll down to '.to nothing because there is no options..'
4. See error no menu 

**Expected behavior**
A clear and concise description of what you expected to happen. Idk 

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [latest build]
 - Device: [ Quest_2]
 - QuestCraft Version [1.0.0]

**Additional context**

**Comment by Goldenfreddy0703** [comment]
Hey so not sure if this is due to a bug but you may want to do the tutorial again but make you sure select "keep me login" on the login page sense it was not mentioned in the tutorial.
