### ISSUE TITLE
[BUG] Game never loads, and instead redirects you to a malware site.

### ISSUE THREAD

**Issue by BrainSlugs83** [QuestCraftPlusPlus/QuestCraft#360]
**Describe the bug**
Using both the released version from this site, and the version for SideQuest, the launcher never starts minecraft.  Instead after logging in (sometimes forcing you to login like 5 times), it then redirects you to `quest-craft.com` which appears to be a malware site.

Even closing out of that and pressing play does nothing, just puts you in a black screen that never does anything.

**To Reproduce**
1. Install the apk from releases, or from SideQuest.
2. Run the app and Login.
3. Get redirected to a malware site (`quest-craft.com`).
4. Close out of site, and try pressing play?
5. Wait 15 minutes in the black darkness without even a progress bar and then finally give up.
6. Uninstall, change your minecraft password, and log a bug on the appropriate github repo. 😅

**Expected behavior**
1. The app should not be redirecting us to external websites after we log in to it -- it should just close the browser (but definitely not sussy looking malware sites).
2. Pressing play should start the game -- if the game does not start within 10 seconds, there should be a loading bar so you know how long to wait.

**Headset Details (please complete the following information):**
 - Quest Build: v42
 - Device: Quest_2
 - QuestCraft Version; 1.3.1

**Comment by G3Coolness** [comment]
same thing happened to me

**Comment by BrainSlugs83** [comment]
I got a response on the developer's applab page that says they don't own the domain anymore. -- So to me that just confirms that the app is redirecting to malware, and shows that this is something which urgently needs to be fixed.

**Comment by AndrewTheNormalPerson** [comment]
Yeah, their website got sniped by some shady scammers on the dark web.

**Comment by Flopgop** [comment]
> Yeah, their website got sniped by some shady scammers on the dark web. So they completely lost control of the domain, [This](https://questcraft.net/) Is the link to their new domain.

Questcraft.net is **NOT** our new domain, https://questcraft.org is our new official domain

**Comment by Flopgop** [comment]
Closing because this issue is fixed.
