### ISSUE TITLE
browser bug

### ISSUE THREAD

**Issue by portalfanman** [QuestCraftPlusPlus/QuestCraft#361]
when launching it opens ww7.quest-craft.com

1. Click on play
3. wait for red screen
4. See the site

**Expected behavior**
Minecraft opens

**Headset Details (please complete the following information):**
 - Quest Build: [ v42.0]
 - Device: [Quest_2]
 - QuestCraft Version [e.g. v1.3.1]

**Comment by MBProductions** [comment]
encountered same bug when i finally got it too load, the site does not open on verisons under 1.19 but the screen stays black when trying verisons under 1.19 for me.

**Comment by Flopgop** [comment]
Fixed.
