### ISSUE TITLE
[BUG] Sign in broken

### ISSUE THREAD

**Issue by MBProductions** [QuestCraftPlusPlus/QuestCraft#362]
I just got Questcraft after months of trying, and was exited to finally play, but when trying to sign in i was given an error. Error 401 to be exact, so i searched it up, found a solution tried it, and then after that i got a new error! Now i couldnt even open the microsoft login page, so i searched it up, found a weird but functional solution, and tried signing in. And continue to get the 401 Error. Tired of it not working, i come here and see a multitude of bugs just uploaded about 1.3.1, and see that there must be someone taking hold of the game and using it to redirect people to a virus site!
I dunno if its failing to login because of this, or if its something else entirely. But here is how to reproduce it.

1. Open the game on the Quest 2 Headset
2. Wait for it to open, and press the microsoft loggin
3. Enter loggin info, and trying logging in, only to be given the 401 error
4. Search online for solution multiple times for way too long, only to circle back to the 401
5. Pray your info isnt being stollen after looking at most recent bug reports, and report but!

 - Quest Build: Latest Build
 - Device: Quest_2
 - QuestCraft Version 1.3.1

**Comment by MBProductions** [comment]
UPDATE:
Finally signed in, and saw the same issue the last 3 people uploaded, when pressing play the game opens a link to a virus site, WHICH IVE SEEN BEFORE EVEN! Closing the site and trying to play causes a black screen that does not fade!

I find it worth mentioning how the latest update, mentions no new Minecraft versions being playable, and only being able to play 1.18 but when i opened the game finally, i saw the versions 1.19 and 1.19.1

I tried playing 1.19 as thats the verison all my friends are, and encountered the. As i've dubbed it "Virus.Bug"
Im gonna try 1.18 to see if the same happens, until then im reporting the same bug as the last 3 under me
"Virus.Bug"

**Comment by MBProductions** [comment]
UPDATE:
When putting my headset on, it showed the loading dots without loading into anything.
After reseting the console, signigng in, opeing QuestCraft, and Trying 1.18 instead of 1.19 i saw that the game didnt open the virus site, instead downloading the version content like normal and allowing me to press play, but upon pressing lpay i encountered the black screen of death once more.
Assuming the worst since im not the only one today experiencing this.
I presume that Questcraft has been broken / hacked, and is attempting to get people to download a virus if not careful, and not allowing those who manage to press play, to play.
"Virus.Bug"

**Comment by MBProductions** [comment]
Trying to play more, ive found that the site is the legit verison of a site ive seen before, witht he one ive seen before being a recreation made to download viruses, how do i know that? I tried doing the same thing that gave my old computer a virus from the look-a-like site, and instead saw a normal site. So it is not a virus.

BUT ALSO when trying to load the verison 1.19 and above, they force open the site, and do not open any game. But versions 1.18 as ive seen so far, will open the game (kinda).
I can tell they load in the game because i hear a menu theme introduced in 1.18 only, but the screen stays black. After a bit it also opens the under construction site. I havent tested lower versions yet, but i assume they do the same, just with an old menu theme instead of the 1.18 new ones.

**Comment by Starkium** [comment]
same issue here

**Comment by Flopgop** [comment]
This is fixed.
