### ISSUE TITLE
[BUG] questcraft lotteraly unplayable because of dumb website thing

### ISSUE THREAD

**Issue by wingbroman** [QuestCraftPlusPlus/QuestCraft#363]
Every time I load up the launcher I usually wait for the browser to pop up then remove and then I can play but now it's gotten worse no matter what I do I can't play. I press play on the launcher after i closes the website. But then the website opens again causing the loading process to cancel every time I try to load quest craft website keeps opening and canceling my loading process.

**To Reproduce**
1. Go to questcraft
2. Click on select account
3. Wait for browser to pop up
4. Close it
5. Press play on the launcher wait for it to load:
6. Browser opens again and I cancels loading process

**Expected behavior**

**Screenshots** 
![Uploading 182635702...]

**Headset Details (please complete the following information):**
 - Quest Build: [v42.0.0]
 - Device: [Quest_2]
 - QuestCraft Version V1.3.1

**Additional context**
Would love an update if this getting fixed or not

**Comment by wingbroman** [comment]
Nevermind the issue was a mod I was trying to install but still would love the website issue to get fixed it's kinda repeative

**Comment by G3Coolness** [comment]
> 

what mod was it?

**Comment by Flopgop** [comment]
Fixed.
