### ISSUE TITLE
[BUG] Questcraft Opening ww12.quest-craft.com URL in Quest Browser

### ISSUE THREAD

**Issue by DanteTheEgregore** [QuestCraftPlusPlus/QuestCraft#365]
**Describe the bug**
This may sound odd, but I've got a bug in which Questcraft keeps opening the URL https://ww12.quest-craft.com in my Quest Browser which appears to just be a parked domain. I installed Questcraft via Sidequest and have not installed any further applications or made any changes except adding some mods to the .minecraft folder.

This issue initially started after I relaunched Questcraft a few times trying out new mods. It popped up a "what would you like to open this with" dialog listing the Quest Browser or Quest Runtime Framework as options. Without thinking I just hit "Quest Runtime Framework" and "Always Use This" (not the exact wordings) and this is when the issue began.

It's highly annoying as opening this page pulls focus away from Questcraft, requiring me to close out the web page and re-open the app.

**To Reproduce**
1. Install Questcraft via Sidequest
2. When given the option of what program to open the URL with, select "Quest Runtime Framework" and "Always Use This" (not the exact wording)
3. Questcraft now opens an annoying web page every time you launch it.

**Expected behavior**
No annoying web page.

**Headset Details (please complete the following information):**
 - Quest Build: 42.0
 - Device: Quest_2
 - QuestCraft Version: 1.3.1 according to Sidequest

**Additional context**
I am also unable to view any news in the launcher and am instead met with a white box in the portion where said news should be.

**Comment by Byoung3** [comment]
I agree. This same issue has been happening for me. So much that it is unplayable

**Comment by knightedangel** [comment]
Same here, i am on a quest 1 however

**Comment by Flopgop** [comment]
Fixed.
