### ISSUE TITLE
[BUG]Keeps opening shady website

### ISSUE THREAD

**Issue by Basis97867** [QuestCraftPlusPlus/QuestCraft#366]
Whenever i open questcraft it opens a shady website upon opening, and loading in is constantly interrupted by the website opening and cancelling loading 

I expected the game to load, but it didnt

1. Go to Questcraft
2. Click on Select account
3. At this point the website opens
4. Press play in the pojav launcher
5. during loading it will cancel and open shady website

 - Quest Build: 42 0.0.130.250.381640954
 - Device: Quest_1
 - QuestCraft Version v 1.3.1
.

**Comment by Basis97867** [comment]
Link to the shady site is ww12.quest-craft.com

**Comment by baq99** [comment]
I am also getting this issue

**Comment by tomivokhiddel** [comment]
download an older version of quest craft I also have this issue with the new version but I downloaded 1.2.0 of questcraft and it worked (it still opens the website but it wont cancel the loading screen)

**Comment by JacobWasTaken** [comment]
Just close the website and reopen the launcher.

**Comment by baq99** [comment]
Closing the first pop up is fine, but the second pop up closes the game and upon relaunching the launcher you need to relaunch the game which spawns the pop-up which closes the game and so on infinitely.

**Comment by JacobWasTaken** [comment]
What? Why? I only get one popup because my launcher doesn't actually close, it just minimizes when I get the browser popup

**Comment by baq99** [comment]
Mine does too, then after launching the game, I get a second pop-up which closes the game. As such, just relaunching the launcher fails to solve the problem.

**Comment by JacobWasTaken** [comment]
Odd, I dont get that. Do you have mods, if so would one of them open a page?

**Comment by baq99** [comment]
No mods, fresh install, correct renderer and the modified build selected. I think it may be a crash that then launches the website. Either way I can't play it.

**Comment by IvanDrago103** [comment]
I found the solution:

Reinstall it, and when it asks to update browser, DON’T UPDATE IT. I was having the same problem and that was why it was happening, so you have to reinstall it and when it says Browser has an Update, don’t update it. Have a good Minecraft game!

**Comment by IvanDrago103** [comment]
Nvm now it just replaces the website with the browser asking to update

**Comment by AndrewTheNormalPerson** [comment]
Their website got sniped!!!

**Comment by AndrewTheNormalPerson** [comment]
And They Lost control of their domain

**Comment by Flopgop** [comment]
Fixed.
