### ISSUE TITLE
[BUG] Both ways of downloading end up with the same thing.

### ISSUE THREAD

**Issue by 5ix1t** [QuestCraftPlusPlus/QuestCraft#367]
**Describe the bug**

**To Reproduce**
1. Go to questcraft launcher.
2. Click on play.
3. Wait for the red screen to pop up.
4. Game crashes.
I tried getting questcraft through side quest and the oculus sidequest app and they both crashed.
**Expected behavior**
I thought if i tried sideloading it it would work. I have never been more wrong in my life.

**Headset Details (please complete the following information):**
 - Quest Build: dont know :/
 - Device: Quest 2
 - QuestCraft Version 1.1.3

**Additional context**
Please fix ive been waiting to play minecraft vr for 9 months.

**Comment by Flopgop** [comment]
Closing because this issue is stale, try using 2.0.0 and seeing if that fixes your issue.
