### ISSUE TITLE
[BUG] when I use mods, it opens a malware website (now gives me error when i download mods from the launcher

### ISSUE THREAD

**Issue by G3Coolness** [QuestCraftPlusPlus/QuestCraft#368]
**Describe the bug**
When I install a mod, a malware website opens up

**To Reproduce**
1. Install quest craft on sidequest
2. Download mods from your pc
3. Open Pojav launcher
4. Click play.
5. website opens up, stopping the game from launching

**Expected behavior**
The game to load perfectly 

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: latest versions
 -
 - Device:  Quest_2]
 - QuestCraft Version 1.3.1
 - 

**Additional context**
please help

**Comment by wellsilver** [comment]
Check if the mods are doing that

**Comment by JacobWasTaken** [comment]
I have mods and what works for me is to open QuestCraft launcher then wait for the website to open (it does it automatically, I don't know how to stop it), then launch the game when you close the browser and reopen the launcher.

**Comment by PersvicxYT** [comment]
check the mods. they might be malicious.

**Comment by G3Coolness** [comment]
okay so 2.0.1 came out, I downloaded mods from the launcher and it gives me and error, both of them say null something something

**Comment by G3Coolness** [comment]
fixed it
