### ISSUE TITLE
[FEATURE] easier way to backup

### ISSUE THREAD

**Issue by JaffaJace** [QuestCraftPlusPlus/QuestCraft#369]
**Is your feature request related to a problem? Please describe.**
Most people forget to backup their worlds and mods when they uninstall to update, then they lose everything and cry about it.

**Describe the solution you'd like**
Add two buttons to the launcher, called **Backup** and **Restore**. **Backup** will grab all your worlds, mods and configs, and then **Backup** to an area outside of the net.kdt.pojavlaunch folder (so they dont get deleted when you uninstall). **Restore** would then read to that designated location and attempt to **Restore** the users worlds, mods and configs.

**Describe alternatives you've considered**
Add an auto-updater system :fakerealtroll:

**Additional context**
This is a good idea :)

**Comment by Flopgop** [comment]
Planned.
