### ISSUE TITLE
[BUG]cant play

### ISSUE THREAD

**Issue by dbolinger36** [QuestCraftPlusPlus/QuestCraft#370]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by dbolinger36** [comment]
theFile isn't There

**Comment by StormDragon-64** [comment]
you gave them 0 information, they can't do anything if you don't even provide a description xd
