### ISSUE TITLE
[BUG] Bows only shoot in one direction no matter where you look in QuestCraft 2.0

### ISSUE THREAD

**Issue by ObinSesami** [QuestCraftPlusPlus/QuestCraft#372]
**Describe the bug**
Is in the title

**To Reproduce**
1. Go to single player creative or survival
2. Choose a bow and arrow
3. Start shooting the arrow and you will see it will only shoot in one direction 

**Expected behavior**
YOu should expect to see the Arrow on ly shoot in one direction no matter where you look

**Screenshots**
None at the moment

**Headset Details (please complete the following information):**
 - Quest Build: V43
 - Device: Quest_2
 - QuestCraft Version 2.0

**Additional context**

**Comment by Flopgop** [comment]
This is because the server (or singleplayer server) spawns the arrow depending on the way your head is facing, and because the way your head is facing is the same way your actual IRL head is facing.

**Comment by thejudge156** [comment]
Will be included in the new VR mod
