### ISSUE TITLE
Can vr players see vr players hand movements?

### ISSUE THREAD

**Issue by TecEash1** [QuestCraftPlusPlus/QuestCraft#375]
Hi, I was just wondering if mxcr core is installed on a fabric server, and 2 people that are running questcraft joined, would they be able to see each others hand movements?

**Comment by StormDragon-64** [comment]
I don't think so, but I know it is planned

**Comment by Flopgop** [comment]
No, this feature is planned eventually though. Closing as this is a dupe.
