### ISSUE TITLE
[BUG] Doesn't Launch Minecraft from Pojav

### ISSUE THREAD

**Issue by Galdere** [QuestCraftPlusPlus/QuestCraft#38]
Doesn't Launch Minecraft from Pojav

Installed apk and copied unzipped data to correct directory
Chose 3rd option for OpenGL and chose Fabric.
On selecting play it stays on the three flashing loading circles for ever.

**Comment by mrtomer** [comment]
Me to

**Comment by Goldenfreddy0703** [comment]
If you guys go to the login page and check the "keep me logged in" it should help you alot. It's what fixed my issue.
