### ISSUE TITLE
Qc keeps crashing when i install mods.

### ISSUE THREAD

**Issue by jfoisjdoifverojoijerje** [QuestCraftPlusPlus/QuestCraft#382]
Quest craft will not work unless i have no mods. Every time I install a mod, it will crash my game. Ive tried instaling my mods in-game and manually. I even tried to reinstall qc. My freiend is also experiencing this problem, and so is alot of other ppl.

**Comment by Eliascoollo** [comment]
Any updates?

**Comment by swaggio7** [comment]
It's been one year, issues like these should be taken to discord
