### ISSUE TITLE
[FEATURE] Add the ability to rebind controls

### ISSUE THREAD

**Issue by Ak4055** [QuestCraftPlusPlus/QuestCraft#383]
I don’t like the new controller binds I think you should be able to make your own or have a few different presets I don’t like that there isn’t a sprint button I don’t like the crouch and I liked the old hot bar scrolling method with the stick the top trigger to select was the only thing I liked about the new controls.

**Comment by thejudge156** [comment]
OpenXR limitation, waiting for Sorenon to make a layer named SuInput that allows rebinding
