### ISSUE TITLE
[BUG] Getting kicked

### ISSUE THREAD

**Issue by JoshyJoshyVR** [QuestCraftPlusPlus/QuestCraft#384]
**Describe the bug**
I keep getting kicked from servers when using immersive controls, with error kicked for using hacks

**To Reproduce**
1: Launch questcraft, join a server and make sure immersive controls are on
2: break blocks

**Expected behavior**
being able to play game

**Screenshots**
none

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Manguyyesno332** [comment]
servers may be kicking you out because they think your using an autoclicker

**Comment by JoshyJoshyVR** [comment]
Oh alright, I contacted the owner, and they said they use "Vulcan" Anticheat. Would there be any way to stop me getting kicked? Its very annoying

**Comment by Manguyyesno332** [comment]
you cant use immersive controls in public servers unless it supports it because there's a chance that immersive controls can hit something like 20 times in a second

**Comment by JoshyJoshyVR** [comment]
Alright, Ill have a speak to the owner about it.
Thank you!
