### ISSUE TITLE
[FEATURE] Bring Back "Extractroot.zip".

### ISSUE THREAD

**Issue by AndrewTheNormalPerson** [QuestCraftPlusPlus/QuestCraft#386]
All the youtubers wrote that you had to extract the extractroot.zip archive to your oculus and you suddenly removed it. Either Someone give me a direct download link to extractroot.zip or bring it back

**Comment by 5ghzx** [comment]
The reason its gone is because it's longer needed. The devs understand that it was an annoyance to have to do this, so they streamlined the process.

**Comment by AndrewTheNormalPerson** [comment]
Thanks lol, it's dad talking now haha, I fixed it for the lil fella
