### ISSUE TITLE
[BUG] READ THIS

### ISSUE THREAD

**Issue by s2tb2007** [QuestCraftPlusPlus/QuestCraft#387]
BUG:Anyone reading this, DO NOT enable immersive controls when joining a public server (F.E. Hypixel), I just had to learn the hard way and got perm banned for (suspicious actions) when i went to punch a block. admins, what I would do to fix this is auto-disable the immersive controls when going into specific servers that are most competitive so that there are no advantages or risks of getting permbanned or getting kicked.

1. Go to an popular server known for its anticheat
2. Join it
3. Turn on immersive controls
4. Spam hit a block or a player and get permabanned or kicked in said server.

**Expected behavior**
I don't know if this is anticipated or not, i guess i just got unlucky.

**Headset Details (please complete the following information):**
 - Quest Build: v43.0
 - Device: Quest_2
 - QuestCraft Version 2

**Comment by JoshyJoshyVR** [comment]
This is obvious, immersive controls can click like 20 times a second. Just dont use immersive controls
