### ISSUE TITLE
[BUG] Oculus does not enter VR mode

### ISSUE THREAD

**Issue by 1XxEPICDJxX1** [QuestCraftPlusPlus/QuestCraft#389]
**Describe the bug**

**To Reproduce**
1. Go to 'Questcraft'
2. Click on 'Play'
3. See ‘Memory set to [default number]
4. See the gray screen where the launcher was

**Expected behavior**
For it to load the game properly and not launch the game in app mode.

**Headset Details (please complete the following information):**
 - Quest Build: [v44]
 - Device: [Quest_2]
 - QuestCraft Version [2.0.1]

**Additional context**

What I think is happening is the game runs but in the 2D app mode (which just shows a gray screen) instead of the normal 3D Game mode.

**Comment by thejudge156** [comment]
PTC issue, cant do much about it, (thanks oculus)

**Comment by 1XxEPICDJxX1** [comment]
Is there a way to downgrade from PTC?

**Comment by Proud754** [comment]
> Is there a way to downgrade from PTC?

No you just have to wait until the next official update and leave the Ptc so you don’t get issues again

**Comment by Rickeyrabbit** [comment]
same things happening to me on v46

**Comment by Rickeyrabbit** [comment]
> PTC issue, cant do much about it, (thanks oculus)

im on v46 and the meta app says im not in the ptc, having the same issue

**Comment by 1XxEPICDJxX1** [comment]
> > PTC issue, cant do much about it, (thanks oculus)
> 
> im on v46 and the meta app says im not in the ptc, having the same issue

@Rickeyrabbit they are aware of this if you check the discord, they are working on a fix because Meta broke QuestCraft.
