### ISSUE TITLE
[BUG] Sign text doesn't save 

### ISSUE THREAD

**Issue by LatteStarbuck** [QuestCraftPlusPlus/QuestCraft#392]
**Describe the bug**
So I place a sign in a server, I put some text on it like "Latte's House" and then I walk away from the sign, once it unloads and I walk back to the sign, the text is gone and everyone can see that it's gone, it only happens when I place signs in questcraft.

**To Reproduce**
1. place a sign
2. Put text on it
3. Walk away until it unloads the sign then come back to it.
4. See the text is gone

**Expected behavior**
The text would stay on the sign as intended 

 - Quest Build: Latest (I forgot it)
 - Device: Quest 2
 - QuestCraft Version 2.0.1

**Comment by thejudge156** [comment]
Yeah, Izzy forgot to send a packet to the server when sign text is entered, I will talk to him.

**Comment by thejudge156** [comment]
Will be included in the new VR mod
