### ISSUE TITLE
 [BUG] bow has incorrect accuracy

### ISSUE THREAD

**Issue by isseithegod** [QuestCraftPlusPlus/QuestCraft#393]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Flopgop** [comment]
Dupe of #372

**Comment by isseithegod** [comment]
> Dupe of #372

oop sorry didn't see it
