### ISSUE TITLE
[BUG] Minecart hurt me 🥲

### ISSUE THREAD

**Issue by ILikepeaches098** [QuestCraftPlusPlus/QuestCraft#398]
https://user-images.githubusercontent.com/114115251/191624895-24a37c9b-2bbc-454a-ab11-c1a553daff59.mp4

Small bug Mine-carts are painful 

**Headset Details 
 - Quest Build: [ v43.0]
 - Device: [Quest_2]
 - QuestCraft Version [v2.0.1]

**Comment by RealityXP** [comment]
bruh thats stock mc, this isn't even a qc issue you need to mine a block above

**Comment by ILikepeaches098** [comment]
Oh sry Ima try that rn and see if it works

**Comment by ILikepeaches098** [comment]
I broke 2 blocks above just incase and it helped on the way down, but not when riding the cart up the track…. 




https://user-images.githubusercontent.com/114115251/191627989-6ca3ef62-759c-4e2b-93f5-b9eebd83745c.MOV

**Comment by ILikepeaches098** [comment]
https://user-images.githubusercontent.com/114115251/191652629-802959b2-49ea-40e4-bb79-854067b867f5.MOV

I just tested this and it is for sure a bug , when you use a minecart to travel upward you’ll take damage..
