### ISSUE TITLE
[FEATURE] Access Game Offline

### ISSUE THREAD

**Issue by SiegemusDaBoss** [QuestCraftPlusPlus/QuestCraft#399]
Hi! So I know as of the time of posting this, PojavLauncher let's you create offline accounts to access the game, but you have to login with a Microsoft account that has Minecraft Java Edition purchased on it in order to actually download and play the game. I think this is great, because it ensures that only people who have purchased Minecraft officially play the game, yet also let's you play the game offline. What I usually do is create an offline account, then exit PojavLauncher, then re-enter the game and login with my Microsoft account that has my copy of Java Edition linked to it to start downloading the game. Once I have the game downloaded, and if I don't have wifi access on my Android device for whatever reason (in the car, or what have you) I can sign in with my offline account to get to the main menu of the app, and then login with my Microsoft account to play the game offline. All this to say, I think that QuestCraft would benefit greatly from bringing back the offline account access, yet keeping the current system of verifying the account with Microsoft servers (I'm talking about logging in with an offline account to access the main menu, then signing in to your Microsoft account to play the game offline while avoiding piracy).

**Comment by swaggio7** [comment]
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/87071118/869de1c6-8586-4b7b-bc6b-2ddff11ab621)
