### ISSUE TITLE
cant raise the chunk render distance

### ISSUE THREAD

**Issue by hydratedlava** [QuestCraftPlusPlus/QuestCraft#40]
when the chunk render distance or almost anything but vsync is tampered with the game insta crashes
**To Reproduce**
first ive seen many different people do it with out this no idea what makes mine and a few others not be able to turn it up
step 1: go to settings
step 2: click video settings
step 3:turn render distance up past 2
step 4 wait 3 seconds 
step 5: crash

**Expected behavior**
up'd render distance with out a crash every time i boot it up after

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest_2
 - QuestCraft Version 1.0.0

[latestlog.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8117752/latestlog.txt)

**Comment by Foxlum** [comment]
Best thing you can do is slowly pull it up, while staying relatively still, keeps the quest from rendering more and not cause the quest to forcibly kill QuestCraft.

**Comment by hydratedlava** [comment]
> Best thing you can do is slowly pull it up, while staying relatively still, keeps the quest from rendering more and not cause the quest to forcibly kill QuestCraft.

just tried it still cause QuestCraft to crash
