### ISSUE TITLE
[BUG]not loading just stays on a grey sceen then crashes

### ISSUE THREAD

**Issue by Savagediamond14** [QuestCraftPlusPlus/QuestCraft#400]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Flopgop** [comment]
Invalid issue
