### ISSUE TITLE
Portal Damage[BUG]

### ISSUE THREAD

**Issue by GeminVR07** [QuestCraftPlusPlus/QuestCraft#408]
**Describe the bug**

Often, when I go through a Nether Portal or End Portal, I take suffocation damage.

**To Reproduce**
1. Go through portal
2. Damage is taken

**Expected behavior**
When you go through a portal, suffocation damage is taken

**Headset Details (please complete the following information):**
 - Quest Build: v46
 - Device: Quest 2
 - QuestCraft Version: 2.0.1

**Additional context**
I suspect it is because I am not standing in the exact middle of my guardian, although I have not yet tested this hypothesis

**Comment by CADIndie** [comment]
I believe that your hypothesis is correct in some regard. When you are teleported in Minecraft, you are reset to the center of the portal I believe but with MCXR the player is placed according to their headset position which can lead to you being placed inside of the portal frame.

Our Vivecraft build should fix this issue as we have ceased all MCXR development aside from YVR specific implementations.

**Comment by GachaMeow** [comment]
YVR Can this all-in-one machine run?

**Comment by GachaMeow** [comment]
YVR Can the all-in-one machine work normally?
