### ISSUE TITLE
[BUG] repeating random red fried flash while playing

### ISSUE THREAD

**Issue by magmaroka** [QuestCraftPlusPlus/QuestCraft#41]
**Describe the bug**
when i open the game u will see a red flash while playing and in the menu.
it doesn't effect the game but it's quite annoying.

**To Reproduce**
1. to own a oculus quest 1
2. play the game

**Expected behavior**
to have no epilepsy like feeling while playing

**screenshot**
![Screenshot (103)](https://user-images.githubusercontent.com/75309620/155162012-f6501d43-20a1-4275-a121-9ced25d3f453.png)

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Quest_1
 - QuestCraft Version v1.0.0 (v1.1.0 unknown thanks to other bug)

**Comment by magmaroka** [comment]
no its when u play normaly in a word and outside of it


> Is this the same red flash that occurs when Minecraft starts, or a different thing?

**Comment by MrCardboard123** [comment]
This is happening to me aswell, for some more info (at least for me) it mainly happens on either the right half of the screen or the left half, I am not sure about this but it may have something to do with the position of the left hand.
