### ISSUE TITLE
[FEATURE] Add a drop down menu to choose mode

### ISSUE THREAD

**Issue by MythicGithub** [QuestCraftPlusPlus/QuestCraft#412]
I have a feature request, can you guys perhaps add a drop down menu to choose between MCXR and Vivecraft? Kinda like this:

Select VR Mod
vvvvvvvvvvvvv
Vivecraft
MCXR (Deprecated)

**Comment by Cartrigger** [comment]
no, as mcxr is no longer being worked on, vivecraft fabric has replaced it fully.

**Comment by MythicGithub** [comment]
i know that’s why I put [deprecated] but I feel like it would be a good option for those who prefer mcxr

**Comment by DED0026** [comment]
i agree with you that mcxr should be kept as history or a legacy version
it has still been worked on before the vivecraft switch so i feel it wouldnt be really great if that work was made obsolete

**Comment by DJZSwag** [comment]
But mcxr is incompatible with the latest Quest versions, so it would be useless

**Comment by MythicGithub** [comment]
you right I forgot mcxr was broken on v44+

**Comment by DED0026** [comment]
> But mcxr is incompatible with the latest Quest versions, so it would be useless

mcxr didnt break due to v44
it broke due to an issue with starting vr view or something along those lines
mcxr should still be able to run in new versions of questcraft launcher.
