### ISSUE TITLE
[FEATURE] Smooth Look PLEASE

### ISSUE THREAD

**Issue by DJZSwag** [QuestCraftPlusPlus/QuestCraft#413]
**Is your feature request related to a problem? Please describe.**
No, but I am a long time VR user, and I HATED Snap Look. It just felt so immersion breaking and was a major turn-off if a game ONLY supports Snap Look. And I hopped in the server only to find out that Smooth Look is available.
**Describe the solution you'd like**
Just add Smooth Look.

**Additional context**
No, but the experience was quite a performance mess, but seeing as the entire app is rewritten, and the fact that it's a public beta kinda makes sense.

**Comment by LimeDev8756** [comment]
Its a thing, just gotta find it

**Comment by DJZSwag** [comment]
Where is it? I NEED TO KNOW AND MY LIFE WILL BE COMPLETE

**Comment by JaffaJace** [comment]
Where you have the snap look degree slider, just drag it all the way to the left :skull:
