### ISSUE TITLE
[BUG] Nether Portals Not Always Animated

### ISSUE THREAD

**Issue by LimeDev8756** [QuestCraftPlusPlus/QuestCraft#414]
**Describe the bug**
Nether portal only animates while I'm punching it

**To Reproduce**
1. Make a nether portal
2. See its not animated 
3. Punch it

**Expected behavior**
For it to be normal :/

**Headset Details (please complete the following information):**
 - Quest Build: v47
 - Device: Quest 2
 - QuestCraft Version v3.0.0 🎉

**Comment by OstapOmega** [comment]
Turn off "animate only visible textures" in sodium options

**Comment by wellsilver** [comment]
Nether Nortal 💀 💀

**Comment by MythicGithub** [comment]
Pether portal

**Comment by LimeDev8756** [comment]
Gets you to the greatest dimension, the Pether, might make that a mod now

**Comment by WI87** [comment]
> Turn off "animate only visible textures" in sodium options

The default should be changed so that thats on automatically

**Comment by X-Sly** [comment]
> > Turn off "animate only visible textures" in sodium options
> 
> The default should be changed so that thats on automatically

It's so the game runs smoother and is less laggy

**Comment by LimeDev8756** [comment]
Override why did you change the Pether Nortal 😭
