### ISSUE TITLE
[BUG] Sprinting and Interacting are on the same bind

### ISSUE THREAD

**Issue by Lexian-droid** [QuestCraftPlusPlus/QuestCraft#416]
**Describe the bug**
When pressing the button: Right trigger on the left hand (aka: "Use" button) will cause you to sprint in the direction that hand is pointed.

**To Reproduce**
1. Start a world or join a server
2. Point your hand outward
3. Take your non-dominant hand
4. Press and hold the trigger button
5. Your character will sprint depending on where your non-dominant hand is pointing.

**Expected behavior**
The use button should only be for using blocks and interactable. The issue causes the player to run forward, being that this is VR, means your hand may move, or if you're pressing a button, may cause delay.

**Screenshots**
N/A

**Headset Details (please complete the following information):**
 - Quest Build: 49
 - Device: Quest_2
 - QuestCraft Version 3.0.0

**Additional context**
It is important to know that this error was seen on a server running Paper 1.19.3, and a bungeecord proxy network. It was Not using a plugin of any kind to appoint VR support. It was not tested on a regular server, or the XRCraft server.

**Comment by DED0026** [comment]
i believe this is only accurate on servers without vivecraft plugin, cart had recently added it to the known issues

**Comment by Lexian-droid** [comment]
> i believe this is only accurate on servers without vivecraft plugin, cart had recently added it to the known issues

Perhaps you are correct, and I think I found a fix, temporary fix, join MCXR, and then leave, then join the server you want to join, and the sprinting with trigger doesn't happen anymore.
