### ISSUE TITLE
[BUG] Can't place seeds

### ISSUE THREAD

**Issue by Hk-5** [QuestCraftPlusPlus/QuestCraft#418]
Hi, I'm just trying to play and not starve to death an I made a farm and I go to try to place a seed and it wasn't working

**Comment by RealityXP** [comment]
very detailed (totally)

**Comment by Hk-5** [comment]
I accidentally pressed submit to early. I updated it

**Comment by Hk-5** [comment]
Fixed it. It's very picky with its light

**Comment by LimeDev8756** [comment]
Thats how seeds work 💀
They need a certain light level

**Comment by Flopgop** [comment]
@Hk-5 could you tell us what light level you were trying to grow the seeds in? Vanilla Minecraft requires direct sunlight (skylight level of >8) for most plants to grow.

**Comment by thejudge156** [comment]
Can't repro.
