### ISSUE TITLE
[BUG] Game load stalls on Three Dots.

### ISSUE THREAD

**Issue by Kazlehoff** [QuestCraftPlusPlus/QuestCraft#42]
**Describe the bug**
Game load stalls on Three Dots. Minecraft menu music can be heard playing, but nothing else. 

**To Reproduce**
1. Open Pavlov launcher. Sign in to Microsoft account (merged account)
2. Set renderer to third option from top.
3. Scroll down to last option in menu, the one that is using Fabric. Allow game to download files.
4. Stare at three dots menu indefinatly.

**Expected behavior**
Expect main menu of game to show up

**Headset Details (please complete the following information):**
 - Quest Build: 37.0.0.147.109.346379382
 - Device: Quest 2 256GB model.
 - QuestCraft Version: 1.0.0

**Comment by wylie39** [comment]
make sure to reboot quest, open the launcher and hit "select account" instead of sign in

**Comment by Goldenfreddy0703** [comment]
Make sure you also select "keep me logged in" on the login page. It fixed my issue yesterday

**Comment by Kazlehoff** [comment]
Both suggestions above  did not correct issue.

**Comment by Goldenfreddy0703** [comment]
Best thing I would do is to start all over again and then follow the tutorial video but make sure to select "keep me logged in" on the login page sense it was not mentioned in the tutorial video.

**Comment by Goldenfreddy0703** [comment]
That's odd, it fixed my issue and alot of people had this same problem. 

Thank you for closing this though.
