### ISSUE TITLE
[FEATURE] Immersive portal fabric support

### ISSUE THREAD

**Issue by Bmbay10** [QuestCraftPlusPlus/QuestCraft#420]

**Comment by Ryguy6001** [comment]
Immersive portals is not going to work, it would require shaders to be added and shaders are most likely not the highest of priority.

**Comment by thejudge156** [comment]
Shaders are actually a huge priority of mine, not like making-the-game-look-good shaders, but OpenGL shaders. The translation between Desktop GL and GLES is finicky and does not work 25% of the time.

**Comment by Foxxy-01** [comment]
Can't wait for this, even if it takes ages, just can't wait

**Comment by swaggio7** [comment]
> Can't wait for this, even if it takes ages, just can't wait :)

Guess what! Next update will bring in Vulkan support, so IP might function!
