### ISSUE TITLE
[FEATURE] Add old movement settings back

### ISSUE THREAD

**Issue by WI87** [QuestCraftPlusPlus/QuestCraft#424]
I know this might not be a qc issue but a vivecraft issue but i would appreciate if you could bring back the old movement settings where you can set things like walking/running direction to be based on where the head is looking but keep flying/swimming direction based on where the hand is facing. I like this instead of it all just being one setting for all ways of movement. Thanks

**Comment by CADIndie** [comment]
We want to stay as feature parody as possible with Vivecraft. We may add this in the future if it is requested enough but we have not found much push for it as of yet.
