### ISSUE TITLE
[FEATURE] MCXR Support

### ISSUE THREAD

**Issue by SmashHits** [QuestCraftPlusPlus/QuestCraft#426]
i dont think i will get used to the new vivecraft settings and ui and stuff, so i request a loader that allows the vr support found in 2.0 because it is just better, or atleast have a setting to make vivecraft as close as possible.

**Comment by CADIndie** [comment]
Our switch from MCXR to Vivecraft has forced us to use very specific libraries that would not allow us to (at least easily) support MCXR. We may make a EOL (end of life) version that supports MCXR in the future but we will no longer support MCXR officially nor will we update it.
