### ISSUE TITLE
Authorization Code Loop - Can't login with Microsoft Login (issue 417 fix unresolved)

### ISSUE THREAD

**Issue by emanuelkoseos** [QuestCraftPlusPlus/QuestCraft#427]
The fix to resolve issue #417 with QCXR patch 3.0.1 has created a new issue.

After code is submitted in browser and authorization verified; when the QuestCraft app is re-opened instead of allowing to login it resends another code to re-authorize; there is a continual reauthorization loop.

Cannot login via the Microsoft login

**Comment by sethamclean** [comment]
I was able to fix this issue by launching the java edition once using my Microsoft account.

**Comment by emanuelkoseos** [comment]
That worked for me as well; I created a new account and launched the java edition. Not sure if its the bedrock account that is the issue or not - that account has both bedrock and java. Believe we can close this now.

**Comment by emanuelkoseos** [comment]
Okay to close for now - I will continue testing. I am also able to build myself; although I have not figured out how to do testing on my laptop as yet. Looking to see if my 3.0.1 apk works now.
