### ISSUE TITLE
Changes not documented in 3.0.1 changelog

### ISSUE THREAD

**Issue by HungryBoy02** [QuestCraftPlusPlus/QuestCraft#429]
Updates were made to the controller settings menu of the vr settings that differ from 3.0.0

removed option to swap hands for lefties
removed option "right click repeat"
removed "show advanced bindings"

**Comment by HungryBoy02** [comment]
Additional changes i just noticed

Splash image previously said "Pojlib mcxr", this now says "Pojlib vivecraft"

**Comment by ferriarnus** [comment]
Seems like the reverse option got removed in https://github.com/ferriarnus/VivecraftMod/commit/12e7438d1ee771666cb092137a00a85387cc74b7#diff-2dbe4d60e3fa63ad464dfabb023b812444c1ea28f6c84bd5ef244748cf40983e Might be an oversight but could be intentional, related to some binding weirdness.

**Comment by thejudge156** [comment]
I removed it intentionally because it does not play well with OpenXR

**Comment by HungryBoy02** [comment]
> I removed it intentionally because it does not play well with OpenXR

How so? When I used it in 3.0.0 it seemed to work fine, aside from the joysticks being reversed. Furthermore please *document* these changes in your changelog.

**Comment by HungryBoy02** [comment]
if you're referring to the bindings not taking effect immediately, you just need to restart the game. This applies to vivecraft as well, and works as intended.

**Comment by ferriarnus** [comment]
Bit of a side note: only the button git removed, the actual config is still present and can be set. But as this seems to be working for people, maybe it can be brought back?
