### ISSUE TITLE
[feature] request

### ISSUE THREAD

**Issue by heyyou129** [QuestCraftPlusPlus/QuestCraft#43]
**Is your feature request related to a problem? Please describe.**
pls add something so people know how long they have to wait

**Describe the solution you'd like**
a loading screen

**Describe alternatives you've considered**
none

**Comment by gusbunce** [comment]
Its, a little know fact but loading screens are actually quite difficult to make and they are theoretically speaking "never" accurate. There is no way to know exactly how long something is going to take. I can definetly take a look in the code to see if there is a way to do this. Maybe if there is already a loop while loading we can. Implement to adjust the laoding bar by one increment every interation. Also is this in relation to loading the world or loading into the game?
