### ISSUE TITLE
[BUG] Game refuses to load after switching to flatscreen

### ISSUE THREAD

**Issue by Ctop28** [QuestCraftPlusPlus/QuestCraft#430]
**Describe the bug**

**To Reproduce**
1. Download Questcraft using Sidequest
2. Click on Microsoft login
3. Click Play
4. See three dots loading infinitely

**Expected behavior**
The game will open and I can play

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest 2
 - QuestCraft Version 3.0

**Additional context**
The first time I played I loaded in fine, and it seemed that is wasn't in the right vr mode, and on the side it said switch vr modes or something like that so I pressed it. It said changes will be made next load in, and I couldn't load in ever after that

**Comment by DirttKidd** [comment]
Everytime i hit the play button it takes me out of questcraft

**Comment by Flopgop** [comment]
Uninstall, then reinstall, and make sure you're updated to 3.0.1.
