### ISSUE TITLE
[BUG] player model render issues

### ISSUE THREAD

**Issue by LOLZSICKA** [QuestCraftPlusPlus/QuestCraft#432]
installed first person mod for 1.18.2 fabric: https://www.curseforge.com/minecraft/mc-mods/first-person-model/files

played, model rendered directly above head instead of below where it should be

in 2.0 this wasnt an issue, in 3.0 it is, and this isnt the only mod a bug happend.
the custom player models mod doesnt seem to render the model according to another who put it on for same version. it seems that player model from mods other than vivecraft has been bugged.

**Comment by youngchief-btw** [comment]
Just a bit confused why you'd want to effectively change the first person model when you're already in first person?
Maybe I misread this or something, so correct me if I'm wrong.

**Comment by thejudge156** [comment]
This is a vivecraft bug, report it to the fabric devs
