### ISSUE TITLE
[FEATURE] Distant Horizons Compatibility

### ISSUE THREAD

**Issue by rickeyrabbitt** [QuestCraftPlusPlus/QuestCraft#434]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
No thanks

**Describe alternatives you've considered**
Nah

**Additional context**

Distant horizons compatibility would be a great feature, to be able to set your render down super far and have lod fill in the rest would be amazing for performance.

**Comment by LimeDev8756** [comment]
They would have to fork the mod and develop their own version which means this will be low priority I think

**Comment by rickeyrabbitt** [comment]
> version

Probably, but if we're trying to get Java Mc to perform fast enough to really use on quest 2 then an LOD mod might be in order, think of the performance you could gain with your render set to 2 but you can see out to 10
