### ISSUE TITLE
[BUG] Multiplayer is broken

### ISSUE THREAD

**Issue by XcoolmanX** [QuestCraftPlusPlus/QuestCraft#435]
I use the version for Oculus not Oculus link not via computer we have a VR called meta quest 2 and formerly Oculus Quest 2 Recently I noticed that only English servers and some non-English servers work and all of them do not work, for example, no server from Poland, i.e. my country, is working servers are down at the end .pl I really want to fix Multiplayer because I had a great time playing with other people on vr and even people didn't have to have Vr only through a computer or other device and I had fun playing through VR no matter what they were on the device I had a great time and I want this option to come back so that you can play on every Multiplayer server and not just on some I have to mention that version 2.0.1 there was no such error and all servers were working and I would really like it to be like in this old version, so that all servers work again, not just those specified from your Quest Craft discord, I found out It's a bug, so I'm reporting it

**Comment by Eatham532** [comment]
That shouldnt be a QuestCraft issue. I am guessing that it may be an issue with your internet. 

What is the error that you get when trying to join a non english server?

**Comment by XcoolmanX** [comment]
it's not my internet's fault because after testing and discovering what exactly doesn't work in multiplayer Why don't all servers work I checked on the old version of questcraft 2.0. there was no problem in the old version of questcraft and I switched to multiplayer and so it wasn't the internet's fault As for what happens when I try to connect to the server, it keeps connecting to the server and doesn't want to enter as the wheel loads for a minute server on the list to detect Is there such a server, information pops up that there is no such server, but if I actually enter the wrong IP of the server, it immediately detects that there is no such server, i.e. as if it knew there was such a server, but could not locate it and could not enter it

**Comment by XcoolmanX** [comment]
until questcraft 2.0.1 version Multiplayer worked on every server without exception every server Multiplayer worked But since questcraft 3.0.0 all servers don't work only some probably only English but I'm not 100% sure if only English so I would like all servers to work and not only specified

**Comment by XcoolmanX** [comment]
will it be fixed?

**Comment by FedFer98123** [comment]
What error do you get when you try to join a server that doesn't work?

**Comment by XcoolmanX** [comment]
I can't quite explain it to understand exactly what I mean, that's why I made a video that shows what's happening to me, but English servers work for me, but Polish ones don't work for me and most of the servers except English ones don't work, some servers I took only as an example and they are not even on this version but although it should show me that it is not for this version and there is still a server connection no matter if these servers are for this version or not every time it is the same but as some examples of servers there that are for this version

Video:https://youtu.be/i46sRUVre-w

**Comment by FedFer98123** [comment]
It looks like you might have typed the IP addresses incorrectly

**Comment by XcoolmanX** [comment]
I checked they are entered correctly because on the computer and on the phone it worked I don't want it to work only on the vr version and when I enter the wrong IP it immediately detects that there is no such server And if I entered it correctly it is loading and after a minute it pops up that there is no such server server, so it detects something there but it doesn't finish and with each of these servers there is still joining the server and when I rewrite it, it immediately pops up that there is no such server, so something else

**Comment by Foxxy-01** [comment]
Are you 100% sure you typed the IPs correctly as I have only seen those errors when either, my WiFi is not connected and/or having issues, my server is having issues (not letting anyone join) or I have just typed the ip wrong so mabye ~~double~~ triple check all of those?

**Comment by XcoolmanX** [comment]
it is entered correctly I checked it because even six times when I talked to the administration on discord it turned out that the other action is these servers so the only thing I haven't tried yet because I basically have no influence on it, it seems to me that it may be some error with the account Microsoft, despite the fact that I have a premium, there are supposedly some problems that some people can't log in to their account, maybe I also have a problem with a different variant with a Microsoft account because I can't see anything else that could cause this error all the most standard ways which could be causing this I checked and it is not their cause So the simplest methods are not the cause of it

**Comment by XcoolmanX** [comment]
still on purpose, because I know a little about it, I transferred the files from the computer to record IPs of Multiplayer servers to VR to transfer all IPs of servers that I have entered on the computer and correctly, all of them work on the computer and even after transferring all IPs from the computer to VR Multiplayer still doesn't work for me so it's definitely not a fact of entering the IP incorrectly because that's how all servers would work for me

**Comment by cmbruns** [comment]
I found that when I entered the NUMERICAL ip address of my multiplayer server it connected correctly, but when I use the NAMED ip address I get a "Connection Refused" error. 

What works:
  * Connecting from QuestCraft 3.0.1 using the numerical IP address
  * Connecting from QuestCraft v44 using the named IP address
  * Connecting from PC minecraft using the named IP address
  * Connecting from PC ViveCraft with HTC Vive headset using the named IP address

What does not work:
  * Connecting from QuestCraft 3.0.1 using the named multiplayer server IP address

@XcoolmanX are you using a numerical IP address or a name IP address?

**Comment by XcoolmanX** [comment]
I also tried the numeric from the servo also does not work

**Comment by XcoolmanX** [comment]
I tried

**Comment by XcoolmanX** [comment]
did not work

**Comment by cmbruns** [comment]
Thank you. I see the issue I had is unrelated to yours. Sorry for hijacking your issue thread.

**Comment by XcoolmanX** [comment]
Problem rozwiązała wersja 4.0.0

**Comment by XcoolmanX** [comment]
Version 4.0.0 solved the problem

**Comment by superboo07** [comment]
this issue isn't fixed. im on the latest questcraft available on sidequest, and I cannot join my own server. Every single other device on my network can, but my quest specifically can't because it "can't connect to server". This is maddening, and I've tried typing in the ip. i've tried both domains i have pointing to my server. the push keyboard is rediculous because its too low while im sitting and i end up jamming my hand in my thigh. so I use the pointer one and if theres a button behind the keyboard that gets pressed instead.
