### ISSUE TITLE
[BUG] Boat controls are rotated 90 degrees counter-clockwise

### ISSUE THREAD

**Issue by Red5d** [QuestCraftPlusPlus/QuestCraft#44]
While riding a boat, the left hand joystick movement controls are "rotated" 90 degrees counter-clockwise.

The "forward" direction in the boat is joystick-left, rotate boat left is joystick-down, etc.

I'm running the current (Feb 22) version of QuestCraft from Sidequest.

**Comment by dangerousones** [comment]
Can reproduce

**Comment by ManiacGamer156** [comment]
Will report to Sorenon, this is probably a mcxr issue not a QC issue
