### ISSUE TITLE
[FEATURE] Change the Color Range to normal (Or at least have a option to switch it)

### ISSUE THREAD

**Issue by OstapOmega** [QuestCraftPlusPlus/QuestCraft#443]
I know you guys switched the color range to sRGB for performance. But almost all people hate the high gamma caused by this. I think it would be much better if there was a option just to switch between the normal color range and sRGB. And i think its not so hard to do that

**Comment by StormDragon-64** [comment]
Gamma is already fixed in dev builds, Just wait for them to finish 3.1.

**Comment by StormDragon-64** [comment]
(I think)

**Comment by thejudge156** [comment]
Actually, we aren't using an sRGB texture, this is a bug in Oculus where non-sRGB textures are washed out by a gamma factor of 2.2. This IS fixed in dev builds by changing gamma in the config, closing.

**Comment by thejudge156** [comment]
(This also happens for sRGB textures as well as GL4ES's sRGB handling is weird.)
