### ISSUE TITLE
[FEATURE] Add Debugify, Memory leak fix, EBE, More culling and Exordium as pre installed mods

### ISSUE THREAD

**Issue by OstapOmega** [QuestCraftPlusPlus/QuestCraft#445]
Debugify - Fixes annoying bugs, and also adding some performace improvements without affecting the gameplay https://modrinth.com/mod/debugify

EBE (aka Enhanced Block Entities) - will Reduce FPS lag with block entities UPD: Also mod indium required to get this to work https://modrinth.com/mod/indium
https://modrinth.com/mod/ebe

Memory Leak Lix - A mod that fixes random memory leaks for the client, will reduce memory ussage 
https://modrinth.com/mod/memoryleakfix

More Culling (Incompactible with cull less leaves) A mod that changes how multiple types of culling are handled in order to improve performance, also adding more culling options, and leaves culling is also included
https://modrinth.com/mod/moreculling

Exordium - Just renders the game GUI at lower framerate in order to sped up world rendering
https://modrinth.com/mod/exordium

**Comment by DJZSwag** [comment]
Were the mods tested on qcxr? Just want to know so I can add them

**Comment by OstapOmega** [comment]
> Were the mods tested on qcxr? Just want to know so I can add them

Yes. All mods are tested by me and are working perfectly with QC

**Comment by DJZSwag** [comment]
EBE, Indium, and More Culling didn't work, just crashed Vivecraft MC on boot.

**Comment by OstapOmega** [comment]
> EBE, Indium, and More Culling didn't work, just crashed Vivecraft MC on boot.

Remove cull less leaves mod, it is Incompactible with more culling

**Comment by DJZSwag** [comment]
I dont have the cull leaves mod, as that crashes MC on its own. Without it, it still crashes.

**Comment by DJZSwag** [comment]
Indium doesn't work, that is very restrictive as many mods that are compatible with Sodium require Indium.

**Comment by OstapOmega** [comment]
> Indium doesn't work, and that is very restrictive, as many mods that are compatible with Sodium require Indium.

Maybe it's issue in another mod. Cuz for me the mods are working perfectly

**Comment by DJZSwag** [comment]
Aight. You can rest this issue because I added all of ye mods to the recommended mods section (new pr will be published soon after this) except for EBE because it crashed MC on boot.

**Comment by swaggio7** [comment]
Aight. The PR will probably take a million years because I accidentally deleted my changes, so yeah
