### ISSUE TITLE
[FEATURE] Move .minecraft folder to the root of the Quest storage

### ISSUE THREAD

**Issue by DJZSwag** [QuestCraftPlusPlus/QuestCraft#446]
**Is your feature request related to a problem? Please describe.**
Whenever I install an update with SideQuest, I have to copy my worlds, uninstall, then install it due to some weird error when installing the apk.

**Describe the solution you'd like**
A good solution to this problem is moving the .minecraft folder (where mods, worlds, the core .jar, and other stuff is) To the root of the Quest's storage. It's similar to Guestroom, where the .wads of Doom and mods go to, so you dont have to worry when you are updating.

**Comment by DJZSwag** [comment]
Hmm? Why is it closed?

**Comment by JaffaJace** [comment]
Look at the reason for closure, 'not planned'

**Comment by DJZSwag** [comment]
Oop. Why tho
