### ISSUE TITLE
questcraft won't finish installing properly

### ISSUE THREAD

**Issue by XcoolmanX** [QuestCraftPlusPlus/QuestCraft#447]
I have a problem during installation at the time of installation questcraft keeps throwing me to the meta quest menu and the download doesn't finish so I can't start playing I deleted and reloaded several times and during the installation in the questcraft menu when I log in and wait for it to finish downloading after about 20 seconds it crashes questcraft and stops installing and doesn't work

**Comment by XcoolmanX** [comment]
in the previous version of questcraft there was no such problem

**Comment by NateMob1** [comment]
Experiencing this too on Quest 2. This wasn’t happening on 3.0.0

**Comment by DJZSwag** [comment]
Have you tried deleted the com.qcxr.qcxr folder in sdcard/Android/files?

**Comment by NateMob1** [comment]
> Have you tried deleted the com.qcxr.qcxr folder in sdcard/Android/files? Then try installing QCXR again.

Tried that, still happening :/

**Comment by NateMob1** [comment]
Fixed mine by just retrying and retrying, logging in each time but not reinstalling, until it worked.

**Comment by diskreet90** [comment]
seems this is happening again to me
