### ISSUE TITLE
[BUG] Indium isn't working, thus making lots of mods incompatible

### ISSUE THREAD

**Issue by DJZSwag** [QuestCraftPlusPlus/QuestCraft#449]
**Describe the bug**
In the latest version (3.1), lots of performance mods have been implemented, including Sodium. Because of that, however, I would need to get Indium in order to get access to lots of mods that are required. This didn't work, because it crashes on boot, for whatever reason. Removing the mod lets things run as normal, but as of a result, I can't use many mods. I am concerned of the fact that Indium is only happening to my headset only, as another user (OstapOmega from #445) got Indium working on their headset, so it could be that this bug applies to certain installations. Or it could just be my mods that are interfering, however.

**To Reproduce**
1. Download Latest Indium jar from Modrinth (CurseForge does the same)
2. Copy jar to mods folder using SideQuest
3. Launch QuestCraft

**Expected behavior**
Just to load properly

**Headset Details (please complete the following information):**
 - Quest Build: v47
 - Device: Quest 2
 - QuestCraft Version 3.1.0
**Additional context**
I did install some mods, and they all worked perfectly. I don't know if they are the ones interfering with Indium.

**Comment by Flopgop** [comment]
There is already a leaf culling mod installed

**Comment by DJZSwag** [comment]
Ooop, thanks.

**Comment by DJZSwag** [comment]
Welp, as it turns out, I just needed to update sodium.
