### ISSUE TITLE
[FEATURE] (1.19.3 Only) Update Sodium and add FastAnim as pre installed mod

### ISSUE THREAD

**Issue by OstapOmega** [QuestCraftPlusPlus/QuestCraft#456]
Sodium just released a new 0.4.9 version which adds some more performance https://modrinth.com/mod/sodium/version/mc1.19.3-0.4.9

FastAnim is a mod that just speeds up entity calculations https://modrinth.com/mod/fastanim
(Mod was tested by me and should work perfectly with QC)

**Comment by thejudge156** [comment]
Hey! Thanks for the heads up on Sodium, that will be very helpful for us. As for FastAnim I will get some of our testers to try it.

**Comment by thejudge156** [comment]
Just to see if it’s worth putting in

**Comment by swaggio7** [comment]
I can do another PR if it’s planned for 3.2.

**Comment by thejudge156** [comment]
@swaggio7 I am cool with that, but mods get updated on the fly, we can change them and Pojlib will grab them without a reinstall.

**Comment by swaggio7** [comment]
I didn't mean a PR for Pojlib! I meant the README.
