### ISSUE TITLE
[FEATURE] Add FPS presets in grahics options

### ISSUE THREAD

**Issue by OstapOmega** [QuestCraftPlusPlus/QuestCraft#458]
I know that most of the people are not enjoying these locked 72FPS on QuestCraft, and i know that QuestCraft has really bad FPS in some scenarios. But i believe, that it can reach at least 90fps at some points so it could be cool to just add FPS presets in options to switch between: 72, 90, (Maybe even 120 Frames Per Second)

**Comment by Flopgop** [comment]
Stable (locked) fps is better than fluctuating fps in my experiences.

**Comment by OstapOmega** [comment]
> Stable (locked) fps is better than fluctuating fps in my experiences.

For me too, but there are some points where you can get stable 90fps in QC - For example, play in a flat world with 2-4 chunks or while playing on a server. I was testing the FPS on the Peaceful Vanilla Club server and the framerate was Surprisingly good! I got stable 72 fps at 4 chunks! So maybe the framerate at some servers/worlds is not that good or stable, but again, at some points, you will get stable 90 fps. If not, you can everytime change the option in the settings.
