### ISSUE TITLE
[FEATURE] Ability to view chunk borders

### ISSUE THREAD

**Issue by saranicole** [QuestCraftPlusPlus/QuestCraft#459]
**Is your feature request related to a problem? Please describe.**
I would like to turn on chunk viewing in order to build a farm but I am unable to because there are no function keys on the keyboard to enable it.

**Describe the solution you'd like**
Add function keys that work as they do in regular Minecraft

**Describe alternatives you've considered**
I would also be fine with just some way to view chunks in Minecraft, although I feel like adding function keys that work would be a more universal solution.

**Additional context**
I am on Questcraft 1.19.3 on the Meta Quest 2.

Thanks!

**Comment by Cartrigger** [comment]
Overlay button shows f3 info... how would f5 work in vr

**Comment by saranicole** [comment]
@Cartrigger  thank you so much for the quick response!  Maybe all the function keys is too big an ask, I would definitely settle for just being able to view chunk borders via some button from the Settings screen.

**Comment by swaggio7** [comment]
The Alternate Radial menu is a good choice to place it. Easy to access.

**Comment by thejudge156** [comment]
I *could* add this as a custom keybinding, or make it so you can add key combinations to radial menu, I will implement this at some point.

**Comment by saranicole** [comment]
Awesome, thank you so much!

**Comment by saranicole** [comment]
Hey, I have great news, I figured out that with the Chunk Borders mod the command to show chunk borders actually shows up as available for the Radial menu.  Now my only issue is I can't seem to rebind any keys to open the Radial menu.  I have the perfect key for it - I don't use teleportation so the X key would be ideal, however when I highlight the "Unknown" button for "Toggle Borders" and press X nothing happens.  If I use a different key that's already mapped it shows up as red, and I can't figure out how to clear a button that's already mapped (so as to use the different key).

So close!  If you guys can unblock me on this last bit we may have our solution.
