### ISSUE TITLE
[BUG] Keyboard Doesn’t appear in multiplayer menu when adding server

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [QuestCraftPlusPlus/QuestCraft#46]
**Describe the bug**
When entering the Add Server menu of the multiplayer menu, the boxes for the IP address appears, however upon clicking this no keyboard appears.

**To Reproduce**
1. Go to Multiplayer
2. Click on Add Server
3. Click on one of the inputs
4. See the lack of keyboard.

**Expected behavior**
A keyboard appears

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0] 37.0
 - Device: [e.g. Quest_1, Quest_2] Quest 2
 - QuestCraft Version [e.g. v1.2.3] 1.0

**Additional context**
Note: you can still drag in servers.dat from your pc to add servers to the server list.

**Comment by ultimatexilliam** [comment]
They mentioned in the tutorial, that for now you need to use the servers.dat file

**Comment by BrandNewName** [comment]
To add a server, open up Minecraft on your computer, put in the server IP and then push Win + R, then type %appdata% and hit enter. Go into your .minecraft folder, and move the servers.dat item into the .minecraft folder in your quest.

**Comment by ATXLtheAxolotl** [comment]
Ok
