### ISSUE TITLE
[FEATURE] Make All Recommended Mods Pre-Installed

### ISSUE THREAD

**Issue by swaggio7** [QuestCraftPlusPlus/QuestCraft#461]
I have listed plenty of mods in the Recommended Mods section that;
A. Increases Performance (Memory Leak Fix, Exordium, etc.)
B. Makes the Experience Better and More Immersive (LambDynamicLights)
C. Makes Lots of Mods compatible with QCXR (Indium and Architecturary API)
It would be nice to have them all installed and make it much more convenient for the user.

Hmm, might as well make it a mod pack at this point.

**Comment by OstapOmega** [comment]
Debugify not only fixes minecraft bugs, it also adds some performance improvements replacing some other optimization mods

**Comment by swaggio7** [comment]
Only makes it more reasonable to include it!

**Comment by Flopgop** [comment]
It would be easier to list which mods Debugify is *not* incompatible with, it's such an incompatible mod 
It also has some shady behavior, see [here](https://gist.github.com/fxmorin/9770473614e3e5e0703e44273dab33f7).

**Comment by swaggio7** [comment]
Damn. On second thought, I could put Debugify onto the side for now.

**Comment by swaggio7** [comment]
There isn't any need to keep this issue up, as the devs stated that there wouldn't be any need for performance mods in the future.
