### ISSUE TITLE
Black World

### ISSUE THREAD

**Issue by TemiWhodeezarr** [QuestCraftPlusPlus/QuestCraft#462]
https://user-images.githubusercontent.com/125834297/219978956-4e4d4d23-04e5-478b-b3ad-9a4c297e888e.mp4

**Describe the bug**
After creating or entering an existing world, the display goes black. You can hear mobs around you and yourself breaking blocks if you hold the right trigger, but you can't see anything.

**To Reproduce**
1. Go to Questcraft and log in
2. Click on singleplayer (I don't have any servers to try on multiplayer so I don't know if it's the same)
3. Create a world or load an existing world 
4. Observe issue

**Expected behavior**
You will be able to hear mobs and yourself breaking blocks, but the display will be black.

**Headset Details (please complete the following information):**
 - Quest Build: v47.0
 - Device: Quest_2
 - QuestCraft Version: v3.1.0

**Comment by TecEash1** [comment]
This is a known issue, try setting your graphics quality to 'fast' ![image](https://user-images.githubusercontent.com/92249532/219979464-10c03a67-ac00-4ffe-9948-d68d35a2d6f4.jpeg) (it is in the top left of this image)

**Comment by JaffaJace** [comment]
You dont have to be ingame to change your graphics quality by the way.
If the issue persists, i suggest creating a ticket in the discord server and pinging either @JaffaJace#5930 or @TechyGiraffe999#0135

**Comment by TemiWhodeezarr** [comment]
Thanks it worked perfectly. 👌
