### ISSUE TITLE
[FEATURE] Adding QuestCraft Version number to be seen

### ISSUE THREAD

**Issue by ZbotZero** [QuestCraftPlusPlus/QuestCraft#464]
### **Is your feature request related to a problem? Please describe.**
I currently do not know what version I have, and this is an issue because if I don't know what version I'm on I don't know whether if upgrading will put me on where I already was or not, and **I don't like having to re-login.**

### **Describe the solution you'd like**
Showing the version number upon start, or shown inside the launcher when you choose what game version to launch in

### **Describe alternatives you've considered**
It could also be shown in the "F3" menu, but it's probably not needed

### **Additional context**
I have nothing else to add

**Comment by cmbruns** [comment]
I agree.
