### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by treatmeniceplz** [QuestCraftPlusPlus/QuestCraft#466]
**Describe the bug**
When trying to play Minecraft quest craft closes
**To Reproduce**
Just play Minecraft in the new Uu
**Expected behavior**
Minecraft launches
**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]
V39 quest 2 latest questcraft 
**Additional context**
I can't play Minecraft at all

**Comment by TecEash1** [comment]
Sorry, does this happen when you click play or when you are trying to join a world/server?

**Comment by treatmeniceplz** [comment]
> Sorry, does this happen when you click play or when you are trying to join a world/server? 

Press play

**Comment by Flopgop** [comment]
Invalid Issue, please use the [questcraft discord](https://discord.gg/questcraft) for support on playing the game. If you haven't already, try uninstalling *completely* and then reinstalling afterwards.
