### ISSUE TITLE
[FEATURE] Remappable keybinds

### ISSUE THREAD

**Issue by j5155** [QuestCraftPlusPlus/QuestCraft#467]
**Is your feature request related to a problem? Please describe.**
In Vivecraft you can remap keybinds using SteamVR. As questcraft does not use SteamVR there is no way to remap the controllers.

**Describe the solution you'd like**
Controller mapping options inside the launcher, like how Vivecraft and SteamVR work.

**Describe alternatives you've considered**
Technically an ingame menu like MidnightControls could also work, but that sounds more complex.
**Additional context**

**Comment by j5155** [comment]
@thejudge156 the issue isn't fixed.

**Comment by thejudge156** [comment]
OpenXR limitation, sorry.
