### ISSUE TITLE
[FEATURE] add a gamma slider

### ISSUE THREAD

**Issue by TwoKrazy** [QuestCraftPlusPlus/QuestCraft#470]
**Is your feature request related to a problem? Please describe.**
I've noticed that the whole game (apart from the launcher) looks like when you turn the gamma slider all the way up in the legacy console editions; it makes the colors look pretty washed out.

**Describe the solution you'd like**
Adding a gamma slider could fix the color issue, and people would be able to set it manually

**Describe alternatives you've considered**
Seeing that the brightness slider doesn't work in the vivecraft mod, I can't just set that to a negative value to correct it.

**Additional context**
This screenshot I've provided is in the main menu, but it looks exactly the same in-game
![com.qcxr.qcxr-20230225-104830.jpg](https://user-images.githubusercontent.com/45135693/221479889-a9fe0fbb-7b25-4be4-8eea-faf2373415dd.jpg)

**Comment by TwoKrazy** [comment]
I've edited the photo to show roughly how it _should_ look:
![com.qcxr.qcxr-20230225-104830.jpg](https://user-images.githubusercontent.com/45135693/221480639-3c44f534-71c9-46c1-ad58-f74f480d2291.jpg)

**Comment by Eyndjl** [comment]
It's not just the gamma level that's the problem. It's also a problem with the color range.

As I understand it, this flaw is fixed in the dev builds.

**Comment by Eyndjl** [comment]
This problem is fixed in dev builds, as far as I know.
