### ISSUE TITLE
[FEATURE] Pre-Installed Mods for the next update

### ISSUE THREAD

**Issue by swaggio7** [QuestCraftPlusPlus/QuestCraft#472]
As the next update will allow plenty of mods to work again, I recommend that ImmersiveMC and Distant Horizons be included to enhance the immersive experience further.

**Comment by thejudge156** [comment]
Remove distant horizons for now, as it requires OpenGL functions that are not currently implemented

**Comment by thejudge156** [comment]
Oh I read that wrong

**Comment by thejudge156** [comment]
Nevermind

**Comment by swaggio7** [comment]
We make mistakes 🤷‍♂️
