### ISSUE TITLE
[BUG] Failed to log in

### ISSUE THREAD

**Issue by alwzfolwd** [QuestCraftPlusPlus/QuestCraft#474]
**Describe the bug**
Unable to log in

**To Reproduce**
1. Go to login screen
2. Click on '.... Microsoft Login
3. Follow login instructions.'
4. Click on Microsoft login again
5. See error

**Expected behavior**
I expect to be logged in

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0] 
 - Device: [e.g. Quest_1, Quest_2] Quest 2
 - QuestCraft Version [e.g. v1.2.3]  unknown

**Additional context**

I'm able to log in to my Microsoft account and link it to the game as per the instructions, however, upon completing the download and clicking the "Microsoft Login" button again, nothing happens. It is frozen there and nothing has helped.

**Comment by EyaeM** [comment]
Did u wait until instances are done downloading before pressing login again?

**Comment by EyaeM** [comment]
dude u cant just make a bug report and dip

**Comment by alwzfolwd** [comment]
Meaning what exactly?

**Comment by alwzfolwd** [comment]
Yes, I waited until all files were downloaded per the instructions and still nothing.

**Comment by StormDragon-64** [comment]
What version of quest craft are you using? If you don’t know, then when did you install questcraft?

**Comment by alwzfolwd** [comment]
I installed questcraft yesterday.

**Comment by alwzfolwd** [comment]
Anything?

**Comment by StormDragon-64** [comment]
Just reinstall questcraft and try again. Make sure to not take off you headset while it's downloading and wait for it to finish downloading everything before you continue.

**Comment by TecEash1** [comment]
Hi 👋 

I am from the Questcraft Support team on their [discord server](https://discord.gg/questcraft). 

- Do you own Minecraft java editon by any chance?
- Also if you do own it, does it have a username linked to it?
