### ISSUE TITLE
[FEATURE] Desktop players see VR players' hands

### ISSUE THREAD

**Issue by TheZoidMaster** [QuestCraftPlusPlus/QuestCraft#475]
**Is your feature request related to a problem? Please describe.**
**My feature request is not related to a problem.**

**Describe the solution you'd like**
**I would like desktop Minecraft players to see VR player's hands.**

**Describe alternatives you've considered**
**I'm not really sure of any alternates to this besides just not doing it.**

**Additional context**
**_No additional context_**

**Comment by Ryguy6001** [comment]
This will not work with stock minecraft, I believe it will work if you have vivecraft installed on the pc you are watching the VR character with.

**Comment by cmbruns** [comment]
I can confirm that using the client side NONVR variant of the vivecraft mod definitely does allow desktop PC players to see the hand movements of players using QuestCraft (and other vivecraft-based VR players), as mentioned by Ryguy6001. That is the only way.
