### ISSUE TITLE
[BUG] Login Button does nothing

### ISSUE THREAD

**Issue by carkwithasee** [QuestCraftPlusPlus/QuestCraft#476]
MAJOR login issue. it seems that every version dowloaded to my oculus quest headset gets me as far as the microsoft login page before going no further. multiple redownloads and headset resets were of 0 aid. 

1. open up the app in the headset
2. wait for the dowloading to stop, then type in the code
3. press microsoft login button as intructed
4. nothing happens

everything from java minecraft to my microsoft account has been checked to make sure it wasn't the problem, confirmed to not be.

 - Device: Quest_2
 - QuestCraft Version 3.0.0 - 3.1.1

i asked a dev for help on the discord and even he couldn't help.

**Comment by thejudge156** [comment]
Does it even freeze?

**Comment by danilyer228** [comment]
same thing. @thejudge156 yep. It's freeze for e few seconds then nothing happened.

**Comment by TecEash1** [comment]
Hi 👋 

I am from the Questcraft Support team on their [discord server](https://discord.gg/questcraft). 

- Do you own Minecraft java editon by any chance?
- Also if you do own it, does it have a username linked to it?

**Comment by n3u7r1n0s** [comment]
Hello! We are experiencing identical behaviour to carkwithasee.

I just wanted to add that we purchased "Minecraft: Java & Bedrock Edition for PC" from the Windows store.  There seems to be multiple versions of Minecraft java edition - not sure if this causes a problem for QCXR auth?

**Comment by TecEash1** [comment]
> I just wanted to add that we purchased "Minecraft: Java & Bedrock Edition for PC" from the Windows store. There seems to be multiple versions of Minecraft java edition - not sure if this causes a problem for QCXR auth?

Hey, could you please join the discord server and file a login issue/ticket?
- feel free to ping me and I can help you there

**Comment by Flopgop** [comment]
Does this affect build 4.0.0?

**Comment by n3u7r1n0s** [comment]
My issue was that the Microsoft account was under 18 - I verified this by attempting to access security settings and received the "Why can’t I change my privacy settings?" page - once I updated the account to be over 18, everything went smoothly.  

I was advised it was also possible to change the security settings with a parent account linked to the child account.

**Comment by eypacha** [comment]
I'm having the same issue (I think). When I touch the Log In button after entering the code I get the following message:

`Login failure! Ensure you have acccepted the permission theb try again. Click the Microsoft button again once done`

I assume that with "Microsoft button" you mean the Login one.

The permissions are granted and this message appears enter the valid code, an incorrect one or even enter nothing. I bought the Java version, I'm over 18 and I don't know what else to add

**Comment by fnfiseasy** [comment]
I'm having the same issue where it says "Login failure! Ensure you have acccepted the permission then try again. Click the Microsoft button again once done". If anyone knows the fix for this please tell us !!!!1!!
And i am over 18.

**Comment by n3u7r1n0s** [comment]
Try joining the discord server and logging a ticket; they were super quick and helpful over there <3
