### ISSUE TITLE
[BUG] Mods cause menus to be streched, as if eye stencil is off in game

### ISSUE THREAD

**Issue by ShadowFlame45** [QuestCraftPlusPlus/QuestCraft#477]
**Describe the bug**
When using Essentials, the main menus will be weird and streched.

**To Reproduce**
1. Download and install Essentials
2. Launch game and see that the main menu is streched

**Expected behavior**
The menus should not be streched.

**Screenshots**
Unable to, screenshots appear unaffected by bug

**Headset Details (please complete the following information):**
 - Quest Build: v49.0.0(?)
 - Device: Quest 2
 - QuestCraft Version 3.1.1

**Additional context**
None.

**Comment by Eyndjl** [comment]
Same issue.

**Comment by TecEash1** [comment]
I believe the essentials mod is currently unsupported by QuestCraft at the moment, more mod support will be coming in the next V4.0 update
