### ISSUE TITLE
[BUG] Black Screen when joining server

### ISSUE THREAD

**Issue by dedkarnilo** [QuestCraftPlusPlus/QuestCraft#479]
**Describe the bug**

**To Reproduce**
Когда создаешь новый мир или пытаешься присоединиться к сетевому миру то играет музыка и черный экран, перезагрузка VR шлема не помогает, переустановка questcraft не помогает, что можно сделать? Questcraft ставил из SideQuest

When you create a new world or try to join the network world, music plays and a black screen, rebooting the VR helmet does not help, reinstalling questcraft does not help, what can I do? Questcraft set from SideQuest

**Headset Details (please complete the following information):**
 - Quest Build: [v58.0]
 - Device: [Quest_2]
 - QuestCraft Version [e.g. v3.1.1]

**Additional context**

**Comment by JaffaJace** [comment]
1) there was no reason for you to put your issue in Russian, we all speak English here.
2) This is a known issue, it is due to the Fabulous Graphics settings making the game not load the world for whatever reason, please set it to Fast or Fancy.

**Comment by dedkarnilo** [comment]
Спаси

> Брат. Увы, тут не говорят по-русски. Короче, это баг. Возникает при использовании "Потрясающей" настройки графики. Поменяй в конфиге графику на fast и радуйся.

Спасибо, помогло!!!
