### ISSUE TITLE
[BUG] Cannot log in

### ISSUE THREAD

**Issue by BeckPhillips** [QuestCraftPlusPlus/QuestCraft#480]
**Describe the bug**
Login never loads

**To Reproduce**
1. Launch the app
2. Click on "Microsoft Login"
3. Sync accounts through microsoft website, using supplied code.
4. Wait for Installation to finish
5. Screen freezes for a few seconds, looking around produces a black void to your sides, and an upside-down duplicate of the frozen image behind you. 
6. Nothing happens.

**Expected behavior**
A Login window should appear

**Headset Details (please complete the following information):**
 - Quest Build: I actually have no idea how to find this, unless its the headset version?
 - Device: Quest_2
 - QuestCraft Version 3.1.1

**Additional context**
I've loaded it onto my headset through SideQuest, and other games work, just not this one.

**Comment by TecEash1** [comment]
Hi 👋 

I am from the Questcraft Support team on their [discord server](https://discord.gg/questcraft). 

- Do you own Minecraft java editon by any chance?
- Also if you do own it, does it have a username linked to it?

**Comment by BeckPhillips** [comment]
Yes. I even tried launching several versions while I was loading the game on QuestCraft. 
I've got a username as well, and I've had the account for over a year and have played with it regularly.

**Comment by TecEash1** [comment]
> Yes. I even tried launching several versions while I was loading the game on QuestCraft. 
> 
> I've got a username as well, and I've had the account for over a year and have played with it regularly.

Ok Please can you screenshot what you see when you visit this [link](https://account.xbox.com/Settings), or please say what you see 

- make sure that you login with the exact same Microsoft account you own Java edition on

**Comment by BeckPhillips** [comment]
The link asks me to enter my password, then it shows my XBOX account info, with "Privacy & online safety" in big text over the top.

My issue is that I'm not able to log in on QuestCraft. the entire screen freezes for a moment when I click on it, then nothing happens when it unfreezes.

**Comment by BeckPhillips** [comment]
okay, !DED from the discord helped me, but in short: I am an absolute fool. I had mistakenly not logged in with the correct account.
Sorry for potentially wasting you guys' time.

**Comment by TecEash1** [comment]
np, Glad !DED could help! 
Have a nice day!

**Comment by TecEash1** [comment]
Also sorry not replying quickly, GitHub doesn’t ping me 😅
