### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by zymsik** [QuestCraftPlusPlus/QuestCraft#482]
Whenever I try to click the Microsoft buttion again, as instructed, it doesn’t finish the proccess
**To Reproduce**
1. Click on Microsoft button
2. Use code and login to Microsoft account
3. Click on Microsoft button again
4. Cannot progress

I expected myself to be logged in

**Headset Details (please complete the following information):**
 - Quest Build: v49.0.0.207.357.445159226
 - Device:  Quest 2
 - QuestCraft Version 3.1.1
I have an Java account

**Comment by zymsik** [comment]
I GOT IT WORKING!!!!!!!

**Comment by RubiKade83** [comment]
How did you get it to work? (I'm having a similar issue)
