### ISSUE TITLE
[BUG] Download freezes on 8.388% and doesn't go up and keeps me from being able to play the game

### ISSUE THREAD

**Issue by wingbroman** [QuestCraftPlusPlus/QuestCraft#483]
**Describe the bug**
Download 
Keeps freezing up and won't move up any further 

1. Install questcraft apk
2. Open questcraft and log in 
3. Wait for it to install assets
4. Asset code "Downloading 47800737d078751698df291054adc596ba8195a freezes at 8.388 MB

**Expected behavior**
I expected it to download and let me play

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: Quest_2]
 - QuestCraft Version 3.1.1

**Comment by DevLimeAtSkyo** [comment]
These support questions are more suited for the Discord server, they normally get done a lot quicker than GitHub issues
