### ISSUE TITLE
Questcraft instances download sometimes just gives up

### ISSUE THREAD

**Issue by EyaeM** [QuestCraftPlusPlus/QuestCraft#486]
Yea it just randomly stops and when I click the Microsoft login again to get into my acc it downloads 1 file then stops again then I click Microsoft login again 1 file download give up an endless loop which I cannot hope to escape with my shitty Egyptian internet. (P.S I will beat the shit out of my ISP soon.)

**Comment by treatmeniceplz** [comment]
Honestly I would rather the instances be a thing u put in the files and that would help this issue
