### ISSUE TITLE
[FEATURE] Add a progress Bar Pleaseeee

### ISSUE THREAD

**Issue by EyaeM** [QuestCraftPlusPlus/QuestCraft#487]
**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is.** 
I'm always frustrated when I do not know if my questcraft instances are done or just gave up

**Describe the solution you'd like**
A green progress bar which shows you the percentage of the instances downloaded so you know if it's done

**Describe alternatives you've considered**
Telling the user when it's done downloading instances

**Additional Context**
(I hate my shitty ISP)

**QuestCraft Version**
3.1.0

**Comment by dugo3number2** [comment]
Crap ISP + no progress bar = intense frustration
I think this should be added

**Comment by TheDog404** [comment]
This would be very useful, as some people may not notice the text on the menu. As well as reducing the frustration and giving up count.

**Comment by EyaeM** [comment]
> This would be very useful, as some people may not notice the text on the menu. As well as reducing the frustration and giving up count.

Naw my problem is that sometimes it just gives up and i dont know if it gave up or if its done

**Comment by treatmeniceplz** [comment]
Honestly this would help me a lot

**Comment by EyaeM** [comment]
wait is this a feature now send clip
