### ISSUE TITLE
piracy mode lol

### ISSUE THREAD

**Issue by Windows3280** [QuestCraftPlusPlus/QuestCraft#489]
if you install qc 1.1.1, with offline account, and update it to 1.2.0 the offline account will remain lololololol

**Comment by swaggio7** [comment]
How did you manage to use 1.1.1?

**Comment by JaffaJace** [comment]
Dude, wake up, qc is on 3.1.1 already

**Comment by RealityXP** [comment]
bro is stuck in last year lol

**Comment by swaggio7** [comment]
Lmao, 3.1.2 just released
