### ISSUE TITLE
[water placement problem]

### ISSUE THREAD

**Issue by oliverwesley1** [QuestCraftPlusPlus/QuestCraft#49]
**Describe the bug**
when placing water buckets it doesent place where the crosshair is, it places where the player is looking

**To Reproduce**
1. open a world (for me it happened on server, havent tried single player, should be the same though)
2. place water bucket while crosshair and direction of look is different

**Expected behavior**
water places where crosshair is rather than where player is looking

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device:  Quest_2
 - QuestCraft Version [e.g. v1.0.0]

**Additional context**

**Comment by JD-The-65th** [comment]
Can confirm this actually happens.

**Comment by oliverwesley1** [comment]
Note, I'm not sure if this happens with other fluids e.g. lava and axolotl buckets, I have only tested with water

**Comment by JD-The-65th** [comment]
It happens with axolotl buckets too.

**Comment by oliverwesley1** [comment]
What about lava?

**Comment by JD-The-65th** [comment]
Never tested, should be the same.

**Comment by oliverwesley1** [comment]
I would have thought that water wouldn't fire from the players view though
