### ISSUE TITLE
Oculus Quest 1 mod menu

### ISSUE THREAD

**Issue by Ryguy6001** [QuestCraftPlusPlus/QuestCraft#491]
Will the quest 1 get the mod menu and then get deprecated? or will it stay get deprecated and not get a mod menu.

**Comment by swaggio7** [comment]
Latter. 4.0 will only support the Quest 2. Sorry, mate.

**Comment by TecEash1** [comment]
Do you mean modmenu or mod manager?

**Comment by TecEash1** [comment]
> Latter. 4.0 will only support the Quest 2. Sorry, mate.

Not sure if 4.0 for Quest 1 will have mod manager support but it 4.0 will have partial support on Quest 1. It’s not recommended to use it tho - but u can :)

**Comment by swaggio7** [comment]
> > Latter. 4.0 will only support the Quest 2. Sorry, mate.
> 
> 
> 
> Not sure if 4.0 for Quest 1 will have mod manager support but it 4.0 will have partial support on Quest 1. It’s not recommended to use it tho - but u can :)

Won't 4.0 include the PTC fixes, thus making it unavailable for Quest 1?

**Comment by TecEash1** [comment]
> > > Latter. 4.0 will only support the Quest 2. Sorry, mate.
> > 
> > 
> > Not sure if 4.0 for Quest 1 will have mod manager support but it 4.0 will have partial support on Quest 1. It’s not recommended to use it tho - but u can :)
> 
> Won't 4.0 include the PTC fixes, thus making it unavailable for Quest 1?

Idk but that’s what was announced [here](https://discord.com/channels/820767484042018829/928885002752647229/1093951060835569724)

**Comment by DevLimeAtSkyo** [comment]
Can load v51 hotfix on v50 btw

4.0 will break that however
