### ISSUE TITLE
[BUG] crashing with no mods

### ISSUE THREAD

**Issue by Whatiswrong111** [QuestCraftPlusPlus/QuestCraft#492]
crashing on newest patch and i have no mods other then the ones that help

**Comment by Whatiswrong111** [comment]
im about ready to break something

**Comment by CrowPixel** [comment]
> im about ready to break something 
> 
> 

Hello please be patient, something might be happening considering the discord picked up issues like this, strange pattern

**Comment by TecEash1** [comment]
> crashing on newest patch and i have no mods other then the ones that help

The issue has been resolved, please reinstall QuestCraft.
If your issue persists it’s recommended to join the discord server for quicker support.
