### ISSUE TITLE
[BUG]  README incorrect

### ISSUE THREAD

**Issue by JaffaJace** [QuestCraftPlusPlus/QuestCraft#493]
The readme is incorrect?

![image](https://user-images.githubusercontent.com/94018839/233207372-067c9146-9f5b-44a8-857b-5dacb5bb4b27.png)

I dont know what you would want to change it to, but i felt like pointing this out so that you know of it.

**Comment by swaggio7** [comment]
Funny story: the PR for this was merged too early. It isn't supposed to be like this now, only when 4.0 gets publicly released. (I made this, so any info is great.)

**Comment by swaggio7** [comment]
Also, what are the corrections I need to make? Anything wrong?

**Comment by DevLimeAtSkyo** [comment]
I think it's immersive portals that Jaffa doesn't like there

**Comment by JaffaJace** [comment]
Its both actually, neither of those mods will work regardless. I had consulted Judge about mod compatibility when adding the renderer command to Crafty, you can use Create as your mod example.

**Comment by JaffaJace** [comment]
Sorry for the late response btw, i made that issue at 11pm last night

**Comment by thejudge156** [comment]
> > Funny story: the PR for this was merged too early. It isn't supposed to be like this now, only when 4.0 gets publicly released. (I made the pr, so any info is great.)
> 
> Just a note that’s a good idea is making a new branch, and then pr it but mark is as a draft. So it doesn’t get pulled automatically by accident :)

Cad moment

**Comment by treatmeniceplz** [comment]
4.0 is out please close this seems to be resolved

**Comment by DevLimeAtSkyo** [comment]
Not resolved, readme is still a bit broken

**Comment by swaggio7** [comment]
The new PR is done; there is no need for this issue to be still up.

**Comment by JaffaJace** [comment]
Gotcha
