### ISSUE TITLE
Crashed when clicked play

### ISSUE THREAD

**Issue by Dawidoax1** [QuestCraftPlusPlus/QuestCraft#494]
[latestlog.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/11288875/latestlog.txt)
idk what happens i just click on microsoft login then play and then its crashed

**Comment by DED0026** [comment]
please come to [the discord](https://discord.gg/questcraft) for these types of issues, it looks like the download was either corrupted or didn't fully install.

**Comment by Dawidoax1** [comment]
> please come to [the discord](https://discord.gg/questcraft) for these types of issues, it looks like the download was either corrupted or didn't fully install.

done
