### ISSUE TITLE
[BUG]stable crash when rendering Skeleton horse

### ISSUE THREAD

**Issue by vocaloidkiss** [QuestCraftPlusPlus/QuestCraft#495]
There is a stable crash when rendering Skeleton horse

Whenever the player client starts rendering Skeleton Horses, it will crash

![2023-04-22 165543](https://user-images.githubusercontent.com/115659586/233774328-ed3665ce-bd3b-4450-acd4-3146c5b0a863.png)

**Comment by vocaloidkiss** [comment]
minecraft version：1.19.4
mod version ：1.5.7-1.19.3

**Comment by RealityXP** [comment]
Wrong repo, this is questcraft, which runs on the headset and is a **standalone experience**. Now if you are using fabric vivecraft, report it within [https://github.com/ferriarnus/VivecraftMod](url)

**Comment by thejudge156** [comment]
^
