### ISSUE TITLE
[BUG] It crashes when I press play

### ISSUE THREAD

**Issue by Taz8041** [QuestCraftPlusPlus/QuestCraft#496]
### 🤔 Current Behavior

When I press play it immediately crashes and goes to the home screen, then when I try to boot it up again it is stuck on a infinite loading screen.
Any suggestions?

### 🥽 Headset Details

Quest 2

**Comment by Taz8041** [comment]
then when i wait on the home screen for a little bit it goes to a black screen with three dots in the middle and does not do anything else

**Comment by Sainnamonbuns** [comment]
do you actually own minecraft on your quest

**Comment by treatmeniceplz** [comment]
> then when i wait on the home screen for a little bit it goes to a black screen with three dots in the middle and does not do anything else

Have you tried just waiting @Taz8041

**Comment by KingHippoSE** [comment]
I got it to work on my Quest 2 by clicking Dev Options in the first screen and changing memory from 2048 to 1024. Only tried with 1.18.x version.

**Comment by RiddleMajor** [comment]
This issue still exists over a year later.

**Comment by treatmeniceplz** [comment]
I forgot about it this issue lol I'll try it soon

**Comment by treatmeniceplz** [comment]
> This issue still exists over a year later. 

Look at the above comment

**Comment by treatmeniceplz** [comment]
@RiddleMajor

**Comment by TheRealFame** [comment]
This isn't completed by any means and it still happens.

**Comment by treatmeniceplz** [comment]
I'll investigate this one next week

**Comment by treatmeniceplz** [comment]
> This isn't completed by any means and it still happens.

I will see
