### ISSUE TITLE
I can't download the game

### ISSUE THREAD

**Issue by AmberStardust1** [QuestCraftPlusPlus/QuestCraft#498]
### 🤔 Current Behavior

My install doesn't fully finish, I tried using Questcraft on pc, then on the Quest, then using the GitHub download. After every try through pc and git hub, it says the game is not updated and on the quest, it asks you to update but then never downloads the game, I hope you can help me with this problem, I only recently got minecraft and I was really excited to try it on my quest.

### 🥽 Headset Details

Quest 2
SideQuest Version : most recently updated

**Comment by NasirOMG** [comment]
I have the same problem

**Comment by DevLimeAtSkyo** [comment]
Not quite sure what is going on, please take these support questions to the [Discord server](https://discord.gg/questcraft) as they are answered faster there
