### ISSUE TITLE
[BUG] Unsupported SDK Version

### ISSUE THREAD

**Issue by bruh34763847** [QuestCraftPlusPlus/QuestCraft#499]
### 🤔 Current Behavior

cant install
A task failed. Check the tasks screen for more info. QCXR-4.0.apk: /data/local/tmp/_stream.apk could not be installed [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl157534594.tmp/base.apk (at Binary XML file line #8): Requires newer sdk version #32 (current version is #29)]

### ✅ Expected Behavior

should install
no errors

### 🥽 Headset Details

quest 2
questcraft 4.0

### ℹ️ Anything else?

idk what to put here

**Comment by Flopgop** [comment]
Update your headset.

**Comment by bruh34763847** [comment]
> Update your headset.

how
