### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tridon1088** [QuestCraftPlusPlus/QuestCraft#50]
**Describe the bug**
Crashes upon trying to launch the game.

**To Reproduce**
1. Open Launcher
2. Click Play
3. minute of loading followed by red screen, crash

**Expected behavior**
Game to open

**Headset Details (please complete the following information):**
 - Quest Build: v37.0.0.147.110.346379395
 - Device: Quest 2
 - QuestCraft Version 1.1.0

**Additional context**
Followed instructional video the whole time I was installing.

**Comment by gusbunce** [comment]
@ManiacGamer156 @CADIndie May be able to help you out with this.

**Comment by Tridon1088** [comment]
Thank you @ManiacGamer156. I look forward to playing questcraft as soon as I'm able :)
