### ISSUE TITLE
[BUG] Cobblemon Crashes

### ISSUE THREAD

**Issue by SyeGD** [QuestCraftPlusPlus/QuestCraft#500]
### 🤔 Current Behavior

My game crashes with the Cobblemon Fabric mod installed.
I got it with the Modmanager.

### ✅ Expected Behavior

I expect it to open Minecraft with Cobblemon installed. It doesn't. I will update this if trying to install it without the modmanager would work.

### 🥽 Headset Details

Quest 2
Questcraft v4.0

### ℹ️ Anything else?

a mcdouble.

**Comment by Flopgop** [comment]
Please provide logs

**Comment by SyeGD** [comment]
I don't think it has logs.

**Comment by SyeGD** [comment]
It just crashes with no warning whatsoever.

**Comment by SyeGD** [comment]
Tried the MCVR API. Didn't work.

**Comment by AbyssVoid205** [comment]
![com qcxr qcxr-20230430-130345](https://user-images.githubusercontent.com/132178183/235374632-fe00fd4d-a557-4444-afd8-921c78f111d7.jpg)

**Comment by AbyssVoid205** [comment]
but when loading a world it gets half way and crashes saying not enough memory

**Comment by thejudge156** [comment]
Duplicate of #520
