### ISSUE TITLE
Cant download 

### ISSUE THREAD

**Issue by NasirOMG** [QuestCraftPlusPlus/QuestCraft#502]
### 🤔 Current Behavior

its prompting me to update quest craft but then says that i already installed it and i deleted it but it still didn't work 

### ✅ Expected Behavior

.  

### 🥽 Headset Details

Quest 2

**Comment by DevLimeAtSkyo** [comment]
Please use a custom adb command

`adb uninstall com.qcxr.qcxr`

**Comment by NasirOMG** [comment]
How do I do that exactly

**Comment by TrenchSinaj** [comment]
Watch a tutorial on how to use adb commands in Sidequest. Then just paste the command above. Worked for me <3
