### ISSUE TITLE
[BUG] <Fix for "INSTALL_FAILED_UPDATE_INCOMPATIBLE">

### ISSUE THREAD

**Issue by LetoDK** [QuestCraftPlusPlus/QuestCraft#503]
### 🤔 Current Behavior

I couldn't install. I got:

> _A task failed. Check the tasks screen for more info. QCXR-4.0.apk: : /data/local/tmp/_stream.apk could not be installed [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.qcxr.qcxr signatures do not match previously installed version; ignoring!]_

I couldn't find qcxr, and thus couldn't uninstall it. So I ran this ADB command:

`adb uninstall com.qcxr.qcxr`

And then I could install it.

### ✅ Expected Behavior

To be able to install it.

### 🥽 Headset Details

Quest build v53
Quest 2
1.19.4/Fabric

**Comment by DevLimeAtSkyo** [comment]
This is normal, this is not an issue

**Comment by DevLimeAtSkyo** [comment]
The disappearing isn't however, the devs are looking into that

**Comment by Mythix444** [comment]
im having the same issue and i also cannot find it, it is supposed to be in tmp right? also, i cant seem to uninstall it

**Comment by LetoDK** [comment]
Run this adb command:

`adb uninstall com.qcxr.qcxr`

**Comment by UniXeal** [comment]
i have the same issue i just dont know how to use adb commands
where do i use that command?

**Comment by UniXeal** [comment]
never mind found it
