### ISSUE TITLE
[BUG] this is not neccacarly a bug but i still need an answer

### ISSUE THREAD

**Issue by maxplayz2746** [QuestCraftPlusPlus/QuestCraft#504]
### 🤔 Current Behavior

I am trying to run a minecraft server with support of simple voice but i have no clue what version of simple voice chat is running on the quest. my server is also running via version at 1.16.5

### ✅ Expected Behavior

it working

### 🥽 Headset Details

i was going to try to find it myself but have no idea where the .minecraft folder is

**Comment by TecEash1** [comment]
you need to enable 'show hidden files' to view the ``.minecraft`` folder, the folder can be found at the path below:

````android/data/com.qcxr.qcxr/files/.minecraft````
If you need further help I would suggest letting us know in the [discord server](https://discord.gg/questcraft) for a quicker response
