### ISSUE TITLE
The game will crash while downloading and after crashing the quest will say it does not have enough ram to run QuestCraft.

### ISSUE THREAD

**Issue by brodysithtwohouses** [QuestCraftPlusPlus/QuestCraft#505]
### 🤔 Current Behavior

The game will crash while downloading game files and a box saying I don’t have enough ram appears.

### ✅ Expected Behavior

I expected to be able to download and play the game

### 🥽 Headset Details

Quest Build v51
Quest 2
Version 4.0.0

**Comment by Eyndjl** [comment]
I noticed this problem when I allocated 3GB of RAM instead of 2GB to the game. Try allocating less RAM.

**Comment by AbyssVoid205** [comment]
Try adding some ram to the game in dev options

**Comment by brodysithtwohouses** [comment]
> Try adding some ram to the game in dev options

I have upped the ram in-game and think it may be a system issue. It has since been happening in other games as well.

**Comment by thejudge156** [comment]
Duplicate of #520
