### ISSUE TITLE
[BUG] I cannot change the rendering mode

### ISSUE THREAD

**Issue by Eyndjl** [QuestCraftPlusPlus/QuestCraft#506]
### 🤔 Current Behavior

The README.md states that QuestCraft has two rendering modes: Zink and Vulkan. 
The default rendering mode is Zink, and I want to change to Vulkan and I can't figure out how to change it. 

### ✅ Expected Behavior

Use Vulkan rendering. 

### 🥽 Headset Details

Quest build: v53
Device: Quest 2
QuestCraft version: 4.0.0

**Comment by DED0026** [comment]
will have, vulkan isnt made yet.
sorry for the confusion, take issues to the discord server please.

**Comment by Eyndjl** [comment]
> will have, vulkan isnt made yet. sorry for the confusion, take issues to the discord server please.

Understood, accepted, assimilated, processed. Thank you for your response.
