### ISSUE TITLE
[FEATURE] <Iris Shader Questcraft 4.0>

### ISSUE THREAD

**Issue by poopdog2** [QuestCraftPlusPlus/QuestCraft#507]
### 🛠️ Describe the solution you'd like

I've downloaded Iris shaders to 1.19.4 and I wanted to get a low-end shader pack to put on it. I would love that if you could show people how to do it.

### 🤔 Describe alternatives you've considered

I thought there would be a folder of iris shaders to put in there but idk

**Comment by JaffaJace** [comment]
There is a folder for it, its called shaderpacks

**Comment by poopdog2** [comment]
thank you

**Comment by Eyndjl** [comment]
Jesus Christ......
