### ISSUE TITLE
Not downloading!!!

### ISSUE THREAD

**Issue by Parker0808** [QuestCraftPlusPlus/QuestCraft#509]
<img width="1469" alt="Screenshot 2023-05-02 at 4 39 52 PM" src="https://user-images.githubusercontent.com/122655298/235800862-033714b6-c5c2-40b5-a646-69765ffb6ff8.png">
When I try to download it it just says this error and I deleted my old version on my quest 2

**Comment by DED0026** [comment]
If you're having an issue with uninstalling and need to perform a force uninstallation, Please make sure you are using [**Sidequest Advanced**](https://sidequestvr.com/setup-howto) as basic SideQuest wont work. Run the command: ``adb uninstall com.qcxr.qcxr``, as shown in the image below.
![image](https://user-images.githubusercontent.com/98061642/235802083-c954e62a-3611-486f-8d90-ad6e93eec5f7.png)
for future issues please contact us on the [Discord server](https://discord.gg/questcraft)

**Comment by Parker0808** [comment]
It worked thank you!!!

**Comment by DED0026** [comment]
glad i could help you.
