### ISSUE TITLE
Black Screen BUG]

### ISSUE THREAD

**Issue by Incergence** [QuestCraftPlusPlus/QuestCraft#51]
**Describe the bug**
When pressing play after following the tutorial multiple times, the screen stays black and never loads the game

**To Reproduce**
Press play to play the game
Eternal black Screen

**Expected behavior**
The game to load

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Quest 2
 - QuestCraft Version Latest i believe

**Additional context**

**Comment by BLANCO711** [comment]
Any fixes??

**Comment by CubeGamer647** [comment]
The game actually loads, as there is music, but the screen remains black, which leads me to believe it is not rendering properly.

**Comment by FFoxyyy** [comment]
literally i waited a while then the white dots just disappeared, just black screen at that time

**Comment by The-Blue-Goose** [comment]
Try restarting the headset. Rather than clicking login using Microsoft or Mojang, use the "Existing Account" Button. Clicking play will still cause the game to load on a black screen for about a minute, but it should eventually load. 

That fixed this issue for me, so I hope it helps you.
