### ISSUE TITLE
[BUG] QC keeps downloading outdated preinstalled mods whenever I delete them

### ISSUE THREAD

**Issue by swaggio7** [QuestCraftPlusPlus/QuestCraft#512]
### 🤔 Current Behavior

So I have updated Sodium and removed Iris and Portals, but it keeps on downloading the original mods whenever I play, thus crashing MC on load!

### ✅ Expected Behavior

Just to load MC with updated Sodium

### 🥽 Headset Details

V53 PTC
Quest 2
4.0.0

**Comment by DevLimeAtSkyo** [comment]
and "Portals"?

**Comment by DevLimeAtSkyo** [comment]
better not be immersive portals...

**Comment by swaggio7** [comment]
> better not be immersive portals...

It was in ModManager, I thought it was going to work!

**Comment by DevLimeAtSkyo** [comment]
Lmao, it's good, also swag, maybe go to discord next time...
Much quicker lmao

**Comment by swaggio7** [comment]
Solution found: Removing the mods from custom-mods.json fixes the problem.
