### ISSUE TITLE
[FEATURE] AutoModpack to the default modlist!

### ISSUE THREAD

**Issue by Merith-TK** [QuestCraftPlusPlus/QuestCraft#515]
### 🛠️ Describe the solution you'd like

there is a mod called "automodpack", and it works really well in QuestCraft outside of an few issues which I am patching as I type this, I think it would be an good idea to include it so that Quest Users can have alot less of a headache when joining a modded server!

### ℹ️ Anything else?

https://github.com/Skidamek/AutoModpack

**Comment by DED0026** [comment]
thats interesting, is this mod going to be released on modrinth or curseforge?

**Comment by Merith-TK** [comment]
The mod is already released on modrinth, 
https://modrinth.com/mod/automodpack/

**Comment by Merith-TK** [comment]
Due to how Automodpack works, it would be theoretically possible to integrate it into the launcher itself rather than as a mod, since it (if I recall correctly) has modpack management, and can automatically change what mods are currently downloaded depending whats on the server,

integrating into the launcher rather than as a mod also has the added benifit of fixing litterally all of the issues I am having to manually figure out how to patch

since it likes to "auto restart" (aka, kill) the game to reload the mods

**Comment by DED0026** [comment]
oh, my bad just found it there.
if you want to include it with qc you can open a pull request to the [default mods file of qc on pojlib](https://github.com/QuestCraftPlusPlus/Pojlib/blob/QuestCraft/mods.json). for implementation into the launcher you might wanna talk to cadindie or judge, both can be found on the [questcraft server](https://discord.gg/questcraft)

**Comment by RealityXP** [comment]
I remember this was discussed by staff a few months back, wonder if it could be revisited

**Comment by Merith-TK** [comment]
Will make a PR after I fix up a good chunk of issues with the mod, and maybe have an build where auto-self-update is disabled by *default* (as it will make the client close when that happens)

**Comment by Merith-TK** [comment]
https://mclo.gs/rnUZgif
looks like my automodpack patches are working

**Comment by thejudge156** [comment]
Cool, are you still planning to do that AutoModpack PR?

**Comment by Merith-TK** [comment]
already made and merged!
