### ISSUE TITLE
[FEATURE] External Keyboard Support

### ISSUE THREAD

**Issue by lamaprogramer** [QuestCraftPlusPlus/QuestCraft#516]
### 📝 Is your feature request related to a problem? Please describe

There are so many key binds that can't fit on the Oculus controller. And it may also be nice to bind movement keys to a physical keyboard as well.

### 🛠️ Describe the solution you'd like

I would like physical keyboard support so that you can more easily access menus and/or player abilities added by other mods. This could make it more accessible to people who can't hold Oculus controllers for extended periods. Oculus has Bluetooth support, so I am hoping you could utilize that functionality.

### 🤔 Describe alternatives you've considered

An alternative I have considered would be an organizable menu to perform the actions of those key binds, for example, you could have a part of the menu specifically for voice chat, so if you click on the mute button, it would perform the action of the "mute" key bind. _(I am aware the voice chat already has a menu for this, however, this is just an example)_

**Comment by swaggio7** [comment]
But wouldn't that mean they have to program a physical keyboard that's always displayed in-game? Kinda sounds weird cause QC aims to be a full immersive experience. The Radial Menu exists as well.

**Comment by lamaprogramer** [comment]
Why would it need to be displayed in-game? I want input fro a physical keyboard, not a virtual one

**Comment by swaggio7** [comment]
> Why would it need to be displayed in-game? I want input from a physical keyboard, not a virtual one.

... 
Unless you memorized the QWERTY keyboard, you wouldn't know keys your fingers are on.

**Comment by lamaprogramer** [comment]
Depends on how you layout your key binds, If I'm playing Minecraft pvp, I rarely look at my keyboard because I know where all the keys are

**Comment by swaggio7** [comment]
> Depends on how you layout your key binds, If I'm playing Minecraft pvp, I rarely look at my keyboard because I know where all the keys are

Alright then. Suit yourself.

**Comment by ID86s** [comment]
v54 brings controllers support :D
[proof](https://communityforums.atmeta.com/t5/Announcements/New-Feature-for-Gamepads-Paired-with-Quest-in-v54/td-p/1050163)
