### ISSUE TITLE
[BUGn't?] cannot open quick commands pallet since mod menu is included by default

### ISSUE THREAD

**Issue by walksanatora** [QuestCraftPlusPlus/QuestCraft#518]
### 🤔 Current Behavior

MC 1.19.4
QC 4.0.0
cannot access quick commands from the pause menue with mod menu as they overlap eachother and modmenue is placed on top

### ✅ Expected Behavior

the ability to use my quick commands that I can setup in VR settings

### 🥽 Headset Details

quest 2 running v53
QuestCraft 4.0.0

**Comment by thejudge156** [comment]
Mod Menu will not be auto-included in the next update

**Comment by CrazyBobcatStudios** [comment]
U can fix this by going into the mod menu, find the mod menu mod, and then click the settings icon next to it. There's a button that says in game button location or something like that and you can click it and cycle it to button next to bugs

(The bugs button is where the commands is now)
