### ISSUE TITLE
[BUG] Runs perfectly except black fog.

### ISSUE THREAD

**Issue by ArsenicBismuth** [QuestCraftPlusPlus/QuestCraft#52]
You can see from the screenshots. I don't know if they're known bug or not, but I don't see any tracked issue yet about this.

**Screenshots**
![image](https://user-images.githubusercontent.com/19264532/155222904-20634d5b-9209-4992-bb7e-1da92a4b7198.png)
![image](https://user-images.githubusercontent.com/19264532/155223018-56d781d9-aa52-492a-bd95-3e65b56d97c8.png)

**Headset Details (please complete the following information):**
 - Quest Build: Latest
 - Device: Quest 2
 - QuestCraft Version: v1.1.0

**Comment by JD-The-65th** [comment]
set graphics mode to fabulous if you haven't already
