### ISSUE TITLE
[BUG] Quest Pro Issues / Memory Leak in System

### ISSUE THREAD

**Issue by ID86s** [QuestCraftPlusPlus/QuestCraft#520]
### 🤔 Current Behavior

FPS is below 30 even if you load precreated world and stand still around 5 minutes
<strike>Weird memory allocation (around 2gb for 12gb ram)</strike>
Lower values for render distance and render resolution not increases fps (higher values actually decrease fps)

### ✅ Expected Behavior

stable FPS higher that 30
<strike>RAM allocation higher that 2gb</strike>
Render distance and render resolution correctly affects fps
Multitasking affects FPS

### 🥽 Headset Details

Quest Pro v55/v54/v53/v51 (same results, but v54 had stable 24 fps even up to 7 chunk render distance)
QuestCraft 4.0.0
Minecraft 1.19.4-fabric/1.18.2-fabric (downloaded and installed by questcraft itself)
No mods (except that ones that was downloaded and installed by questcraft itself)

### ℹ️ Anything else?

<strike>There is popular way to install questcraft with zink render, but no instructions how to install with vulkan render, so i don't know how to test on vulkan render</strike>

**Comment by Flopgop** [comment]
The Vulkan renderer mentioned in the README is not yet implemented, note that the quest pro has an identical chip to the quest 2 and minecraft is highly cpu bound.

**Comment by ID86s** [comment]
> note that minecraft is highly cpu bound, and the quest isn't really correctly prepared to run questcraft
i just saw on YouTube that people is optimizing questcraft from below 30 to below 60, but seems like sodium, lithium and some optimization mods are already installed. 
Weirdly enough, i had no working programs in background, so i think quest 2 run questcraft better that quest pro right now

**Comment by HowToCodeDE** [comment]
> Weird memory allocation (around 2gb for 12gb ram)
In the launcher is an option, where you can allocate more RAM. Before pressing sign in, go to the dev settings.

**Comment by ID86s** [comment]
> Can I ask how much you have assigned? I would like to make a PR so it can be automatically assigned more when using Quest Pro

5gb works without any problems, i wanna test more values, i guess 6-7gb will works fine too (testing on v53 right now)

**Comment by HowToCodeDE** [comment]
Thanks

**Comment by TecEash1** [comment]
<img width="304" alt="image" src="https://github.com/QuestCraftPlusPlus/QuestCraft/assets/92249532/e388772f-fab9-40d3-9359-8b29804ce9fa">
Basically, currently there is a horrid memory leak on the Quest system itself, QuestCraft can't control it. Some headsets have it worse then others. Other app devs are starting to complain, but also meta devs told us "We only added that out-of-memory dialog because of how bad it got on our end."

![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/92249532/c6ef8090-4d45-48bf-a8bf-8d5d9c198031)

**Comment by ID86s** [comment]
> Quest system

Thanks for reply.
Well, i guess vr will be useable in ~2030, now it's like beta testing, because they just updating <strike>OS</strike> software to add QoL features, but not fixing anything important like: weird artifacts in quest pro (bug since release, appears only if you don't reboot your headset after charging), weird wi-fi support in quest pro that can crash or bugged the software (if you have 4x4 mu-mimo, that can works on >=80mhz channel wide) and that memory leak that u've mentioned.
Well there's meta competitor releases, so i hope they will change those annoying bugs and won't discontinue a quest pro/quest 2 support after 1 year of quest 3 release

**Comment by thejudge156** [comment]
> > Quest system
> 
> Thanks for reply. Well, i guess vr will be useable in ~2030, now it's like beta testing, because they just updating OS software to add QoL features, but not fixing anything important like: weird artifacts in quest pro (bug since release, appears only if you don't reboot your headset after charging), weird wi-fi support in quest pro that can crash or bugged the software (if you have 4x4 mu-mimo, that can works on >=80mhz channel wide) and that memory leak that u've mentioned. Well there's meta competitor releases, so i hope they will change those annoying bugs and won't discontinue a quest pro/quest 2 support after 1 year of quest 3 release

Hey there, sorry I haven't seen this earlier. Performance is quite low due to how Vivecraft does its rendering. It does ~7 game renders every frame. I am working with the Vivecraft team to fix this and hopefully change it to single-pass instanced rendering, which by some calculations should increase performance by a little over 60%, this is still in the works but it will take a while. Stay in touch, hopefully there will be much better performance.

In terms of updates right now, JRE-21 is being implemented which should up your performance to 40-ish, so yeah.

**Comment by ID86s** [comment]
> Performance is quite low due to how Vivecraft does its rendering. It does ~7 game renders every frame.

Wow that's makes sense now, because as I've previously said
> multitasking is not affecting fps

so it's not cpu issue atleast. Thanks for reply, where i need to put this bug? open, closed or leave as not planned?

**Comment by thejudge156** [comment]
We are being bottlenecked by the CPU, but not because it’s low-power but because we do so many cpu draw calls in a already slow game. The GPU has to communicate more with the CPU leading to slower frame times.

**Comment by ID86s** [comment]
testing v55 with QC 4.0.0: 
Scalling up render resolution (from 100% (1440x1584) to 150% (1764x1940) ) gives u 1fps difference
Scalling down render resolution (from 100% to 50% (1019x1121), because from 100 to 80 has no different in fps) finally boost your fps to unstable 36 to 24 (ONLY IF: you filming video and/or open&close oculus menu ( if you not - stable 24 fps ) )
![com qcxr qcxr-20230617-103209](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/86255195/529825c1-273f-4e90-af09-e6fe66c17ea4)
Changing render distance from 4 to 6 and vice-versa without scalling down render resolution (from 100% to 50-60%) doesn't affect fps 
Night time still gives you 18-20fps

**Comment by thejudge156** [comment]
Modern-Fix should increase FPS a ton, 10-15. Plus it reduces the amount of memory QuestCraft needs
