### ISSUE TITLE
Add Mod’s version number next to the name

### ISSUE THREAD

**Issue by KendrickLamar2003** [QuestCraftPlusPlus/QuestCraft#521]
### 📝 Is your feature request related to a problem? Please describe

Let’s say a crash happens. It’s because of one of the mods. Did I download the wrong version? I can’t check it’s version number through Mod Menu, because MC will not load.

### 🛠️ Describe the solution you'd like

Thats why you should add a version number. Like: Fastload-3.4.0.jar instead of Fastload.jar

### 🤔 Describe alternatives you've considered

Nothing really.

**Comment by JaffaJace** [comment]
Version numbers are only omitted from the file names of the built in mods, any mod you download from mod manager or otherwise should keep its original filename. *I say should as i dont know if Cad did code it like that or not.*

**Comment by zer0ra** [comment]
It downloads the latest version of the mod, don’t it?

**Comment by swaggio7** [comment]
I'm not using modman. I mainly use the traditional way of putting mods in the mods folder. Also, putting mod versions help with diagnosing a problem and/or updating a mod to a new version.

**Comment by JaffaJace** [comment]
So you mean version numbers of the preinstalled mods? Maybe you could ask cad/judge about doing that.
