### ISSUE TITLE
[BUG] <3 dots crash and 4.0.0 crashes when instances download>

### ISSUE THREAD

**Issue by jack19dollar** [QuestCraftPlusPlus/QuestCraft#522]
### 🤔 Current Behavior

crashes questcraft if i click the volume button or home button on the controller it just crashes, i dont know what im doing wrong

And When im on version 4.0.0 of questcraft it stutters while its trying to download in the home and crashes and says not enough space.

i got 2 problems with this, can you help me with them?

### ✅ Expected Behavior

it to hopefully not crash and load up

### 🥽 Headset Details

idk

**Comment by swaggio7** [comment]
The second is an extremely common bug; the best way to overcome this is to keep trying by pressing play again. It may crash a couple of times but still try. You should eventually load into Minecraft.
2. If you want a quicker experience in getting your problem solved, please join the [QuestCraft server.](discord.gg/questcraft)
