### ISSUE TITLE
Swap thumb-sticks [Feature]

### ISSUE THREAD

**Issue by tompayne36** [QuestCraftPlusPlus/QuestCraft#524]
I have changed to Left Handed mode but would like the thumb-sticks to retain their original functionality for moving and rotating. I would like a feature that allows this to be independently swapped.

**Comment by JaffaJace** [comment]
This is already a global option in Settings > Movement(?)
It swaps the thumbsticks on the controllers

**Comment by tompayne36** [comment]
Hi…I have searched all over for something like this. @JaffaJace: Can you give a specific path to the setting?

**Comment by JaffaJace** [comment]
I shouldve mentioned, i meant in Oculus settings, not QuectCraft settings

**Comment by tompayne36** [comment]
Awesome. Thanks! I can play the game again!

**Comment by swaggio7** [comment]
Just a reminder to close this issue, tom.

**Comment by tompayne36** [comment]
(I still think it would be useful to have this in game, but am satisfied with this work around.)
