### ISSUE TITLE
[BUG] not showing

### ISSUE THREAD

**Issue by Ovodud** [QuestCraftPlusPlus/QuestCraft#525]
### 🤔 Current Behavior

The game is not showing when I installed it on side quest it said it had installed but dosnt show in my unknown sources. I had it like 3 months ago and it worked fine but now it dosnt

### ✅ Expected Behavior

I expected it to show

### 🥽 Headset Details

Quest 2
Latest quest software version of 2nd June
Latest quest craft version of 2nd june

**Comment by DiveaLism** [comment]
Hi!
First of all these sort of questions are more suitable for the [Discord server](https://discord.gg/questcraft).
Second of all, you may want to run an adb command, here are some instructions in the image attached

If you have anymore questions please consider the Discord server for a quicker responce :)
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/100384210/c63b7468-9d19-48d1-a2d4-a80a1c7deef4)
