### ISSUE TITLE
[BUG] Unable to scroll through mods on modmanager

### ISSUE THREAD

**Issue by Lockl00p** [QuestCraftPlusPlus/QuestCraft#527]
### 🤔 Current Behavior

I load into the launcher on my V54 quest 2 and go to mod manager. Then I search for my mod and when I don't find it in the first 3 results, I try to scroll. I can't scroll (even though it looks like you should be able to).

### ✅ Expected Behavior

I can scroll through mods to find the one I want.

### 🥽 Headset Details

Build = v54.0.0.151.344.480997738
Quest 2 
Questcraft Ver 4.0

**Comment by swaggio7** [comment]
The devs are aware of this. Unfortunately, it seems that issue is out of their control and is at the fault of Meta.

**Comment by TecEash1** [comment]
<img width="315" alt="image" src="https://github.com/QuestCraftPlusPlus/QuestCraft/assets/92249532/52708c3c-b6b8-4d3d-ad5c-f76df06cf3c7">

**Comment by thejudge156** [comment]
This is fixed in the WIP update.

**Comment by swaggio7** [comment]
> This is fixed in the WIP update.
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/87071118/df356233-db92-4d38-aada-81f994f76ada)
