### ISSUE TITLE
[BUG] Not enough memory

### ISSUE THREAD

**Issue by DethDefier** [QuestCraftPlusPlus/QuestCraft#528]
### 🤔 Current Behavior

My game is installed fine, just did a fresh install. I run it, it waits for a bit, and it crashes and says "there is not enough memory to run questcraft"

### ✅ Expected Behavior

The game should probably start.

### 🥽 Headset Details

Quest 2
Questcraft latest release

**Comment by swaggio7** [comment]
1. After pressing play, did nothing happen? If so, QuestCraft is installing the MC version you selected. This is an extremely common bug; the best way to overcome this is to keep trying by pressing play again. It may crash a couple of times but still try. You should eventually load it into Minecraft.

**Comment by wellsilver** [comment]
There's a memory leak
https://github.com/QuestCraftPlusPlus/QuestCraft/issues/520 (told somewhere here)
It's not questcrafts fault and haved to wait for meta to fix

**Comment by thejudge156** [comment]
Duplicate of #520
