### ISSUE TITLE
Game crashes with any mod but the preinstalled ones

### ISSUE THREAD

**Issue by Xenovyy** [QuestCraftPlusPlus/QuestCraft#529]
### 🤔 Current Behavior

whenever i download almost any mod, the game crashes when I click play. it has no error message and simply goes back to the oculus home

Example:
ModMenu crashes 😐

### ✅ Expected Behavior

to be able to run SOME mods, only able to run barely any

### 🥽 Headset Details

Oculus quest 2, latest version
1.19.4, i believe im on Zinc renderer but idk because I don't even know how to switch to vulkan

### ℹ️ Anything else?

Crash log and other log i found about a java runtime error

[hs_err_pid21084.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/11751660/hs_err_pid21084.log)
[latest.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/11751661/latest.log)

**Comment by RealityXP** [comment]
A. The log files attached are literally 0KB, legit nothing is in them.
B. The discord has a list of mods that outright don't work, including iris beyond 1.19.2 as well as immersive portals and distant horizons to give a few examples.
C. Make sure ANY AND ALL dependencies are installed prior to launching the mods

**Comment by thejudge156** [comment]
Please attach new log files
