### ISSUE TITLE
Where’s 1.20?

### ISSUE THREAD

**Issue by egas-goop** [QuestCraftPlusPlus/QuestCraft#530]
just asking

**Comment by swaggio7** [comment]
It’s coming out as an update soon to the public. Please be patient.

**Comment by egas-goop** [comment]
Thank you

**Comment by polyzium** [comment]
Implemented, please close this issue

**Comment by ausfestivus** [comment]
Fixed in https://github.com/QuestCraftPlusPlus/QuestCraft/releases/tag/4.0.2.

Well, 4.0.1 actually but 4.0.2 is the latest.
