### ISSUE TITLE
[BUG] Game crashes with incompatible Fabric Loader with 1.19.4

### ISSUE THREAD

**Issue by saranicole** [QuestCraftPlusPlus/QuestCraft#531]
### 🤔 Current Behavior

Game crashes with 1.19.4 with the following log

```
[22:23:29] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.19 with version 0.14.21 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.83.0+1.19.4 requires version 0.14.21 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.19!
	 - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.1 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

This happens with an existing install of the game but I tried deleting my 1.19.4 mods folder and reinstalling from Sidequest and it failed the same way.

### ✅ Expected Behavior

Expected the game to load

### 🥽 Headset Details
Quest Build: 54.0.0.155.348.482042417
Device: Quest 2
Questcraft Version: Fabric 1.19.4

### ℹ️ Anything else?

Fabric 1.19.3 works without issue.
[latest.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/11793850/latest.log)

**Comment by saranicole** [comment]
I think the issue is in .fabric > remappedJars -> that redownloads 1.19.4-0.14.19 when I remove it and reinstall.  This should be 14.21.

**Comment by DED0026** [comment]
you should be able to download a new fabric api on your own, i think this issue was resolved earlier today, try restarting questcraft.

**Comment by saranicole** [comment]
@DED0026  thanks so much for your response!  I tried installing the latest Fabric-API and no luck, I also tried the oldest 1.19.4 - https://github.com/FabricMC/fabric/releases/tag/0.78.0%2B1.19.4 - which didn't work either.  Just a plain restart didn't help.  Anything more specific I can try?

**Comment by saranicole** [comment]
I used the command `adb uninstall com.qcxr.qcxr` to uninstall Questcraft and reinstalled and everything worked.
