### ISSUE TITLE
1.20.1 crashes when loading/creating 

### ISSUE THREAD

**Issue by TwoHeartsGK** [QuestCraftPlusPlus/QuestCraft#534]
### 🤔 Current Behavior

everytime i try to load or create a world on 1.20.1 it crashes

### ✅ Expected Behavior

it sould not crash and it should let me play

### 🥽 Headset Details

im on the quest 2

using the newest questcraft update

**Comment by swaggio7** [comment]
This is a common issue. Please wait for a hotfix

**Comment by TwoHeartsGK** [comment]
i can play in a server but not load my own worlds

**Comment by swaggio7** [comment]
Like I said, please wait for a hotfix. Until then, try using 1.19.2

**Comment by TwoHeartsGK** [comment]
sorry but i would rather go into the files and fix it myself

**Comment by swaggio7** [comment]
Would like to see you try, then.

**Comment by TwoHeartsGK** [comment]
did it the problem was vivecraft not loading the custom player data for me

**Comment by SpaceMan986** [comment]
It's happening for me, but it's not just 1.20.1. I've tried reinstalling the app, restarting my headset trying the different versions, nothing works. So it looks like I gotta wait until they fix this themselves :/

**Comment by monkeyman1632** [comment]
> 

One thing I noticed why do you talk like an npc 💀

**Comment by swaggio7** [comment]
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/87071118/56c477db-64bd-45a6-9ab7-25445feca5c7)

**Comment by thedinotnt** [comment]
> did it the problem was vivecraft not loading the custom player data for me

how did you fix it?

**Comment by swaggio7** [comment]
Just update to 4.0.2, it should fix most of the issues.

**Comment by TeddyHuang-00** [comment]
I just got my quest 3, and version 1.20.1 keeps crashing on it. Using latest QuestCraft from SideQuest and haven't tested on 1.19.2 yet.

**Comment by ddwalters** [comment]
> I just got my quest 3, and version 1.20.1/1.19.4/1.19.3 keeps crashing on it. Using latest QuestCraft from SideQuest.

I have this happening as well but version 1.18.2 also crashes.

**Comment by Deretaz** [comment]
Still Crashing on Meta Quest 3 with all versions (Sidequest & QuestCraft)
Sign-In works, but after hitting the Button "Play" the Loadscreen apears for ~10 Seconds before it crashes to doom :D

**Comment by swaggio7** [comment]
QuestCraft on Quest 3 is broken and can't be used, so please wait until a new update comes out. Also, this issue talks about the Quest 2, not 3, so please make a new issue if you continue to encounter issues with QC.

**Comment by Eddie-Baledy** [comment]
I have a similar issue but every version doesnt load for me and I am on Quest 2..
When and where is the hotfix?. Someone said there was gonna be a hotfix like a year ago, a hotfix is usually done pretty quickly to get it running for users and thats why its called a hotfix..
If it isnt gonna be quick then maybe dont call it a hotfix but instead call it something else, like maybe saying it will be patched next update..
I am not entirely pissed even though it may come out looking like I am but I am indeed annoyed at trying to get it to work with so many different methods and even spending quite a bit of time trying to troubleshoot it but nothing..

Please if there is a hotfix still planned to keep people updated..
