### ISSUE TITLE
[FEATURE] add offline accounts

### ISSUE THREAD

**Issue by vrheady** [QuestCraftPlusPlus/QuestCraft#535]
### 📝 Is your feature request related to a problem? Please describe

i cant buy a mc java acc, so it would be cool

### 🛠️ Describe the solution you'd like

play without accounts

**Comment by swaggio7** [comment]
Are you asking for us to add piracy to QC? Sorry man, but you gotta close this issue as it's a YOU problem that you cant buy an MC account. We don't support Piracy

**Comment by Eyndjl** [comment]
> Are you asking for us to add piracy to QC? Sorry man, but you gotta close this issue as it's a YOU problem that you cant buy an MC account. We don't support Piracy

And what about the Offline-mode of MultiMC or Official Minecraft launcher? They also do not support piracy, but there is an Offline-mode in their launchers.

**Comment by TecEash1** [comment]
This will not be added. QCXR does not enforce piracy in any way, shape or form. 
If you own a bedrock PC account then you get java for free so you can play via that way. However bedrock will not/can never be supported due to the Minecraft TOS.

**Comment by polyzium** [comment]
While I do understand the reasoning behind your rejection, please be advised that some people residing in sanctioned countries such as Russia or Iraq cannot buy Minecraft legally.

Such people have to resort to gray markets, or even black markets to obtain a "technically licensed" copy of Minecraft.

**Comment by swaggio7** [comment]
Sorry man, but we don't want to get sued by a giant fortune 500 company. We want to pursue with QuestCraft development, but adding piracy will make things worse.
Also, nice AI reply!

**Comment by polyzium** [comment]
~~Nice accusation!~~ Believe it or not, that response was entirely handwritten by me. I haven't used ChatGPT nor any LLM models to write that response.

...or I might be too formal in this regard. Pardon my manners.

**Comment by swaggio7** [comment]
> ~~Nice accusation!~~ Believe it or not, that response was entirely handwritten by me. I haven't used ChatGPT nor any LLM models to write that response.

Aaannd you ignored 90% of my message. I don't want to turn this into an argument, but we do not wish Piracy and will never implement it. We can't do anything if the user is in a sanctioned country. It's not their fault, but it's not ours as well. You are on your own; I'm not continuing this any further.

**Comment by OstapOmega** [comment]
> While I do understand the reasoning behind your rejection, please be advised that some people residing in sanctioned countries such as Russia or Iraq cannot buy Minecraft legally. For Russians, this is due to credit cards being essentially no longer valid for SWIFT.
> 
> Such people have to resort to gray markets, or even black markets to obtain a "technically licensed" copy of Minecraft.

They can. They are using another sites to buy minecraft keys/accounts

**Comment by TecEash1** [comment]
> While I do understand the reasoning behind your rejection, please be advised that some people residing in sanctioned countries such as Russia or Iraq cannot buy Minecraft legally. For Russians, this is due to credit cards being essentially no longer valid for SWIFT.
> 
> Such people have to resort to gray markets, or even black markets to obtain a "technically licensed" copy of Minecraft.

Please refer to the message above then. While that does personally concern me greatly fortunately there should still be legal ways to purchase the game via 3rd party websites. Furthermore even if this is not the case then I’m afraid there’s not alot we can do as QuestCraft/QCXR cannot endorse piracy in any way shape or form. Adding the offline account functionality you mentioned is strictly prohibited and is illegal as well as violating Mojangs TOS.

**Comment by Gun334frenqw** [comment]
> > While I do understand the reasoning behind your rejection, please be advised that some people residing in sanctioned countries such as Russia or Iraq cannot buy Minecraft legally. For Russians, this is due to credit cards being essentially no longer valid for SWIFT.
> > Such people have to resort to gray markets, or even black markets to obtain a "technically licensed" copy of Minecraft.
> 
> Please refer to the message above then. While that does personally concern me greatly, fortunately there should still be legal ways to purchase the game via 3rd party websites. Furthermore even if this is not the case then I’m afraid there’s not alot we can do as QuestCraft/QCXR cannot endorse piracy in any way shape or form. Adding the offline account functionality you mentioned is strictly prohibited and is illegal as well as violating Mojangs TOS.

Was pojavlauncher sued? I think not

**Comment by TecEash1** [comment]
it may happen in the future but not in the way I think your suggesting it:
<img width="637" alt="image" src="https://github.com/QuestCraftPlusPlus/QuestCraft/assets/92249532/d9ad5858-07cc-4130-b339-ab6b989ad3e8">

**Comment by polyzium** [comment]
> They can. They are using another sites to buy minecraft keys/accounts

This is literally the definition of gray markets. Stuff like G2A belongs there too (I know it might be a scummy company, but I had no other example).

**Comment by thejudge156** [comment]
This is not a possibility legally. Nor do we want non-legit accounts being used in the first place.
