### ISSUE TITLE
[FEATURE] Add support for LabyMod 4

### ISSUE THREAD

**Issue by TheReal-Flo** [QuestCraftPlusPlus/QuestCraft#537]
### 📝 Is your feature request related to a problem? Please describe

On PC, I always play with the LabyMod client, and I would like to use it also on my Quest.

### 🛠️ Describe the solution you'd like

Add the option to install LabyMod from the launcher.

### 🤔 Describe alternatives you've considered

None

**Comment by artdeell** [comment]
jesus why do you guys even use this stuff instead of just, like, using some nice mods like the ones qc packs in?

**Comment by JarzaClay** [comment]
Why add an option to a launcher, just install into the mods folder?

**Comment by swaggio7** [comment]
> jesus why do you guys even use this stuff instead of just, like, using some nice mods like the ones qc packs in?

Fucking hell dude, why are you so rude?

**Comment by swaggio7** [comment]
Jarza, you can install mods a different way. Go to Android/data/com.qcxr.qcxr/.Minecraft/mods/(version number) on your Quest and place the mod there

**Comment by JarzaClay** [comment]
> Why add an option to a launcher, just install into the mods folder?

That's literally what I said.

**Comment by 5ghzx** [comment]
Ask the creators of labymod to make on for the quest, as different clients are probably hell to implement.
