### ISSUE TITLE
[BUG] Game loads forever

### ISSUE THREAD

**Issue by polyzium** [QuestCraftPlusPlus/QuestCraft#538]
### 🤔 Current Behavior

I choose any Minecraft version, I download the assets, press Play. I see the loading dots. Shortly after, I hear the music playing, but it glitches from time to time. I let the headset sit for around 10 minutes, it still displayed a black screen and never recovered.

I restarted the headset multiple times.
I removed the .minecraft folder multiple times.

Nothing worked so far.
I am starting to get fed up, honestly, it's better to just rent a cloud PC and play that way.

### ✅ Expected Behavior

I expected at least the Minecraft main menu to pop up, akin to Vivecraft on PC.

### 🥽 Headset Details

Quest firmware version 54 (v55 hasn't rolled out for me yet)
QuestCraft version 4.0.1
This happens on all Minecraft versions, be it 1.20.1, 1.19.4, 1.19.2, etc etc.

### ℹ️ Anything else?

Sometimes the launcher would crash while downloading files.
After you press Quit and launch the app again. it also causes for the headset to be softlocked and unresponsive to the Oculus button, since it takes forever to load the second time. Can be solved by either rebooting or typing `am force-stop com.qcxr.qcxr` in your adb shell.

**Comment by Dogg0Time** [comment]
Do you know if this issue has been looked into yet?

**Comment by polyzium** [comment]
After a bit of investigation, it seems like this issue is caused by essential mods not properly being downloaded. You can download and launch the game as usual, but something happens in the downloading routine that causes mods to download with a random chance. It is a hit-or-miss.

This is why the game loads forever and displays a black screen, as well as plays music in the background.

If you do encounter this issue for 1.20.1, please use this zip file as a workaround for now.
[mods.zip](https://github.com/QuestCraftPlusPlus/QuestCraft/files/12032907/mods.zip)
Unpack this to `Android/data/com.qcxr.qcxr/files/.minecraft/mods/1.20.1`

CC @CADIndie

**Comment by polyzium** [comment]
Fixed in https://github.com/QuestCraftPlusPlus/Pojlib/commit/3c7d42f78cd8d51b41ff4e961333fc06571ecf25
Awaiting new release.
