### ISSUE TITLE
[BUG] It says i have to update the game when its installed & breaks

### ISSUE THREAD

**Issue by TNT-King** [QuestCraftPlusPlus/QuestCraft#539]
### 🤔 Current Behavior

So, i was gonna install questcraft & then when i was gonna do it it said upgrade when it wasnt on my catalog. & i was like hmm. must have been a bug, so i clicked update & it installed, but it didnt say like, successfully installed the prompt just closed. & it still doesnt show in my catalog. Pls fix this

### 🥽 Headset Details

My quest 2 is in the newest version

**Comment by TecEash1** [comment]
Please try uninstall the game and reinstall it.

**Comment by diskreet90** [comment]
I'm having the same issue. There isn't an app to uninstall either on the quest or through sidequest. And this is making it so I can't install the game. I've gone through the files in android and obb and saw a folder there in both but deleted them and the problem still persists.
