### ISSUE TITLE
[FEATURE] document how to install custom versions

### ISSUE THREAD

**Issue by walksanatora** [QuestCraftPlusPlus/QuestCraft#541]
### 📝 Is your feature request related to a problem? Please describe

i wanted to play a modpack, but questcraft uses `fabric` not `quilt`, and there are no guides/documentation on how to add a custom version (apperently cad says it is possible, but no further information was given)

### 🛠️ Describe the solution you'd like

either a markdown file in this repo and/or the support tab on the website explaining how to add a custom version (eg: quilt)

### 🤔 Describe alternatives you've considered

a dedicated buttton to add more versions that would require more work from devs

**Comment by TecEash1** [comment]
It is not possible to add custom versions or different software to QuestCraft. *However,* you mentioned using quilt, most quilt mods should work on fabric ok. 

Currently the only software QuestCraft supports is fabric and versions 1.18.2,1.19.2,1.19.4 and 1.20.1

**Comment by walksanatora** [comment]
I was told it is possible to install custom versions (somehow)
