### ISSUE TITLE
[BUG] <Game Closing after pressing play>

### ISSUE THREAD

**Issue by TheEmeraldCreeperRB** [QuestCraftPlusPlus/QuestCraft#545]
### 🤔 Current Behavior

After installing a Mod to try in VR, The game just closed after i pressed play, And continued to do so, Even after i tried uninstalling/deactivating the mod.

### ✅ Expected Behavior

The game to Start

### 🥽 Headset Details

Build - v56.0
Device - Q2
Version - 1.20.1

**Comment by thejudge156** [comment]
What mod did you install?
