### ISSUE TITLE
[BUG] <crash because of mods>

### ISSUE THREAD

**Issue by Eliascoollo** [QuestCraftPlusPlus/QuestCraft#547]
### 🤔 Current Behavior

Questcraft on the Oculus Quest 2 is crashing every time when I have mods on It when I click play on 1.20.1.

+

I cannot remove the mods.

### 🥽 Headset Details

Quest Build: [e.g. v37.0]
Device: [e.g. Quest 2
Questcraft Version [e.g. v4.0.2]

**Comment by DED0026** [comment]
what mods?

**Comment by Eliascoollo** [comment]
Pehkui and Immersive portals

**Comment by RealityXP** [comment]
> Pehkui and Immersive portals

_**please check the discord for mods that do NOT work with QuestCraft, you selected 2 mods that don't even work in PCVR**_
discord.gg/questcraft

**Comment by Eliascoollo** [comment]
Ok I didn't knew it. But I cannot delete them.

**Comment by RealityXP** [comment]
Sometimes the uninstall button doesn't work
Do you have a PC, if so: go to the (advanced) sidequest app and use the file manager (the folder on the top bar) to navigate to the path shown  below and delete mods.json (this is what QC uses to grab mods)
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/100168440/e7340b7e-a579-4b52-8486-aa2ca5bbb5be)
make sure you also delete the mods already installed by navigating to this path below and selecting which version you want to fix and deleting the mods you added
![image](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/100168440/18103ac6-0c4e-479d-83c9-cc04238e627c)

If you don't, you can use a file manager to access these paths on the headset itself
If you don't have a PC or don't have a file manager sideloaded, you can always take the route of completely uninstalling and reinstalling the game

**Comment by Eliascoollo** [comment]
Thank you very much. I'll try that soon.
