### ISSUE TITLE
[BUG] once the game is uninstalled once it cannot be reinstalled 

### ISSUE THREAD

**Issue by tubtub1080** [QuestCraftPlusPlus/QuestCraft#55]
Describe the bug
The game is no longer able to be redownloaded or seen after being redownloaded once uninstalled once

To Reproduce

Go to unknown sources
Click on uninstall game
See error
Expected behavior
I expected that I could simply reinstall the game and once again see the application and use it

Headset Details (please complete the following information):

Quest Build: [e.g. v37.0]
Device: Quest_2]
QuestCraft Version [e.g. v1.0.0
Additional context
Once the game loaded I wasnt shown a menu and unable to play, so I uninstalled the game to hopefully reinstall it and play again, but once reinstalled I was unable to even see the game in unknown sources let alone play it

**Comment by monkemungus** [comment]
I have the same issue

**Comment by NateNoNameSOFT** [comment]
This happened to me. To fix this open a terminal (and make sure you have adb installed) then run the following 
`adb uninstall net.kdt.pojavlaunch.debug`
after you run that you can reinstall the apk file

**Comment by Centium76** [comment]
> This happened to me. To fix this open a terminal (and make sure you have adb installed) then run the following `adb uninstall net.kdt.pojavlaunch.debug` after you run that you can reinstall the apk file

I ran the command successfully, but I'm still getting "QuestCraft: : /data/local/tmp/_stream.apk could not be installed [INSTALL_FAILED_VERSION_DOWNGRADE]"

**Comment by Linker7504** [comment]
> This happened to me. To fix this open a terminal (and make sure you have adb installed) then run the following `adb uninstall net.kdt.pojavlaunch.debug` after you run that you can reinstall the apk file

How do I change the directory to adb so I can run this command?

**Comment by NateNoNameSOFT** [comment]
If you are on GNU/Linux simply run these two commands
`sudo apt install adb` (or whatever package manager you use)
`adb uninstall net.kdt.pojavlaunch.debug`
If you are on windows open sidequest and click on the adb button on the top right and click custom command, for the custom command put `uninstall net.kdt.pojavlaunch.debug`

After you do that install the Questcraft APK

**Comment by HalfBakedBaker** [comment]
Im having same issue & when trying to run that ADB command i get an error

I can see the file is on the quest, but isnt showing in the "unknown sources tab" when i put headset on
