### ISSUE TITLE
(FEATURE [QUERY]) LAN Servers with PC players

### ISSUE THREAD

**Issue by boobthecat** [QuestCraftPlusPlus/QuestCraft#550]
### 📝 Is your feature request related to a problem? Please describe

I haven't seen anyone ask this, sorry if it was already answered. Can you play with PC players on LAN servers?

### 🛠️ Describe the solution you'd like

Use Radmin VPN, Hamachi or even Aternos to play with PC friends.

**Comment by 5ghzx** [comment]
why do you think you cant already do this

**Comment by 5ghzx** [comment]
this is the same minecraft as pc, just on quest

**Comment by 5ghzx** [comment]
run your server, download the extension and the pc client, and everything works

**Comment by 5ghzx** [comment]
search for hamachi android and use that

**Comment by Flopgop** [comment]
The purpose of LAN is to connect to other players on the Local Network (hence the name Local Area Network), if you want to play with other players it's preferable to use a real server. This feature would not fit in base QuestCraft FYI, it would be better off as it's own mod.
