### ISSUE TITLE
[BUG] Game is not logging in after i accept permissions

### ISSUE THREAD

**Issue by SergeiTregub** [QuestCraftPlusPlus/QuestCraft#552]
### 🤔 Current Behavior

My game is not logging in, i accepted permissions and then it just says "Login Failure! Ensure you have accepted permissions then click Microsoft button once done."

### 🥽 Headset Details

Device: Meta Quest 2
QuestCraft Version: 4.0.2

**Comment by Flopgop** [comment]
Please use our [discord server](https://discord.gg/questcraft) for support, github issues is for bugs with the application only
