### ISSUE TITLE
[BUG] <game crashes when pressing play>

### ISSUE THREAD

**Issue by radyBOMB** [QuestCraftPlusPlus/QuestCraft#554]
### 🤔 Current Behavior

when pressing play the app crashes

### ✅ Expected Behavior

i expect it to open minecraft

### 🥽 Headset Details

Quest build: v52
Device: Quest 2
Questcraft version: 4.0.2

### ℹ️ Anything else?

[crash-2021-12-13_21.50.07-client.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/12670515/crash-2021-12-13_21.50.07-client.txt)
i downloaded the whole 1.18.2 version too.
and i downloaded the apk file from here on github.

**Comment by RealityXP** [comment]
1. We don't support anything under 1.18.2 nowadays
2. That log is from 2021
3. "4.0.2" doesn't contain MCXR, which is all over that log

**_PLEASE UPDATE YOUR GAME BEFORE CREATING AN ISSUE IN GITHUB._**

Completely uninstall and reinstall the game to update past (what I think is) 2.0. 4.0.2 is also the default on SideQuest if you want to use that instead of side-loading.

**Comment by Cartrigger** [comment]
Version 1.1.1
💀

**Comment by radyBOMB** [comment]
> 1. We don't support anything under 1.18.2 nowadays
> 2. That log is from 2021
> 3. "4.0.2" doesn't contain MCXR, which is all over that log
> 
> **_PLEASE UPDATE YOUR GAME BEFORE CREATING AN ISSUE IN GITHUB._**
> 
> Completely uninstall and reinstall the game to update past (what I think is) 2.0. 4.0.2 is also the default on SideQuest if you want to use that instead of side-loading.

SORRY SORRY MY BAD 1.18.2 I pressed the wrong number.

**Comment by RealityXP** [comment]
You are still running on an ancient version of QuestCraft, again **_please uninstall and reinstall the game_**

**Comment by radyBOMB** [comment]
> You are still running on an ancient version of QuestCraft, again **_please uninstall and reinstall the game_**

wait you sure? i did it 2 times and i downloaded your 4.0.2 version from github. and the crash log is new why it says from 2021?
can you suggest a place that i can download the newest version or the most working version from there? because you can download questcraft on here github , sidequest and questcraft.net

**Comment by RealityXP** [comment]
1. the log's name has the date on it
2. the contents of the log all come from things that were from the 2021 version of QuestCraft (are you sure you pulled it from com.qcxr.qcxr and not from net.kdt.pojavlauncher?)
3. we don't own QuestCraft.net, my guess is someone using it for ad money but I don't exactly know the full story. [This is the official site](https://questcraft.org/)

**Comment by radyBOMB** [comment]
yes im sure i picked it from com.qcxr.qcxr. and thanks for telling me the main site :D.
