### ISSUE TITLE
Crashes on Quest 3 after hitting the PLAY Button (already downloaded)

### ISSUE THREAD

**Issue by Bastian6261** [QuestCraftPlusPlus/QuestCraft#557]
### 🤔 Current Behavior

Hi, installed this game on my Quest 3 by using SideLoader. Can start it, login and download the Game. But once downloaded and hitting the Play Button, the dots will appear for a while and after that the game crashes. 

Would love to play Minecraft on my Quest 3 :( 

### 🥽 Headset Details

Quest 3, latest Firmware (12.10.2023)

**Comment by Cartrigger** [comment]
We are well aware of the issue, please check the discord for updates, QC will need a hot fix to fix this issue.

**Comment by vulcano76** [comment]
Yes, some problem on my quest 3!

**Comment by zq19961113** [comment]
Has this problem been solved? I also encountered it

**Comment by SergeiTregub** [comment]
No guys, quest 3 support is coming soon.

**Comment by TaoRone** [comment]
quest3 is not suppost now
