### ISSUE TITLE
[BUG] <Could not find libjava.so or Jave SE runtime environment>

### ISSUE THREAD

**Issue by baseinfinite** [QuestCraftPlusPlus/QuestCraft#558]
### 🤔 Current Behavior

My game is crashing when i press play on 1.20.1 and in the latest log file stating it cannot find libjava.so or Java SE Runtime environment/

### ✅ Expected Behavior

For 1.20.1 to open and run correctly with no errors

### 🥽 Headset Details

Latest ver
Quest 2
4.0.2

**Comment by thejudge156** [comment]
Need the log
