### ISSUE TITLE
[FEATURE] <Forge mods support>

### ISSUE THREAD

**Issue by lazyrama** [QuestCraftPlusPlus/QuestCraft#559]
### 📝 Is your feature request related to a problem? Please describe

I'm feeling upset when I see amount of mods available with Fabric, so I wanna have forge mods support

### 🛠️ Describe the solution you'd like

I can try to learn java and take some actions for helping you add a Forge support

### 🤔 Describe alternatives you've considered

I have an idea of converting forge mods what i like to fabric or ask the developer for this

**Comment by swaggio7** [comment]
Forge is a kind of sluggish and slow when played on QuestCraft. Also, you can't simply convert a mod from Forge to Fabric. The mod dev must write their mod for Fabric, we can't do anything about it.

**Comment by lazyrama** [comment]
Okay, thanks

**Comment by RealityXP** [comment]
The issue isn't that the devs can't implement forge, it's that it is quite literally unplayable when they have attempted, unless you want to run the game at roughly 5fps it won't be added.

**note that I am not a developer and don't know if there was something recent that could make it possible, although unlikely**
