### ISSUE TITLE
1.20.1 not loading

### ISSUE THREAD

**Issue by TheExtremeRunner** [QuestCraftPlusPlus/QuestCraft#560]
### 🤔 Current Behavior

I've been experiencing this for quite some time now. I can only play on version 1.18 without the game crashing. Basically, when I click 'play' on 1.20.1, or any other version apart from 1.18, the game would load for some time, then crash again. Please fix this...

### ✅ Expected Behavior

I expected my headset to launch minecraft 1.20.1 with no issues.

### 🥽 Headset Details

I don't really know my meta quest 2 headset's version. I was playing on version 4.0.2 of questcraft. Sorry for the lack of information here.

**Comment by portal2707070** [comment]
I delete questcraft folder in data and delete questcraft, when I installed it again it work

**Comment by TheExtremeRunner** [comment]
I tried that... Should I try again and delete the folder data this time?
