### ISSUE TITLE
[FEATURE] 1.20.2 Update

### ISSUE THREAD

**Issue by windowsflytheac** [QuestCraftPlusPlus/QuestCraft#562]
### 📝 Is your feature request related to a problem? Please describe

Minecraft Has Realesed Their new update and idk if its coming on the quest 3 or not

### 🛠️ Describe the solution you'd like

PS if i use dev optiobs on the 1.20.1 it crashes

**Comment by Cartrigger** [comment]
Coming in 5.0.0
