### ISSUE TITLE
[BUG] <Fresh install - can't use the 'sign in' button>

### ISSUE THREAD

**Issue by mychaylo** [QuestCraftPlusPlus/QuestCraft#563]
### 🤔 Current Behavior

Just installed, tried both sidequest and github. When I load either, I get into a starting room where I can choose sign in, or dev options. the Sign in button here can be highlighted, but nothing happens when you press it. tried to reload, didn't 

### ✅ Expected Behavior

I expected to go to sign in screen (of some kind).

### 🥽 Headset Details

4.0.2
Quest Pro v59

**Comment by swaggio7** [comment]
Does a message appear saying something about logging in with a code?

**Comment by swaggio7** [comment]
Also, issues like these are best taken to the Discord since more support members are active there but you can continue on GitHub.

**Comment by thejudge156** [comment]
As of right now, it looks like microsoft services are having an outage. Still trying to confirm this.

**Comment by iamahuman-notai** [comment]
have you tried allowing microphone access, cause that suprisingly worked for me
