### ISSUE TITLE
cant find fabric

### ISSUE THREAD

**Issue by goldman5** [QuestCraftPlusPlus/QuestCraft#57]
i searched in the versions of minecraft and i went all the way to the bottom of the list and i cant find fabric how can i fix this Issue?

**Comment by JD-The-65th** [comment]
Did you extract the zip file to the root directory of your quest?

**Comment by goldman5** [comment]
yes i did but its not showing up

**Comment by JD-The-65th** [comment]
Then you extracted it incorrectly. Extract the zip, and copy over android in the zip to android on your quest

**Comment by lowill232** [comment]
> opy

i did that too and it doesnt work

**Comment by goldman5** [comment]
I figured it out try reseting your headset and try again
