### ISSUE TITLE
[BUG] <title> Sign in problems

### ISSUE THREAD

**Issue by McD987** [QuestCraftPlusPlus/QuestCraft#571]
### 🤔 Current Behavior

So  whenever i sign in and put in the code to sign in It says I have signed in then I press on the sign in button inside QuestCraft but it does not do anything except bring me to the play menu but my account is not signed in and the account username is username. Can someone please help me with this?

### 🥽 Headset Details

Oculus Quest 2 (newest update)
(newest sidequest and qc ver.)

**Comment by McD987** [comment]
please help me :(

**Comment by McD987** [comment]
and when pressing play for 1.20.1 freezes completly and other versions just freeze for 30-40 seconds then un freezes

**Comment by McD987** [comment]
and i cant sign out

**Comment by computer-catt** [comment]
there's a reason we ask for the version, different people have different "newest versions"
procedural rollout, and if the log in button throws you to the play screen it means you've signed in previously.
