### ISSUE TITLE
"new login detected" issue.

### ISSUE THREAD

**Issue by SuperAngerLuigi** [QuestCraftPlusPlus/QuestCraft#572]
### 🤔 Current Behavior

Every time I try to sign in, and put out this exact code in the "remoteconnect" It'll always will "login failure" and Microsoft keeps sending me the same mail Saying about "New login detected" And I don't know why this happens

### ✅ Expected Behavior

I expected For the code to work to let me sign in

### 🥽 Headset Details

Device: Quest_2

**Comment by 2rv** [comment]
Hello. I have got the same problem

**Comment by 2rv** [comment]
I downloaded the game today. Logged into the game. I clicked on the login button. It gave me a code for Microsoft. I entered it, then confirmed my access rights. I was taken to a page where it was stated that my Microsoft account was successfully connected. But after 1 second I was transferred to the page with an error, where it says that there was an error and the code is out of date. In the game itself, when I click again on the login button, the game hangs for 3 seconds and then hangs and says that I am not logged in to my Microsoft account. The next time I click on the login button, this message appears instantly without a 3 second delay.

**Comment by 2rv** [comment]
@CADIndie

**Comment by 2rv** [comment]
@Cartrigger

**Comment by Cartrigger** [comment]
Just go to support in the QuestCraft discord, they can help you there

**Comment by grothkopp** [comment]
I have the same issue. Might have something to do with the account with MC attached belongs to my underaged kid. But I have a microsoft family setup like the discord help suggests and it still doesn't work.
