### ISSUE TITLE
[BUG] questcraft freezes immediately on "made with unity" intro screen

### ISSUE THREAD

**Issue by Rickeyrabbittt** [QuestCraftPlusPlus/QuestCraft#574]
### 🤔 Current Behavior

quest 2 v63, latest questcraft freezes immediately upon opening launcher. freezes in intro screen "made with unity"

### ✅ Expected Behavior

seriously?

### 🥽 Headset Details

v63 quest 2, latest questcraft

### ℹ️ Anything else?

pecker

**Comment by Rickeyrabbittt** [comment]
found out that it only freezes on certain mobile hotspots, as if it cant reach a server for verification or something

**Comment by KendrickLamar2003** [comment]
Hey bud, I don't really think it's a good idea to host a file that contains downloaded Minecraft versions. I'd rather you delete this before it's too late.

**Comment by Rickeyrabbittt** [comment]
> Hey bud, I don't really think it's a good idea to host a file that contains downloaded Minecraft versions. I'd rather you delete this before it's too late. Just to be on the safe side.

Well they still have to sign in to play it right?

**Comment by thejudge156** [comment]
Fixed with 5.0
