### ISSUE TITLE
[BUG] Sign in button does not work

### ISSUE THREAD

**Issue by Penguin7105** [QuestCraftPlusPlus/QuestCraft#576]
### 🤔 Current Behavior

The Sign In button does not display any text or a code when I click it.

### ✅ Expected Behavior

I have signed in before and it pops up with a link and code to sign in.

### 🥽 Headset Details

QuestCraft Version:Latest on SideQuest, Headset:Quest 2, Headset Version:50799390063500150(Headset says no updates availiable).

**Comment by Seve-ferihus** [comment]
I had the same problem.
Click the button a few times, it worked for me.

**Comment by Penguin7105** [comment]
still doesn’t work, i tried uninstalling and reinstalling the app and didn’t work. i also checked and my friend can’t log in either

**Comment by Penguin7105** [comment]
after another reinstall, the sign in button works but all versions just crash back to the home menu

**Comment by Penguin7105** [comment]
After many reinstalls and downgrading to 1.19.2, the launcher is still a little glitched with my profile, but the actual game runs fine
