### ISSUE TITLE
[BUG] <Game does not create new game on meta quest 3 >

### ISSUE THREAD

**Issue by Mrjam007** [QuestCraftPlusPlus/QuestCraft#579]
### 🤔 Current Behavior

when I launch the game it works and sign in but when i click play nothing happpens.

### ✅ Expected Behavior

I expected the play button to create a new game and spawn me into it

### 🥽 Headset Details

Device: Meta Quest 3
Quest craft downloaded from: Side Quest

**Comment by Killerminigun** [comment]
They. Are. Working. On. It.

**Comment by Killerminigun** [comment]
Patience.

**Comment by AmeliaGL0w0** [comment]
questcraft doesnt support quest3 yet. be patient

**Comment by fridaystreet** [comment]
Just signed up to their patroen and downloaded the quest 3 version, works an absolute treat. Well worth $8

**Comment by lastperson** [comment]
@fridaystreet hey, do they also have a Quest 1 version there? After pressing Play it just loads for a minute then crashes.

**Comment by fridaystreet** [comment]
@lastperson not sure about Quest 1, not that I know. It's rerally just about quest 3. I'm guessing if the quest 2 version doesn't already support quest 1 then you'll be out of luck unfortunately. From a hardware perspective it probably wouldn't be able to support it? From a development perspective, probably couldn't see anyone necessarily wanting to sink time in to making it work for old hardware. :-( sorry
