### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GearMaster0000** [QuestCraftPlusPlus/QuestCraft#58]
There is an x-ray glitch when you go underwater you can see objects through walls

**Expected behavior**
normal minecraft water

**Screenshots**

**Headset Details (please complete the following information):**
v37.0
Quest_2
v1.2.3

**Additional context**

**Comment by JD-The-65th** [comment]
Duplicate of #31

**Comment by ATXLtheAxolotl** [comment]
This is a duplicate as mentioned above can this be closed.
