### ISSUE TITLE
[BUG] <quest3 can't choose any release, can't start a game>

### ISSUE THREAD

**Issue by MaceYU** [QuestCraftPlusPlus/QuestCraft#582]
### 🤔 Current Behavior

I successfully logged in MS account on my quest3, but I got stuck in the start menu. The button on the left seems like a  choosing release version button but all blank as I saw, so the game just can not start. I'm running the latest version, 5.0.0.

### 🥽 Headset Details

Quest Build v55, device quest3, questcraft build v5.0.0

**Comment by paypay-a** [comment]
@MaceYU Update your headset
