### ISSUE TITLE
[BUG] cosmeticlauncher menu arm texture issue

### ISSUE THREAD

**Issue by PixelcrafterEXE** [QuestCraftPlusPlus/QuestCraft#583]
### 🤔 Current Behavior

The texture of the left arm appears either flipped or rotated by 180º
![com qcxr qcxr-20240525-191835](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/57109813/33f6b8d9-facc-415c-a759-e33ce1f2d4f2)

### 🥽 Headset Details

Quest Build: v66
Headset: Quest_3
Version: RC5 V5.0.0

**Comment by computer-catt** [comment]
what's your minecraft username? I'll try to fix this right now.

**Comment by PixelcrafterEXE** [comment]
@computer-catt username is 'Pixelcrafter_exe'. 

![Pixelcrafter_exe (1)](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/57109813/6385b4a6-00fc-4e8e-8e4a-082a7669bb06)

**Comment by computer-catt** [comment]
https://github.com/QuestCraftPlusPlus/QuestCraft/assets/98061642/b154d349-8beb-4291-ae8a-3d8c87a2dc00
this should fix it

**Comment by paypay-a** [comment]
> https://github.com/QuestCraftPlusPlus/QuestCraft/assets/98061642/b154d349-8beb-4291-ae8a-3d8c87a2dc00
> 
> this should fix it

What tf was that music?!?

**Comment by computer-catt** [comment]
> > 2024-05-25.17-45-08.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > this should fix it
> 
> What tf was that music?!?

no idea, doesnt matter though :3
