### ISSUE TITLE
[BUG] <Breaks Shaders>

### ISSUE THREAD

**Issue by GBCVR** [QuestCraftPlusPlus/QuestCraft#585]
### 🤔 Current Behavior

The "BIG ONE" breaks all shaders unfortunately for some reason

### ✅ Expected Behavior

Please FIX THIS, for now i will use a older version

### 🥽 Headset Details

Quest 2

**Comment by Cartrigger** [comment]
Shaders don't work at all wdym

**Comment by RowdyTJ** [comment]
The renderer is already running as light as possible to hit 50 fps on Quest 2 and 90 on Quest 3. Running shaders standalone is highly discouraged. If you would like to run shaders at more than 1 frame per decade, I’d use Vivecraft on a decent PC.

**Comment by thejudge156** [comment]
Out-Of-Scope for QuestCraft, if it works it is merely a coincidence until stated otherwise.
