### ISSUE TITLE
[BUG] Immediately crahses apon hitting play 

### ISSUE THREAD

**Issue by RiddleMajor** [QuestCraftPlusPlus/QuestCraft#586]
### 🤔 Current Behavior

Quest Craft Version 5.0.0

### ✅ Expected Behavior

To play the game

### 🥽 Headset Details

 Quest Version 65 (Latest Update)
Quest 3

**Comment by KendrickLamar2003** [comment]
Could be a failed install. Use this ADB command to uninstall QuestCraft: `adb uninstall com.qcxr.qcxr` 
Then reinstall it, and make sure to wear the headset for about 5-10 minutes when downloading a certain MC version.

**Comment by RiddleMajor** [comment]
I tried to sign out and sign back in and it crashed my entire headset, I had to hold the power button and restart it.

**Comment by KendrickLamar2003** [comment]
Note that the command will delete your worlds, so back those up to a computer before continuing if you have any

**Comment by RiddleMajor** [comment]
I wasn't able to open it once ever so I have no worlds.

**Comment by RiddleMajor** [comment]
This worked thank you!
