### ISSUE TITLE
[BUG] cant open java only music 1.18.2<title> problem running quest craft on quest 2

### ISSUE THREAD

**Issue by STAPAIO** [QuestCraftPlusPlus/QuestCraft#587]
### 🤔 Current Behavior

when I select the play button the games loading for infinite loop after that then again starts playing the music 1.18.2

### ✅ Expected Behavior

when I select the play button the games loading for infinite loop after that then again starts playing the music 1.18.2

### 🥽 Headset Details

V15
QUEST 2
5.0.0

**Comment by paypay-a** [comment]
V15?!?!?

**Comment by KendrickLamar2003** [comment]
Hmm I wonder how to fix this

**Comment by paypay-a** [comment]
Update your headset :3

**Comment by computer-catt** [comment]
1.18.2 doesnt work
