### ISSUE TITLE
[BUG] <game not appearing>

### ISSUE THREAD

**Issue by MrQuasySauce** [QuestCraftPlusPlus/QuestCraft#589]
### 🤔 Current Behavior

My game is gone

### ✅ Expected Behavior

I expected to get on my oculus and play quest craft but it wasn't there

### 🥽 Headset Details

v65.0, Oculus Quest 2

### ℹ️ Anything else?

![17173838123995521963671151408072](https://github.com/QuestCraftPlusPlus/QuestCraft/assets/171530053/2acd4c6e-df3e-43c4-97fd-39129d87da72)

**Comment by thewiilover** [comment]
were you able to open the questcraft app before?

**Comment by CrazyBobcatStudios** [comment]
Delete the game using adb commands

**Comment by STAPAIO** [comment]
Kind of the exact same problem as me

**Comment by STAPAIO** [comment]
Kind of of the exact same problem as me

**Comment by MrQuasySauce** [comment]
> were you able to open the questcraft app before?

Yes I was

**Comment by thejudge156** [comment]
Meta bug. Join the Discord for support.
