### ISSUE TITLE
[BUG]Black Screen

### ISSUE THREAD

**Issue by Hayzone2131** [QuestCraftPlusPlus/QuestCraft#59]
escribe the bug
When pressing play after following the tutorial multiple times, the screen stays black and never loads the game

To Reproduce
Press play to play the game
Eternal black Screen

Expected behavior
The game to load

Screenshots

Headset Details (please complete the following information):

Quest Build: [e.g. v37.0]
Quest 2
QuestCraft Version Latest i believe
Additional context

**Comment by bootrec-exe** [comment]
I've also been experiencing this same issue. My Quest running the latest system software (v37), and I've tried downloading QuestCraft from GitHub and Sidequest, following both the official tutorial and The Mystical's tutorial, but I've had no success.

**Comment by mattbrigand** [comment]
Hello me have thib black screen too

**Comment by The-Blue-Goose** [comment]
Try restarting the headset. Rather than clicking login using Microsoft or Mojang, use the "Existing Account" Button. Clicking play will still cause the game to load on a black screen for about a minute, but it should eventually load.

**Comment by mcdermott87** [comment]
I managed to reach the menu once, then played 2 maps, but since I got no luck, 3 dots forever. I have a logcat, I didn't find any log files on the quest.
[logcat.txt](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8132826/logcat.txt)

**Comment by mattbrigand** [comment]
after a lot of reinstallation and having installed v 1.1.1 the game finally
starts and works very well thank you and good luck for developing it. bye

Le jeu. 24 févr. 2022 à 14:38, mcdermott87 ***@***.***> a
écrit :
