### ISSUE TITLE
[BUG] Crash At Login

### ISSUE THREAD

**Issue by mrbeaaaaaast** [QuestCraftPlusPlus/QuestCraft#591]
### 🤔 Current Behavior

When accepting the final prompt in Microsoft's Link website, Questcraft Crashes nearly 5-10 Seconds later, No matter what, Login is Not saved.

### ✅ Expected Behavior

Questcraft Logs Me in.

### 🥽 Headset Details

Quest 2 Running V65
QuestCraft RC5.0.0

### ℹ️ Anything else?

Has been happening for awhile, But i ignored it thinking it was because QC overloaded when i closed my game which had alot of mods, 70 around.

**Comment by thewiilover** [comment]
@mrbeaaaaaast seems like you already own minecraft java. when was the last time you were able to login and play the game?

**Comment by DicedTea** [comment]
Questcraft also crashes after linking on my Quest 3. Fresh install too.

**Comment by mrbeaaaaaast** [comment]
> @mrbeaaaaaast seems like you already own minecraft java. when was the last time you were able to login and play the game?

Two days ago, i experienced crashing after installing a few mods from my pc (i bulk mod) and had to fresh install, after a hot minute i found the issue but now my game would be on the three dots permanently even when you coul already hear the music, so i fresh installed again in hopes of fixing it, but the back then rare bug of the login now dominates my install.

**Comment by mrbeaaaaaast** [comment]
Ki

**Comment by Cartrigger** [comment]
just use discord
https://discord.gg/questcraft for support, this is not a bug

**Comment by thejudge156** [comment]
> just use discord https://discord.gg/questcraft for support, this is not a bug

This is simply incorrect, any unexpected crash should be handled, not cause a crash.

**Comment by mrbeaaaaaast** [comment]
> just use discord https://discord.gg/questcraft for support, this is not a bug

This is not only a bug, But a bug in the launcher.

**Comment by mrbeaaaaaast** [comment]
I might also want to add, That microphone acess is 100% allowed at all times.

**Comment by tulzke** [comment]
@mrbeaaaaaast I had same problem, as you. I buy minecraft, but don't play it never on this licence copy.
Choosing nickname at https://www.minecraft.net/en-us/msaprofile/mygames/editprofile helps to me, and then login at microsoft.com/link works properly.

**Comment by tulzke** [comment]
But, yes, i think this is a bug. Client does not crash

**Comment by mrbeaaaaaast** [comment]
> @mrbeaaaaaast seems like you already own minecraft java. when was the last time you were able to login and play the game?

I checked into this, Turns out, 2 full yearss after purchasing minecraft trough microsoft, I've been fucking robbed! And the game no longer exists on my library! Wtf???

**Comment by mrbeaaaaaast** [comment]
This is a Microsoft Issue, The Questcraft Team Cannot do anything about this.
