### ISSUE TITLE
[BUG] Launching without microphone permission prevents login

### ISSUE THREAD

**Issue by RedNicStone** [QuestCraftPlusPlus/QuestCraft#592]
### 🤔 Current Behavior

When launching the application without previously granting the permission for microphone access, the app dosent proceed to the screen where the user is promoted to login using his microsoft account.

### ✅ Expected Behavior

The application should be usable without granting the microphone permission.

### 🥽 Headset Details

Device: Quest 3
QuestCraft version: v5.0.0
Installer: ADB 1.0.41 for 34.0.4-android-tools

### ℹ️ Anything else?

I don't see why this permission is a requirement for this app.
I believe this permission should be disabled or at least made option, especially when considering this is a closed source application.

**Comment by thewiilover** [comment]
@RedNicStone all requested permissions are required. if you don't want voice chat on then you can disable it from within the game using simple voice chat settings menu. again microphone access is required but it is only used for the voice chat functions of questcraft.

**Comment by RedNicStone** [comment]
In that case, why does this prevent sign-in on startup? A correct way to handle is the prevent the user from using voice chat in game in case microphone access is not granted, rather than to prevent use of the app without it.

**Comment by thewiilover** [comment]
> ### 🤔 Current Behavior
> When launching the application without previously granting the permission for microphone access, the app dosent proceed to the screen where the user is promoted to login using his microsoft account.
> 
> ### ✅ Expected Behavior
> The application should be usable without granting the microphone permission.
> 
> ### 🥽 Headset Details
> Device: Quest 3 QuestCraft version: v5.0.0 Installer: ADB 1.0.41 for 34.0.4-android-tools
> 
> ### ℹ️ Anything else?
> I don't see why this permission is a requirement for this app. I believe this permission should be disabled or at least made option, especially when considering this is a closed source application.

also wtf you mean this is a closed source app. have you even tried to look at the github profile. the source code for questcraft is located in the repo "QuestCraftPlusPlus/QCXR-XR-Wrapper" and also "QuestCraftPlusPlus/Pojlib"

**Comment by TheReal-Flo** [comment]
Also came just here to state the closed source thing. QuestCraft was literally open source and transparent with everything from the very beginning

**Comment by TheReal-Flo** [comment]
> In that case, why does this prevent sign-in on startup? A correct way to handle is the prevent the user from using voice chat in game in case microphone access is not granted, rather than to prevent use of the app without it.

The game would crash, when it doesn't have the microphone permission, but when we are just talking about it, wouldn't it be possible to just not install Simple Voice Chat when the microphone permission isn't present?

**Comment by thewiilover** [comment]
> In that case, why does this prevent sign-in on startup? A correct way to handle is the prevent the user from using voice chat in game in case microphone access is not granted, rather than to prevent use of the app without it.

this probably is possible but would require some kind of rewrite of a large chuck of questcraft's source. so it probably will never happen

> Also came just here to state the closed source thing. QuestCraft was literally open source and transparent with everything from the very beginning

technically this isnt true. the wrapper was closed source in the beginning.

**Comment by RedNicStone** [comment]
> also wtf you mean this is a closed source app. have you even tried to look at the github profile. the source code for questcraft is located in the repo "QuestCraftPlusPlus/QCXR-XR-Wrapper" and also "QuestCraftPlusPlus/Pojlib"

This is not made clear in the repo. There is no link, nor any statement that the app is open source. And when looking at this repository all I see is an empty repo what contains no source code, with no mention of that in the readme.

**Comment by 5ghzx** [comment]
is this like the stupid smelly nerds thing?

**Comment by TheReal-Flo** [comment]
> is this like the stupid smelly nerds thing?

Yes

**Comment by RedNicStone** [comment]
Also the source code has not been updated to the newest version

**Comment by 5ghzx** [comment]
> > also wtf you mean this is a closed source app. have you even tried to look at the github profile. the source code for questcraft is located in the repo "QuestCraftPlusPlus/QCXR-XR-Wrapper" and also "QuestCraftPlusPlus/Pojlib"
> 
> This is not made clear in the repo. There is no link, nor any statement that the app is open source. And when looking at this repository all I see is an empty repo what contains no source code, with no mention of that in the readme.

its on github

**Comment by thewiilover** [comment]
> Quote reply

im saorry but have you looked at the discord. there is a direct link the the repo for the wrapper in the faq channel.

**Comment by TheReal-Flo** [comment]
> > also wtf you mean this is a closed source app. have you even tried to look at the github profile. the source code for questcraft is located in the repo "QuestCraftPlusPlus/QCXR-XR-Wrapper" and also "QuestCraftPlusPlus/Pojlib"
> 
> This is not made clear in the repo. There is no link, nor any statement that the app is open source. And when looking at this repository all I see is an empty repo what contains no source code, with no mention of that in the readme.

Ermm, there actually is
> The QCXR forks we use are: [Pojlib](https://github.com/questcraftplusplus/pojlib), [VivecraftMod](https://github.com/questcraftplusplus/vivecraftmod), [VulkanMod](https://github.com/QuestCraftPlusPlus/VulkanMod), and [Unity Env](https://github.com/QuestCraftPlusPlus/QCXR-XR-Wrapper).

**Comment by thewiilover** [comment]
> Also the source code has not been updated to the newest version

brother, what? how do you think the devs build app

**Comment by RedNicStone** [comment]
> > > also wtf you mean this is a closed source app. have you even tried to look at the github profile. the source code for questcraft is located in the repo "QuestCraftPlusPlus/QCXR-XR-Wrapper" and also "QuestCraftPlusPlus/Pojlib"
> > 
> > 
> > This is not made clear in the repo. There is no link, nor any statement that the app is open source. And when looking at this repository all I see is an empty repo what contains no source code, with no mention of that in the readme.
> 
> Ermm, there actually is
> 
> > The QCXR forks we use are: [Pojlib](https://github.com/questcraftplusplus/pojlib), [VivecraftMod](https://github.com/questcraftplusplus/vivecraftmod), [VulkanMod](https://github.com/QuestCraftPlusPlus/VulkanMod), and [Unity Env](https://github.com/QuestCraftPlusPlus/QCXR-XR-Wrapper).

That is not a link the the source code

**Comment by TheReal-Flo** [comment]
> Also the source code has not been updated to the newest version

wtf It's updated, was even updated always before the update

**Comment by TheReal-Flo** [comment]
> That is not a link the the source code

Yes it is? Unity-Env is the Wrapper, Pojlib is the launcher library?

**Comment by RedNicStone** [comment]
> > Quote reply
> 
> im sorry but have you looked at the discord. there is a direct link the the repo for the wrapper in the faq channel.

I have not joined the discord, and this should not be required to get essential information.

Not that it matters, this isent the issue here and clearly off-topic

**Comment by RedNicStone** [comment]
> > That is not a link the the source code
> 
> Yes it is? Unity-Env is the Wrapper, Pojlib is the launcher library?

I think you do not understand the definition of source code. These are external utilities and libraries

**Comment by 5ghzx** [comment]
no, that is the code for questcraft. that is quest craft.

**Comment by 5ghzx** [comment]
this repo is nothing

**Comment by 5ghzx** [comment]
just an issue hub

**Comment by TheReal-Flo** [comment]
> > > That is not a link the the source code
> > 
> > 
> > Yes it is? Unity-Env is the Wrapper, Pojlib is the launcher library?
> 
> I think you do not understand the definition of source code. These are external utilities and libraries

What do you think QuestCraft is, it's just a *Wrapper* to launch Minecraft. The Main Repos are the Unity-Env and Pojlib ones

**Comment by RedNicStone** [comment]
> no, that is the code for questcraft. that is quest craft.

None of these would enable me to build the application. Ergo: not source code

**Comment by thewiilover** [comment]
> > no, that is the code for questcraft. that is quest craft.
> 
> None of these would enable me to build the application. Ergo: not soure


the wrappar allows you to build an apk file that is in fact questcraft. i would call something like that the source code

**Comment by TheReal-Flo** [comment]
> > no, that is the code for questcraft. that is quest craft.
> 
> None of these would enable me to build the application. Ergo: not source code of this application

Bet? I'm not a developer of this app and still have a self build which hashes doesn't match with any of those who got released publicly

**Comment by RedNicStone** [comment]
How exactly does this relate to the issue at hand?

**Comment by TheReal-Flo** [comment]
> How exactly does this relate to the issue at hand?

I don't know, you opened an issue and stated that it's closed source, and we tried to correct you

**Comment by thewiilover** [comment]
> How exactly does this relate to the issue at hand?

its showing that your being stubborn. please do your research before you go around calling something open source, closed source. its all avalable on this very github profile that this issue is on

**Comment by RedNicStone** [comment]
And I pointed out that this isent made clear in this repository, maybe this should be addressed in another issue.

**Comment by RedNicStone** [comment]
> is this like the stupid smelly nerds thing?

Also insulting someone for opening what seems to be a fixable issue is extremely unprofessional behaviour even for a community project. I think your project may have a management/moderation problem.

I will be unsubscribing from this issue until a willingness is shown to resolve this issue.

**Comment by thewiilover** [comment]
> > is this like the stupid smelly nerds thing?
> 
> Also insulting someone for opening what seems to be a fixable issue is extremely unprofessional behaviour even for a community project. I think your project may have a management/moderation problem.
> 
> I will be unsubscribing from this issue until a willingness is shown to resolve this issue.

i think you should stop typing before you get yourself into more trouble than you want right now

**Comment by 5ghzx** [comment]
> > is this like the stupid smelly nerds thing?
> 
> Also insulting someone for opening what seems to be a fixable issue is extremely unprofessional behaviour even for a community project. I think your project may have a management/moderation problem.
> 
> I will be unsubscribing from this issue until a willingness is shown to resolve this issue.

that wasnt an insult, that a reference to a reddit post where developers were slandered for not posting exes on their github repos.

**Comment by thejudge156** [comment]
Howdy, actual developer here. I see the concern, it's a leftover piece from when we had Simple Voice Chat (SVC) installed by default. I will work on a fix now.

**Comment by thejudge156** [comment]
And for future reference, Pojlib builds an AAR which goes *into* the wrapper. Assets/Plugins/Android is the path relative to the root of the QCXR-XR-Wrapper project.

**Comment by RedNicStone** [comment]
I should probably ask this in a separate issue (or on discord), but are there any build instructions?

**Comment by thejudge156** [comment]
> We do have some documentation in the works so stay tuned.

^

**Comment by RedNicStone** [comment]
Github dosent update comments without reloading the tab for me :/

**Comment by TheReal-Flo** [comment]
> I should probably ask this in a separate issue (or on discord), but are there any build instructions?

@RedNicStone if you want to join the Discord, you could mention me there \@TheReal_Flo_ and I could gladly help you with the build ^^

**Comment by CADIndie** [comment]
> > I should probably ask this in a separate issue (or on discord), but are there any build instructions?
> 
> @RedNicStone if you want to join the Discord, you could mention me there @TheReal_Flo_ and I could gladly help you with the build ^^

Hello, Lead Project Manager here, I have written documentation at https://docs.questcraft.org/getting-started/setup/
