### ISSUE TITLE
Readme isn't clear about what open source parts are used

### ISSUE THREAD

**Issue by TheReal-Flo** [QuestCraftPlusPlus/QuestCraft#593]
> And I pointed out that this isent made clear in this repository, maybe this should be addressed in another issue.

_Originally posted by @RedNicStone in https://github.com/QuestCraftPlusPlus/QuestCraft/issues/592_

I will address this issue later and commit a change

**Comment by 5ghzx** [comment]
this issue or rednic's issue?

**Comment by thewiilover** [comment]
> this issue or rednic's issue?

rednic's issue

**Comment by TheReal-Flo** [comment]
> > this issue or rednic's issue?
> 
> rednic's issue

This one, what is in the title

**Comment by 5ghzx** [comment]
could i?

**Comment by TheReal-Flo** [comment]
> could i? make a contribution?

Yeah, if you want

**Comment by TheReal-Flo** [comment]
Closing this, as it's fixed in #594
