### ISSUE TITLE
[BUG] <Having microphone muted causes game to crash during sign-in>

### ISSUE THREAD

**Issue by memorymanxd** [QuestCraftPlusPlus/QuestCraft#595]
### 🤔 Current Behavior

If the microphone is muted via the Meta Quest options prior to launching the game, you will be prompted to use a sign in code again, even if you have previously signed in. Attempting to do so will result in the game crashing shortly after entering the code on the Microsoft Link Account page.

### ✅ Expected Behavior

Game would continue to function while microphone is muted via headset options. Player would still be signed in from previous game session.

### 🥽 Headset Details

Quest Version: v66 (Latest)
Device: Quest 3
Version: RC5 V5.0.0

**Comment by KendrickLamar2003** [comment]
Why not mute the microphone after launching the game?

**Comment by memorymanxd** [comment]
I could do that. But it's still a bug.

**Comment by thejudge156** [comment]
Probably a side effect fixed by #592 ‘s resolution. Will verify.

**Comment by mrbeaaaaaast** [comment]
How can i enable these permissions?
