### ISSUE TITLE
Freeze on World gen

### ISSUE THREAD

**Issue by 5ghzx** [QuestCraftPlusPlus/QuestCraft#60]
if you gen the world, on done editing, it freezes
 
1 open questcraft
2 gen a world

shoulda loaded

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
quest 2
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by JD-The-65th** [comment]
Redownload Quest Craft Please.
