### ISSUE TITLE
[BUG] <game crashes when I sign>

### ISSUE THREAD

**Issue by Orenob** [QuestCraftPlusPlus/QuestCraft#601]
### 🤔 Current Behavior

My game crashes when I finish signing into my Microsoft account and when I get back in to the game it asks my user to sign in again and then crashes again.

### ✅ Expected Behavior

I expect it not to crash when I try to sign in I am incapable of playing it because of this.

### 🥽 Headset Details

Quest 2

**Comment by Killerminigun** [comment]
My good sir microsofts auth servers are shiting themselves

**Comment by Killerminigun** [comment]
Have been for a few days now

**Comment by Orenob** [comment]
Hi did my bug report go through

**Comment by Orenob** [comment]
Is there something I can do to get around this

**Comment by RealityXP** [comment]
at the moment no, since microsoft/mojang still haven't solved the issue. Their website as well as 3rd party launchers are the most affected. [https://bugs.mojang.com/browse/WEB-7179](url)

**Comment by Orenob** [comment]
Oh ok so it will work when Microsoft fixes it

**Comment by Orenob** [comment]
Can you please inform me when it gets fixed

**Comment by Orenob** [comment]
It has been fixed

**Comment by Orenob** [comment]
Thanks
