### ISSUE TITLE
[BUG] <title> cant open QuestCraft 1.18.2-1.19.2 only music problem running quest craft on Quest 3

### ISSUE THREAD

**Issue by Ragefiren** [QuestCraftPlusPlus/QuestCraft#603]
### 🤔 Current Behavior

Set custom ram 4000, or not ether way then Load In download 1.18.2 or 1.19.2 hit the play button the games loads 3 dots once it loads in still see 3 dots but it starts playing the music.
can't see nothing.
This is same with 1.19.2 so I included a video with just 1.18.2 sense that's what's apparently so stable yet can't even run ...

This is with default mods & when you remove all leaving just fabric & vivecraft it doesn't matter it will not load.

### ✅ Expected Behavior

I expected the game to load in like it does with 1.20.1 where you are on a mini island & see a floating Minecraft menu with settings etc.

### 🥽 Headset Details

Quest 3 on latest 65 version no updates available at the time of typing this out. 
Latest Quest Craft 5.0.0 from SideQuest again at the time of typing this.

### ℹ️ Anything else?

https://github.com/QuestCraftPlusPlus/QuestCraft/assets/124943287/ce1bd6f9-7511-4a4d-be7e-54c56692d99e

**Comment by Cartrigger** [comment]
Please go to our discord. we dont do support in github issues
