### ISSUE TITLE
[BUG] questcraft casually lag

### ISSUE THREAD

**Issue by F4bi05** [QuestCraftPlusPlus/QuestCraft#607]
### 🤔 Current Behavior

When i'm playing in single player, even if i'm still, the game freezer for 1/2 seconda. This olso happen when I try to hit a mob with the sword. I've tried installing many performance mod but nothing seems so fix this lag. Obviosly i've also tried diminishing the chuni and some athore setting but It was the game.

### 🥽 Headset Details

Quest build: v66
Device: Quest 2
Questcraft version: 5.0.0
Minecraft versione:1.20.4

**Comment by Killerminigun** [comment]
Yea that makes sense.
Go play on a server. Any server.

**Comment by F4bi05** [comment]
So I tried and it was all smoother. My fps were fixxed at 60, even if i don't have v-sync turned on,  that's actually strange. But it kept freezing casually, the same lag it did in singleplayer. Any fix?

**Comment by Killerminigun** [comment]
Not user fixable
Its an internal thing 

This is already stupid good for java with it rendering twice and doing vr

Devs are working on it

**Comment by F4bi05** [comment]
Ok thanks. I thought that It was and internal things but i never heard no one complain about that on post or video so i thought It was my problem.

**Comment by Killerminigun** [comment]
Nah its normal
