### ISSUE TITLE
ERR_NAME_NOT_RESOLVED issue 

### ISSUE THREAD

**Issue by Vrgaemer** [QuestCraftPlusPlus/QuestCraft#61]
Please fix this, this has been very annoying and I have wasted 2 days trying to play questcraft. I'm very frustrated and all you do to recreate is press "login with Microsoft"

**Comment by pizza-beep** [comment]
that is POJAV launcher not questcraft

**Comment by pizza-beep** [comment]
Complain to Pojav launcher dont complain to questcraft

**Comment by ATXLtheAxolotl** [comment]
Could you provide screenshots?

**Comment by ATXLtheAxolotl** [comment]
I believe your problem is the same as #7 go check there for the solution.

**Comment by ATXLtheAxolotl** [comment]
Also can someone close this because the solution is in #7 and #7 has already been closed.
