### ISSUE TITLE
[BUG] Loading screen not responding

### ISSUE THREAD

**Issue by TechnicallyJackson** [QuestCraftPlusPlus/QuestCraft#610]
### 🤔 Current Behavior

My game is stuck on the login screen. It says loading... then it goes back to Log In. 

### ✅ Expected Behavior

I expected a code to put in on a different browser.

### 🥽 Headset Details

Device: Quest 2
Build Number: v67.0
Questcraft Version: v5.0.0 Rc5

### ℹ️ Anything else?

I also tried it offline, and it gave the same result. This means it can't connect to a server it needs to connect to.

**Comment by thewiilover** [comment]
Does this happen every time you try?
If so what have your troubleshooting steps been?

**Comment by TechnicallyJackson** [comment]
No, I just happened yesterday. It’s been awhile since I opened it and sidequest.

**Comment by TechnicallyJackson** [comment]
I fixed it! The other times I didn’t allow the microphone permission. I did now, and it works. Please fix this bug unless it’s a feature

**Comment by thewiilover** [comment]
> I fixed it! The other times I didn’t allow the microphone permission. I did now, and it works. Please fix this bug unless it’s a feature 

The devs have a fix for this
