### ISSUE TITLE
[BUG] Game not installing

### ISSUE THREAD

**Issue by peacefulboii** [QuestCraftPlusPlus/QuestCraft#611]
### 🤔 Current Behavior

i'm having an issue with installing the game. When i try to install on my quest it gives me a prompt to "Update application" and then i press it but when it finishes it says "App not installed as package conflicts with an existing package" and i can't figure out how to fix it.

### ✅ Expected Behavior

The game to let me install 

### 🥽 Headset Details

Device: Quest 2
Device build: v67.0
Questcraft Version: v5.0.0 

### ℹ️ Anything else?

my friend said when it gave him the prompt to "update" he had no issue but he also never had questcraft installed until i told him about it

**Comment by thewiilover** [comment]
Please go to the discord with help for this. As for your problem uninstall the current version you have installed and then install the latest version of the apk. If you need more help go to the discord

**Comment by peacefulboii** [comment]
> To fix your problem uninstall the current version you have installed and then install the latest version of the apk. If you need more help go to the discord

i don't have it installed and i never have but it still refuses to let me install

**Comment by RealityXP** [comment]
again, this isn't an unprecedented issue and you most likely have to do an ADB command, instructions are in the discord server.

**Comment by kicius54** [comment]
try factory reset if adb uninstall command dont work
