### ISSUE TITLE
[FEATURE] Support for Better Than Adventure

### ISSUE THREAD

**Issue by Bright5park** [QuestCraftPlusPlus/QuestCraft#614]
### 📝 Is your feature request related to a problem? Please describe

I think it is great that modern versions of Minecraft work as well as they do, but since the "Golden Age" of Minecraft and the Better Than Adventure mod/fork getting some attention in particular, I think it would be neat to be able to play BTA on the Quest as well.

### 🛠️ Describe the solution you'd like

Ideally work with the developers of Better Than Adventure as well as the Better Than VR/Nostalgic Reality to bring it to the Quest

### 🤔 Describe alternatives you've considered

You could always just use PCVR in some fashion, but I reckon that the Quest should be more than capable to run a version of Minecraft from 10 years ago, modded as it may be.

### ℹ️ Anything else?

In case it helps, here is the Nostalgic Reality/BTVR mod for BTA on GitHub: https://github.com/GiantLuigi4/better-than-vr

Note: I am not affiliated with either the Better Than VR/Nostalgic Reality mod, nor with Better Than Adventure.

**Comment by Killerminigun** [comment]
Hah

**Comment by Killerminigun** [comment]
Its beta mc not happening

**Comment by Killerminigun** [comment]
Reason is qc only uses vivecraft mixin
Thats why theres no versions lower than 1.18.2

**Comment by Cartrigger** [comment]
I personally have already looked into this, yes possible but worth it due to the low playerbase: no
