### ISSUE TITLE
Questcraft manual mod importing

### ISSUE THREAD

**Issue by GaMeR-debugjpg** [QuestCraftPlusPlus/QuestCraft#615]
How would I import mods manually if this is possible, and if I were to do so how wouls I make sure it worked?

**Comment by Cartrigger** [comment]
please run /mods in crafty, and choose PC.

**Comment by GaMeR-debugjpg** [comment]
thanks for the info! I'll try that to see if it worked for me. I'm leaving this open just in case it doesn't so I can get more help if needed.
