### ISSUE TITLE
[FEATURE] re add the local account option

### ISSUE THREAD

**Issue by j202-61** [QuestCraftPlusPlus/QuestCraft#620]
### 📝 Is your feature request related to a problem? Please describe

please

### 🛠️ Describe the solution you'd like

please re add this beautiful button

### 🤔 Describe alternatives you've considered

or add a new button

**Comment by computer-catt** [comment]
it's not happening

**Comment by j202-61** [comment]
:(

**Comment by j202-61** [comment]
bye bye local account option :(

**Comment by computer-catt** [comment]
it hasn't been in questcraft for like 3 years already

**Comment by RealityXP** [comment]
answer: no :)
