### ISSUE TITLE
[BUG] <Game Crashes Apon Pressing Play>

### ISSUE THREAD

**Issue by TheRealFame** [QuestCraftPlusPlus/QuestCraft#628]
### 🤔 Current Behavior

I both uninstalled and reinstalled questcraft, I used an alt account, And I used my main. The only time questcraft has worked is when loading version 1.18 (I wish I could return to 1.16 without a PC.)

So anytime I load 1.18 it get's into the game but doesn't display anything. Leaving me with just sound but no display. (3 Dot's Loading)

### ✅ Expected Behavior

The forge loading screen/fabric loading screen in vr, And to be put in front of the main menu of the game in order to play.

### 🥽 Headset Details

Version 5.0.0 | Latest Quest Update at the time of writing.
Quest 2: 32 GB Version/Default (No Third Party Tinkering)
Connected to an active meta quest account.

### ℹ️ Anything else?

I don't have the link to the logs of my game, But since this issue is common and only 1.18 has loaded for me, I am guessing it's broken compatibility with the code that put's you into Minecraft vr/Vivecraft itself.

I do plan to later experiment with trying to obtain the older files noted in tutorials of how to install questcraft, To see if they fix the issue, Because I heard most people were able to get into quest craft a year ago. And more players having issues now at the modern time.

**Comment by TheRealFame** [comment]
I'll record a video of it happening in action if that help's! You may be able to collect the log link itself that way, Instead of me manually typing out the long given link. Just tell me if it's needed! Because I was really hoping to try out this compatibility layer/software

**Comment by TheRealFame** [comment]
Okay so I was actually wrong LOL

So it turns out. You actively do need to wait 10 in world minutes for files to download. And there's actually no good progress bar that says everything is done.

**Comment by TheRealFame** [comment]
Before I close the ticket though. I'd like for a better progress bar to be implemented! Cause the current one never says or estimates when things will actively finish.

**Comment by Cartrigger** [comment]
A progress bar will be implemented in the next major update.

**Comment by TheRealFame** [comment]
> A progress bar will be implemented in the next major update.

I'm guessing it's coming in a day or two now 😅
