### ISSUE TITLE
[FEATURE] Ability to install new versions of the games as soon as Vivecraft supports it. 

### ISSUE THREAD

**Issue by AwesomeParley** [QuestCraftPlusPlus/QuestCraft#629]
### 📝 Is your feature request related to a problem? Please describe

I'm always frustrated when a new update comes out, and for over at least a month, you block it from the general public to try out. This shouldn't be a new update. QuestCraft is a loader, and shouldn't have to update for each MC release that comes out. You can pretty easily get the Vivecraft Update from the [curseforge](https://www.curseforge.com/minecraft/mc-mods/vivecraft) or [modrinth](https://modrinth.com/mod/vivecraft) API. 

### 🛠️ Describe the solution you'd like

I would like there to be an easy way to add new versions when they come out on vivecraft, regardless of how updated questcraft is. 

### 🤔 Describe alternatives you've considered

There basically are no alternatives out there due to discontinuation of actual VR MC, but one alternative is PCVR. but for those who want to have an actual on-the-go MC experience, aren't able to use a link cable or Ethernet, or don't have a strong enough PC, there is none.

**Comment by thewiilover** [comment]
Hey, just letting you know that questcraft uses a custom build of vivecraft that has is used because regular vivecraft doesn't work correctly with how questcraft is setup to work. This is the main reason why questcraft has to be updated in order to have newer version of Minecraft

**Comment by M4j0d1** [comment]
What Thewiilover Said, Using The Normal Vivecraft Versions Will Just Not Work In QuestCraft

**Comment by itsnotalexthere** [comment]
Then it should get it from GitHub, not the mod

**Comment by thewiilover** [comment]
> Then it should get it from GitHub, not the mod getting from the releases
> 
> 
> 
> Edit: realised that it it not as simple, sorry

Yea no. The releases on the mod pages are from the GitHub lol

**Comment by Cartrigger** [comment]
In the future, this might be subject to change because of what they are working on right now, but as of right now, it is not that simple sadly.

**Comment by thejudge156** [comment]
Here is what requires a Binary update (Apk update) and here is what needs a OTA update:

Conditions:
- Does the new update require new OpenGL features? **Requires Binary update**
- Does the new update require a new Java Version? **Requires Binary update**
- Does the new update require a new LWJGL version? **Requires Binary update** (to be remedied soon)

If the update does not meet **at least one** of these factors, it can be done Over-The-Air from our mods.json file. QuestCraft is not just a loader. Updates would be 1000% faster if it were.

**Comment by thejudge156** [comment]
Casual issue close failure 💀
