### ISSUE TITLE
[BUG] Cannot find fabric in pojav

### ISSUE THREAD

**Issue by Eccentric1847** [QuestCraftPlusPlus/QuestCraft#63]
Unable to locate the fabric options in the game version menu on the pojav launcher. I have attempted restarting my quest, I followed the tutorial for installing QuestCraft to a T.

**To Reproduce**
1. Go to pojav launcher
2. Open the version chooser menu
3. No fabric visible

**Expected behavior**
I expected to be able to select the fabric build.

**Screenshots**
**Headset Details (please complete the following information):**
 - Quest Build: most recent update (37.0)
 - Device: Quest 2
 - QuestCraft Version: most recent, to my knowledge

**Comment by Eccentric1847** [comment]
I fixed it myself

**Comment by Pokesketch** [comment]
@Eccentric1847 how?

**Comment by KiNGBUDDAH305** [comment]
@Eccentric1847 how did you fix it?

**Comment by dodders59** [comment]
when you fixed it did just uninstalling from unknown sources do the trick before reinstalling apk or is there more to search for in the files to remove, im having the same issue

**Comment by Eccentric1847** [comment]
@dodders59 I Uninstalled it through sidequest, so I assume Unknown sources would work too.

**Comment by dodders59** [comment]
@Eccentric1847 ive tried that multiple times and it hasnt worked lol, im fr about to give up on this

**Comment by ATXLtheAxolotl** [comment]
As @Eccentric1847 has said he has resolved this issue.

**Comment by ATXLtheAxolotl** [comment]
> @KiNGBUDDAH305 @Pokesketch I Uninstalled my game (remove pojav) and then redownloaded the apk. I then deleted all instances of the zip file and redownloaded it, then went into the quest files as I copied it to make sure literally everything was there. I don't know if I did something weird, but there you go.

The issue should be closed since it has been resolved.
