### ISSUE TITLE
[BUG] Quits out when exiting a text field.

### ISSUE THREAD

**Issue by Dazza82** [QuestCraftPlusPlus/QuestCraft#630]
### 🤔 Current Behavior

I have a quest 2 and a quest 3. Bug is happening to both, and started at the same time. Every time that you finish entering text, the game quits out. This happens in the game and in the menu. Also, after playing the game for a seamingly random time, even without entering text, the game quits out.

### ✅ Expected Behavior

It used to no quit out.

### 🥽 Headset Details

Questcraft v5.0
Bith quest 2 and 3

**Comment by Cartrigger** [comment]
Please read known issues in the discord, you are on v71 which is unsupported at the moment
