### ISSUE TITLE
Quest 3s support

### ISSUE THREAD

**Issue by Ballers6** [QuestCraftPlusPlus/QuestCraft#631]
### 📝 Is your feature request related to a problem? Please describe

Can you guys please make quest 3s support Bcus it ha lag spikes every 4 seconds and if you item switch items on your hand the game crashes

### 🛠️ Describe the solution you'd like

Less lag and fix arm item crash

**Comment by RealityXP** [comment]
Please read the discord, this is not a quest 3S specific issue
