### ISSUE TITLE
[BUG]I can only hear voices

### ISSUE THREAD

**Issue by GachaMeow** [QuestCraftPlusPlus/QuestCraft#632]
### 🤔 Current Behavior

I used it in yvr1,The result is that you can start the game, but you can't see the game screen, but you can hear the sound of the game.

### ✅ Expected Behavior

The version that Yvr can run

### 🥽 Headset Details

YVR1

**Comment by AmeliaGL0w0** [comment]
well, questcraft is built for a quest headset, and not yvr1, so you are on your own here (unless devs have a kind heart and port qc to your headset like they did with pico 4, but i highly doubt that will happen)

**Comment by GachaMeow** [comment]
One of my findings is that I saw some files related to YVR in the QCXR-XR-Wrapper version branch, as well as a map of the launcher, so does that mean I can compile a usable one?



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 6, 2024 23:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
well, questcraft is built for a quest headset, and not yvr1, so you are on your own here (unless devs have a kind heart and port qc to your headset like they did with pico 4, but i highly doubt that will happen)

**Comment by Killerminigun** [comment]
Most likely

**Comment by GachaMeow** [comment]
Then how can I compile it?Or can you help me?



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 01:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
Most likely

**Comment by Cartrigger** [comment]
we haven't supported YVR in over 2 years as our contract has ended with YVR.

**Comment by Cartrigger** [comment]
And YVRCraft (whatever that is in Chinese) never got updated passed 2.0, so you dont have the unity environment or Vivecraft.

**Comment by GachaMeow** [comment]
Well, the front seems to have given me hope and he seems to have given up on me again.


=(

---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 11:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
And YVRCraft (whatever that is in Chinese) never got updated passed 2.0, so you dont have the unity environment or Vivecraft.

**Comment by GachaMeow** [comment]
He can't pass 2.0, which means that the first version can be used normally?

---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 11:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
And YVRCraft (whatever that is in Chinese) never got updated passed 2.0, so you dont have the unity environment or Vivecraft.

**Comment by Cartrigger** [comment]
If you can find YVRCraft on the store, you will be able to play 1.19.2 and 1.18.2.

**Comment by GachaMeow** [comment]
YVR The official app store.Found him, but he only supported YVR2 rather thanYVR1,If I really have no choice, I wonder if I can From others have And extract the installation package to me

---Original---
From: ***@***.***&gt;
Date: Sat, Dec 7, 2024 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
If you can find YVRCraft on the store, you will be able to play 1.19.2 and 1.18.2. Other than that, you can get a Meta device or a Pico 4 with Patreon membership.

**Comment by computer-catt** [comment]
![the-voices-meme (1).gif](https://github.com/user-attachments/assets/ea3916cf-e05a-43cf-8e35-68c984b30d2f)

**Comment by Cartrigger** [comment]
Continued on Discord, YVRCraft isn't the same version as current QuestCraft.

**Comment by GachaMeow** [comment]
I've been working on it these days, but pojav There is a branch of yvr I was wondering if I could compile one&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 14, 2024 12:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuestCraftPlusPlus/QuestCraft] [BUG]I can only hear voices(Issue #632)




 
Continued on Discord, YVRCraft isn't the same version as current QuestCraft.
