### ISSUE TITLE
[BUG] Discord link on website is expired

### ISSUE THREAD

**Issue by slavdok** [QuestCraftPlusPlus/QuestCraft#633]
### 🤔 Current Behavior

When I go to https://questcraft.org/support and click the Discord icon on the top right, it says "Invite Invalid", it may have expired

### ✅ Expected Behavior

I expect to click Discord link and for it to work

### 🥽 Headset Details

n/a

**Comment by computer-catt** [comment]
it's valid, you may just be banned.

**Comment by Cartrigger** [comment]
I dunno, it works just fine

**Comment by Cartrigger** [comment]
I'm not sure what you mean by it not working. It works just fine.
