### ISSUE TITLE
[FEATURE] <title>add Minecrafts free trial

### ISSUE THREAD

**Issue by ahmedjacop68** [QuestCraftPlusPlus/QuestCraft#636]
### 📝 Is your feature request related to a problem? Please describe

I don't own Minecraft and I know piracy is not your guys's place

### 🛠️ Describe the solution you'd like

I would like for you guys to add the free trial version of Minecraft that you can play without an account

**Comment by computer-catt** [comment]
its already a feature in the next update

**Comment by ahmedjacop68** [comment]
yyayayayayayyayayayayay

**Comment by computer-catt** [comment]
you should close the issue
