### ISSUE TITLE
[BUG] <title> qc crashes on quest 3s when moving from one text field to another, or loading worlds with mods

### ISSUE THREAD

**Issue by Rickeyrabbittt** [QuestCraftPlusPlus/QuestCraft#637]
### 🤔 Current Behavior

When I try to edit quick commands for example, or put in server address. When I try to edit one of the quick commands, change it to /setworldspawn, then click on the next quick command to add another command, qc crashes. When I type in the server address, then afterwards click on the server name field, it also crashes. I had a small amount of mods installed as well on another instance, easy mods that worked together on windows (for testing) like valkyrien ships, mca reborn, simple animated guns, just for example, when I moved the mods to questcraft it booted up, but when I tried to start a world it crashed. Is qc currently compatible with the 3s? Is that the problem?

### ✅ Expected Behavior

I expected it to function normally

### 🥽 Headset Details

Quest 3S

**Comment by Cartrigger** [comment]
Please read the broken mods list
https://discord.com/channels/820767484042018829/1242887330969157723/1243302943365796003
Please read the v71/2 notice
https://discord.com/channels/820767484042018829/1242887330969157723/1302544824288804865
https://discord.com/channels/820767484042018829/928885002752647229/1318387979563307040

These are all known, and is not headset specific.
