### ISSUE TITLE
[BUG] <title> qc on 3s crashes when moving from one text field to another

### ISSUE THREAD

**Issue by Rickeyrabbittt** [QuestCraftPlusPlus/QuestCraft#638]
### 🤔 Current Behavior

When I try to edit quick commands for example, or put in server address. When I try to edit one of the quick commands, change it to /setworldspawn, then click on the next quick command to add another command, qc crashes. When I type in the server address, then afterwards click on the server name field it also crashes. This is on a vanilla qc install of 1.20.4, 1.20.1, and 1.19.4, and it seems to happen in the menu when moving from one text field to another

### ✅ Expected Behavior

I was hoping it would work

### 🥽 Headset Details

Quest 3s

**Comment by Cartrigger** [comment]
Please don't spam. Your bugreport has already been answered. Do not open another one.
#637

**Comment by Rickeyrabbittt** [comment]
Half of the previous one was answered. It's not spam, this one wasn't addressed. The mods part was addressed, but not this one

**Comment by Cartrigger** [comment]
> Half of the previous one was answered. It's not spam, this one wasn't addressed. The mods part was addressed, but not this one

Read the notice. It was answered.

**Comment by Rickeyrabbittt** [comment]
I mean how are people supposed to know about a legitimate bug if it's closed and never addressed?

**Comment by Cartrigger** [comment]
# Latest Firmware (V72) has a issue that needs to be fixed!

Specific issues may entail:
Radial menu crashing
Search crash
Item selection (via clicking on hotbar)
Certain actions may crash randomly

Update:
V71 and V72 has released, you can disable updates in the updates settings page in general. 
If you update, downgrading on release versions is **IMPOSSIBLE** and cannot be undone!

Update 2: 
Roadblocks have been found that has delayed releasing to Patreons and public.

Update 3: 
Most things have been fixed like the keyboard, but some may observe certain crashes such as the radial menu.

# To fix some issues like blocks, update ( #dev-logs )

**Comment by Rickeyrabbittt** [comment]
Gotcha, I see it was addressed, my bad guys
