### ISSUE TITLE
[FEATURE] Gesture / Immersive Controls 

### ISSUE THREAD

**Issue by EricWasTakenWasTaken** [QuestCraftPlusPlus/QuestCraft#64]
**Is your feature request related to a problem? Please describe.**
a way to break blocks by physically hitting them 
features you've considered.

**Additional context**

**Comment by IzzyDotExe** [comment]
It's in the plans for the future

**Comment by BobbyMcg2021** [comment]
Is it possible for us to punch mobs with our fists? And even block with a shield using our arms?
