### ISSUE TITLE
[BUG] Crashes if you look at it funny

### ISSUE THREAD

**Issue by TheRedDraqon** [QuestCraftPlusPlus/QuestCraft#640]
### 🤔 Current Behavior

Game crashes upon doing basically anything. Pressing done on entering a server address, punching anything, clicking anything (e.g. punching blocks/mobs, opening doors, climbing ladders)

### ✅ Expected Behavior

The game to work normally ._.

### 🥽 Headset Details

Quest Build: 72.0.0.530.347.670816297 (Sideloaded as suggested in QCXR Discord)
Quest Model: Quest 3
QuestCraft Version: Doesn't matter. Happens on both 5.0.0 and RC6

Also, you misspelt Helpful as Heplful in > Heplful needed info

**Comment by bernhardriegler** [comment]
duplicate #639
