### ISSUE TITLE
Crashes when loading the menu in game

### ISSUE THREAD

**Issue by writtenwig596** [QuestCraftPlusPlus/QuestCraft#644]
### 🤔 Current Behavior

I believe that the issue here is that the game contains 2 cursors when I press and hold a the game would crash

### ✅ Expected Behavior

The menu with no crashing 

### 🥽 Headset Details

Meta Quest 3S the newest version of Quest and questcraft

### ℹ️ Anything else?

NA

**Comment by writtenwig596** [comment]
@Cartrigger What do you mean by not planned

**Comment by Cartrigger** [comment]
It's a generic close label

**Comment by OatmealCreampie** [comment]
whenever i press a or b or whatever the button is to get to the menu that you use to open chat and drop item and presumably my inventory idk i just got this game it crashes. i tried uninstalling all the mods i could but that didnt work, i tried preformance mods, i've trieid everything i can think of. i downloaded it using this guide idk if this has anything to do with it but im stuck https://www.youtube.com/watch?v=yGcQcIqmbSg&embeds_referring_euri=https%3A%2F%2Fwww.bing.com%2F&embeds_referring_origin=https%3A%2F%2Fwww.bing.com&source_ve_path=Mjg2NjY
