### ISSUE TITLE
Menu Far away

### ISSUE THREAD

**Issue by writtenwig596** [QuestCraftPlusPlus/QuestCraft#645]
### 🤔 Current Behavior

Quest craft via the standalone method

### ✅ Expected Behavior

The menu to be right in front of me not 50 blocks behind me

### 🥽 Headset Details

Newest Version of Quest 3S, QuestCraft, and Software

**Comment by Killerminigun** [comment]
Use roomscale instead of stationary

**Comment by writtenwig596** [comment]
> stationary

Sorry new to GitHub I can’t seem to find reply, anyways I already tried that it still didn’t work

**Comment by TruFoox** [comment]
Does this happen every time you play?

**Comment by Cartrigger** [comment]
#602

**Comment by writtenwig596** [comment]
> Does this happen every time you play?

Yeah
