### ISSUE TITLE
Server Resource Pack Red Screen Crash

### ISSUE THREAD

**Issue by MostRandomGamer** [QuestCraftPlusPlus/QuestCraft#66]
The bug will not allow players to open the game and have the game crash when the red screen is shown.

1. Go to Servers
2. Load into a server that uses a custom resource pack (ex: Origin Realms)
3. Join
4. You will see a black and white Mojang studios loading screen that will always reset right as its about to finish loading and be forced to restart the game
5. Now when you boot the game you will be unable to get past the red screen without it crashing

The game will get to the red screen and crash shortly after. The only way to fix this issue is to reinstall the game.

 - Quest Build: v37.0
 - Device: Quest 2
 - QuestCraft Version 1.1.0

**Comment by MostRandomGamer** [comment]
@CADIndie Hey I tested this again on the new update and it still exists do you think you could re-open the issue?

**Comment by Web7283** [comment]
he closed a lot of issues recently, nobody really knows why. I would suggest reposting this.

**Comment by MostRandomGamer** [comment]
alright
