### ISSUE TITLE
Make a possibility to the xbox game pass players connect to questcraft

### ISSUE THREAD

**Issue by OncleIlyess** [QuestCraftPlusPlus/QuestCraft#67]
Hello could you make that people who bought the "xbox game pass" on their Microsoft accounts can access minecraft because now on the Xbox game pass there is free java minecraft and therefore would it be possible to sign in to our Microsoft account which has the xbox Game pass or there is minecraft and be able to play it please

**Comment by MidnightBlight** [comment]
I was able to get Questcraft working with Game Pass. What I did was I downloaded the Xbox app on my PC and downloaded the Minecraft launcher from it. Then I clicked to install Minecraft Java and was prompted to make a username. After you do that, you can either cancel the installation or continue to download it on your PC. Either way, when you log into Microsoft on Questcraft, it should recognize that you own Minecraft Java.

**Comment by EricWasTakenWasTaken** [comment]
after i logged into minecraft from my pc with my gamepass account, it worked fine
