### ISSUE TITLE
[BUG] Loading into menu

### ISSUE THREAD

**Issue by braden644** [QuestCraftPlusPlus/QuestCraft#68]
**Describe the bug**

**To Reproduce**
1. Go to 'Play fabric-loader-0.12.12-1.18.1 '
2. When it starts loading It goes to black screen to red screen back to black screen loading
5.Doesn't load after that

**Expected behavior**
To load into the Minecraft Menu

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: v37.0.0.147.110.346379395
 - Device: Quest 2 64gb model
 - QuestCraft Version :1.1.1

**Additional context**
When trying to load into the Minecraft it goes to black screen loading and then it goes to red and back to black and doesn't load into the menu.

**Comment by JD-The-65th** [comment]
Have you set your game renderer to the third option?

**Comment by braden644** [comment]
Yes I have double checked to make sure that option was selected before clicking play.

**Comment by JD-The-65th** [comment]
You might wanna reinstall questcraft then, and make sure that when you sign in, you select "Keep me logged in"
