### ISSUE TITLE
how to update

### ISSUE THREAD

**Issue by 5ghzx** [QuestCraftPlusPlus/QuestCraft#69]
no clue how do you?

**Comment by JD-The-65th** [comment]
Install the new apk WITHOUT deleting the old one, then extract the new zip file to the root of your Quest.

**Comment by ATXLtheAxolotl** [comment]
If you've installed it on SideQuest I believe you can update it there if you installed it dirrectly from an apk do the above. Can someone close this issue since it's been resolved.
