### ISSUE TITLE
[BUG] hands

### ISSUE THREAD

**Issue by lrutjens** [QuestCraftPlusPlus/QuestCraft#70]
**Describe the bug**
Hands don’t appear in the start screen when graphics are set to fabulous

**To Reproduce**
1. Open settings
2. Change to fabulous 

**Expected behavior**
Hands appearing 

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Mage-Enderman** [comment]
Is it raining while you're at the title screen? if so that's why
For now you can fix it with this
https://www.curseforge.com/minecraft/mc-mods/particle-rain
or if you don't want rain at all
https://www.curseforge.com/minecraft/mc-mods/no-weather-effects

**Comment by IzzyDotExe** [comment]
Most likely the rain issue go to #83 to discuss closing this.
