### ISSUE TITLE
[BUG] Won't load past the red screen.

### ISSUE THREAD

**Issue by JJ2COOL** [QuestCraftPlusPlus/QuestCraft#72]
I log in with my microsoft account and then do all the other steps. But when I press play it just won't load past the red screen and then kicks me back to the log in screen.

**To Reproduce**
1. Log into microsoft account
2. Do all the steps required
3. Click play
4. Won't load past red screen then kicks me to log in.

**Expected behavior**
I expected to see the main menu.

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: idk
 - Device: Quest 2
 - QuestCraft Version Latest version

**Additional context**

**Comment by kyjus25** [comment]
+1 on this. Side loaded this morning and played for about an hour, came back to play tonight and crashes after red screen. Restarting the device did not help, I have not tried reinstalling the game

**Comment by JJ2COOL** [comment]
Maybe we need to reinstall it. Not entirely sure tho. It was working before for me as well.

**Comment by JD-The-65th** [comment]
Yes, I suggest reinstslling the game, and making sure you've set your renderer to the third option. Also, when you press login, select "keep me logged in" when logging in.

**Comment by JJ2COOL** [comment]
That seems to have worked. I will keep this open in case the next day it does the same thing tho.

**Comment by ATXLtheAxolotl** [comment]
> That seems to have worked. I will keep this open in case the next day it does the same thing tho.

Did you have the problem again or no?

**Comment by JuriRappsilber** [comment]
Hi there, unfortunately +1 from me. 
Device: Quest 2
QuestCraft Version 1.3.1 (latest), I have only started today and tried reinstalling as a solution. 
I can confirm "keep me logged in" and third option.

**Comment by kyjus25** [comment]
I have a Quest 2 also, forgot to mention.

**Comment by JavaMR-HTML** [comment]
+1 from me too. Upon crashing I am booted out to my passthrough home unable to pull up the quest menu, forcing me to restart my quest.

**Comment by jiang1feng** [comment]
Also have this issue. Won't load after the red screen. Either stuck at 3 dots screen and need restart the device, or crash back to "select account" page.

**Comment by jiang1feng** [comment]
Forgot to mention that I installed using "Sidequest Easy Installer (Beta)". The installation was very easy since it would install inside Quest2. Have tried re-installation a few times. Selected Open GL ES 3 and fabric-loader.

**Comment by NoahXSims** [comment]
I have the same problem. I get to the red screen and boom, it crashes.

**Comment by NoahXSims** [comment]
> 

I'll try it to tell you how it goes. Thanks for trying to help

**Comment by NoahXSims** [comment]
> Hi,
> 
> It finally worked for me after selecting Ultimate Gl4es from Renderer. It needs to make it's thing about 2 mins, then you just pop in the menu, after that you could select Fast graphics from Video settings but it will crash again and you need to restart, for better perfomance, as far as I know.
> 
> Have a nice day, I just made my account for this reply lol

Thank you so god damn much. First thing to work for me. All I had to do was change the video and renderer. Thank you so much. Really.

**Comment by ghuntington** [comment]
using Ultimate GI4es finally got me to the menu screen but the game crashes when I try to start a game. Did you find some settings that allowed you to start a game?

**Comment by InstaDanielul** [comment]
I'm not sure about Quest 1. Try getting a lower resolution, it is set at 100%, you can go lower, in that menu before you  start minecraft. After that you can try set graphics at fast on settings in game and render distance much lower, maybe 4-5 chunks

**Comment by NoahXSims** [comment]
> using Ultimate GI4es finally got me to the menu screen but the game crashes when I try to start a game. Did you find some settings that allowed you to start a game? Also, I'm on a Quest1.

Yeah, take InstaDanielul's advice. I turned down the chunks and turned the graphics to fast. Also lower your resolution at the launcher could help.

**Comment by lelzguy21** [comment]
> Hi,
> 
> It finally worked for me after selecting Ultimate Gl4es from Renderer. It needs to make it's thing about 2 mins, then you just pop in the menu, after that you could select Fast graphics from Video settings but it will crash again and you need to restart, for better perfomance, as far as I know.
> 
> Have a nice day, I just made my account for this reply lol



> > Hi,
> > It finally worked for me after selecting Ultimate Gl4es from Renderer. It needs to make it's thing about 2 mins, then you just pop in the menu, after that you could select Fast graphics from Video settings but it will crash again and you need to restart, for better perfomance, as far as I know.
> > Have a nice day, I just made my account for this reply lol
> 
> Thank you so god damn much. First thing to work for me. All I had to do was change the video and renderer. Thank you so much. Really.

i dont have the ultimate gl4es option what version are you on?

**Comment by NoahXSims** [comment]
> > Hi,
> > It finally worked for me after selecting Ultimate Gl4es from Renderer. It needs to make it's thing about 2 mins, then you just pop in the menu, after that you could select Fast graphics from Video settings but it will crash again and you need to restart, for better perfomance, as far as I know.
> > Have a nice day, I just made my account for this reply lol
> 
> > > Hi,
> > > It finally worked for me after selecting Ultimate Gl4es from Renderer. It needs to make it's thing about 2 mins, then you just pop in the menu, after that you could select Fast graphics from Video settings but it will crash again and you need to restart, for better perfomance, as far as I know.
> > > Have a nice day, I just made my account for this reply lol
> > 
> > 
> > Thank you so god damn much. First thing to work for me. All I had to do was change the video and renderer. Thank you so much. Really.
> 
> i dont have the ultimate gl4es option what version are you on?

As far as I know, I am on the latest version. Try reinstalling it.

**Comment by verdantserpent** [comment]
Oculus Quest 2 user reporting that using the FIRST option in renderer settings allowed it to boot past the red screen.

**Comment by NoahXSims** [comment]
> Oculus Quest 2 user reporting that using the FIRST option in renderer settings allowed it to boot past the red screen.

Ye, we said that part
