### ISSUE TITLE
Yooo why is this feature not in the game? This is a problem.

### ISSUE THREAD

**Issue by Monke554** [QuestCraftPlusPlus/QuestCraft#73]
WHY IS THERE NO FABRIC PORT OF THE SEX MOD?!?!?!?!?! If it's unsupported with pojav just make it supported duhh 🙄.

**Comment by JD-The-65th** [comment]
Not the place to complain about a mod not having a fabric port. If you want to complain about a mod not having a fabric port, take it up with the mod devs.



Also, ya nasty.
