### ISSUE TITLE
Crashes at login[BUG]

### ISSUE THREAD

**Issue by witthree** [QuestCraftPlusPlus/QuestCraft#74]
**Describe the bug**
game crashes at launch

**To Reproduce**
1. logged in
2. selected 3rd rendering option
3. selected bottom most game version
4. clicked "Play"
5. after it downloads the assets (445.95mb), it crashes showing me a black screen and 3 dots. It remains like this indefinitely. If I reboot the oculus I get as far as to click Play, then within a few seconds the 3 dots.

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build:  v37.0.0.147.109.346379382
 - Device: Quest_2
 - QuestCraft Version: not sure where to look for this. I just downloaded the app-debug.apk file today. 2-22

**Additional context**
The game version at bottom of list is fabric-loader-0.13.3-1.18.1
Uninstalled and reinstalled with the same results.

**Comment by wyt3dr4g0n** [comment]
I have this exact same issue. I thought it was because of trying to install the recommended mods at first because it worked before doing that. However even after uninstalling and redownloading, reinstalling, unzipping and copying the folder from scratch it still keeps doing this and won't actually load the game. Just the 3 white dots indefinitely unless I hit the O button on the controller and then it crashes back to Pojav.

**Comment by JD-The-65th** [comment]
I suggest reinstalling the game, and making sure when you press login, you select "keep me logged in" when logging in

**Comment by wyt3dr4g0n** [comment]
Yep, that seems to help in my case at least. Takes a minute on the black screen but does load eventually. Even loaded with all the mods copied over. Thanks

**Comment by JD-The-65th** [comment]
No problem. Please do remember to close the issue.

**Comment by witthree** [comment]
I still need to look at this. Likely tomorrow.

**Comment by CubeGamer647** [comment]
I tried reinstalling and pressing keep me logged in and it still has the black screen. There is music however, so I think the game is loading but it is not rendering.

**Comment by JD-The-65th** [comment]
Did you set the renderer to the third option?

**Comment by JD-The-65th** [comment]
You shouldn't try 1.7.10. make sure you're using the fabric profile at the bottom of the list.

**Comment by CubeGamer647** [comment]
There is no fabric profile at the bottom of the list, did I install something wrong?

**Comment by JD-The-65th** [comment]
Yup. You have to extract the zip file named "extracttoroot"  to the root directory of your quest.

Extract the Zip file on your pc, and copy over android in the zip file to android on your quest

**Comment by Mattshark89** [comment]
Once this happened to me when I, attempting to reset the installation, readded extracttoroot but did not reinstall the apk. Fabric was gone. Reinstalling everything again, apk included, fixed it for me

**Comment by witthree** [comment]
Ok, so after reinstalling and checking box to stay logged in, it did open but then froze as soon as I clicked the button to create the world (can't seem to edit world name either). After that it was back to freezing showing 3 dots as soon as I click 'Play'. 
If it matters, I have never seen the 'play anyway' message/warning that appears immediately after clicking Play, as it does in the tutorial video.

**Comment by witthree** [comment]
Redownloaded APK and Android folder and reinstalled. Works now.
