### ISSUE TITLE
[FEATURE] Have some way to prevent players from looking through blocks

### ISSUE THREAD

**Issue by AriSparks** [QuestCraftPlusPlus/QuestCraft#75]
**Is your feature request related to a problem? Please describe.**
It's not really a bug, mainly because Minecraft is supposed to render like that with everything being transparent behind visible block faces, but it's way too easy for players to look through blocks and see all of the caves and stuff around them, including player bases if there are any. 

**Describe the solution you'd like**
If possible, a way to detect if a player is inside a block and gray out the screen until outside would be perfect, just like most vr games. Making it so that the player can still stick their head through, but it wouldn't give any advantages.

**Comment by JoshTGHgithub** [comment]
Not a good idea when you're tall
