### ISSUE TITLE
[BUG] No way to get rid of hints like "move the mouse to look around".

### ISSUE THREAD

**Issue by torynet** [QuestCraftPlusPlus/QuestCraft#77]
**Describe the bug**
I can't figure out a way to get rid of certain "hints" that expect computer inputs.

**To Reproduce**
Open the game.
Look at the hint above your left hand about moving the mouse to look around.

**Expected behavior**
A way to get rid of the hints.

**Screenshots**
![171](https://user-images.githubusercontent.com/959980/155274489-2548fe0a-ccac-4cb9-9751-84aee46a5624.jpg)

**Headset Details (please complete the following information):**
 - Quest Build: v37.0.0.147.109.346379395
 - Device: Quest_2
 - QuestCraft Version not sure where to look for this. I just loaded through SideQuest today. 2-22

**Comment by mastercreeper66** [comment]
You can remove it by going into the .minecraft folder and opening the “options.txt”, you have to find the line that says “tutorialStep:” and change it to “tutorialStep:none”

**Comment by The-Blue-Goose** [comment]
alternatively, you could also download the "I know what I'm doing" mod from curse forge; however, you need to make sure you go to the files tab at the top and get the one labeled "Fabric," not "Forge."

Here is a link:
https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing

**Comment by Flamgop** [comment]
We will implement this into the base qcxr soon.
