### ISSUE TITLE
Change How Items Are Selected

### ISSUE THREAD

**Issue by MalekiRe** [QuestCraftPlusPlus/QuestCraft#78]
**Is your feature request related to a problem? Please describe.**
I am frustrated when selecting items from my hotbar, in fact, i am also frustrated when doing so on Vivecraft

**Describe the solution you'd like**
Instead, if on the left arm, a 3D version of the blocks/items, but miniturized sat on the arm, and then you put your right hand there, and hold, and then it "grabs" it and makes it your selected slot, importantly you have to have your grip button held down.

The items/blocks are miniturized and run down the side of the arm.

**Comment by ultimatexilliam** [comment]
Tbh, thats a really good idea and i support it too, but maybe you could select it in the settings so people who like the old style, can use the old style

**Comment by Flamgop** [comment]
This seems like an interesting idea, I will see how it can be done.

**Comment by kaiw1011** [comment]
Good idea

**Comment by KeepTheChange0** [comment]
This sounds like a really elegant way to manage the hotbar actually
