### ISSUE TITLE
[BUG] Crash when loading world

### ISSUE THREAD

**Issue by CatCentralGitHub** [QuestCraftPlusPlus/QuestCraft#79]
**Describe the bug**
Crashes when loading world

**To Reproduce**
1. Open/create a world
2. Wait
3. Red screen/Mojang screen
4. Oculus Home

**Expected behavior**
Opens world

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest 2
 - QuestCraft Version: v1

**Comment by Flamgop** [comment]
Could you get attach some logs? They are located at `Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/logs` and it should be called `latest.log`.
