### ISSUE TITLE
[FEATURE] Backwards Compatibility 

### ISSUE THREAD

**Issue by ReubenDollmanYT** [QuestCraftPlusPlus/QuestCraft#80]
**Is your feature request related to a problem? Please describe.**
It would be good if we had the ability to use this on older minecraft versions aswell as older versions would have less new things reduceing lag on the quest

**Describe the solution you'd like**
Ability to use diffrent minecraft versions

**Describe alternatives you've considered**
Vivecraft on pc but my laptop is not powerfull enough

**Comment by Mage-Enderman** [comment]
While Backwards compatibility could be nice for some reasons I feel this is not one of them as while yes older versions might have less things they also would probably be less optimized

**Comment by Flamgop** [comment]
Unfortunately, we tried this originally with qcxr and we got about 5 fps on vivecraft with optifine on 1.12.2. Unless someone makes a more optimized version of forge and/or vivecraft for older versions then we cannot fulfill this suggestion.
