### ISSUE TITLE
[BUG] Greater battery drain

### ISSUE THREAD

**Issue by mcdermott87** [QuestCraftPlusPlus/QuestCraft#82]
**Describe the bug**
The battery drains faster while playing QuestCraft. 
My headset went from 100% to 60% in half an hour. Comapred to other games like Walkabout mini golf, Contractors, Dead Horizon, Ultrawings, etc. I get around 75% battery left after half an hour.

**To Reproduce**
1. start up QuestCraft and compare battery usage to other games.
**Expected behavior**
Some kind of optimization if applicable.

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest_1
 - QuestCraft Version latest of 23rd of February from sidequest.

**Additional context**
My headset is "old" but it's battery is still in OK condition and I know how fast it drains. It would be nice if someone would try to reproduce, maybe I am the only one involved.
I know this is a hard to fix (or a no fix at all), But I noticed this, maybe it's related to some rendering issues.  I know Java Minecraft is resource heavy, but the issue might not be related to that, rather some other part of the project.

EDIT: I was running with graphics set to fast (not fancy), everything other was left default. I set the fps limiter to 80.

**Comment by oliverwesley1** [comment]
this probably wont be fixed as it isnt rlly a bug, more of a limitation. due to quest craft using alot of resources on the quest. it has to use more battery

**Comment by mcdermott87** [comment]
> this probably wont be fixed as it isnt rlly a bug, more of a limitation. due to quest craft using alot of resources on the quest. it has to use more battery

I understand, thank you for your reply!

**Comment by Flamgop** [comment]
This problem would be really difficult to fix, my suggestion for now is to get some memory optimization mods, as those will reduce the amount of memory it uses and should prolong your battery life a bit.
