### ISSUE TITLE
[BUG] Crosshair and hands invisible in rain

### ISSUE THREAD

**Issue by Dawidak** [QuestCraftPlusPlus/QuestCraft#83]
On Fabulous graphics settings the crosshair is invisible in the world and hands are invisible in inventory.

1. Wait for rain or change the weather using mod
2. Crosshair is invisible
3. Open inventory menu
4. Hands turn invisible

They should be visible all the time.

![QuestCraft2](https://user-images.githubusercontent.com/57863506/155330587-911dff77-7738-4290-b015-f772e991d970.png)
![QuestCraft](https://user-images.githubusercontent.com/57863506/155330595-68c51496-d739-42ce-a44f-8872901bd9ac.png)

Headset Details:
 - Quest Build: v37.147.0
 - Device: Quest_2
 - QuestCraft Version: 1.1.0

When changed to Fast or Fancy this problem is resolved just like the "visible caves underwater" so I guess it's related.
Here's how it looks on Fancy:
![QuestCraft4](https://user-images.githubusercontent.com/57863506/155331302-9f0fec46-4851-4d20-9a4f-2da12c6b9b4f.png)

**Comment by Villagerjj** [comment]
you can temporarily fix this with the particle rain mod

**Comment by Mage-Enderman** [comment]
> you can temporarily fix this with the particle rain mod

Other more extreme option
https://www.curseforge.com/minecraft/mc-mods/noweather

**Comment by Villagerjj** [comment]
lol
that can work!
