### ISSUE TITLE
[FEATURE] Add pointer or crosshair in menu/inventory

### ISSUE THREAD

**Issue by Dawidak** [QuestCraftPlusPlus/QuestCraft#84]
It's a little bit hard to choose options. I have to look at what button is highlighted or aim like with a gun to know where I'm clicking.

It would be nice to have a dot/cross pointer like in Quest or a beam like in SteamVR.

I tried to aim with my arm straight but It's not very comfortable in the long run.

**Comment by jakershaker1** [comment]
im confused because footage captured on the quest had the crosshair but it didnt on release versions.

**Comment by Goldenfreddy0703** [comment]
I'm not sure what footage your referring to but whenever you pause the game or look into your inventory, there is not a crosshair hair to show what your pointing at. In vivecraft, there is and I think it's necessary to have one on quest craft so it can act like a mouse.

**Comment by Dawidak** [comment]
From curiosity, I have checked the PC version of the MCXR mod and found out that it has this (weird and ugly) red ray. It's not pretty I know, but it's much better than nothing. 
So if it's not hard you could just bring it back but only in the menu and inventory? And if you can I think it would look nicer being a little shorter and white :)

**Comment by jakershaker1** [comment]
> I'm not sure what footage your referring to but whenever you pause the game or look into your inventory, there is not a crosshair hair to show what your pointing at. In vivecraft, there is and I think it's necessary to have one on quest craft so it can act like a mouse.

The mysticle's video on it shows the crosshair in the menu

**Comment by Goldenfreddy0703** [comment]
> > I'm not sure what footage your referring to but whenever you pause the game or look into your inventory, there is not a crosshair hair to show what your pointing at. In vivecraft, there is and I think it's necessary to have one on quest craft so it can act like a mouse.
> 
> The mysticle's video on it shows the crosshair in the menu
> 

Hey sorry I never replied but can you send me a link to the video, I reviewed some of his questcraft videos and I could not find the crosshair on rhe menu.

**Comment by Goldenfreddy0703** [comment]
Thank you very much for reopening this request. 
I just hope this request gets planned in the future. 

Again, Thank you

**Comment by Antorboy** [comment]
Cursor on the chat menu would be useful too, for any command that gets executed from the chat text like teleportation command from /locate.

**Comment by IzzyDotExe** [comment]
The crosshair is in progress of being added.

**Comment by Goldenfreddy0703** [comment]
niceeeeeeee, can't wait until its out so i can  play some miecraft on my quick

**Comment by Flopgop** [comment]
Dupe.

**Comment by Goldenfreddy0703** [comment]
Hey I just noticed this was not planned instead of completed. Sense you guys are just using a line instead of a crosshair. Would you guys considered this completed I guess?

**Comment by wellsilver** [comment]
tbh a line is godly

**Comment by Goldenfreddy0703** [comment]
> tbh a line is godly

Oh yeah i agree, i just wish we had the crosshair like vivecraft. It makes it feel like your playing the legacy console edition of minecraft and your inventory is a crosshair.
