### ISSUE TITLE
[FEATURE] Coordinations / factions

### ISSUE THREAD

**Issue by Ayd3nL** [QuestCraftPlusPlus/QuestCraft#85]
I’ve started a small faction type thing so to make stuff a little easier can you guys  implement somthing such as coordinate’s or some type of factions  i’ve made a small group it’s a faction type server for the quest craft smp, it’s called the founders currently it’s a Oligarchy. but we would love to be able to have a little boost to find each other. or somthing such as a in browser map

One of my partners checked out: https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap 

and 

https://www.curseforge.com/minecraft/mc-mods/journeymap

**Comment by Flamgop** [comment]
This feature would be handled better by a mod than built in.
