### ISSUE TITLE
After selecting the version, i get to a red screen and then it goes to the black screen with 3 dots and hangs.

### ISSUE THREAD

**Issue by keirman1** [QuestCraftPlusPlus/QuestCraft#88]
I follow the youtube vid and it doesnt work i did everything right

**Comment by kruemmelbande** [comment]
I have the same issue, except that there never is a red screen. It just goes straight to the black loading screen.
I checked the version and the renderer. A reinstall didnt fix it, allthough i can actually hear the minecraft menu music.

**Comment by EricWasTakenWasTaken** [comment]
i fixed this issue by installing the latest version from github, NOT the youtube video

**Comment by ATXLtheAxolotl** [comment]
> i fixed this issue by installing the latest version from github, NOT the youtube video

This issue has been solved can someone close this ticket?
