### ISSUE TITLE
How to crouch, use virtual keyboard, etc.

### ISSUE THREAD

**Issue by CubeGamer647** [QuestCraftPlusPlus/QuestCraft#89]
Not sure if this is the right place to post, nor is it a bug, but once I finally got the game working I had a few control problems. How do I crouch, open the keyboard, use chat, or switch hotbar slots?

EDIT: is there a quick bind for dropping items, or must it be done from the inventory?

**Comment by EricWasTakenWasTaken** [comment]
to crouch, you can use the side button under the left trigger

**Comment by MCTRACO** [comment]
To switch hotbar slots move the right joystick up and down

**Comment by oliverwesley1** [comment]
in future ask this in #support in the discord otherwise the devs will get annoyed

**Comment by Flamgop** [comment]
Controls are pinned in the discord, I will arrange to add them to the readme. The keyboard is currently in the works and with it will come a chat keybind.
