### ISSUE TITLE
[BUG] Crashes on loading world

### ISSUE THREAD

**Issue by hellidox** [QuestCraftPlusPlus/QuestCraft#9]
When loading a world or joining a server, Pojav crashes completely
[latest.log](https://github.com/QuestCraftPlusPlus/QuestCraft/files/8112766/latest.log)

**Comment by hellidox** [comment]
I'm realizing that log doesn't have the crash details

**Comment by Foxlum** [comment]
I know one thing about the Quest, unless you can handle it gracefully, the Quest will kill apps if it feels extremely stressed (presumably to keep itself from overheating, and hold tracking and system functions.)

**Comment by kaiw1011** [comment]
I tried setting GPU level to 4 in sidequest, that helps a bit
