### ISSUE TITLE
[FEATURE / IN PROGRESS] Add an On-screen keyboard to type things

### ISSUE THREAD

**Issue by IZZYGamez361** [QuestCraftPlusPlus/QuestCraft#90]
I started a server on the PC so I could save resources on the Quest. I cannot figure out how to enter that IP without a keyboard.
I also tried using a keyboard with an adapter and it still won't let me type.

**Comment by Eccentric1847** [comment]
You have to take the server.dat file from your pc and put it into the pojav folder on quest

**Comment by IZZYGamez361** [comment]
> You have to take the server.dat file from your pc and put it into the pojav folder on quest

Ok, but that still doesn't help that you can't name a new world.

**Comment by Flamgop** [comment]
This feature is in progress.

**Comment by Goldenfreddy0703** [comment]
Ooo great, can't wait to try it, I hope it's like the vivecraft keyboard I use to use when I was on pc.

**Comment by IzzyDotExe** [comment]
Feature finished!
