### ISSUE TITLE
movements

### ISSUE THREAD

**Issue by EricWasTakenWasTaken** [QuestCraftPlusPlus/QuestCraft#91]
can other people see the movements you make in game? i would test this myself, but i only have 1 minecraft account

**Comment by Leeo97one** [comment]
I guess it is visible to players with the [MCXR](https://github.com/QuestCraftPlusPlus/MCXR) mod.

**Comment by LetoDK** [comment]
Not yet. The devs are working on it. Also, please make more descriptive titles. The word "movements" says nothing.
