### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Micocono123** [QuestCraftPlusPlus/QuestCraft#92]
I would love to see Physical movement and things like jumping crouching and breaking blocks BUT i want that this will be optional so there will be vr controls and regular controls please consider it.

**Comment by Flamgop** [comment]
A toggle for immersive controls does sound nice, but vivecraft has it so you can do either or without a toggle. We may implement it in a similar way.

**Comment by IzzyDotExe** [comment]
Duplicate #64 gestures are coming later
