### ISSUE TITLE
[FEATURE / IN PROGRESS] UI Buttons for commands and/or chat (Not directly mentioned below but I'm hoping for "pages")

### ISSUE THREAD

**Issue by Mage-Enderman** [QuestCraftPlusPlus/QuestCraft#93]
**Is your feature request related to a problem? Please describe.**
Considering the utility and sometimes necessity of commands or chat
I think it is a problem that we can't execute commands or chat

**Describe the solution you'd like**
In future it'd be nice for a in-game keyboard to be added (or the ability to use a bluetooth one)
But I think as this is a VR game, for commands/basic chat stuff it'd be nice to have a menu where you can add
UI buttons for specific commands or chat stuff like buttons for "Hello!", "How are you?", "Ready to play?", "I'm alright", "go to sleep plz"
or buttons for "/spawn", "/gamemode creative", "/gamemode survival", "/home", "/sethome" etc

**Describe alternatives you've considered**
as mentioned, in-game keyboard which I imagine'll be tricky
or support for a Bluetooth or maybe even wired keyboard which would be nice but wouldn't solve this for as many people
and isn't as convenient anyway considering this is a game where you have a screen blindfold and can't as quickly/easily see the keyboard

**Additional context**
While looking to solve this myself I found this
https://www.curseforge.com/minecraft/mc-mods/command-gui-buttons
Which sadly doesn't work but there was a github in the comments for a newer version
...That I don't know how to compile/install but may be useful for people with more knowledge on it like the devs of MCXR or Questcraft

**Comment by Flamgop** [comment]
We are working on an in game keyboard at the moment (see my [fork](https://github.com/flamgop/mcxr)) but this does seem pretty cool.

**Comment by Mage-Enderman** [comment]
> We are working on an in game keyboard at the moment (see my [fork](https://github.com/flamgop/mcxr)) but this does seem pretty cool.

I get that and yes I do think an in-game keyboard will be wonderful to have
but even with a keyboard this should still be a feature IMO
so you don't have to manually type out everything as that's annoying for most in VR

**Comment by Flamgop** [comment]
yea fair fair, I may add some extra configurable buttons to the keyboard that are hotkeys that auto type that stuff.

**Comment by Mage-Enderman** [comment]
> yea fair fair, I may add some extra configurable buttons to the keyboard that are hotkeys that auto type that stuff.

That could be nice though personally I'd want it to be like it's own page or section kinda separate from the keyboard
As I feel the keyboard would limit how many hotkeys you could have where as if it had it's own bit then it'd be less restricted?

**Comment by IsraelAristide** [comment]
Quick chat buttons will be added in v1.2.0

**Comment by IzzyDotExe** [comment]
Quick chat has been finished, it will ship in 1.2.0 along with customizable quick chat messages.
