### ISSUE TITLE
Croshair not in working in rain

### ISSUE THREAD

**Issue by gapplar** [QuestCraftPlusPlus/QuestCraft#95]
I played in survival and my croshair was not working so i couldnt see what block i was looking at, I used only vanilla mods and it didnt work in snow either

**Comment by oliverwesley1** [comment]
Read other bugs before submitting Ur own, I'm not a Dev or mod but this has been said multiple times. Idk if you can delete them. But if you submit anymore check to see if a similar bug has been submitted.

**Comment by IzzyDotExe** [comment]
#83 to discuss this bug
