### ISSUE TITLE
when i try to play there is fabric option and i cant play the game iin vr[BUG]

### ISSUE THREAD

**Issue by ethan5844** [QuestCraftPlusPlus/QuestCraft#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Flamgop** [comment]
Bug does not follow issue template. We have no idea what your problem is because you provided no info. I am closing this issue.
