### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by verityyy** [QuestCraftPlusPlus/QuestCraft#97]
game endlessly loads after u click play after it says preparing to download resources, already using forge and followed all tutorial steps
**To Reproduce**
1. click play

**Comment by Mage-Enderman** [comment]
You're not supposed to use Forge
You didn't follow the tutorial steps if you did

This isn't a bug this is user error.

**Comment by The-Blue-Goose** [comment]
Assuming you meant Fabric, try restarting the headset. Rather than clicking login using Microsoft or Mojang, use the "Existing Account" Button. Clicking play will still cause the game to load on a black screen for about a minute, but it should eventually load.

**Comment by Flamgop** [comment]
A few things, 
1: There is no forge in QCXR
2: Did you follow all instructions on sidequest, the discord, or the github?
3: The game does take about a minute or 2 to start.

**Comment by verityyy** [comment]
> You're not supposed to use Forge You didn't follow the tutorial steps if you did
> 
> This isn't a bug this is user error.

soz i mean fabric

**Comment by ATXLtheAxolotl** [comment]
This ticket has become inactive did you ever solve the issue?
