### ISSUE TITLE
[FEATURE] Joystick press (L3 and R3?) doesn't map to anything I feel it should be mappable

### ISSUE THREAD

**Issue by Mage-Enderman** [QuestCraftPlusPlus/QuestCraft#98]
**Is your feature request related to a problem? Please describe.**
I got CommandGUI working but I can only map it to left or right click or unknown (which doesn't work)
I thought maybe I could map it to the joystick press or even the "Menu" button on the left controller 
(the button under the joystick and to the left of the X button)
But no neither are mappable

**Describe the solution you'd like**
I request that Joystick (L3 and R3) and the "Menu"(?) button become mappable
Not mapped (well maybe the menu button could open the options menu but idk)

**Describe alternatives you've considered**
Allow for bluetooth/wired keyboard support
Allow for the grip buttons to be mapped

**Comment by Flamgop** [comment]
A controls menu is being worked on by sorenon.

**Comment by Foxygamer151** [comment]
In my opinion the controls for the grip buttons (crouch and sprint) should be swapped with R3 and L3 (L3 for sprint and R3 for crouch like consoles) and one of the grip buttons should be used for the f3 screen to see coordinates.

**Comment by tylerhacker999** [comment]
> In my opinion the controls for the grip buttons (crouch and sprint) should be swapped with R3 and L3 (L3 for sprint and R3 for crouch like consoles) and one of the grip buttons should be used for the f3 screen to see coordinates.

Yeah i think this would be a really good idea!!!

**Comment by IzzyDotExe** [comment]
Both joystick buttons are now mapped in update 1.2.0, custom mappings are coming in a later update
