### ISSUE TITLE
[BUG] Error cant find any compatible java runtime

### ISSUE THREAD

**Issue by dustin7789** [QuestCraftPlusPlus/QuestCraft#99]
**Describe the bug**
When I press play it gives me the error in the title
Yes I have installed the files on the root in the android folder thing.
Yes I have changed the Renderer .
Yes I'm on the right fabric version.

**To Reproduce**
1. Load up the launcher
2. select account
3. press play

**Expected behavior**
To load up

**Headset Details (please complete the following information):**
 - Quest Build: idk what this means but my quest is fully updated
 - Device: Quest 2
 - QuestCraft Version  Latest version idk the number

**Comment by bradyshutt** [comment]
I'm getting this too

**Comment by Flamgop** [comment]
The builds in Actions do not come with a JRE, we are fixing this.

**Comment by dustin7789** [comment]
> The builds in Actions do not come with a JRE, we are fixing this.

what do you mean by action and any ETA on a fix?
